### ISSUE TITLE
[feat] 需要支持屏幕坐标和相对节点坐标点击

### ISSUE THREAD

**Issue by lisonge** [gkd-kit/gkd#10]
[选择器](https://github.com/gkd-kit/selector)  已经能解决绝大部分广告/弹窗

但是仍然存在点击位置无法通过节点确认的情况 <https://github.com/gkd-kit/subscription/issues/28>

另外如 <https://gkd-kit.gitee.io/import/12519653>, <https://github.com/gkd-kit/subscription/issues/28> 酷安的这个开屏广告界面的跳过那块是一整个区域节点，这种无法根据节点信息点击

**Comment by CKylinMC** [comment]
我在尝试自己编写补充规则的时候遇到了[和这里提到的网易邮箱大师一样的情况](https://github.com/gkd-kit/subscription/issues/6)，但是我发现下方的会员免广告按钮是可以找到的。我觉得如果可以依靠一个能稳定找到的按钮进行坐标偏移，或许可以比绝对坐标更具有通用性？

**Comment by hjhsjywanan** [comment]
https://gkd-kit.gitee.io/snapshot/1698430807247

**Comment by hjhsjywanan** [comment]
微博的这种信息流广告现在也是这样了，没有X的控件信息

**Comment by lisonge** [comment]
> https://gkd-kit.gitee.io/snapshot/1698430807247

@hjhsjywanan 

快照发错了，但是我应该明白你说的是什么，微博帖子列表页面帖子卡片右上角的x确实是一整块图片

无障碍无法获取这个关闭x图标按钮的具体信息

**Comment by zz3999** [comment]
np管理器的广告怎么跳过，
快照
https://i.gkd.li/import/13798922
