### ISSUE TITLE
魅族16T无障碍权限设置故障

### ISSUE THREAD

**Issue by OGGGXYT** [gkd-kit/gkd#101]
魅族16T
系统：flyme 8.1.8.0A(安卓9)
版本：gkd v1.2.1
在对软件授权无障碍权限时，在设置->无障碍->搞快点->勾选给与权限时，显示此服务出现故障（无法执行。点击按钮可查看相关信息）且软件无法正常工作进行广告的跳过。

**Comment by lisonge** [comment]
试试 https://github.com/gkd-kit/gkd/releases/tag/v1.3.0 呢?

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
