### ISSUE TITLE
能否支持用户自定义规则（类似auto.js的简单批处理功能）

### ISSUE THREAD

**Issue by Saeviome** [gkd-kit/gkd#106]
如题

**Comment by lisonge** [comment]
自己在本地订阅添加规则就行

**Comment by Saeviome** [comment]
请问，官方有没有添加规则的wiki

> 自己在本地订阅添加规则就行

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/blob/main/CONTRIBUTING.md
