### ISSUE TITLE
[功能请求] 连接Shizuku自动授权无障碍和悬浮窗权限

### ISSUE THREAD

**Issue by PYUDNG** [gkd-kit/gkd#108]
现有issue里好多无法授权无障碍的，理论上可以直接通过shizuku授权这些权限（而且据说shizuku授权的无障碍权限更加稳定），希望可以连接shizuku后自动授权，省去手动点击这一和系统设置斗争的过程，一劳永逸。

**Comment by lisonge** [comment]
duplicate

https://github.com/gkd-kit/gkd/issues/22

**Comment by PYUDNG** [comment]
@lisonge #22 为使用shizuku模拟点击，此issue为利用shizuku授予权限（如AppOps，权限狗那样），前者是更换点击的实现方式，后者为更改系统权限授权方式，不是同一个需求。

**Comment by lisonge** [comment]
确实 不是同一个需求

但是人家都装 shizuku 了，实际上 shizuku 的授权比 无障碍更难，感觉没这个必要

另外 AppOps，权限狗 我并没有看到它们能 操作 无障碍 权限

**Comment by PYUDNG** [comment]
感谢您的回复

> 但是人家都装 shizuku 了，实际上 shizuku 的授权比 无障碍更难，感觉没这个必要

shizuku的安装是一次性的工作，并且很可能在安装gkd前就已经装好了。gkd的界面里并没有引导用户安装激活shizuku的任何提示或教程（甚至都没有告诉用户shizuku是什么），那么我觉得我可以认为gkd的shizuku模式是面向那些在安装使用gkd之前就已经熟悉并安装激活好shizuku的用户的。
那么，对于已经装好shizuku的用户来说，这个功能就具有明显的简化操作的作用。对于已经装好shizuku的用户而言，shizuku的授权仅仅是点击屏幕中央的弹窗允许按钮一次，而在系统设置授权需要反复跳转点击，操作成本差异巨大。也许你觉得这算吹毛求疵，但是我确实很看重这点速度和便利性上的差异。

> 另外 AppOps，权限狗 我并没有看到它们能 操作 无障碍 权限

这个基于shizuku的 [**无障碍管理器**](http://tools.huluxia.com/share/page/ANDROID/4.1?app_id=87007) 可以。
[无障碍管理器 12 (com.accessibilitymanager).apk.zip](https://github.com/gkd-kit/gkd/files/12841388/12.com.accessibilitymanager.apk.zip)
在它的简介图片里了解到，可能和 _android.permission.WRITE_SECURE_SETTINGS_ 权限有关，这也许会对您的开发有所帮助

**Comment by lisonge** [comment]
确实有道理

**Comment by PYUDNG** [comment]
辛苦了，感谢开发！

**Comment by lisonge** [comment]
取消 shizuku 对此的支持

因为 shizuku 调用的隐藏 api 签名在各机型签名不一致，有的机型还没调用方法就直接报错

此外某些机型还存在无法获取对应服务的问题

**Comment by lisonge** [comment]
类似的问题 https://github.com/gkd-kit/gkd/issues/358

**Comment by lisonge** [comment]
> GKD 自身可以手动调用 Settings.Secure.putString 方法直接开启或者关闭无障碍服务的功能

感谢大佬建议，会在后续版本加上

**Comment by lisonge** [comment]
> GKD 自身可以手动调用 Settings.Secure.putString 方法直接开启或者关闭无障碍服务的功能

[v1.9.0-beta.1](https://github.com/gkd-kit/gkd/releases/tag/v1.9.0-beta.1)
