### ISSUE TITLE
IQOOZ7开启软件后过一段时间自动无效

### ISSUE THREAD

**Issue by Mitpoppy** [gkd-kit/gkd#109]
就是开启软件能用，并且一段时间能用，但是时间稍微长一点，比如我上午开了，下午用就会发现不自动跳过任何广告，并且权限全部开了（无障碍权限 自启动 关联启动 悬浮窗 电池后台高耗电 任务后台锁定 通知权限 并且开了shizuku依然这样，不开也是），然后后台还有一个李跳跳在运行，在GKD软件无效时候，李跳跳依然能用
类似 #64 ，不能说一样，应该是一模一样问题
重启软件+无障碍权限后正常

**Comment by each1026** [comment]
一样，设备 mate60 pro ，一段时间就不运行了。现在用的是李跳跳

**Comment by Mitpoppy** [comment]
挂了一天多GKD突然发现正常用了🌚，不知道什么原因，现在一直挂着也没出现无效情况

**Comment by each1026** [comment]
> 挂了一天多GKD突然发现正常用了🌚，不知道什么原因，现在一直挂着也没出现无效情况

不可能 绝对不可能,   你重启看看

**Comment by Mitpoppy** [comment]
> > 挂了一天多GKD突然发现正常用了🌚，不知道什么原因，现在一直挂着也没出现无效情况
> 
> 不可能 绝对不可能,   你重启看看

我这里一直正常了，不敢重启🌚

**Comment by Mitpoppy** [comment]
> > 挂了一天多GKD突然发现正常用了🌚，不知道什么原因，现在一直挂着也没出现无效情况
> 
> 不可能 绝对不可能,   你重启看看

昨天晚上能用的，今天下午又不能用了🌚

**Comment by each1026** [comment]
> > > 挂了一天多GKD突然发现正常用了🌚，不知道什么原因，现在一直挂着也没出现无效情况
> > 
> > 
> > 不可能 绝对不可能,   你重启看看
> 
> 昨天晚上能用的，今天下午又不能用了🌚

太惨了

**Comment by lisonge** [comment]
duplicate

https://github.com/gkd-kit/gkd/issues/64

https://github.com/gkd-kit/gkd/releases/tag/v1.3.0
