### ISSUE TITLE
[feat] 兼容李跳跳规则

### ISSUE THREAD

**Issue by zutzo** [gkd-kit/gkd#11]
https://github.com/zfdang/Android-Touch-Helper/issues/64

从隔壁项目看到的主意 感觉可以整上

附：https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules 李跳跳规则
在线订阅 https://raw.githubusercontent.com/Snoopy1866/LiTiaotiao-Custom-Rules/main/AllRules.json

**Comment by lisonge** [comment]
这个是 GKD APP 的默认订阅 https://github.com/gkd-kit/subscription

如你所见，为了增加它的可维护性，基本每个规则都有自己的界面快照，这个 `李跳跳规则` 没有快照，可维护性较低

但是这个仓库绝大部分 李跳跳的规则 可以转换到 GKD 规则，比如 [`{"id":"青少年模式","action":"我知道了"}`](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/T/tv.danmaku.bili/readme.md#id%E9%9D%92%E5%B0%91%E5%B9%B4%E6%A8%A1%E5%BC%8Faction%E6%88%91%E7%9F%A5%E9%81%93%E4%BA%86) 可以转换为 

`{matches:['[text="青少年模式"||desc="青少年模式"||id="青少年模式"]', '[text="我知道了"||desc="我知道了"||id="我知道了"]']}`

实际上这个青少年模式弹窗在 [默认订阅](https://github.com/gkd-kit/subscription/blob/e87492361a74155e43bceded16c178dd2fe96189/src/apps/tv.danmaku.bili.ts#L25) 里可以简单是 `[text*='青少年模式'] + [text='我知道了']`  ，而且 `+` 准确描述了这两个节点是相邻兄弟关系



而且 GKD 由于有 [快照审查器](https://github.com/gkd-kit/inspect) 写规则的速度是高于这个 李跳跳规则 的

---

因此我不太考虑支持，毕竟这个APP还一堆BUG没改，但是我可以写一个网页将 李跳跳规则 转成 GKD 规则，另外没有 快照 的话，默认订阅是不会收录的

相反我更推荐把 `李跳跳规则` 的每个快照提交到 <https://github.com/gkd-kit/subscription>，毕竟打快照是很简单的

**Comment by lisonge** [comment]
不应该啊，我为了访问速度特意在 gitee pages 也部署了，是不是你的梯子无法访问 gitee

你可以把域名换成以下任意域名，它们的代码是同步部署的

- <https://gkd-kit.songe.li> github pages

- <https://gkd-kit.gitee.io> 大陆访问

- <https://gkd-kit.netlify.app> netlify

- <https://gkd-kit.vercel.app> vercel

**Comment by lisonge** [comment]
随便找了个测试网站，网速相比国外网站还是挺不错的

![image](https://github.com/gkd-kit/gkd/assets/38517192/59a8dedd-d196-4d9f-a4bb-5780eeaa97e6)

![image](https://github.com/gkd-kit/gkd/assets/38517192/b9aceb69-c649-400e-976e-ce58a54219f6)

**Comment by lisonge** [comment]
@lshilshi 
> 但是自添加规则太麻烦，还得保持http服务开启，服务关闭，自定义规则订阅会被清理

http服务是用来调试实时规则的不是用来添加长久规则的，你一开始就用得不对。

另外如果你不想在http服务关闭的时候清除内存订阅，可以动动小手把 `高级设置-自动清除内存订阅` 关闭

就目前而言添加规则的唯一方式是使用 http 链接订阅，最简单的方式是你手动新建一个 json/json5 文件上传到 github 然后在 APP 添加订阅 git-raw/jsdelivr 链接，每个人本来就可以补充和使用自己的订阅，只是当前方式有局限性

你的问题只需要 APP 增加 `本地规则管理`  这个功能而已，这个后续会增加的

**Comment by lshilshi** [comment]
> http服务是用来调试实时规则的不是用来添加长久规则的，你一开始就用得不对。
> 
> 另外如果你不想在http服务关闭的时候清除内存订阅，可以动动小手把 `高级设置-自动清除内存订阅` 关闭
> 
> 就目前而言添加规则的唯一方式是使用 http 链接订阅，最简单的方式是你手动新建一个 json/json5 文件上传到 github 然后在 APP 添加订阅 git-raw/jsdelivr 链接，每个人本来就可以补充和使用自己的订阅，只是当前方式有局限性
> 
> 你的问题只需要 APP 增加 `本地规则管理` 这个功能而已，这个 #23 后续会增加的

是的，等你增加“本地规则管理”功能之后我再回来。
另外，现在快照模式添加可以作为扩展，但是能保留李跳跳那样的简单增加规则方式更佳

毕竟，增加个规则就要http调试（看了下，还要增加脚本，让https下访问http协议资源）相对来说还是繁琐了
虽然作者为大，再说也不是收费软件，我也没捐赠
提太多要求不合适
但是这年头家具都考虑人体工学，手机都来无障碍不是

软件易用一些，应该是更普适的

**Comment by xmbhsqktdqfpqdy** [comment]
试用了一会，感觉最大的问题可能就是没有通用规则，没法默认跳过带跳过两个字的广告。每个APP都需要专门的规则。

**Comment by lisonge** [comment]
> 试用了一会，感觉最大的问题可能就是没有通用规则，没法默认跳过带跳过两个字的广告。每个APP都需要专门的规则。

后续会支持通用规则

**Comment by Crisy1084** [comment]
> 会支持通用规则

mark，期待通用规则！！

**Comment by zgkm169** [comment]
> > 试用了一会，感觉最大的问题可能就是没有通用规则，没法默认跳过带跳过两个字的广告。每个APP都需要专门的规则。
> 
> 后续会支持通用规则

中秋节快乐

**Comment by boplay** [comment]
> 这是 GKD APP 的默认订阅https://github.com/gkd-kit/subscription
> 
> 如你所见，为了增加它的可维护性，基本每个规则都有自己的界面快照，这个`李跳跳规则`没有快照，可性维护较低
> 
> 但是这个仓库初始化李跳跳的规则可以转换为GKD规则，比如[`{"id":"青少年模式","action":"我知道了"}`](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/T/tv.danmaku.bili/readme.md#id%E9%9D%92%E5%B0%91%E5%B9%B4%E6%A8%A1%E5%BC%8Faction%E6%88%91%E7%9F%A5%E9%81%93%E4%BA%86)可以转换为
> 
> `{matches:['[text="青少年模式"||desc="青少年模式"||id="青少年模式"]', '[text="我知道了"||desc="我知道了"||id="我知道了"]']}`
> 
> 其实这个青少年模式弹窗在[默认订阅](https://github.com/gkd-kit/subscription/blob/e87492361a74155e43bceded16c178dd2fe96189/src/apps/tv.danmaku.bili.ts#L25)里可以简单的是`[text*='青少年模式'] + [text='我知道了']` ，而且`+`准确地描述了这两个节点是相邻兄弟关系
> 
> 而且GKD得益于有[快照审查器](https://github.com/gkd-kit/inspect)写入规则的速度是和这个李跳跳规则的
> 
> 因此我不太考虑支持，毕竟这个APP还有一个BUG没改，但是我可以写一个网页将李跳跳规则转成GKD规则，另外没有快照的话，默认订阅是不会收录的
> 
> 相反，我更推荐把`李跳跳规则`每个快照拍摄到https://github.com/gkd-kit/subscription，毕竟打快照是很简单的

发现这个比李跳跳更强，就是没有编程基础不会写规则。看了下教程，有些能看懂，有些不知道啥意思，上手难度比较大。

**Comment by wryyy6** [comment]
怎么把自己编写的规则添加到订阅规则里啊？

**Comment by adproqwq** [comment]
https://ltt2gkd.adproqwq.top
规则转换网站

**Comment by shisansir** [comment]
感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月3日(周三) 下午3:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gkd-kit/gkd] [feat] 兼容李跳跳规则 (Issue #11)




 
https://ltt2gkd.adproqwq.top
 规则转换网站
