### ISSUE TITLE
耗电优化

### ISSUE THREAD

**Issue by jiangfeiyang0228** [gkd-kit/gkd#112]
![Screenshot_2023-10-06-01-24-26-392_com miui securitycenter](https://github.com/gkd-kit/gkd/assets/68383449/b8797215-c3e5-4e7e-b5c7-f57f37e1be21)
![Screenshot_2023-10-06-01-35-18-313_com miui securitycenter](https://github.com/gkd-kit/gkd/assets/68383449/42a850f9-7c16-4cff-a2c6-f8b1c097cbb9)

**Comment by lisonge** [comment]
好的，后面会做一下耗电优化，如果目前觉得耗电过多，可暂时停止使用 APP，后续优化后再使用

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/112

**Comment by JianPpan** [comment]
这是来自QQ邮箱的自动回复邮件。您好，来信已经收到，将尽快给您回复。
