### ISSUE TITLE
无法单独关闭某项规则

### ISSUE THREAD

**Issue by dev-techmoe** [gkd-kit/gkd#113]
twitter（X）目前的自动关广告规则有问题，尝试关闭，发现无论如何关闭（关闭单独规则 or 关闭整个app规则）均无效果，打开twitter之后仍然在不停的执行规则。

如果需要日志或者复现视频请回复我，我现在在外面不太方便准备，需要的话我会抽时间准备这些信息。

**Comment by lisonge** [comment]
> 关闭单独规则 or 关闭整个app规则

关闭后通知栏规则数量是否显示变化？

**Comment by dev-techmoe** [comment]
> > 关闭单独规则 or 关闭整个app规则
> 
> 关闭后通知栏规则数量是否显示变化？

没有变化，无论怎么更改应用开关状态或者单一规则状态，一直是306规则 587规则组。

已安装release的最新版。

系统是MIUI 14 (Android 13)。

**Comment by lisonge** [comment]
那你把订阅删除后点击右下角重新添加默认订阅呢

**Comment by dev-techmoe** [comment]
> 那你把订阅删除后点击右下角重新添加默认订阅呢

刚刚干脆直接把应用数据清了重新启动了。

暂时好了，开关规则通知里的数字会变。

我先把issue关了，再出这种问题我再打开。
