### ISSUE TITLE
MIUI14，k60ultra 无法使用

### ISSUE THREAD

**Issue by JianPpan** [gkd-kit/gkd#114]
在开屏广告页面时没有触发自动跳过，偶尔触发去广告，已配置所有权限，规则为最新 v122

**Comment by JianPpan** [comment]
[log.zip](https://github.com/gkd-kit/gkd/files/12830920/log.zip)

**Comment by lisonge** [comment]
> 在开屏广告页面时没有触发自动跳过

在什么应用的开屏广告？我看你的日志也没啥问题

**Comment by JianPpan** [comment]
> > 在开屏广告页面时没有触发自动跳过
> 
> 在什么应用的开屏广告？我看你的日志也没啥问题

所有应用开屏广告都不生效

**Comment by lisonge** [comment]
什么叫所有应用？，我看你日志里也没打开几个应用，你下载个知乎或者酷安看看，这两是明确有开屏广告的

**Comment by JianPpan** [comment]
不好意思，应该是我的问题，和李跳跳有冲突，卸载了好像能行了

**Comment by lisonge** [comment]
看起来不应该，我看其他人都是可以两个APP一起使用的
