### ISSUE TITLE
miui14更新1.3后依旧无法工作

### ISSUE THREAD

**Issue by jiegebuyaola1** [gkd-kit/gkd#122]
miui14 Android13，更新1.3版本后，后台一会依旧没办法跳过广告。
打开悬浮窗后就正常，是不是因为没有保持前台服务的原因，我看以前用李跳跳的时候他设置就有保持前台服务，所以识别率会高一些？

**Comment by huanghaobaobao** [comment]
我也是一样情况，知乎打开后会延迟2s左右才能跳过

**Comment by lisonge** [comment]
> 保持前台服务

@jiegebuyaola1

你的通知栏有显示吗？

**Comment by 9k001** [comment]
我是不稳定。。这个不知道什么原因

**Comment by RouRouX** [comment]
我也是知乎没法跳过，开启悬浮窗快照的按钮以后就可以跳过了，和楼主描述一致。

**Comment by lisonge** [comment]
好吧，那你们先开启悬浮窗按钮，然后暂时在通知渠道里把这个渠道关闭，这样这个按钮就不会显示在屏幕上了

我后续看看怎么修复

**Comment by jiegebuyaola1** [comment]
> > 保持前台服务
> 
> @jiegebuyaola1
> 
> 你的通知栏有显示吗？

有显示，但是就是不行，我测试了，界面在gkd里面，小窗开酷安能跳过，开快照悬浮窗也能跳过，关了就不行，应该就是后台识别率低，前台服务可能就识别率高了

**Comment by huanghaobaobao** [comment]
> > > 保持前台服务
> > 
> > 
> > @jiegebuyaola1
> > 你的通知栏有显示吗？
> 
> 有显示，但是就是不行，我测试了，界面在gkd里面，小窗开酷安能跳过，开快照悬浮窗也能跳过，关了就不行，应该就是后台识别率低，前台服务可能就识别率高了

看来大家都是这个问题啊

**Comment by lisonge** [comment]
并不是后台识别率低，是 GKD 在后台时，service 里的代码就不运行了

我在开发初期遇到过这个问题，在后台里写每隔 3 秒输出 1,2,3,n++ 到控制台，当 GKD 在前台时，它能输出，切到后台时就不输出了里面的代码也不运行了，后面我开启通知栏常驻之后这个问题就解决了

你们的通知栏有 GKD 的常驻通知吗？

**Comment by jiegebuyaola1** [comment]
> 并不是后台识别率低，是 GKD 在后台时，service 里的代码就不运行了
> 
> 我在开发初期遇到过这个问题，在后台里写每隔 3 秒输出 1,2,3,n++ 到控制台，当 GKD 在前台时，它能输出，切到后台时就不输出了里面的代码也不运行了，后面我开启通知栏常驻之后这个问题就解决了
> 
> 你们的通知栏有 GKD 的常驻通知吗？

![Screenshot_2023-10-09-11-45-41-006_com coolapk market](https://github.com/gkd-kit/gkd/assets/147312428/fa49dd93-8438-4df8-aa29-ecd3663a599b)
![Screenshot_2023-10-09-11-45-53-495_com miui securitycenter](https://github.com/gkd-kit/gkd/assets/147312428/6fa0c657-b22b-49eb-b4ac-4cef522742ce)
我现在就是这样，开着快照悬窗然后设置不允许悬浮窗就不会有红框影响

**Comment by jiegebuyaola1** [comment]
> 并不是后台识别率低，是 GKD 在后台时，service 里的代码就不运行了
> 
> 我在开发初期遇到过这个问题，在后台里写每隔 3 秒输出 1,2,3,n++ 到控制台，当 GKD 在前台时，它能输出，切到后台时就不输出了里面的代码也不运行了，后面我开启通知栏常驻之后这个问题就解决了
> 
> 你们的通知栏有 GKD 的常驻通知吗？

如果快照那个关了，状态栏虽然有常驻运行但是不会跳过

**Comment by lisonge** [comment]
我下个版本加个 1x1 的悬浮窗看看

**Comment by RouRouX** [comment]
> 并不是后台识别率低，是 GKD 在后台时，service 里的代码就不运行了
> 
> 我在开发初期遇到过这个问题，在后台里写每隔 3 秒输出 1,2,3,n++ 到控制台，当 GKD 在前台时，它能输出，切到后台时就不输出了里面的代码也不运行了，后面我开启通知栏常驻之后这个问题就解决了
> 
> 你们的通知栏有 GKD 的常驻通知吗？

常驻通知了，但是折叠到不重要里面了，难道和折叠到不重要有关系？

**Comment by jiegebuyaola1** [comment]
> > 并不是后台识别率低，是 GKD 在后台时，service 里的代码就不运行了
> > 我在开发初期遇到过这个问题，在后台里写每隔 3 秒输出 1,2,3,n++ 到控制台，当 GKD 在前台时，它能输出，切到后台时就不输出了里面的代码也不运行了，后面我开启通知栏常驻之后这个问题就解决了
> > 你们的通知栏有 GKD 的常驻通知吗？
> 
> 常驻通知了，但是折叠到不重要里面了，难道和折叠到不重要有关系？

不是，我没开不重要，也是不行

**Comment by RouRouX** [comment]
> > 并不是后台识别率低，是 GKD 在后台时，service 里的代码就不运行了
> > 我在开发初期遇到过这个问题，在后台里写每隔 3 秒输出 1,2,3,n++ 到控制台，当 GKD 在前台时，它能输出，切到后台时就不输出了里面的代码也不运行了，后面我开启通知栏常驻之后这个问题就解决了
> > 你们的通知栏有 GKD 的常驻通知吗？
> 
> ![Screenshot_2023-10-09-11-45-41-006_com coolapk market](https://user-images.githubusercontent.com/147312428/273494426-fa49dd93-8438-4df8-aa29-ecd3663a599b.jpg) ![Screenshot_2023-10-09-11-45-53-495_com miui securitycenter](https://user-images.githubusercontent.com/147312428/273494438-6fa0c657-b22b-49eb-b4ac-4cef522742ce.jpg) 我现在就是这样，开着快照悬窗然后设置不允许悬浮窗就不会有红框影响

GKD常驻通知且折叠到不重要通知，开启GKD内部的悬浮选项，关闭系统设置中GKD的悬浮窗权限。
知乎打开测试了一下，有效。

**Comment by lisonge** [comment]
重点应该是 关闭系统设置中GKD的悬浮窗权限，但是这样跳过提示也没有了

**Comment by RouRouX** [comment]
> 重点应该是 关闭系统设置中GKD的悬浮窗权限，但是这样跳过提示也没有了

不是下个版本都要1像素点了吗，也就可以把权限打开了，关闭权限也就是临时用着。

**Comment by jiegebuyaola1** [comment]
> 重点应该是 关闭系统设置中GKD的悬浮窗权限，但是这样跳过提示也没有了

现在看不到没办法，能明显看到到b站 酷安有点击跳过的动作，能用就行

**Comment by MrCharlesWu** [comment]
同样小米MIX4 MIUI14，GKD老是会自动被关闭无障碍权限，导致无法使用。李跳跳就没遇到这个问题，求指导解决

**Comment by Sibadaer** [comment]
可以和李跳跳作者沟通下，李跳跳安卓14目前使用Ok
