### ISSUE TITLE
更新 1.30 版本，没有默认订阅了

### ISSUE THREAD

**Issue by 8267020** [gkd-kit/gkd#126]
正常使用中，更新 1.30 以后，订阅页面就剩下本地订阅了。
https://github.com/gkd-kit/inspect/files/12840970/file.zip  日志

![Screenshot_20231008_225454_li songe gkd](https://github.com/gkd-kit/gkd/assets/105423402/6fab2853-7289-47b4-9f18-af9bfd83c5d1)
![Screenshot_20231008_225450_li songe gkd](https://github.com/gkd-kit/gkd/assets/105423402/1eb464b8-91e5-449b-a08f-042638b447d5)

**Comment by lisonge** [comment]
点击右下角+号 -> 添加默认订阅

**Comment by 8267020** [comment]
> 点击右下角+号 -> 添加默认订阅

不好意思，才接触使用，没有更新过不了解情况。

**Comment by lisonge** [comment]
不是，更新后默认订阅缺失 确实是 bug

**Comment by 8267020** [comment]
> 不是，更新后默认订阅缺失 确实是 bug

明白了
