### ISSUE TITLE
更新1.3.0以后，高级里面没有快照记录这个选项了！

### ISSUE THREAD

**Issue by 8267020** [gkd-kit/gkd#127]
手机端看不到已经创见的快照，也不能删除快照了！

**Comment by dlh996** [comment]
有这个选项，你点一下最下边试试。这个界面忘了加滚动了。超出长度，给遮挡住了。 @lisonge

**Comment by 8267020** [comment]
是，点下面的空白处 能行。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
