### ISSUE TITLE
GKD网络权限疑问

### ISSUE THREAD

**Issue by 157152816** [gkd-kit/gkd#128]
您好，我问一下：GKD调用了网络权限后，除了规则订阅外，是否还会有其它功能需求，如个人数据上传等？手机型号vivo

**Comment by 157152816** [comment]
如果清除最近任务，APP就需要重新启动。

**Comment by lisonge** [comment]
> 是否还会有其它功能需求

快照上传

> 如个人数据上传等？

无

**Comment by lisonge** [comment]
> GKD隐藏最近任务后台失效

确实有小点问题，可以通过操作步骤解决 <https://github.com/gkd-kit/gkd/issues/56#issuecomment-1731846396>

这个问题将在下个版本修复
