### ISSUE TITLE
后台隐藏无效（开启后，后台依旧可以看见该程序）

### ISSUE THREAD

**Issue by AdamWfeng** [gkd-kit/gkd#130]
## 环境
* OPPO ColorOS 13
* Android Version : 13
* Device Model : PFEM10
* Android SDK : 33

## 描述
开启后台隐藏后，回到主页后，在打开最近任务，依旧可以看到该程序。

## 复现
![Screenshot_2023-10-09-12-15-53-87_b783bf344239542](https://github.com/gkd-kit/gkd/assets/117447272/c6222f85-f067-471b-acf9-aef8453329df)

**Comment by RouRouX** [comment]
如果从GKD直接切换到最近任务我是能看到的，如果返回到桌面，再次进入最近任务就看不到了。

k40 miui14

**Comment by AdamWfeng** [comment]
> 如果从GKD直接切换到最近任务其他的程序我也是能看到的，如果在GKD滑动手势返回到桌面，再次进入最近任务就看不到了。
> 
> k40 miui14

我是回到桌面后，在进入最近任务，依然可以看到。

**Comment by KiWinger** [comment]
> > 如果从GKD直接切换到最近任务其他的程序我也是能看到的，如果在GKD滑动手势返回到桌面，再次进入最近任务就看不到了。
> > k40 miui14
> 
> 我是回到桌面后，在进入最近任务，依然可以看到。

使用 “返回” 键回到桌面即可隐藏
不能使用主页键（上滑）

**Comment by AdamWfeng** [comment]
> > > 如果从GKD直接切换到最近任务其他的程序我也是能看到的，如果在GKD滑动手势返回到桌面，再次进入最近任务就看不到了。
> > > k40 miui14
> > 
> > 
> > 我是回到桌面后，在进入最近任务，依然可以看到。
> 
> 使用 “返回” 键回到桌面即可隐藏 不能使用主页键（上滑）

谢谢提供解决方法，刚刚尝试了一下，这样确实就隐藏了，但是我使用李跳跳，使用主页键（上滑），就看不见了，就来提了一手 issue ，哈哈哈

**Comment by lisonge** [comment]
> 谢谢提供解决方法，刚刚尝试了一下，这样确实就隐藏了，但是我使用李跳跳，使用主页键（上滑），就看不见了。

确实是个小 bug，将在下个版本解决，使用 HOME/MENU 键也能隐藏

**Comment by lliioollcn** [comment]
#139 
上次忘了在重启应用之后启用该功能，也就是说只有在切换开关后才生效
现在会在应用页面直接切换到最近任务时自动移除页面，并且修复了在重启应用后从应用页面退出隐藏不生效的功能
