### ISSUE TITLE
能否支持设定点击的范围？

### ISSUE THREAD

**Issue by skyfire0705** [gkd-kit/gkd#131]
遇到一个场景：
页内广告的关闭按钮刚好和app本身的功能按钮重叠了，点击器会不停点击app按钮，无法关闭广告。比如百度贴吧、NGA

**Comment by Snoopy1866** [comment]
切换点击节点至 `clickable=true` 的控件可以解决这个问题，但有些规则的目标节点不是 `clickable=true`，向上找父节点也能也没有 `clickable=true` 的节点

**Comment by skyfire0705** [comment]
您好，我已收到您的邮件~

**Comment by skyfire0705** [comment]
能否加个功能，点击时判断是否在屏幕中的指定区域，比如离底部多少百分比或多少像素这样。

**Comment by lisonge** [comment]
duplicate

https://github.com/gkd-kit/gkd/issues/10
