### ISSUE TITLE
批量全部打开/关闭规则？

### ISSUE THREAD

**Issue by Anivie** [gkd-kit/gkd#132]
发现默认规则列表里有很多功能都是默认关闭的，是否考虑添加一键开/关功能给受不了任何打扰的“极端”用户方便的控制规则？

**Comment by Snoopy1866** [comment]
好家伙，地图定位权限都给你关了🤣
- https://github.com/gkd-kit/subscription/issues/141

**Comment by Snoopy1866** [comment]
也有不少规则是容易误触的，默认是关闭的。

**Comment by Anivie** [comment]
> 也有不少规则是容易误触的，默认是关闭的。

这类规则不是已经被标记为“容易导致误触”了吗，可以在遍历的时候规避掉或者用户手动选择
再者，既然已经是极端用户了完全可以忽略这些风险，只要在一键开启的时候toast提醒一下就行了

**Comment by small-ora** [comment]
我有类似的需求,很多规则都是默认关闭的,新增的规则都不知道有哪些,建议每次新增规则以后能发送一个通知,点击通知以后进入app页面,app页面会跳出本次新增的规则,然后用户可以直接在这里点击需要哪些规则开启.

**Comment by Sec-ant** [comment]
这个和 #87 应该可以合并为同一个需求（引用一下）
