### ISSUE TITLE
可以实现自定义规则：打开高德导航回家后，分享行程到微信给指定朋友么？？

### ISSUE THREAD

**Issue by Hchunjun** [gkd-kit/gkd#134]
这个是我生活中经常用到的场景，每次下班回家，家里老是想知道我到哪里了？所以每次我都导航后手动点点点。。、。 很麻烦

**Comment by Snoopy1866** [comment]
这个建议自定义吧，毕竟每个用户的微信好友都不一样。

**Comment by lisonge** [comment]
这个不好弄，建议你使用 autojs 一类的更灵活的工具自己实现
