### ISSUE TITLE
悬浮窗快照 偶发单击无反应

### ISSUE THREAD

**Issue by jiuqianyuan** [gkd-kit/gkd#137]
手机：Xiaomi 
OS: MIUI14 Android 13
GKD Version: 1.3.0

有的时候悬浮窗快照按钮 点一次会没反应，
必须双击，虽然会提示“正在截屏，不可重复截屏”，但快照可成功生成。

**Comment by 8267020** [comment]
特别是遇到倒计时开屏广告的时候，着急拍照拍不了。到底是单机拍照还是双击。

**Comment by lisonge** [comment]
> 特别是遇到倒计时开屏广告的时候，着急拍照拍不了。到底是单机拍照还是双击。

单击/双击 都行，因为在保存快照期间，重复点击按钮只会弹出重复点击提示，不会造成其它行为
