### ISSUE TITLE
默认订阅被覆盖

### ISSUE THREAD

**Issue by DearZack** [gkd-kit/gkd#138]
比如默认订阅里某个APP的规则A默认是关的，我把它打开了，但是更新默认订阅后，会被覆盖，就又变成关的了
是否可以对修改过的规则数据不覆盖？

**Comment by lisonge** [comment]
> 但是更新默认订阅后，会被覆盖

因为 v1.3.0 把数据库合并了，之前的某些旧数据我懒得做迁移，所以就和出现配置丢失的情况，这个情况后面不会出现了
