### ISSUE TITLE
Android 14闪退

### ISSUE THREAD

**Issue by nxyd** [gkd-kit/gkd#14]

**Comment by lisonge** [comment]
感谢反馈，但是我没有 android 14 设备，请问你的手机型号具体是什么

**Comment by nxyd** [comment]
三星s23u

**Comment by lisonge** [comment]
好的，我已经在 bugly 后台看到了这个错误，后续版本会修复，感谢反馈

**Comment by DoveBoy** [comment]
同样的问题，Android 14闪退

**Comment by lisonge** [comment]
可以试试，应该没问题了 <https://github.com/gkd-kit/gkd/releases/download/v1.1.0/app-release-v1.1.0.apk>

**Comment by DoveBoy** [comment]
然后又出来了新问题，无障碍一直故障，无法使用
![Screenshot_2023-09-09-21-56-06-83_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/gkd-kit/gkd/assets/19201447/84084144-dffa-4a89-a184-6c8e26d616cc)

**Comment by lisonge** [comment]
感谢反馈，抱歉是我疏忽了，异常应该是
```txt
java.lang.RuntimeException:Unable to create service li.songe.gkd.service.ManageService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type callerApp=ProcessRecord{b5b31e7 2795:li.songe.gkd:remote/u0a376} targetSDK=34
```
这次我把android14模拟器装上实测一遍

**Comment by lisonge** [comment]
这次在 android 14 模拟器上测试了没问题

使用 github action 构建了一下，可以用这个蓝奏云下载 <https://lisonge.lanzouy.com/i7ZpY17va57c>

如果没问题的话我就正式发一个版本了

**Comment by DoveBoy** [comment]
可以了，无障碍服务能正常开启了

**Comment by DoveBoy** [comment]
能否优化下耗电问题，跟同类比较耗电有点厉害呀
![Screenshot_2023-09-10-09-40-07-72_0ba066473b79d6e213a1f6f52505e2ee](https://github.com/gkd-kit/gkd/assets/19201447/72d2e631-951e-4df2-8a7f-c520573d0eee)
![Screenshot_2023-09-10-09-40-13-64_0ba066473b79d6e213a1f6f52505e2ee](https://github.com/gkd-kit/gkd/assets/19201447/958d6eb3-31ba-47c8-9846-2393cfa56f10)

**Comment by lisonge** [comment]
好的，后续会优化耗电问题

**Comment by DoveBoy** [comment]
> 然后又出来了新问题，无障碍一直故障，无法使用 ![Screenshot_2023-09-09-21-56-06-83_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/19201447/266784829-84084144-dffa-4a89-a184-6c8e26d616cc.jpg)

@lisonge 此现象1.2.0版本又出来了，请修复

**Comment by lisonge** [comment]
我在 bugly 看又是 Android14 广播的参数错误问题，会尽快修复

**Comment by DoveBoy** [comment]
@lisonge 等修复🤣

**Comment by lisonge** [comment]
先在 android 14 上暂停使用 shizuku 后续再支持，https://github.com/gkd-kit/gkd/releases/tag/v1.2.1

应该是由于 <https://github.com/RikkaApps/Shizuku-API/issues/54> 导致的

**Comment by DoveBoy** [comment]
> 先在 android 14 上暂停使用 shizuku 后续再支持，[`v1.2.1` (release)](https://github.com/gkd-kit/gkd/releases/tag/v1.2.1)
> 
> 应该是由于 [RikkaApps/Shizuku-API#54](https://github.com/RikkaApps/Shizuku-API/issues/54) 导致的

好像Android 14上就不给用adb了，shizuku和黑阈都不能用，shizuku根本激活不了，黑阈激活后就立马掉了，不知道是软件不适配还是adb限制了
