### ISSUE TITLE
发现有时侯APP第一次打开，不自动点击开屏广告。。。

### ISSUE THREAD

**Issue by drw2005** [gkd-kit/gkd#144]
手头有一个闲置OPPO手机，平时专门用作考勤APP用，
今天早上打开考勤APP，开屏广告并没有自动点击，读秒过后自已退出的，
尝试着再打开APP，开屏广告自动点击了。后面再连续打开都能自动点击，
感觉第一次没唤醒似的。

请问大佬这是何原因？

**Comment by lisonge** [comment]
打开 APP - 设置 - 分享日志 - 把 log.zip 或者链接 发到这里

**Comment by drw2005** [comment]
> 打开 APP - 设置 - 分享日志 - 把 log.zip 或者链接 发到这里

https://github.com/gkd-kit/inspect/files/12865784/file.zip

**Comment by drw2005** [comment]
中间反复打开过APP，还重启过一次手机，不知道可影响这个日志。

**Comment by lisonge** [comment]
你的考勤 APP 是 `得力e+` 吗?

根据日志 `10:20:11`  你第一次打开了然后是触发了点击的

你第二次打开是在 `14:17:41` ，这个也是触发了的

不触发是什么时候 ?

**Comment by drw2005** [comment]
> 你的考勤 APP 是 `得力e+` 吗?
> 
> 根据日志 `10:20:11` 你第一次打开了然后是触发了点击的
> 
> 你第二次打开是在 `14:17:41` ，这个也是触发了的
> 
> 不触发是什么时候 ?

是得力E+，不触发是今天上午用这个手机第一次打开这个app的时候。眼看着开屏广告自己读秒退出，没有触发点击。

这几天如果再出现这种情况，我第一时间上传日志。

**Comment by lisonge** [comment]
有 toast 提示吗 ?

**Comment by drw2005** [comment]
> 有 toast 提示吗 ?

toast提示是什么？反正没看到任何提示。

**Comment by lisonge** [comment]
设置 - 点击提示 这个有没有打开 ?

就是当触发跳过的时候，会不会提示一些文字 ?

**Comment by drw2005** [comment]
> 设置 - 点击提示 这个有没有打开 ?
> 
> 就是当触发跳过的时候，会不会提示一些文字 ?

这个没有打开，所以也没有提示。

**Comment by lisonge** [comment]
那你打开看看，等下次就行

**Comment by RouRouX** [comment]
是不是和打开方式不同有关系？
我发现我从知乎系统通知点进去知乎不会自动点击，结束任务从图标打开可以跳过。原因我也不确定。

**Comment by lisonge** [comment]
> 我发现我从知乎系统通知点进去知乎不会自动点击

你可以提供这个快照

**Comment by drw2005** [comment]
> 那你打开看看，等下次就行

刚才又出现不点击的情况了，日志：
https://github.com/gkd-kit/inspect/files/13050882/file.zip

另外，点击提示之前也打开了，但是这次也没见有提示。

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/gkd/assets/38517192/12da5544-f9f5-4077-896c-33872881ba85)

根据日志是匹配界面了的，估计是开屏广告的种类不一样，导致现有规则无法适配

**Comment by lisonge** [comment]
下次你可以额外提供快照看看

**Comment by drw2005** [comment]
> 下次你可以额外提供快照看看

好的。

还有，大多数的跳过都在右上角，为啥不弄个通用规则呢？

**Comment by lisonge** [comment]
> 大多数的跳过都在右上角，为啥不弄个通用规则呢？

没想好通用规则怎么弄，就目前来看唯一有用的通过规则是 点击包含 `跳过` 的文本控件

**Comment by drw2005** [comment]
> > 大多数的跳过都在右上角，为啥不弄个通用规则呢？
> 
> 没想好通用规则怎么弄，就目前来看唯一有用的通过规则是 点击包含 `跳过` 的文本控件

参考一下李跳跳，他的通用规则非常好用，而且最重要的是，反应太快了。

**Comment by Sibadaer** [comment]
借鉴下李跳跳的思路，李跳跳的跳过超级快，几乎就是秒过，目前GKD的强势是规则，要是跳广告的速度优化好那就无敌！

**Comment by drw2005** [comment]
> 借鉴下李跳跳的思路，李跳跳的跳过超级快，几乎就是秒过，目前GKD的强势是规则，要是跳广告的速度优化好那就无敌！

确实，李跳跳的跳过速度极快，这方面GKD还有明显差距，希望作者大佬把重点放到这方面来。

**Comment by drw2005** [comment]
还是偶尔出现不点击的情况，尤其最近几天连接出现不自动点击了，包括最新1.5.2版本。

快照：
https://i.gkd.li/import/13445578

日志：
https://github.com/gkd-kit/inspect/files/13445587/file.zip

**Comment by lisonge** [comment]
> 还是偶尔出现不点击的情况，尤其最近几天连接出现不自动点击了，包括最新1.5.2版本。
https://i.gkd.li/import/13445578

你这纯属规则没适配

**Comment by lisonge** [comment]
规则没有匹配你的快照

https://github.com/gkd-kit/subscription/blob/main/src/apps/com.delicloud.app.smartoffice.ts

**Comment by drw2005** [comment]
> 规则没有匹配你的快照
> 
> https://github.com/gkd-kit/subscription/blob/main/src/apps/com.delicloud.app.smartoffice.ts

不对啊，快照之前都发上来匹配过了的。

**Comment by lisonge** [comment]
规则和你的快照确定不对应，你自己应该能看出来

**Comment by drw2005** [comment]
> 规则和你的快照确定不对应，你自己应该能看出来

那好吧，我重新发快照

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/commit/35b063e86968053744a7d753d99e2beebc916b13

**Comment by lisonge** [comment]
你也可以在本地测试

```json5
{
  id: 'com.delicloud.app.smartoffice',
  name: '得力e+',
  groups: [
    {
      key: 0,
      name: '开屏广告',
      actionMaximum: 1,
      resetMatch: 'app',
      matchTime: 10000,
      rules: [
        {
          quickFind: true,
          matches: '[text*="跳过"][text.length<=10]',
          snapshotUrls: 'https://i.gkd.li/import/13445578',
          exampleUrls:
            'https://m.gkd.li/38517192/52482ac3-a5aa-4559-a006-0103ea0b8238',
        },
        {
          matches: '[id="com.byted.pangle:id/tt_splash_skip_btn"]',
          snapshotUrls: ['https://i.gkd.li/import/12843738'],
        },
      ],
    },
  ],
}
```
