### ISSUE TITLE
新荣耀机型有时能够跳过广告，有时候不行，一般是几个小时行，几小时不行

### ISSUE THREAD

**Issue by oiflippy** [gkd-kit/gkd#145]
目前手边magic5和x50都会这样，GKD软件内一切正常,不显示错误
https://github.com/gkd-kit/inspect/files/12865869/file.zip
这是magic5的日志

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/146

按照这个试试呢 ?

**Comment by oiflippy** [comment]
> #146
> 
> 按照这个试试呢 ?
可以用悬浮窗的方法解决。

**Comment by oiflippy** [comment]
> #146
> 
> 按照这个试试呢 ?

这个方法可以解决

**Comment by oiflippy** [comment]
> 试试这个测试版本呢
> 
> [debug.zip](https://github.com/gkd-kit/gkd/files/13054914/debug.zip)
> 
> 使用这个的时候，先把正式版关闭

目前使用了一天没有问题
