### ISSUE TITLE
MIUI14 安卓14，手机已经root, 开启了无障碍，开启了shizuku，服务也开启了，就是没效果，不跳过任何广告

### ISSUE THREAD

**Issue by Sibadaer** [gkd-kit/gkd#146]
[log.zip](https://github.com/gkd-kit/gkd/files/12866834/log.zip)

**Comment by lisonge** [comment]
如果开启悬浮窗能否跳过

**Comment by lisonge** [comment]
通知栏显示什么文字 ?

**Comment by Sibadaer** [comment]
打开悬浮窗，功能可能，但是屏幕上有个红色的放大镜，很影响体验
![1ae411336bb3d7253d9ae93bc763824](https://github.com/gkd-kit/gkd/assets/38148262/f1b0fc54-c492-4582-a89c-bb9a6a689b9c)

**Comment by Sibadaer** [comment]
![3f1ad5d314b4868760e8919dd8119f2](https://github.com/gkd-kit/gkd/assets/38148262/534c814f-d88c-4fad-a042-27a73b840d43)

**Comment by lisonge** [comment]
> 但是屏幕上有个红色的放大镜，很影响体验

GKD在系统的应用设置 - 通知 - 通知渠道 - 关闭悬浮窗按钮的这个渠道

**Comment by Sibadaer** [comment]
按照你的步骤操作，去除不了，请教下，为啥单独的无障碍不起作用？

https://github.com/gkd-kit/gkd/assets/38148262/293e6d6f-e855-4abf-a787-9caaa9e7dc1a

**Comment by Sibadaer** [comment]
按照你的步骤操作，去除不了，请教下，为啥单独的无障碍不起作用？


https://github.com/gkd-kit/gkd/assets/38148262/991ce9ff-4111-40a8-b4b3-2334c7a775b1

**Comment by lisonge** [comment]
> 按照你的步骤操作，去除不了，请教下，为啥单独的无障碍不起作用？

不好意思，我搞错了，通知渠道关闭是去掉通知栏的 按钮通知

去掉红色的悬浮窗是 `应用信息 - 权限管理 - 显示悬浮窗 - 拒绝`

**Comment by Sibadaer** [comment]
按照你的步骤操作，去除不了，请教下，为啥单独的无障碍不起作用？

https://github.com/gkd-kit/gkd/assets/38148262/f5beb31c-ba04-4669-a36b-0070cf15d20a

**Comment by Sibadaer** [comment]
> > 按照你的步骤操作，去除不了，请教下，为啥单独的无障碍不起作用？
> 
> 不好意思，我搞错了，通知渠道关闭是去掉通知栏的 按钮通知
> 
> 去掉红色的悬浮窗是 `应用信息 - 权限管理 - 显示悬浮窗 - 拒绝`

关闭了悬浮窗权限，软件肯定运行不了，你这个软件需要悬浮窗权限的，进入了死循环

**Comment by lisonge** [comment]
并不是，你先打开红色的悬浮窗，然后再关闭悬浮窗权限就行

**Comment by Sibadaer** [comment]
> 并不是，你先打开红色的悬浮窗，然后再关闭悬浮窗权限就行
操作没达到预期

Uploading 70994885ab398bc9cb93401be510f4c1.mp4…

**Comment by Sibadaer** [comment]
> 并不是，你先打开红色的悬浮窗，然后再关闭悬浮窗权限就行

https://github.com/gkd-kit/gkd/assets/38148262/99d162a7-fe85-4b33-9e05-60722f573e44

**Comment by Sibadaer** [comment]
> > 并不是，你先打开红色的悬浮窗，然后再关闭悬浮窗权限就行
> 
> c53d5256786d677d93ffd01d3391accd.mp4

我操作了一下，是死循环啊！

**Comment by lisonge** [comment]
什么死循环，你是说这个授权按钮吗？那就让它在就行，不影响的，悬浮窗授权并不是 APP 运行的必要条件

![image](https://github.com/gkd-kit/gkd/assets/38517192/8995860b-fa85-4bc7-bd32-4b67c6411130)

**Comment by Sibadaer** [comment]
> 什么死循环，你是说这个授权按钮吗？那就让它在就行，不影响的，悬浮窗授权并不是 APP 运行的必要条件
> 
> ![image](https://user-images.githubusercontent.com/38517192/274215383-8995860b-fa85-4bc7-bd32-4b67c6411130.png)

好的 谢谢 是我理解错了， 我以为这个权限是必须的！
