### ISSUE TITLE
耗电量有点高

### ISSUE THREAD

**Issue by kmk709** [gkd-kit/gkd#147]
背景近7h，耗电占比7％
![Screenshot_20231011_184209_Device care.jpg](https://github.com/gkd-kit/gkd/assets/58921795/88cfad1b-9e9b-40c7-b688-85eb30a88274)

![Screenshot_20231011_184214_Device care.jpg](https://github.com/gkd-kit/gkd/assets/58921795/4e8b482c-4811-4907-aa8f-d7908f366726)

**Comment by lisonge** [comment]
duplicate

https://github.com/gkd-kit/gkd/issues/37
