### ISSUE TITLE
不希望看到点击记录，是否可以提供日志的开关

### ISSUE THREAD

**Issue by dong-jpg** [gkd-kit/gkd#151]
在使用过程中可以自行明显感知到广告跳过，不需要app中记录这么多的日志，不清楚长久使用后的日志占用，实在是不想隔一段时间上去清理一下记录，希望可以添加一个点击记录的开关用于关闭。我准备给家里老人的手机上安装，我希望的是可以在老人手机里安静的保护他们的手机，而不需要在安装后仍然得隔一段时间上去处理一下什么防止出现问题。

**Comment by lisonge** [comment]
日志只会保留最近7天的
