### ISSUE TITLE
失效反馈

### ISSUE THREAD

**Issue by chendi1915** [gkd-kit/gkd#153]
手机是iqoo11 
gkd版本1.3.0
手机静止一段时间软件失效
查看无障碍显示无法运行，取消并重新授权才能恢复
![Screenshot_2023_1012_130932.png](https://github.com/gkd-kit/gkd/assets/146543867/b07fcef9-c2f3-4954-94a1-a70173b6189e)

**Comment by 888818** [comment]
我之前也这样，把GKD软件设置自启动就好了

**Comment by chendi1915** [comment]
都设置了的![Screenshot_2023_1016_130131.png](https://github.com/gkd-kit/gkd/assets/146543867/66949063-a49b-46d4-b6e0-adc9b893cfc6)

**Comment by lisonge** [comment]
> 查看无障碍显示无法运行，取消并重新授权才能恢复

内部有 bug 崩溃了

---

https://github.com/gkd-kit/gkd/releases

请使用最新版本
