### ISSUE TITLE
GKD规则交流QQ群(非官方，官方目前只使用Github)

### ISSUE THREAD

**Issue by lisonge** [gkd-kit/gkd#158]
![1697111402680_temp_qrcode_share_9993](https://github.com/gkd-kit/gkd/assets/38517192/a56a1026-d352-46b7-b9f9-6160ffef6f60)

群主是这位 @Snoopy1866 ，群里面人挺多的

---

此外如果是 GKD 使用的问题可以去 [gkd/issues](https://github.com/gkd-kit/gkd/issues)

如果是 规则不生效 的问题可以去 [subscription/issues](https://github.com/gkd-kit/subscription/issues)

**Comment by Snoopy1866** [comment]
感谢大佬宣传🤣

**Comment by BakaJzon** [comment]
有tg群或者matrix吗

**Comment by lisonge** [comment]
> 有tg群或者matrix吗

抱歉，暂不考虑，我其实除了看黄色不咋用 tg

**Comment by Snoopy1866** [comment]
> 有tg群或者matrix吗

https://t.me/+Uhl4QGfjW4RlNWRl

**Comment by STEEY-ST** [comment]
Uploading Screenrecorder-2023-12-24-00-36-42-532.mp4…

豆瓣开屏无法跳过

**Comment by BakaJzon** [comment]
@STEEY-ST 请另开 issue ，谢谢。
另外，你的视频上传失败了。

开发者是否考虑在 issue template 加一个规则反馈？

**Comment by momingcai** [comment]
大佬，软件规则适配问题在哪里反馈，有个广告软件困扰许久了，一直没有规则治他，叫趣智校园

**Comment by BakaJzon** [comment]
广告规则前往此处提交： [gkd-kit/subscription](https://github.com/gkd-kit/subscription/issues)
请不要在此处反馈规则问题

**Comment by adproqwq** [comment]
1群已满，请加2群：343615129

**Comment by Snoopy1866** [comment]
![85ea79c73efb5d53c967a29d82edcff](https://github.com/gkd-kit/gkd/assets/45487685/d2fdb960-95e9-4bea-9646-9f700405628d)

**Comment by adproqwq** [comment]
Discord：https://discord.gg/EAabdyPu
