### ISSUE TITLE
建议快照创建时支持马赛克

### ISSUE THREAD

**Issue by du33169** [gkd-kit/gkd#16]
部分应用界面快照截图会带有个人信息，不便上传，最好允许并主动提示用户对快照进行打码处理

**Comment by Sec-ant** [comment]
支持这个功能。

同时增加一个小需求，希望可以允许用户自定义一个顶部状态栏高度，每次快照的时可以选择是否模糊/涂抹掉状态栏。

**Comment by lisonge** [comment]
> 每次快照的时可以选择是否模糊/涂抹掉状态栏。

这个后续会增加一个开关控制

---

> 最好允许并主动提示用户对快照进行打码处理

这个后续会增加用户提示，以及快照截图的编辑替换操作

**Comment by aoguai** [comment]
单纯打码的话，在zip里面组件里面的text或者desc还是会可能包含隐私。

**Comment by lisonge** [comment]
你可以手动编辑里面的 json 文件的 text 和 desc 使用等价数量的 `*/#` 代替即可

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0

**Comment by XFFF2022** [comment]
对于已经上传的快照可以申请删除吗
