### ISSUE TITLE
下回版本更新建议

### ISSUE THREAD

**Issue by 1019763141** [gkd-kit/gkd#160]
本地规则能都像一指禅自定义规则一样快捷方便.
用户自己查找出特征控件和目标控件，软件自己链接路径
1.降低操作水平，用户测试通过可以直接上传，开发者负责审核
2.这样一来会有更多人提交，减少大量维护者时间
![f2a2c7ce4aecaf3a344a3053aeec069](https://github.com/gkd-kit/gkd/assets/29418438/5ba73db1-d970-4452-b1da-9e6a57821619)

**Comment by lisonge** [comment]
> 本地规则能都像一指禅自定义规则一样快捷方便.

选择器和规则太复杂，不予支持，可以先了解一下选择器 <https://github.com/gkd-kit/selector>

> 用户自己查找出特征控件和目标控件，软件自己链接路径

APP 目前不考虑支持较复杂的ui，你可以使用网页审查工具 https://github.com/gkd-kit/inspect

> 降低操作水平，用户测试通过可以直接上传，开发者负责审核

没有服务器，也不会做服务器，这个 APP 在设计之初就已经决定不依靠任何私人服务器

唯一的方式是向 https://github.com/gkd-kit/subscription 提起 pr，或者你自己维护一个

**Comment by lisonge** [comment]
APP 内部只提供简单的编辑输入

复杂的输入可以通过网页工具来实现，网页开发快，部署后无需安装用户就能获取最新代码
