### ISSUE TITLE
自己添加本地订阅，导致本地订阅规则清空，并且无法再次添加任何本地规则。

### ISSUE THREAD

**Issue by 8267020** [gkd-kit/gkd#166]

**Comment by lisonge** [comment]
> 并且无法再次添加任何本地规则

具体如何表现呢?

**Comment by 8267020** [comment]
刚才不小心按了回车键，就发出来了。

具体现象如下。

我自己摸索这添加本地规则，在同一个app里面使用了相同的key，添加进去以后直接清空本地规则。显示“-2  此订阅文件暂无规则”
点加号没任何反应，只能清空GKD的app数据重新配置。

后来我把规则里面的key，改成不通的序号。再次添加就正常了！

懂的人肯定不会犯这样的错误，但是我想着如果能检测一下这个错误，也能避免数据被清空。

**Comment by lisonge** [comment]
> 后来我把规则里面的key，改成不通的序号。再次添加就正常了！
但是我想着如果能检测一下这个错误，也能避免数据被清空。

这个检测是存在的，但是看你的描述应该是有点 bug，感谢反馈，后续会修复

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.5.0
