### ISSUE TITLE
是否可以在规则中添加执行次数

### ISSUE THREAD

**Issue by Cupid-y** [gkd-kit/gkd#167]
某监控APP选择“超清”画质需要会员，自己写了一个GKD规则用于变相实现“始终超清”
![image](https://github.com/gkd-kit/gkd/assets/73457325/47fb99e8-b65e-4ccc-8393-234367b3ccf5)

但由于不是广告，用规则执行click后，“标清/超清”选择按钮不会消失，导致会一直循环该规则
效果见视频：
**https://github.com/gkd-kit/gkd/assets/73457325/309f277f-a65b-472d-98f2-e340472d91fd**

**Comment by Cupid-y** [comment]
快照如下：
https://gkd-kit.gitee.io/snapshot/1697304867105
![image](https://github.com/gkd-kit/gkd/assets/73457325/9cef7d50-d02c-4953-9225-1e907a9a33da)


https://gkd-kit.gitee.io/snapshot/1697304870786
![image](https://github.com/gkd-kit/gkd/assets/73457325/e96c16a1-747f-47cc-a2f9-ca69bd2c4c43)

**Comment by lisonge** [comment]
> 是否可以在规则中添加执行次数

这个是后续正在增加的功能，执行次数，执行时间 相关的字段都会增加

> 用规则执行click后，“标清/超清”选择按钮不会消失，导致会一直循环该规则

如果是你正常操作，你点击 超清 后，会如何操作去关闭这个按钮呢？

**Comment by lisonge** [comment]
> https://gkd-kit.gitee.io/snapshot/1697304870786

链接是错的，这个是你本地浏览器的链接，它只在本地生效，你应该点击右上角的 分享 按钮，生成链接-zip

**Comment by Cupid-y** [comment]
> > 是否可以在规则中添加执行次数
> 
> 这个是后续正在增加的功能，执行次数，执行时间 相关的字段都会增加
> 
> > 用规则执行click后，“标清/超清”选择按钮不会消失，导致会一直循环该规则
> 
> 如果是你正常操作，你点击 超清 后，会如何操作去关闭这个按钮呢？

按钮会自动消失
视频：
https://github.com/gkd-kit/gkd/assets/73457325/473d55d6-b8a8-424d-871d-1d98344cddb1

**Comment by Cupid-y** [comment]
> > https://gkd-kit.gitee.io/snapshot/1697304870786
> 
> 链接是错的，这个是你本地浏览器的链接，它只在本地生效(比如你换个浏览器打开这个链接就失效了)
> 
> 你应该点击右上角的 分享 按钮，生成链接-快照(这个链接是通用的)

https://gkd-kit.gitee.io/import/12907107
https://gkd-kit.gitee.io/import/12907189

**Comment by lisonge** [comment]
下个版本会支持

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
