### ISSUE TITLE
鸿蒙3.0和MIUI14好像都不太行

### ISSUE THREAD

**Issue by acesaint** [gkd-kit/gkd#168]
手机，Pixel 5，安卓14，一切正常，微博极速版也能跳过信息流广告；
手机，mate 20，鸿蒙3.0，信息流广告无法跳过；
MIUI 14，同样的，信息流广告无法跳过；

**Comment by jiuqianyuan** [comment]
按照文档 生成快照上传看看才知道

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
