### ISSUE TITLE
1.3.0版本的activityIds检测存在问题

### ISSUE THREAD

**Issue by Etern213** [gkd-kit/gkd#169]
复现方式如下，比如我正在写一个斗鱼直播间页面内广告的关闭规则：
```
activityIds: tv.douyu.view.activity.PlayerActivity
matches: ImageView < ViewGroup + ViewGroup > ImageView
```
找到了唯一的关闭按钮，测试广告可以成功关闭。

但是在退出直播间以后，退出到一个`activityIds`是`com.douyu.module.findgame.tailcateb.page.TailCateBActivity`的页面，上述规则`ImageView < ViewGroup + ViewGroup > ImageView`又被执行了，导致误点情况存在。

分析：
尽管在第二个页面上也有匹配规则`ImageView < ViewGroup + ViewGroup > ImageView`的元素存在，但是`activityIds`是完全对不上的，不应该执行才对，但是gkd貌似执行了，推测是`activityIds`的检测有延迟，导致在切换页面的时候先检测了`activityIds`匹配，然后等执行的时候没有再次检测`activityIds`导致在错误的页面上再次执行规则。

以下是完整的规则代码：
```
{
  id: 'air.tv.douyu.android',
  name: '斗鱼',
  groups: [
    {
      key: 0,
      name: '旧版直播间页面内广告',
      activityIds: [
        'tv.douyu.view.activity.PlayerActivity',
      ],
      rules: [
        {matches: 'ImageView < ViewGroup + ViewGroup > ImageView'}, // 弹幕区域右上角广告
      ],
    },
  ],
}
```

**Comment by lisonge** [comment]
这个 activityIds 检测延迟确实存在，后面修复一下

**Comment by lisonge** [comment]
> 退出到一个activityIds是com.douyu.module.findgame.tailcateb.page.TailCateBActivity的页面，上述规则ImageView < ViewGroup + ViewGroup > ImageView又被执行了，导致误点情况存在

暂时的解决方法是 在原有选择器上 加入一些两个页面不同的节点来判断

**Comment by Etern213** [comment]
> > 退出到一个activityIds是com.douyu.module.findgame.tailcateb.page.TailCateBActivity的页面，上述规则ImageView < ViewGroup + ViewGroup > ImageView又被执行了，导致误点情况存在
> 
> 暂时的解决方法是 在原有选择器上 加入一些两个页面不同的节点来判断
> 
> 

是的，我换了一个不会冲突的匹配方案，暂时避免了这个问题。

能让开发者定位到bug就ok了

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases

是 android 系统的问题，Android 检测 activityId 变更慢于 界面节点变化

使用最新版本有两种方法解决

- 使用 actionDelay ，延迟点击，延迟点击的时候会重新判断 activityId，大概 200-500ms 
- 使用 shizuku，shizuku 提供了主动获取 activityId 的 api，可以准时获取正确的 activityId
