### ISSUE TITLE
[feat] 提供批量删除点击记录和快照记录的选项

### ISSUE THREAD

**Issue by Sec-ant** [gkd-kit/gkd#17]
如题

**Comment by Snoopy1866** [comment]
非常需要这个功能，我的 GKD 存储占用马上就可以突破 1G 了🤣
![06d7495671f8856c07e08bb30bd88d1](https://github.com/gkd-kit/gkd/assets/45487685/871a1652-b551-4e91-b40a-c1e7f80ba51d)

**Comment by lisonge** [comment]
你可以暂时写一个规则来批量删除

**Comment by Snoopy1866** [comment]
> 你可以暂时写一个规则来批量删除

6，天才般的想法

**Comment by Sec-ant** [comment]
> 你可以暂时写一个规则来批量删除

这样会不会每次删一条点击记录都会同时增加两条点击记录？😂

**Comment by Snoopy1866** [comment]
> > 你可以暂时写一个规则来批量删除
> 
> 这样会不会每次删一条点击记录都会同时增加两条点击记录？😂

会的，所以可以批量快照，而不能批量删除点击记录🤣

**Comment by lisonge** [comment]
> > 你可以暂时写一个规则来批量删除
> 
> 这样会不会每次删一条点击记录都会同时增加两条点击记录？😂

好像是的 🤣

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0
