### ISSUE TITLE
本地订阅-复制粘贴字体空白

### ISSUE THREAD

**Issue by jiuqianyuan** [gkd-kit/gkd#175]
本地订阅-添加规则-   “复制粘贴”功能不显示字体，盲点又是正常的，是不是字体颜色问题。
小米手机 安卓13  MIUI14，白天、深色模式都这样
![Screenshot_2023-10-16-18-07-02-596_li songe gkd](https://github.com/gkd-kit/gkd/assets/39406781/d7b06295-0134-46d7-b35e-e4a8a4045dd8)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/55
