### ISSUE TITLE
[feat] 允许用户关闭日志

### ISSUE THREAD

**Issue by wengzhenquan** [gkd-kit/gkd#176]
日志、点击记录，如果没有手动清理会不会越来越大，之后空间占用就无限大了？有没有自动清理功能？
能不能搞一个开关，可以选择关闭日志、和关闭点击记录功能？

**Comment by wengzhenquan** [comment]
说实话，这个东西日常没什么用，只有需要的时候才去看。完全可以当debug调试模式，默认不开。
如果这个软件好用，规则订阅了也好用，规则都能自动更新了。APP压根都不会再打开，记录的日志、点击记录有什么用？只需要记录点击数量就行了

**Comment by wengzhenquan** [comment]
说实话，这个东西日常没什么用，只有需要的时候才去看。完全可以当debug调试模式，默认不开。
如果这个软件好用，规则订阅了也好用，规则都能自动更新了。APP压根都不会再打开，记录的日志、点击记录有什么用？压根没人去看好吧。只有开发者或者写规则的人会去看，普通用户看都看不懂。只需要记录点击数量就行了

**Comment by dong-jpg** [comment]
作者故意的，我也提交了相关的Issues，作者的回复是日志只会保留7天，实在搞不懂一个跳广告软件为什么要带没法关闭的日志

**Comment by wengzhenquan** [comment]
> 作者故意的，我也提交了相关的Issues，作者的回复是日志只会保留7天，实在搞不懂一个跳广告软件为什么要带没法关闭的日志

7天也行吧，不会无限大就行了

**Comment by lisonge** [comment]
> 如果这个软件好用，规则订阅了也好用，规则都能自动更新了。APP压根都不会再打开，记录的日志、点击记录有什么用？压根没人去看好吧。

这个软件目前不好用

**Comment by lisonge** [comment]
> 能不能搞一个开关，可以选择关闭日志、和关闭点击记录功能

后续会增加

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
