### ISSUE TITLE
[Feature Request] Xposed 支持

### ISSUE THREAD

**Issue by alex3236** [gkd-kit/gkd#18]
首先，感谢作者开发如此方便的应用！

在保留原先功能的情况下，引入 Xposed 框架。
- 可以直接隐藏广告控件，而不是点击关闭，极大地提升体验；
- 可以直接结束开屏广告活动，而不是点击跳过，又快又省电；
  这一过程也可以自动识别适配无规则应用（打开应用时界面上有跳过按钮则自动点击，若点击后主界面活动与广告活动不同，则第二次打开时尝试直接结束广告活动，否则依然自动点跳过）
- 即使不打算做以上两点，也可以通过 Hook 保活无障碍服务。

**Comment by buzhayandehuang** [comment]
LSP可用嘛！

**Comment by lukemin** [comment]
什么时候能够支持啊？

**Comment by lisonge** [comment]
暂不考虑支持

**Comment by Foldear** [comment]
顶，支持框架吧，体验比无障碍强的不是一点半点

**Comment by xuangeyouneihan** [comment]
顶

**Comment by chenxiccc** [comment]
非常希望能够支持。体验会有质的变化。

**Comment by lisonge** [comment]
不支持
