### ISSUE TITLE
可以支持长按操作吗？

### ISSUE THREAD

**Issue by valenhuang** [gkd-kit/gkd#181]
可以支持长按操作吗？

**Comment by lisonge** [comment]
请问什么情况下需要长按操作，可否给个视频示例？

**Comment by valenhuang** [comment]
想实现一个自动化流程，里面有长按扫码的操作。希望大神能支持一下^_^

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.5.0
