### ISSUE TITLE
生效的时候可以把 振动关了吗

### ISSUE THREAD

**Issue by javabcde** [gkd-kit/gkd#183]
点击事件生效的时候可以把 振动关了吗 看了下设置 好像没有地方可以设置关闭呢

**Comment by lisonge** [comment]
我都没有申请震动权限，哪来来的震动啊？

**Comment by javabcde** [comment]
> 我都没有申请震动权限，哪来来的震动啊？
很神奇啊 难道是那个无障碍模式的震动？ 我研究研究

**Comment by lisonge** [comment]
![img_v2_43f54ac2-9d02-4f91-b95b-8d86a144213g](https://github.com/gkd-kit/gkd/assets/38517192/43c75974-37bf-4ed4-bf3a-67d91df2eb66)

你试试把通知的震动权限关闭看看？

但是我的手机这个权限是显示开启的，但是我的手机从来没有震动

你的手机是什么型号，Android 几呢？

**Comment by javabcde** [comment]
> ![img_v2_43f54ac2-9d02-4f91-b95b-8d86a144213g](https://user-images.githubusercontent.com/38517192/276208982-43c75974-37bf-4ed4-bf3a-67d91df2eb66.jpg)
> 
> 你试试把通知的震动权限关闭看看？
> 
> 但是我的手机这个权限是显示开启的，但是我的手机从来没有震动
> 
> 你的手机是什么型号，Android 几呢？

我已经研究出来了 是这个无障碍模式点击的时候 会触发震动  我是红米的 有个单独的开关  关了就行

**Comment by lisonge** [comment]
嗯嗯好的，这个也是一个问题，我会记录在后续的文档说明功能里，感谢反馈了
