### ISSUE TITLE
打开app后跳过广告有点慢

### ISSUE THREAD

**Issue by hibuddies** [gkd-kit/gkd#189]
打开app后基本要等2秒左右才会跳过，但是朋友圈和酷安内部的广告又可以秒跳过！手机是小米13u和小米13pro 安卓13的miui14，连续换了三个版本都一样的问题，如果这个能解决基本就可以完美替代李跳跳了！

**Comment by hibuddies** [comment]
测试中发现高级模式-悬浮窗模式打开的情况下就能解决这个问题，但是屏幕总显示一个方块也影响体验

**Comment by lisonge** [comment]
试试这个测试版本呢

 [debug.zip](https://github.com/gkd-kit/gkd/files/13054914/debug.zip)

使用这个的时候，先把正式版关闭

**Comment by hibuddies** [comment]
> 试试这个测试版本呢
> 
> [debug.zip](https://github.com/gkd-kit/gkd/files/13054914/debug.zip)
> 
> 使用这个的时候，先把正式版关闭

这个大多数场景好多了，但是有些摇一摇的广告会无法触发不跳过，尤其酷安的开屏十次有七八次无效

**Comment by lisonge** [comment]
> 但是有些摇一摇的广告会无法触发不跳过，尤其酷安的开屏十次有七八次无效

请提供这个无法跳过的快照看看

**Comment by rockxsj** [comment]
同样的问题，所以尝试两次都切换失败又换回李跳跳了

**Comment by nljxlove** [comment]
> 同样的问题，所以尝试两次都切换失败又换回李跳跳了

我也是这个问题，但是李跳跳乱跳的时候太多了，特别是打游戏的时候太卡顿了，只有舍弃

**Comment by phquathi** [comment]
+1，使用了几天总结了规律：应用首次启动时能百分百跳，但是之后切屏切应用再切回来时的广告就几乎不会触发。软件内部的广告时快时慢

**Comment by Sibadaer** [comment]
+1 目前很严重的问题就是，开屏广告要等2 - 3秒 才会触发跳过广告，体验很差，但有时候又很快不知道为啥！

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.5.0

**Comment by rockxsj** [comment]
> https://github.com/gkd-kit/gkd/releases/tag/v1.5.0

试了这个版本，还是一样的问题，首次打卡app的时候不会跳过，划掉app再次进大概率就会跳过了。  又切换失败了…

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues

给出不跳过快照
