### ISSUE TITLE
审查工具创建的内存规则组在应用重启后消失

### ISSUE THREAD

**Issue by du33169** [gkd-kit/gkd#19]
在审查工具连接时创建的内存规则组会在应用重启后消失，若已经关闭审查标签页则规则无法找回，造成规则调试的不便

**Comment by lisonge** [comment]
> 在审查工具连接时创建的内存规则组会在应用重启后消失

因为应用第一次启动时会清除内存订阅

<https://github.com/gkd-kit/gkd/blob/f59993d33fdd7cf89b47b94c17e87abada7a708b/app/src/main/java/li/songe/gkd/debug/HttpService.kt#L177-L188>

我之前做的时候是 HTTP 服务关闭的时候清除内存订阅，应用重启的时候 HTTP 服务自然没有运行，因此就把内存订阅清除掉了

---

调试 [订阅规则](https://github.com/gkd-kit/subscription) 时，我一般都是在 vscode 里写好，然后复制粘贴到网页发送给 APP

因为 网页编辑框没有代码提示，vscode 有代码提示，所以在 vscode 编辑的体验较好

另外后续会给 <https://github.com/gkd-kit/subscription> 加上自动更新内存订阅功能

比如只需要运行 `pnpm dev -- package.name http://1.2.3.4:8888` ，当使用 vscode 编辑文件时，自动把订阅发送给 APP，这样就能省去上面说的手动粘贴这个步骤

只需要在 vscode 简单编辑文件就能自动更新内存订阅，你上面描述的问题在这种编辑模式下自然就不存在了

**Comment by du33169** [comment]
我还是没有理解为什么要清除内存规则组，不能作为一个普通的本地订阅存在吗

我遇到的情况是写好一个规则，但应用每次打开广告的界面可能会变，需要在较长时间的使用中检测规则是否通用，因此我希望规则能够保留

如果每次都要再连一次电脑也太麻烦了

**Comment by lisonge** [comment]
> 我还是没有理解为什么要清除内存规则组，不能作为一个普通的本地订阅存在吗

内存订阅嘛，只存在于内存，就是 生命周期 和 应用/HTTP服务 一致，你应用都重启了，咋还有之前的内存

因为我在调试的时候都是希望关闭HTTP服务器的时候终止调试并且清除内存订阅，自然也就把内存订阅清除了

---

这个应用重启是啥原因，在无障碍开启的情况下，单纯在任务界面划掉APP是不会终止APP的

只有在 主动结束APP/关闭无障碍或者报错 的情况下才会重启

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/download/v1.1.0/app-release-v1.1.0.apk
