### ISSUE TITLE
贴吧一键签到大师的开屏弹窗怎么去掉

### ISSUE THREAD

**Issue by xlweiw** [gkd-kit/gkd#2]
TR com.baidutieba.Mainactivity

**Comment by lisonge** [comment]
有快照吗？把快照给我就行

**Comment by lisonge** [comment]
开屏快照 <https://gkd-kit.gitee.io/import/12504282>

**Comment by lisonge** [comment]
加上了 https://github.com/gkd-kit/subscription/blob/main/src/apps/com.baidutieba.davy.ts

一个开屏广告 https://gkd-kit.gitee.io/import/12504282

两个内部弹窗广告 https://gkd-kit.gitee.io/import/12504289 https://gkd-kit.gitee.io/import/12504291

byd 这广告还挺多

**Comment by lisonge** [comment]
注意哈，订阅是APP每小时自动更新一次

官方订阅是 https://github.com/gkd-kit/subscription

这个发布后会有最多半小时的缓存延迟

但是我自己在订阅列表下拉刷新后就已经有上面的规则了

没有更新的话可以手动下拉刷新一下
