### ISSUE TITLE
加我 willshion88 //用ai 可以把录屏 转像素xy 值 然后接 inspecter转脚本 实现 录屏转脚本

### ISSUE THREAD

**Issue by willshion** [gkd-kit/gkd#20]

**Comment by willshion** [comment]
玩ai的想合作做点东西

**Comment by willshion** [comment]
就是 转完 xy像素位置 再拿 inspecter的 控件的东西 尝试 丢给gpt/或 code-llama 去实现

**Comment by lisonge** [comment]
你好，感谢使用 GKD ，但是非常抱歉我暂时没有精力去做这个，请问你说的这个东西有相关的 demo 展示吗？我感觉有点悬

**Comment by willshion** [comment]
https://github.com/z-x-yang/Segment-and-Track-Anything  
![top](https://github.com/gkd-kit/gkd/assets/13349979/d6bfac20-49d2-4be9-ab57-08833ed936b7)

**Comment by willshion** [comment]
我把 录屏转xy 给你 然后 你监控 用户下按屏幕的时候 就触发快照

**Comment by willshion** [comment]
你帮我 弄点击然后触发快照的 选项更新一下 应该可以了

**Comment by lisonge** [comment]
看的我有点混乱

你这个工具需要输入什么，能输出什么？

**Comment by willshion** [comment]
录屏 然后就 自动跟踪 手机的点
