### ISSUE TITLE
无障碍权限频繁自动掉

### ISSUE THREAD

**Issue by Book-fall2wish** [gkd-kit/gkd#201]
荣耀Magic4，系统MagicOS7.0 (安卓13）
Device Manufacturer: HONOR
Device Model       : LGE-AN00
Android Version    : 13
Android SDK        : 33
App VersionName    : 1.3.0
App VersionCode    : 7
已经允许后台和自动启动，并且多任务界面中锁定了任务。唯一不是默认设置的选项，我没给软件通知权限(搞快点权限没给，截屏、悬浮窗按钮服务和http服务给了）。然后现在发现无障碍需要频繁手动开启。李跳跳相同配置可以保活至少一个月。另外为什么一定要在通知里显示运行状态，很烦。

日志已上传https://github.com/gkd-kit/inspect/files/13157239/file.zip

**Comment by jackyHuangH** [comment]
同问，常驻通知栏是为了保活吗？不想让它显示在通知栏

**Comment by Book-fall2wish** [comment]
> 同问，常驻通知栏是为了保活吗？不想让它显示在通知栏

目前给我的感觉是这样的，我把所有通知权限放开以后目前没掉（6小时），之前一小时内就掉了

**Comment by junerver** [comment]
高版本系统不给前台通知很难做到长时间后台保活吧

**Comment by Book-fall2wish** [comment]
> 高版本系统不给前台通知很难做到长时间后台保活吧

现在情况是gkd要的啥权限我都给了，结果是依然没法长时间保活。但是李跳跳只用给后台运行权限，悬浮窗和通知都不需要就可以保活数周。

**Comment by mybdye** [comment]
> > 高版本系统不给前台通知很难做到长时间后台保活吧
> 
> 现在情况是gkd要的啥权限我都给了，结果是依然没法长时间保活。但是李跳跳只用给后台运行权限，悬浮窗和通知都不需要就可以保活数周。

试下把“设置” 也锁定后台？我了解是华子有这个问题，荣耀不太清楚

**Comment by Book-fall2wish** [comment]
> > > 高版本系统不给前台通知很难做到长时间后台保活吧
> > 
> > 
> > 现在情况是gkd要的啥权限我都给了，结果是依然没法长时间保活。但是李跳跳只用给后台运行权限，悬浮窗和通知都不需要就可以保活数周。
> 
> 试下把“设置” 也锁定后台？我了解是华子有这个问题，荣耀不太清楚

好的，我试试，目前看好像还真是，把设置杀了以后gkd的无障碍当场就掉了，奇怪的是李跳跳却没掉。。。

**Comment by shiwangtongxue** [comment]
我的也是频繁掉，通知权限给了，后台高耗电也是不限制的。。。

**Comment by Book-fall2wish** [comment]
锁定“设置”后问题解决

**Comment by shiwangtongxue** [comment]
目前该问题已解决，想反馈的是百度极速版跳过ad速度较慢，可以测试一下吗？谢谢。











------------------ 原始邮件 ------------------


    


        发件人: Book-fall2wish  ***@***.***>    






    


        发送时间: 2023-10-31 14:35:03    






    


        收件人: gkd-kit/gkd  ***@***.***>     






    


        抄送: shiwangtongxue  ***@***.***>,Comment  ***@***.***>     






    


        主题: Re: [gkd-kit/gkd] 无障碍权限频繁自动掉 (Issue #201)    

 

锁定“设置”后问题解决

**Comment by lisonge** [comment]
> 想反馈的是百度极速版跳过ad速度较慢

@shiwangtongxue 

默认订阅里并不存在 百度极速版，你可以给出快照适配

https://github.com/gkd-kit/subscription/issues/new/choose

**Comment by ddl-killer** [comment]
> 锁定“设置”后问题解决

如何锁定设置，oppo 遇到了同样问题，无障碍开启后存在自动关闭的情况

**Comment by Book-fall2wish** [comment]
> > 锁定“设置”后问题解决
> 
> 如何锁定设置，oppo 遇到了同样问题，无障碍开启后存在自动关闭的情况

就是锁定手机系统的设置那个的后台

**Comment by shiwangtongxue** [comment]
打开手机设置后切到后台锁定即可











------------------ 原始邮件 ------------------


    


        发件人: Lor  ***@***.***>    






    


        发送时间: 2023-11-02 16:16:12    






    


        收件人: gkd-kit/gkd  ***@***.***>     






    


        抄送: shiwangtongxue  ***@***.***>,Mention  ***@***.***>     






    


        主题: Re: [gkd-kit/gkd] 无障碍权限频繁自动掉 (Issue #201)    

 

 

锁定“设置”后问题解决

 

 

如何锁定设置，oppo 遇到了同样问题，无障碍开启后存在自动关闭的情况

**Comment by tp20c5** [comment]
Moto 的MyUI7.0（安卓14），手机设置、gkd都要设为后台锁定才能不掉权限。。否则标准省电功能一开就会干掉gkd授权，继而还影响其他应用的无障碍权限（比如第三方桌面的双击锁屏功能）

**Comment by Book-fall2wish** [comment]
> Moto 的MyUI7.0（安卓14），手机设置、gkd都要设为后台锁定才能不掉权限。。否则标准省电功能一开就会干掉gkd授权，继而还影响其他应用的无障碍权限（比如第三方桌面的双击锁屏功能）

后来发现和这些都没有关系，是手机低电量就会开始杀后台

**Comment by tp20c5** [comment]
> > Moto 的MyUI7.0（安卓14），手机设置、gkd都要设为后台锁定才能不掉权限。。否则标准省电功能一开就会干掉gkd授权，继而还影响其他应用的无障碍权限（比如第三方桌面的双击锁屏功能）
> 
> 后来发现和这些都没有关系，是手机低电量就会开始杀后台

这里有提到本质原因😄️
https://github.com/gkd-kit/gkd/issues/357#issuecomment-1860209355
