### ISSUE TITLE
希望下一个版本可以支持长按或者点3点导出自用本地规则

### ISSUE THREAD

**Issue by miracomangomanchuria** [gkd-kit/gkd#203]
按照自己的喜好对部分app做了补充规则，很想自己也搞一个订阅链接，想直接导出到json格式到剪贴板也放在github上。

![Screenshot_20231025_135440](https://github.com/gkd-kit/gkd/assets/18415539/651236ac-3b29-49c9-99f6-98b6c17df625)

另外，我自己导入的时候明明是带快照的，但是保存成功以后再去查看json体，发现json体里面无快照了，也希望作者修复一下。谢谢。

**Comment by lisonge** [comment]
> 我自己导入的时候明明是带快照的，但是保存成功以后再去查看json体，发现json体里面无快照了，也希望作者修复一下。谢谢。

快照只是给 github 仓库维护用的，app并不支持，app 保存 json 时会剔除不需要的字段

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
