### ISSUE TITLE
改善锁屏解锁后开屏广告无法跳过

### ISSUE THREAD

**Issue by Redguest** [gkd-kit/gkd#205]
知乎锁屏后，打开出现开屏广告就无法跳过，在别的APP上也是出现。

**Comment by lisonge** [comment]
请提供不跳过的快照

**Comment by Redguest** [comment]
![Screenshot_2023-10-26-14-07-01-824_com zhihu android](https://github.com/gkd-kit/gkd/assets/52919696/5a76d4a8-0255-42cd-b2b6-8710dca4fa61)

**Comment by Redguest** [comment]
> 请提供不跳过的快照

![Screenshot_2023-10-26-14-07-01-824_com zhihu android](https://github.com/gkd-kit/gkd/assets/52919696/e4e18e0f-e63b-44f7-bedd-4b42c9cabadc)

**Comment by Redguest** [comment]
> 请提供不跳过的快照

快照怎么提供啊？我用了悬浮窗服务，显示了快照成功，但是文件在哪我没看到。

**Comment by lisonge** [comment]
点击 高级设置 底部空白 就行，上一个版本有点 bug 不显示快照记录

**Comment by Redguest** [comment]
[1698303926060.zip](https://github.com/gkd-kit/gkd/files/13174018/1698303926060.zip)

**Comment by Redguest** [comment]
> 点击高级设置底部就行，上一个版本有点bug不显示快照空白记录
> 
> 或者将`/sdcard/Android/data/li.songe.gkd/files/snapshot`压缩上传也行

**Comment by lisonge** [comment]
试试这个测试版本呢

[debug.zip](https://github.com/gkd-kit/gkd/files/13188148/debug.zip)

使用这个的时候，先把正式版关闭

**Comment by Redguest** [comment]
已经可以了，我直接用1.4.1广告已经可以自动跳过了

**Comment by Redguest** [comment]
> 试试这个测试版本呢
> 
> [调试.zip](https://github.com/gkd-kit/gkd/files/13188148/debug.zip)
> 
> 使用这个的时候，先把正式版关闭

已经可以了，我直接用1.4.1广告已经可以自动跳过了
