### ISSUE TITLE
无障碍灰色，受限制

### ISSUE THREAD

**Issue by BaiQingGuaJunior** [gkd-kit/gkd#208]
![Screenshot_2023-10-27-22-22-37-36_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/gkd-kit/gkd/assets/146713950/5b1670cb-b2ff-46b0-901d-907cefc818db)

color os 14

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/35

**Comment by lisonge** [comment]
你好，请问找到后可否发个这个设置开关界面的截图，原 issue 里只有文字描述，没有截图
