### ISSUE TITLE
开启app后字体不显示

### ISSUE THREAD

**Issue by bingsunny0730** [gkd-kit/gkd#21]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4924174380539404699 skey=@crypt_803cb60c_aaaacccaff110573b503dd8f87ec1b04 mmweb_appid=wx_webfilehelper](https://github.com/gkd-kit/gkd/assets/131505889/1cfd014c-9798-49e2-bf7f-da5dca1147ca)
打开后字体并未显示，是啥问题造成的，能修复嘛？！

**Comment by lisonge** [comment]
看起来是 compose 的 bug，比如左上角的标题我已经明确指定 `Color.Black` 颜色了

请问你的机型和android版本是什么

**Comment by lisonge** [comment]
把 compose 版本从 1.4.1 升级到 1.5.1 了，你试试看看能不能显示

[debug.zip](https://github.com/gkd-kit/gkd/files/12573330/debug.zip)

**Comment by bingsunny0730** [comment]
测试的是Android11（MIUI 12.5.5版本），试了关掉深色模式就显示正常，一开深色又无法显示了，估计是没适配深色模式吧，先谢谢咯

**Comment by lisonge** [comment]
好吧，感谢反馈，后面会尽快适配深色模式的

**Comment by Half-Newbie** [comment]
现在miui12还是有这个问题，深色模式不显示字体

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13112120/debug.zip)

试试这个测试版本呢，看看字体显示是否有效？

**Comment by Vlastbia** [comment]
有效，字体显示正常。（MIUI 12.5.6）



> [debug.zip](https://github.com/gkd-kit/gkd/files/13112120/debug.zip)
> 
> 试试这个测试版本呢，看看字体显示是否有效？

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
