### ISSUE TITLE
GKD【开启无障碍后闪退】【版本1.4.0】

### ISSUE THREAD

**Issue by wndlsj** [gkd-kit/gkd#212]
机型：小米6
shizuku 已卸载后还是闪退 
1.3.0上一版本使用测试无问题。

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13194543/debug.zip)

使用这个版本试试

**Comment by lisonge** [comment]
如何了？

**Comment by wndlsj** [comment]
抱歉久等了 依然还是 GKD屡次停止运行 闪退

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13194721/debug.zip)

这个呢？这个是测试版本，和正式版本是共存的，你开启的时候要开启测试版本，不要开启正式版本

**Comment by wndlsj** [comment]
这个版本可以的，GKD-debug，灰常感谢 后面的版本可以的

**Comment by lisonge** [comment]
好的，感谢反馈，我一会发一个新的正式版本

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
