### ISSUE TITLE
[bug] index=0 的 rule 的 preRules 不生效

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/gkd#213]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息

快照：
https://i.gkd.li/import/13194276

https://i.gkd.li/import/13194263

GKD 日志：https://github.com/gkd-kit/inspect/files/13194280/file.zip

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
