### ISSUE TITLE
通知栏快捷快照失败

### ISSUE THREAD

**Issue by jiuqianyuan** [gkd-kit/gkd#214]
当使用经典控制中心，且快照按钮不在首行，需要二次下拉出完整通知栏快捷区时。
点击快照，通知栏只能回缩到图2，导致快照失败

![223](https://github.com/gkd-kit/gkd/assets/39406781/d42cd69d-9a4b-4984-919d-2ae55af017cb)

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13194738/debug.zip)

试试这个测试版本呢？这个和正式版本是共存的，使用的时候暂时关闭正式版

**Comment by jiuqianyuan** [comment]
> [debug.zip](https://github.com/gkd-kit/gkd/files/13194738/debug.zip)
> 
> 试试这个测试版本呢？这个和正式版本是共存的，使用的时候暂时关闭正式版

可行

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
