### ISSUE TITLE
能不能增加屏蔽贴吧首页推荐里视频贴的规则？

### ISSUE THREAD

**Issue by lxlalalala** [gkd-kit/gkd#216]
贴吧首页里好多视频贴，而且经常连着三四个视频贴，能不能把这些价格规则把这些帖子全给X了。
一般的帖子在左上角显示的都是贴吧名，但是这种视频贴左上角显示的是用户名，而且右上角的“X”旁边都有个“关注”，应该能根据这个来识别，把视频贴全给X掉。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
