### ISSUE TITLE
请求支持shizuku跳过

### ISSUE THREAD

**Issue by MCxlm1** [gkd-kit/gkd#22]
使用shizuku来代替无障碍的自动点击，来降低一下后台被杀的概率

**Comment by lisonge** [comment]
后续会增加 shizuku 跳过

但是我在手机上用无障碍从来没有被杀过

**Comment by MCxlm1** [comment]
一般来说只要“shizuku_server”这个进程不寄一般shizuku都不会没，还有就是那个李跳跳规则转GKD的网页这句话当真吗（）

**Comment by lisonge** [comment]
> 李跳跳规则转GKD

会增加这个网页工具，但是不会添加到默认规则里，因为没有快照不好维护

**Comment by MCxlm1** [comment]
好的好的，能实现shizuku的话已经很好了，毕竟找遍Github用shizuku做自动跳过的也就一个

**Comment by willshion** [comment]
你跳跳规则 yyds

**Comment by zhanghua000** [comment]
我这里倒是杀后台问题比较严重，基本上睡一觉起来就会被杀，而且被杀后会掉无障碍权限。考虑到已经有 Shizuku 识别界面活动 ID 的功能，建议也加入利用 Shizuku 进行保活的功能

**Comment by lisonge** [comment]
> 我这里倒是杀后台问题比较严重，基本上睡一觉起来就会被杀，而且被杀后会掉无障碍权限。考虑到已经有 Shizuku 识别界面活动 ID 的功能，建议也加入利用 Shizuku 进行保活的功能

感谢建议，后期会加上利用  Shizuku 进行保活

我的手机上 无障碍 从来没有被杀过，你可以尝试在最近任务界面给应用上锁，并且把自启动打开，省电策略改成无限制

**Comment by hrflni** [comment]
> 后续会增加 shizuku 跳过
> 
> 但是我在手机上用无障碍从来没有被杀过
> 
> 反而是我的 shizuku 老是被杀

miui13，开了自启，还是会被杀。 Shizuku没开。

**Comment by haroldleader** [comment]
shizuku授权点击无反应，GKD过几个小时就会被杀，必须重新打开、重新授权
手机为IQOO 10 PRO
不知道是哪里没有设置正确

**Comment by lisonge** [comment]
请给出日志

**Comment by 1653909** [comment]
开启后，youtube不能播放视频

**Comment by PumpkinJui** [comment]
Shizuku模式的开关点击后显示「Shizuku方法校验失败，无法使用」
日志如下：
```
************* Log Head ****************
Date of Log        : 2024_01_18
Rom Info           : RomInfo{name=oppo, version=V5.2.1}
Device Manufacturer: OPPO
Device Model       : OPPO R11s
Android Version    : 8.1.0
Android SDK        : 27
App VersionName    : 1.6.4
App VersionCode    : 19
************* Log Head ****************
10:43:52.218 D/DebugPageKt [DefaultDispatcher-worker-5, li.songe.gkd.ui.DebugPageKt$DebugPage$2$1$2$1$1.invokeSuspend(DebugPageKt.java:12)]: shizuku 无法获取 activity_task
```

**Comment by user310503696** [comment]
> shizuku授权点击无反应，GKD过几个小时就会被杀，必须重新打开、重新授权 手机为IQOO 10 PRO 不知道是哪里没有设置正确

origin系统设置里面有个"自启动"把GKD设为允许自启动就可以了，我是iQOO Z5 GKD还没被杀过后台

**Comment by fxzxmicah** [comment]
我的IQOO Neo7，之前用轻启动，把它要的权限都给了，再把电池优化一关，运行几个月都不会掉后台……反倒是IQOO手机不给好好用Shizuku，一关无线调试Shizuku就被杀掉了。

**Comment by lanyue100** [comment]
我的color os14.0.0.702 一点击清除后台应用，这个就会被杀，也不能锁定，然后重新打开还要重新授权无障碍
