### ISSUE TITLE
[feat]: 自定义通知栏信息

### ISSUE THREAD

**Issue by wgll000** [gkd-kit/gkd#223]
现在还没有卸载李跳跳的原因，就是这个通知栏通知太丑了，给女朋友装了以后他嫌丑，所以赶紧出一个可以自定义通知栏的版本

**Comment by lisonge** [comment]
> 就是这个通知栏通知太丑了

是图标丑还是文字描述丑？，具体丑在哪里？

**Comment by junerver** [comment]
> > 就是这个通知栏通知太丑了
> 
> 是图标丑还是文字描述丑？，具体丑在哪里？

可能是觉得图标和提示的文字太过于geek了，女生大概喜欢李跳跳那种俏皮的吧

**Comment by haoxiaozong** [comment]
关注一下这个问题，虽然现在提示的消息很有有，但我们不关心，只希望能改成自己喜欢的方案来显示（那当然如果动态就更好了，低代码玩法最好）

**Comment by lisonge** [comment]
不支持
