### ISSUE TITLE
Monet取色功能请求

### ISSUE THREAD

**Issue by StrayJoker** [gkd-kit/gkd#224]
MD3这么好看，建议加上莫奈取色

**Comment by lisonge** [comment]
https://developer.android.com/jetpack/compose/designsystems/material3?hl=zh-cn#color-scheme

**Comment by StrayJoker** [comment]
很奈斯，期待更新😘

**Comment by lisonge** [comment]
每次 push 都会自动构建，你可以在这里查看下载构建产物

https://github.com/gkd-kit/gkd/actions/runs/6746109347
