### ISSUE TITLE
自动创建目录失败

### ISSUE THREAD

**Issue by wndlsj** [gkd-kit/gkd#226]
{"id":"com.lucky.luckyclient","name":"瑞幸咖啡","groups":[{"name":"软件更新","key":1,"activityIds":**["com.luckin.client.main.FirstActivity"]**,"rules":[{"preKeys":[],"matches":["@ImageView[id=\"com.lucky.luckyclient:id/dismiss_btn\"] - LinearLayout > ImageView[id=\"com.lucky.luckyclient:id/update_btn\"]"],"excludeMatches":[]}],"snapshotUrls":["https://i.gkd.li/import/12846499"]}]}

其中["com.luckin.client.main.FirstActivity"] 已更新ID为 ["**com.luckin.commclient.update.UpdateActivity**"]

之前的ID并不能跳过广告了，麻烦更新下规则哈~三克油

**Comment by wndlsj** [comment]
然就是我想自己添加规则进去 总提示这个
-----
<img  src="https://wx2.sinaimg.cn/mw690/69a84ad1ly1hjd144npsmj20i60wdgo6.jpg"/>

**Comment by lisonge** [comment]
结束应用后重启，或者你手动在 那个 files/ 下新建一个叫 subscription 的目录

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.5.0
