### ISSUE TITLE
ColorOS14 一加Ace2Pro 无法开启辅助权限

### ISSUE THREAD

**Issue by l2xiang** [gkd-kit/gkd#229]
![微信图片_20231030132716](https://github.com/gkd-kit/gkd/assets/32831535/86f31940-9527-4d5b-8d73-c61b44caebc5)
RT 如图

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/35

**Comment by szw0407** [comment]
Seems that colorOS has blocked users from opening the setting.

The option is provided as expected in one UI, but not in colorOS.
