### ISSUE TITLE
[Bug report]快照按钮点击后提示：正在截屏，不可重复截屏

### ISSUE THREAD

**Issue by Book-fall2wish** [gkd-kit/gkd#238]
荣耀Magic4，系统MagicOS7.0 (安卓13）
Device Manufacturer: HONOR
Device Model : LGE-AN00
Android Version : 13
Android SDK : 33
App VersionName : 1.3.0
App VersionCode : 7

无法截取快照，返回快照记录中显示暂无记录。已经打开shizuku模式、截屏服务、悬浮窗服务、音量快照。
强制停止应用后成功快照。

日志https://github.com/gkd-kit/inspect/files/13236538.zip
强制停止应用后日志（应该包含成功截取快照的日志）https://github.com/gkd-kit/inspect/files/13236778.zip

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.5.0
