### ISSUE TITLE
[bug] MIUI14无法自动跳过,但是开启悬浮窗可以跳过

### ISSUE THREAD

**Issue by fengyie007** [gkd-kit/gkd#24]
为什么开启快照悬浮窗时可以跳过？关了悬浮窗就不行了？开启了app自启并且关闭了 省电策略
小米 12Pro android 13

**Comment by lisonge** [comment]
> 开启了app自启并且关闭了 省电策略

和这个没关系吧，只要状态栏有通知在显示就是正在运行的

> 为什么开启快照悬浮窗时可以跳过？关了悬浮窗就不行了？

我的是 红米 K50U MIUI 14，一直都是能跳过的

你这个看起来是 activityId 无法接收到更改的问题，我的手机之前有出现过，后面加上通知显示就没有出现了

你可以把 `/sdcard/Android/data/li.songe.gkd/files/log` 这个下面的文件发给我看看

**Comment by fengyie007** [comment]
文件怎么发给你？

**Comment by lisonge** [comment]
压缩为 zip 上传到 issue

**Comment by fengyie007** [comment]
[log.zip](https://github.com/gkd-kit/gkd/files/12608347/log.zip)

**Comment by fengyie007** [comment]
后面多试了几次，张大妈这个app开屏，有时候到计时显示完了才出现跳过字样，有时候没有。

**Comment by lisonge** [comment]
> 后面多试了几次，张大妈这个app开屏，有时候到计时显示完了才出现跳过字样，有时候没有。

你的规则具体是什么？

**Comment by lisonge** [comment]
miui 桌面有个 bug，在桌面启动APP，已经进入APP了但是有时候 activityId 仍然是桌面的 com.miui.home.launcher.Launcher

**Comment by lisonge** [comment]
你可以把 shizuku 授权开启，这样它获取的 activityId 就一定是准确的

或者你写规则的时候，不要写 activityIds，这样APP的所有界面都能应用规则

**Comment by fengyie007** [comment]
我是直接用的内置订阅的规则。好的，我试试。

**Comment by lisonge** [comment]
这个 APP 的开屏广告适配了一下 MIUI <https://github.com/gkd-kit/subscription/commit/2778279651c532cb73b0025fdcdf5a50d7cfda9d>

**Comment by fengyie007** [comment]
好的，多谢。
装了shizuku 也不行，有点慢，好像最后一秒才点击。
https://github.com/gkd-kit/gkd/assets/241077/cdfe95af-0530-4191-a12d-2ac383af264a

**Comment by fengyie007** [comment]
开启快照悬浮窗时 会有啥不一样吗？这个打开 的时候好像挺快的。

**Comment by lisonge** [comment]
> 开启快照悬浮窗时 会有啥不一样吗？这个打开 的时候好像挺快的。

不知道，估计是开启悬浮窗时，系统会更快刷新无障碍获取到的节点信息吧

---

另外你刷新订阅试试，现在会把 `com.miui.home.launcher.Launcher` 也匹配进去

**Comment by fengyie007** [comment]
更新了订阅，好像也没效果。😂

**Comment by huanghaobaobao** [comment]
同样问题，打开悬浮窗才能跳过广告，MIUI14

**Comment by allzyaaa** [comment]
我也是这样

**Comment by barton0426** [comment]
我记得李跳跳停更最新版之前的一版 也是miui14有问题 后来在2.2版修复了 原理不懂。。。看看开发者能不能从公众号里获取点灵感

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
