### ISSUE TITLE
保活问题

### ISSUE THREAD

**Issue by miracomangomanchuria** [gkd-kit/gkd#242]
https://gkd-kit.gitee.io/import/13246141
未来是否会支持点击去掉这样的广告？

另，上次反馈的保活问题在Android10 Mate 30Pro上仍没有解决。

**Comment by egmkang** [comment]
mate20也没办法保活, 已经把应用添加到了无障碍列表, 和电池限制

**Comment by egmkang** [comment]
我的mate20, 打开gkd, 然后再打开四五次微博, 就不跳过广告了

**Comment by egmkang** [comment]
[Uploading log.zip…](日志)
大概六七次之后, 连续失败了好几次, 得重新手动打开一次gkd, 才能继续跳过微博的广告

**Comment by lisonge** [comment]
保活问题我不知道怎么解决，因为我的红米k40，k50u，小米平板5pro 连续运行一个月都没问题

**Comment by lisonge** [comment]
> https://gkd-kit.gitee.io/import/13246141
未来是否会支持点击去掉这样的广告？

@miracomangomanchuria 

https://github.com/gkd-kit/gkd/issues/10

**Comment by Ilmiotesoro** [comment]
难道鸿蒙系统都不能保活吗？我的p30鸿蒙3系统，还以为是我设置问题

**Comment by lisonge** [comment]
当应用停止运行时，如果系统的无障碍设置界面显示 `此应用无法运行`，那就是 bug，你只需要重启应用后告诉我你的机型和 Android 版本即可

如果无障碍界面没有显示额外的提示信息，说明是系统主动停止运行的，那我很难知道怎么解决

---

事实上在我的小米手机上，我什么优化都没设置过，在有前台通知的情况下，每次用完都是直接把应用从最近任务界面划掉，从来没出现保活问题

**Comment by lisonge** [comment]
[app-release.zip](https://github.com/gkd-kit/gkd/files/13260161/app-release.zip)

构建了一个单进程版本(耗电优化)的，虽然感觉不大可行，但是可以试试

**Comment by Ilmiotesoro** [comment]
> [app-release.zip](https://github.com/gkd-kit/gkd/files/13260161/app-release.zip)
> 
> 构建了一个单进程版本(耗电优化)的，虽然感觉不大可行，但是可以试试

你这个可以用，我试了，多用几天看情况

**Comment by Nebulafalls** [comment]
> [app-release.zip](https://github.com/gkd-kit/gkd/files/13260161/app-release.zip)
> 
> 构建了一个单进程版本(耗电优化)的，虽然感觉不大可行，但是可以试试

华为，nova7se，鸿蒙3.0，在存在通知的情况下还是会有失效的情况，换成这个版本貌似没问题了吧

**Comment by Ilmiotesoro** [comment]
> [app-release.zip](https://github.com/gkd-kit/gkd/files/13260161/app-release.zip)
> 
> 构建了一个单进程版本(耗电优化)的，虽然感觉不大可行，但是可以试试

经过一天的使用，这个版本一切正常

**Comment by incubus-ohy** [comment]
iqoo 10 没有这个问题，骂一下爱国手机不过分吧

**Comment by CarotaHu** [comment]
> [app-release.zip](https://github.com/gkd-kit/gkd/files/13260161/app-release.zip)
> 
> 构建了一个单进程版本(耗电优化)的，虽然感觉不大可行，但是可以试试

p30pro刚装上,暂时用着挺好的

**Comment by miracomangomanchuria** [comment]
反馈：上述保活问题在Mate 30 Pro上没有解决，单进程版本也不管用，但是我仍然非常喜欢GKD app，我的使用方法是长开截屏按钮，这样后台就不会掉了，希望开发大佬从此方面入手。

**Comment by miracomangomanchuria** [comment]
> [app-release.zip](https://github.com/gkd-kit/gkd/files/13260161/app-release.zip)
> 
> 构建了一个单进程版本(耗电优化)的，虽然感觉不大可行，但是可以试试


反馈：上述保活问题在Mate 30 Pro上没有解决，单进程版本也不管用，但是我仍然非常喜欢GKD app，我的使用方法是长开截屏按钮，这样后台就不会掉了，希望开发大佬从此方面入手。

**Comment by aoguai** [comment]
由于各个厂商都有自己的后台管理机制，即使应用已经加入了后台运行白名单，也有可能被系统强制关闭。 最优的解决方案是，根据用户的手机型号和系统版本，向用户展示一个图文操作步骤，并提供一个按钮，直接跳转到相应的设置页面。然而，这需要对每个厂商每个版本进行适配，工作量十分巨大。

其实，引导用户进行白名单设置的手段是最简单有效的，对比有保活需求的APP大多有一个单独引导开启需要权限的页面来引导用户进行设置。

比如将相关权限设置单独开一个设置页面，引导用户：
- 提醒用户请勿开启「省电模式」
- 提醒用户给APP加锁
- 引导用户给予无障碍权限
- 引导用户将 APP 添加进电池保护名单
- 引导用户给予后台运行权限

类似⬇️
![image](https://github.com/gkd-kit/gkd/assets/34203474/c8e421ab-6d91-442d-8f41-afe8a23bdf8f)
