### ISSUE TITLE
[feat] 新增字段，实现规则分类

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/gkd#248]
不知道 kotlin 实现起来如何，以我有限的编程认知，增加一个字段用于标识规则类型，然后实现一个过滤器接口，在此基础上实现全局启用/停用某一类规则，单个 app 启用/停用某一类规则，这样似乎是可行的。

以下字段值可供参考：
- 开屏广告
- 广告弹窗
- 广告卡片
- 青少年模式
- 更新提示
- 权限索取提示
- 其他

#87

**Comment by walklty** [comment]
再来个浮窗\飘窗广告分类

**Comment by 8267020** [comment]
这个软件用了一个多月，也提供了一些快照。
我最开始的目的是跳过开屏广告，感觉都很不错了。其他的中夹杂的广告，去掉也行不去也行。最近发现有时候广告是去了，但是出现了误触的现象，正打字呢就被跳过了什么东西。很影响体验！
再一个就是app越来越多，其中加载的广告肯定是五花八门，增加了规则的适配量！
我赞同楼主的建议，进行分类，批量开关。不喜欢的可以关闭！
