### ISSUE TITLE
可否在新增规则右边，有个新增提示

### ISSUE THREAD

**Issue by xiaowonet** [gkd-kit/gkd#249]
比如手机安装了新的APP，会在新APP的图标旁有个小绿点，以提醒此APP新安装，还未点击过。
GKD的默认规则，每一次的更新量都比较大，可否也在新规则的右边，出现一个类似的提醒，用户查看过一次后，则提醒消失。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription

![image](https://github.com/gkd-kit/gkd/assets/38517192/eaa7b196-68b3-4f4a-a784-54c9b79b8bef)
