### ISSUE TITLE
[perf] 订阅列表显示优化

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/gkd#250]
有用户反馈不知道默认订阅可以点进去进一步设置各个app的规则，可以稍微优化一下ui。

群友提供了几种可能的优化方法：

1. 订阅名称后面添加文字“点击查看详情”
2. 右侧三个原点的菜单中，添加一个子项，点击后进入订阅详情

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/commit/950b6e6b4b582f17ade71a9ef04f8fbb088391c7
