### ISSUE TITLE
这个电量消耗有点高

### ISSUE THREAD

**Issue by jiangfeiyang0228** [gkd-kit/gkd#251]
![Screenshot_2023-11-05-21-19-44-798_com miui securitycenter](https://github.com/gkd-kit/gkd/assets/68383449/951fc8d4-f2d7-4fb2-a0af-6e7e22f03df2)
![Screenshot_2023-11-05-21-20-47-544_com miui securitycenter](https://github.com/gkd-kit/gkd/assets/68383449/6331fa49-653f-4181-861a-f48631a2f1fd)
![Screenshot_2023-11-05-21-20-50-898_com miui securitycenter](https://github.com/gkd-kit/gkd/assets/68383449/7d72d889-def6-4dbf-81b0-720a0cc148b9)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/37
