### ISSUE TITLE
软件不稳定，经常失效

### ISSUE THREAD

**Issue by Ilmiotesoro** [gkd-kit/gkd#252]
华为手机，鸿蒙3系统，打开了后台隐藏、无障碍前台和无障碍，软件更新到了最新版，默认订阅更新到了最新版，但是现在基本上每次打开软件都不会跳过开屏广告，很奇怪，前段时间老版本还能跳，现在基本上不能跳了。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
