### ISSUE TITLE
[feat] 提供捕获快照的服务入口

### ISSUE THREAD

**Issue by StrayJoker** [gkd-kit/gkd#253]
目前gkd提供的捕获快照的方法虽然比较多，但
悬浮窗、http服务网页审查生成这些都要在复现广告页面前做准备，都不太方便
用xposed edge pro、macrodroid之类的自动化工具实现起来就很不错，用户自己设定按键触发器手势触发器来执行
但是磁贴提供的动作实际上是触发返回键+生成快照，（当然这是非常合理的）
不知道gkd本身能不能直接提供捕获快照这个活动或者说活动intent呢

**Comment by lisonge** [comment]
可以提供的，另外这个 intent 必须的是 activity 类型的吗？

因为打开 activity 意味着当前 appId 和 activityId 都会改变，虽然会立刻 finish 掉这个界面

但是这会有概率导致原应用的 activityId 不能及时获取导致快照的 activityId 错误地变成了 gkd 的

**Comment by StrayJoker** [comment]
![1](https://github.com/gkd-kit/gkd/assets/144357608/78bab8bd-9de8-4f92-8bb3-88f9a51f18f2)
这是我目前曲线实现的触发器触发捕获快照，效果还可以
个人不懂开发，可能的bug触发倒是没有设想过
![2](https://github.com/gkd-kit/gkd/assets/144357608/600b3f28-d0f5-47ec-9d41-1c157555aa00)
![3](https://github.com/gkd-kit/gkd/assets/144357608/c656cfa6-b693-4b6b-80e5-797edab561ac)
这些是可执行的动作类型，大佬作为开发者的身份能不能看看怎么更好实现保存快照这个动作呢

**Comment by lisonge** [comment]
请问 `启动服务` 具体的参数是什么呢？

**Comment by StrayJoker** [comment]
<img src="https://github.com/gkd-kit/gkd/assets/144357608/a4006fe3-019c-4c4f-9c8f-3f1173736a4d" width="30%" height="30%">   <img src="https://github.com/gkd-kit/gkd/assets/144357608/d36e5d93-1f8c-4b7f-b9ce-7c7bcd5116cf" width="30%" height="30%">

**Comment by lisonge** [comment]
你好，请问截图中的 APP 叫什么? 如何下载？

**Comment by StrayJoker** [comment]
shortx，谷歌商店可以搜到

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13306698/debug.zip)

测试启动 SnapshotActionService 这个服务看看

**Comment by StrayJoker** [comment]
抱歉现在才看到orz
<img src="https://github.com/gkd-kit/gkd/assets/144357608/e5ac4518-4cbb-45bf-b12c-a20670292601" width="50%" height="50%">
指令触发非常丝滑，生成快照无bug，大佬牛逼

**Comment by aoguai** [comment]
服务类名现在好像是`li.songe.gkd.debug.SnapshotActionService`，而不是文档写的`li.songe.gkd.SnapshotActionService`


<details> <summary>shortx参考</summary>

```
{
  "actions": [{
    "@type": "type.googleapis.com/StartService",
    "intent": {
      "action": "android.intent.action.VIEW",
      "pkgName": "li.songe.gkd",
      "className": "li.songe.gkd.debug.SnapshotActionService"
    },
    "isForegroundService": true,
    "customContextDataKey": {
    },
    "id": "A-0b5eea40-abd8-4572-bf37-e9e7a9491f37"
  }],
  "id": "SHARED-DA-210e4148-87bf-474f-9d0f-cbb658217e8e",
  "lastUpdateTime": "1733447189351",
  "createTime": "1733447159953",
  "author": {
    "name": "ShortX"
  },
  "title": "gkd快照",
  "versionCode": "1"
}
###------###
{"type":"da"}
```

</details>

<details> <summary>shell脚本参考</summary>

```
#!/bin/sh
# 启动GKD服务快照
am start-foreground-service -n li.songe.gkd/.debug.SnapshotActionService
```

</details>

**Comment by lisonge** [comment]
已更新文档

**Comment by lisonge** [comment]
#1160
