### ISSUE TITLE
【建议】能否出一个最精简的规则？仅跳过开屏广告。

### ISSUE THREAD

**Issue by nanvon** [gkd-kit/gkd#255]
希望默认规则是最精简的跳过开屏广告的规则；或者出一个新规则。
因为在 App 中，滑动到信息流中的广告时，会自动点击进行隐藏，其实体验很差，屏幕会闪动，其实还挺打扰的。

这是我的一个不成熟的想法，是否还存在其他的解决方法呢？

**Comment by lisonge** [comment]
> 是否还存在其他的解决方法呢？

最简单的方法是 你自己写一个代理服务器加一个转换规则对 https://registry.npmmirror.com/@gkd-kit/subscription/latest/files 实行代理，然后更改 group.enable 字段

**Comment by nanvon** [comment]
#248 #87 #236

**Comment by nanvon** [comment]
类似issue：#248 #87 #236

**Comment by AndyYuenOk** [comment]
有同感，刷微信朋友圈的时候，经常跳来跳去，体验稍微不太好，希望之后能优化一下
最后感谢作者能提供这个工具

**Comment by nanvon** [comment]
@lisonge 感谢~已按照您提供的方案操作了，已生效~

**Comment by Sibadaer** [comment]
> 以 cloudflare workers 为代理服务器例子，仅跳过开屏广告的转换器例子是
> 
> ```js
> export default {
>     async fetch() {
>         const subs = await fetch(
>             'https://registry.npmmirror.com/@gkd-kit/subscription/latest/files'
>         ).then((r) => r.json());
>         subs.apps.forEach((app) => {
>             app.groups.forEach((group) => {
>                 if (group.name == `开屏广告`) {
>                     group.enable = true;
>                 } else {
>                     group.enable = false;
>                 }
>             });
>         });
>         return new Response(JSON.stringify(subs));
>     },
> };
> ```

请教下作者
![84b30d30b9f9d3807c25405a867548a5](https://github.com/gkd-kit/gkd/assets/38148262/9dad4d4f-df3b-446f-9a2d-9c5bc8317972)
我发现这个json规则有点乱，以至于java都不能正常解析，JSON就是对象，value为空，可以不能为空呀！
![2f3ec911b3ddc55144e91466112c6be8](https://github.com/gkd-kit/gkd/assets/38148262/cdc33b42-d247-438d-a874-37e5ead8d38d)

**Comment by lisonge** [comment]
> 我发现这个json规则有点乱，以至于java都不能正常解析，JSON就是对象，value为空，可以不能为空呀！

没有乱，就是这么设计的，这个是联合类型，java 没有这种类型你觉得乱很正常

使用联合类型是为了方便用户书写，这是完整类型定义 <https://github.com/gkd-kit/subscription/blob/main/src/types.ts> 

> JSON就是对象，value为空，可以不能为空呀！

没有 key 会有什么影响吗？当作 null 就行，如果夹杂大量的 key: null 无意义字段非常影响阅读，而且会增大文件大小

此外标准的订阅文件是使用 JSON5 格式的，JSON5 最大的特点就是 key 可以不使用引号，这方便用户书写

订阅文件是手动解析，java/kotlin 没有联合类型，是无法使用一般方法解析的，手动使用 kotlin 解析订阅文件的源代码是 

<https://github.com/gkd-kit/gkd/blob/e4be8b6e60d4d3a8edf86a7036f573757bc9e8bc/app/src/main/java/li/songe/gkd/data/SubscriptionRaw.kt#L293-L319>

**Comment by Sibadaer** [comment]
没有说你的思路是错误的，我是做java开发的，早上想过滤一下开屏广告JSON给网友提供出来，发现这份JSON数据格式有点乱，就和你探讨一下，
不管JAVA还是Kotlin 都有面向对象的思维，JSON数据只是对象的一种展示方式而已，如果你的规则能按照对象这种标准格式去做，可能对以后项目的扩展有很大的帮助。比如 后续规则添加规则类型，开发者页面增删改查/上下架规则 这些功能就能很好的扩展
只是探讨，作者别介意哈，毕竟隔行如隔山。我的思路有可能也是错误的！
![图片](https://github.com/gkd-kit/gkd/assets/38148262/a808568d-6874-47a7-a8c4-b460e24ce73e)

**Comment by lisonge** [comment]
![img](https://user-images.githubusercontent.com/38148262/280961528-a808568d-6874-47a7-a8c4-b460e24ce73e.png)

你可以理解为前者是后者的简写形式，完整的标准格式一直都是后者

支持简写是因为这方便用户书写

> 如果你的规则能按照对象这种标准格式去做，可能对以后项目的扩展有很大的帮助。比如 后续规则添加规则类型，开发者页面增删改查/上下架规则 这些功能就能很好的扩展

标准格式一直都是后者，现在的增加字段一直都是在后者上增加，这没毛病

**Comment by Sibadaer** [comment]
> ![img](https://user-images.githubusercontent.com/38148262/280961528-a808568d-6874-47a7-a8c4-b460e24ce73e.png)
> 
> 你可以理解为前者是后者的简写形式，完整的标准格式一直都是后者
> 
> 支持简写是因为这方便用户书写
> 
> > 如果你的规则能按照对象这种标准格式去做，可能对以后项目的扩展有很大的帮助。比如 后续规则添加规则类型，开发者页面增删改查/上下架规则 这些功能就能很好的扩展
> 
> 标准格式一直都是后者，现在的增加字段一直都是在后者上增加，这没毛病

ok  ok  现在规则有做入库吗？ 页面操作控制规则这种

**Comment by incubus-ohy** [comment]
李跳跳 默认就能跳过开屏广告，直接换个软件不就好了

**Comment by ChellyL** [comment]
那你直接换回原始版李跳跳就好了

**Comment by nanvon** [comment]
@incubus-ohy @ChellyL  感谢建议。我正是从李跳跳切换到 GKD 的，不过我现在已经解决了这个问题，通过自己的域名和 CloudFlare 实现了规则分类。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription?tab=readme-ov-file#%E5%85%B6%E5%AE%83

查看底部附加说明即可

**Comment by lisonge** [comment]
https://github.com/orgs/gkd-kit/discussions/355
