### ISSUE TITLE
酷安“摇一摇”形式的开屏广告无法跳过

### ISSUE THREAD

**Issue by lxh1943** [gkd-kit/gkd#256]
![微信图片_20231106214834](https://github.com/gkd-kit/gkd/assets/71052633/f02e3548-1366-4f88-9716-df1c4e3da720)
有的app开屏广告也是摇一摇的形式，但是GKD都可以跳过，酷安的摇一摇开屏无法跳过，请问能否更新一下规则 谢谢

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
