### ISSUE TITLE
重启后自启明明已经给了无障碍还是说没有给，需要关闭无障碍重新打开

### ISSUE THREAD

**Issue by lq-259** [gkd-kit/gkd#268]
已经上传了日志

https://github.com/gkd-kit/gkd/assets/60541200/ca1ca7fe-89db-45a9-abee-617d437db31f

**Comment by lisonge** [comment]
日志在哪里？

**Comment by lq-259** [comment]
不是软件里有个上传日志吗

**Comment by lisonge** [comment]
那是上传日志文件生成链接，和上传快照一个道理
