### ISSUE TITLE
安装完app并开启无障碍开关后不自动更新订阅须手动刷新

### ISSUE THREAD

**Issue by lg0v0** [gkd-kit/gkd#269]
安装完app并无障碍开关开启后不自动更新订阅须手动刷新。多次卸载重新安装均不自动刷新

授予无障碍权限之后启动服务应该强制更新一次订阅，否则启动服务了也无法工作

**Comment by lisonge** [comment]
实际上，app 第一次启动的时候，就自动添加订阅并更新了，起码测试我的3个设备有效。

只是在你的手机上第一次添加没有生效

我不知道原因，你手动刷新即可
