### ISSUE TITLE
关广告关一半

### ISSUE THREAD

**Issue by miao-su** [gkd-kit/gkd#271]
关闭广告只关一半，还要我自己点，还不如不关![Screenshot_2023-11-11-21-37-03-859_com.xunlei.downloadprovider.jpg](https://github.com/gkd-kit/gkd/assets/109133144/eca42dae-1da2-4dfc-82ad-93637cbb89bc)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
