### ISSUE TITLE
WIFI环境自动点击/勾选原图

### ISSUE THREAD

**Issue by Goojoe** [gkd-kit/gkd#276]
请求增加WIFI环境自动点击原图的功能，反之关闭

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues

**Comment by Goojoe** [comment]
啊？是需要去那边提issue吗？我认为这是程序功能的

**Comment by Goojoe** [comment]
也开启issue
https://github.com/gkd-kit/subscription/issues/2050
