### ISSUE TITLE
请问  可以适配  sheter工作用户吗

### ISSUE THREAD

**Issue by wolaijiuni** [gkd-kit/gkd#282]
很多不得不用毒瘤app都被隔离在shelter里没有跳过很难受

**Comment by ztmzzz** [comment]
gkd的逻辑是对于未安装的app，就不启用对应的跳过规则。
这导致了目前无法在工作空间使用的原因是gkd无法读取到工作空间的app列表，也就不会启用跳过的规则。可以在主空间装一个让gkd识别即可。
如果要读取工作空间的app列表必须有root权限或者Shizuku。我测试下来root是可以的，Shizuku我还要改一下代码。
还有一种方法是加个界面让用户手动设置哪些跳过规则可以启用。
如果你有root权限，可以试试看我刚刚编译的
[app-debug.zip](https://github.com/gkd-kit/gkd/files/13459913/app-debug.zip)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases

**Comment by wolaijiuni** [comment]
> gkd的逻辑是对于未安装的应用程序，无法启用对应的跳过规则。 这导致目前无法在工作空间使用的原因是gkd读取无法到工作空间的应用程序列表，因而无法启用跳过的规则。可以在主空间装一个让gkd识别即可。 如果要读取工作空间的应用列表必须有root权限或者Shizuku。我测试下来root是可以的，Shizuku我还要改一下代码。 还有一种方法是加个界面用户手动设置哪些跳过规则可以启用。 如果你有root权限，可以试试看我刚刚编译的 [app-debug.zip](https://github.com/gkd-kit/gkd/files/13459913/app-debug.zip)

大佬  我手机已经root 怎么让gkd 识别工作空间app

**Comment by lisonge** [comment]
未安装应用显示默认关闭，在订阅的 `应用规则` 界面将目标应用手动开启即可
