### ISSUE TITLE
无法分享已经更改过的默认规则

### ISSUE THREAD

**Issue by lubiandewoheni** [gkd-kit/gkd#283]
每次分享的更改后的默认链接都是相同的，和默认的规则相同

**Comment by lisonge** [comment]
没看懂，你想表达什么

你进行什么操作得到了什么行为，预计的行为是什么？

**Comment by lubiandewoheni** [comment]
在手机上下载完软件后，更改了 默认订阅 中大部分应用的规则，在另一台移动设备上没有办法导入我在第一台设备上更改后的 默认订阅，，按照链接导入的仍是更改前的 默认订阅，我想知道怎样将一台设备更改后的 默认订阅 导入另一台手机上

**Comment by lisonge** [comment]
> 更改了 默认订阅 中大部分应用的规则

如何更改默认订阅？据我所知，远程订阅不支持修改

**Comment by lubiandewoheni** [comment]
> > 更改了 默认订阅 中大部分应用的规则
> 
> 如何更改默认订阅？据我所知，远程订阅不支持修改

就是打开和关闭部分规则的开关

**Comment by lisonge** [comment]
这只是修改了本地的数据库规则开关配置，并没有修改订阅

**Comment by lisonge** [comment]
你需要一台服务器来拦截修改订阅文件后作为新订阅，而不是在本地修改

具体参考 <https://github.com/gkd-kit/gkd/issues/255#issuecomment-1797474482>
