### ISSUE TITLE
小米10s掉无障碍呢

### ISSUE THREAD

**Issue by xionghaizhi** [gkd-kit/gkd#292]
权限都给了，还是经常掉呢

**Comment by lisonge** [comment]
请给出日志，你光说一个掉无障碍我不知道咋回事

**Comment by xionghaizhi** [comment]
> 请给出日志，你光说一个掉无障碍我不知道咋回事

https://github.com/gkd-kit/inspect/files/13403711/file.zip

**Comment by lisonge** [comment]
从日志来看，没有任何崩溃异常，是你的手机设置问题

**Comment by lisonge** [comment]
可以参考 https://github.com/gkd-kit/gkd/issues/242#issuecomment-1815752905

但是我的红米k50u只需要上滑加锁就行，其它的设置并不需要

**Comment by xionghaizhi** [comment]
> 可以参考 [#242 (comment)](https://github.com/gkd-kit/gkd/issues/242#issuecomment-1815752905)
> 
> 但是我的红米k50u只需要上滑加锁就行，其它的设置并不需要

好的 我设置一下试试
