### ISSUE TITLE
关于今日头条听书看视频增加ai语音听书时长问题

### ISSUE THREAD

**Issue by duguanghao18** [gkd-kit/gkd#294]
现在今日头条听书里免费时长只有30分钟 然后会弹出一个对话框 说看视频增加30分钟时长 就是说我不想要直接返回 这样不增加时长 要点击“看视频” 然后看视频过程中右上角会30秒倒计时和跳过按钮 然后不满30秒的时候点击跳过也没有增加时长权益 所以说要等倒计时消失后再点击跳过还是关闭按钮 这样才能继续听书 希望软件能增加这个功能 能全自动执行这个流程

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues/new?template=bug_report.yml
