### ISSUE TITLE
gkd  app能否考虑增加 v8a  v7a单独安装包  通用安装包太大，而且x86  x64之类手机处理器没什么人用吧

### ISSUE THREAD

**Issue by tiyuban123** [gkd-kit/gkd#30]
作者能否考虑单独出v8a    v7a安装包

**Comment by lisonge** [comment]
我尝试打包 v8a/v7a 的 apk ，但是构建产物只有 11MB ，相比之前的 13 MB 没差多少

而且 13MB 我认为并不是多大是文件，当前网速下载也就是十几秒的事情

APP 的内部更新基于 <https://npmmirror.com/> 它在大陆有加速，无需担心无法下载
