### ISSUE TITLE
请问能不能在[跟随规则/默认关闭]这个设置里加一个只开启跳过开屏广告的选项

### ISSUE THREAD

**Issue by lg0v0** [gkd-kit/gkd#300]
请问能不能在[跟随规则/默认关闭]这个设置里加一个只开启跳过开屏广告的选项。这个设置里目前只存在全部开启和全部关闭这两个选项，跳过开屏广告几乎是必选，而其他一些跳过规则往往没那么必要，有些还会出现跳过广告以外的效果从而影响正常使用。

我的建议是提供一个默认开启跳过开屏广告的选项，app内部的广告跳过规则默认关闭，让用户按需自行开启。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/255#issuecomment-1817565341
