### ISSUE TITLE
取消对通知权限的不必要依赖

### ISSUE THREAD

**Issue by Raudience** [gkd-kit/gkd#301]
gkd的通知只有保活功能，作为root用户（应该不在少数），我们使用固化为系统应用和无障碍管理器等等手段来保活，这些手段更为强大。
但是开启gkd的服务，并且保证它的后台和无障碍都没问题之后，通知栏里的常驻通知困扰了我--关闭通知就无法开启gkd服务
通知权限不应该成为一个跳广告app启动服务的必要依赖权限，这是没必要的。
可以使用通知权限，但是建议将**是否在通知栏固定通知**设为用户可选项。
感谢大佬

**Comment by lisonge** [comment]
在应用设置通知权限里手动关闭默认的通知渠道即可

**Comment by lingya12** [comment]
> 在应用设置通知权限里手动关闭默认的通知渠道即可

app设置里面设置主动关闭通知栏功能，会不会减少app运行内存，更加省电些？
