### ISSUE TITLE
1.5.1新版本无障碍设置失效

### ISSUE THREAD

**Issue by Ilmiotesoro** [gkd-kit/gkd#305]
鸿蒙3.0系统，更新到最新版后无障碍设置失效

https://github.com/gkd-kit/gkd/assets/57103893/dcf5699e-f4a9-432c-bc1f-6d5efe704147

![Screenshot_20231122_194231_com android settings](https://github.com/gkd-kit/gkd/assets/57103893/fe024be2-4337-4669-9d93-d5a508aef0ef)

**Comment by lisonge** [comment]
结束应用后重新设置
