### ISSUE TITLE
无法启动软件，不断报错闪退

### ISSUE THREAD

**Issue by EagleZhen** [gkd-kit/gkd#308]
Android Version: 13
One UI Version: 5.1

![Screenshot_20231123_085841_One UI Home.jpg](https://github.com/gkd-kit/gkd/assets/31062364/d05ba6a8-38db-4ceb-b04d-25da2e28871d)

**Comment by lisonge** [comment]
哪个版本？

**Comment by EagleZhen** [comment]
> 哪个版本？

最新的1.5.2

**Comment by lisonge** [comment]
结束应用后重启试试

**Comment by lisonge** [comment]
有效果吗？按理来说这个错误是不会出现的

因为app在启动的时候会创建这个目录，但是总有个别手机创建不成功，我真不知道这些手机为什么创建不成功

**Comment by EagleZhen** [comment]
重启/重装软件都失效
不过重启手机以后似乎就修复了
不太清楚系统经历了些什么😂

我一般很少关机，不知道这个对系统是不是会有些影响

**Comment by lisonge** [comment]
不知道，我后续看看
