### ISSUE TITLE
更新 1.52 后，广告跳过变慢，有的无法跳过

### ISSUE THREAD

**Issue by 8267020** [gkd-kit/gkd#309]
我是鸿蒙 4.0 系统，维护云和维护大师 跳不过去，华为主题  有时候行，有时候要等很长时间才能跳过。

回到 1.51 正常跳过
下面是日志
https://github.com/gkd-kit/inspect/files/13445386/file.zip

**Comment by altair441n** [comment]
我也是鸿蒙4.0，更新后大部分广告都跳不了了，上个版本是正常的

**Comment by lliioollcn** [comment]
+1 ，所有广告无法跳过，coloros11

**Comment by JncJordan** [comment]
我发现更新后，快照中ActivityId为空，无法获取有效值

**Comment by lisonge** [comment]
> 我发现更新后，快照中ActivityId为空，无法获取有效值

ActivityId 为空均为你们手机问题，安装 shizuku 可以解决

**Comment by lisonge** [comment]
请提供不跳过的快照

**Comment by wangrui1hao** [comment]
> 请提供不跳过的快照

更新最新版本后确实没办跳过，微博、知乎、腾讯视频等均无反应
快照：https://i.gkd.li/import/13445653

**Comment by lisonge** [comment]
@8267020 

> 我是鸿蒙 4.0 系统，维护云和维护大师 跳不过去，华为主题 有时候行，有时候要等很长时间才能跳过。

我下载了你说的 维护云，我这边是正常跳过

**Comment by lisonge** [comment]
@wangrui1hao 

> 更新最新版本后确实没办跳过，微博、知乎、腾讯视频等均无反应

这3个软件我这边都能正常跳过

**Comment by wangrui1hao** [comment]
> @wangrui1hao
> 
> > 更新最新版本后确实没办跳过，微博、知乎、腾讯视频等均无反应
> 
> 这3个软件我这边都能正常跳过

试过了卸载重装，重启，还是不能跳过
目前暂时回退到 1.51 版本，功能一切正常
另外截了一些1.52版本，不能跳过广告的快照，希望能有帮助，感谢~
https://i.gkd.li/import/13445658
https://i.gkd.li/import/13445664
https://i.gkd.li/import/13445665

**Comment by lisonge** [comment]
@8267020 

从你的日志来看，09:19:53 时触发了维护云的开屏广告，你可以看看点击记录有没有

**Comment by KangSK1** [comment]
鸿蒙4.0折叠屏，外屏可以正常跳过广告，使用内屏时则无法跳过广告。实验了微博 b站 知乎都不行

**Comment by lisonge** [comment]
@KangSK1 请给出日志而不是评论一句不跳过

**Comment by lisonge** [comment]
@wangrui1hao 我看你的 activity 全是 null，你尝试使用 shizuku 模式看看

**Comment by wangrui1hao** [comment]
> @wangrui1hao 我看你的 activity 全是 null，你尝试使用 shizuku 模式看看

shizuku 也试过了，关闭后重新授权，开启 shizuku，同样无反应

**Comment by lisonge** [comment]
@wangrui1hao 麻烦把日志贴一下

**Comment by jiuqianyuan** [comment]
小米的MIUI14（android 13），也出现activity是null的情况，但看日志，跳转app时是识别出了activity的，点击通知栏快照截取按钮后，截取出的快照却是activity为null，是否有些问题

**Comment by wangrui1hao** [comment]
> @wangrui1hao 麻烦把日志贴一下
https://github.com/gkd-kit/inspect/files/13445825/file.zip
更新到1.52 依次打开 微博、知乎、腾讯视频、哔哩哔哩

**Comment by lisonge** [comment]
@wangrui1hao 

从日志来看，你在 `11:30:43` 打开了 腾讯视频 然后触发了开屏广告，你看看点击记录有没有？

**Comment by wangrui1hao** [comment]
> @wangrui1hao
> 
> 从日志来看，你在 `11:30:43` 打开了 腾讯视频 然后触发了开屏广告，你看看点击记录有没有？

对的，只有一个腾讯视频的跳过，其他都没被跳过

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13445863/debug.zip)

试试这个版本呢

**Comment by wangrui1hao** [comment]
> [debug.zip](https://github.com/gkd-kit/gkd/files/13445863/debug.zip)
> 
> 试试这个版本呢

哔哩哔哩 知乎都能跳过，运行正常，但百度网盘还是不能跳过
快照：https://i.gkd.li/import/13445883
日志：https://github.com/gkd-kit/inspect/files/13445885/file.zip

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13445938/debug.zip)

再试试这个呢

**Comment by wangrui1hao** [comment]
> [debug.zip](https://github.com/gkd-kit/gkd/files/13445938/debug.zip)
> 
> 再试试这个呢

知乎、哔哩哔哩、百度网盘均无法跳过

**Comment by 8267020** [comment]
> @8267020
> 
> 从你的日志来看，09:19:53 时触发了维护云的开屏广告，你可以看看点击记录有没有

我打开了好多次，就跳过了一次

**Comment by 8267020** [comment]
@lisonge
下载了debug版本，维护云和维护大师，偶尔能跳过。华为视频 华为音乐 华为主题、腾讯视频 B站 就算能跳过也是要等很长时间。没有启动shizhuku模式，拍照没有界面ID。开启shizuku模式以后还是跟以前一样，但是能拍到快照ID。
喜马拉雅  https://i.gkd.li/import/13446449
腾讯视频 https://i.gkd.li/import/13446454
华为音乐 https://i.gkd.li/import/13446458
华为主题 https://i.gkd.li/import/13446462
维护云 https://i.gkd.li/import/13446465
维护大师 https://i.gkd.li/import/13446468


发现快照的界面都抓到华为桌面的了

**Comment by 8267020** [comment]
![gkd](https://github.com/gkd-kit/gkd/assets/105423402/f39ad775-c653-49f5-b2bc-87b283dd686f)
我刚才又测试了一个软件，有的第一次能跳过，再打开就跳不过去了。
他们的界面ID都成这样了

**Comment by lisonge** [comment]
不知道你们的手机到底怎么回事

**Comment by 8267020** [comment]
> 不知道你们的手机到底怎么回事

从我接触GKD到现象，一直都正常的，拍摄快照也有正常的ID ，就是今天更新 版本以后不行了！

**Comment by lisonge** [comment]
那你先用旧版本吧

**Comment by jiuqianyuan** [comment]
> 那你先用旧版本吧

大佬debug版本解决了activityIds是null的问题了吗

**Comment by 8267020** [comment]
> > 那你先用旧版本吧
> 
> 大佬debug版本解决了activityIds是null的问题了吗

没有

**Comment by lisonge** [comment]
> 大佬debug版本解决了activityIds是null的问题了吗

@jiuqianyuan 试试这个

[debug.zip](https://github.com/gkd-kit/gkd/files/13446699/debug.zip)

**Comment by jiuqianyuan** [comment]
> > 大佬debug版本解决了activityIds是null的问题了吗
> 
> @jiuqianyuan 试试这个
> 

生成快照时activityIds正常了，但是卡顿问题回来了
![454](https://github.com/gkd-kit/gkd/assets/39406781/35b76b1c-9bf0-4a18-ac79-7c03c557c5df)

**Comment by lisonge** [comment]
什么卡顿？

**Comment by jiuqianyuan** [comment]
就是此前1.5.1版本时打开默认app清单和高级模式时内部界面切换的卡顿，不过这会儿又不大感觉的出来了，先当个体感觉差异忽略吧
- #289

**Comment by lisonge** [comment]
debug 版本出现这个是正常情况

**Comment by lisonge** [comment]
@jiuqianyuan 

<https://github.com/gkd-kit/gkd/actions/runs/6966559797> 你使用这个 release 版本应该就不会卡顿

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13446921/debug.zip)

@wangrui1hao @8267020 

麻烦试试这个版本，另外运行后把日志也发出来，这个会输出额外的日志

主要是我没有你们的设备，我所有的设备全是 miui，所以 miui 应该是没问题的

**Comment by drw2005** [comment]
我升级到1.5.2后也是都不跳过了，刚才还重发了快照。

**Comment by fokgaho** [comment]
1.5.2不开shizukuactivityIds是null，开了识别成桌面。miui的，装回1.5.1就正常

**Comment by lisonge** [comment]
反馈有问题的可以试试上面的测试版本然后把日志发出来，就反馈有问题我也不知道咋解决

**Comment by 8267020** [comment]
@lisonge 
看一下日志
https://github.com/gkd-kit/inspect/files/13447223/file.zip
![Screenshot_20231123_160020_li songe gkd debug](https://github.com/gkd-kit/gkd/assets/105423402/998abd74-ccc4-4132-8462-3a53985aabb7)
![gkd](https://github.com/gkd-kit/gkd/assets/105423402/f3fc9431-fb30-4b20-b7ec-7b6303cb7065)

**Comment by lisonge** [comment]
@8267020 

微博你打开了吗？我在日志里并没有看懂微博的id

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13447338/debug.zip)

@8267020 

试试这个呢？

**Comment by lisonge** [comment]
> 打开了，没有跳过 所以没有日志？

不是，只要进去就应该有日志

@8267020

**Comment by fokgaho** [comment]
https://github.com/gkd-kit/inspect/files/13447383/file.zip

**Comment by fokgaho** [comment]
https://github.com/gkd-kit/inspect/files/13447383/file.zip   开了shizuku的快照，不知道这样上传对不对

**Comment by lisonge** [comment]
你用的是不是 <https://github.com/gkd-kit/gkd/issues/309#issuecomment-1823965381> 发的版本

我没有看到任何日志

**Comment by 8267020** [comment]
@lisonge 
这几个 app  又运行了一遍
https://github.com/gkd-kit/inspect/files/13447463/file.zip

**Comment by fokgaho** [comment]
![微信图片_20231123165556](https://github.com/gkd-kit/gkd/assets/151764858/c8e81978-1ca9-4a66-8574-e220bb1b5eb9)

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/gkd/assets/38517192/c9c6edd8-4753-47c0-b413-7709c040b76d)
![image](https://github.com/gkd-kit/gkd/assets/38517192/347f5fa0-e32c-481d-b7ef-f95a2e368ad0)

我有点眉目了，但是还需要确定一下

---

@8267020  麻烦用这个再试试

[debug.zip](https://github.com/gkd-kit/gkd/files/13447667/debug.zip)

**Comment by wangrui1hao** [comment]
> ![image](https://user-images.githubusercontent.com/38517192/285143267-c9c6edd8-4753-47c0-b413-7709c040b76d.png) ![image](https://user-images.githubusercontent.com/38517192/285143195-347f5fa0-e32c-481d-b7ef-f95a2e368ad0.png)
> 
> 我有点眉目了，但是还需要确定一下
> 
> @8267020 麻烦用这个再试试
> 
> [debug.zip](https://github.com/gkd-kit/gkd/files/13447667/debug.zip)

我试了下你最新发的版本，目前常用软件的跳过功能都正常了
日志：https://github.com/gkd-kit/inspect/files/13447856/file.zip

**Comment by 8267020** [comment]
@lisonge 
可以跳过了，速度挺快

目前测试的几个 app，只有维护大师 跳不了

**Comment by lisonge** [comment]
可以，我后续修复一下

**Comment by lisonge** [comment]
> 目前测试的几个 app，只有维护大师 跳不了

这个之前说过是单纯规则不匹配问题

**Comment by lisonge** [comment]
```json5
{
  id: 'com.example.maintenancemaster',
  name: '维护大师',
  groups: [
    {
      key: 0,
      name: '开屏广告',
      actionMaximum: 1,
      matchTime: 10000,
      quickFind: true,
      resetMatch: 'app',
      rules: [
        {
          matches:
            '[id="com.example.maintenancemaster:id/advertisement_countdown_ccd"]',
          snapshotUrls: ['https://i.gkd.li/import/12903877'],
        },
      ],
    },
  ],
}
```

你在本地使用这个规则看看

**Comment by 8267020** [comment]
> ```js
> {
>   id: 'com.example.maintenancemaster',
>   name: '维护大师',
>   groups: [
>     {
>       key: 0,
>       name: '开屏广告',
>       actionMaximum: 1,
>       matchTime: 10000,
>       quickFind: true,
>       resetMatch: 'app',
>       rules: [
>         {
>           matches:
>             '[id="com.example.maintenancemaster:id/advertisement_countdown_ccd"]',
>           snapshotUrls: ['https://i.gkd.li/import/12903877'],
>         },
>       ],
>     },
>   ],
> }
> ```
> 
> 你在本地使用这个规则看看

使用你发的这个规则可以跳过   维护大师 开屏广告了

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.5.3

**Comment by lisonge** [comment]
请问各位更新到 v1.5.3 后是否仍然出现相同的问题？

**Comment by Chivent0506** [comment]
> 请问各位更新到 v1.5.3 后是否仍然出现相同的问题？

大部分已经解决了！给力

**Comment by 8267020** [comment]
没有再出现，很快很好发自我的荣耀手机-------- 原始邮件 --------发件人： Chivent0506 ***@***.***>日期： 2023年11月24日周五 00:48收件人： gkd-kit/gkd ***@***.***>抄送： 8267020 ***@***.***>, Mention ***@***.***>主    题： Re: [gkd-kit/gkd] 更新 1.52 后，广告跳过变慢，有的无法跳过 (Issue #309)

请问各位更新到 v1.5.3 后是否仍然出现相同的问题？

大部分已经解决了！给力
