### ISSUE TITLE
华为-鸿蒙4.0-安装失败-提示未包含任何证书

### ISSUE THREAD

**Issue by 346673164** [gkd-kit/gkd#31]
华为P40 pro 鸿蒙4.0系统安装失败
提示未包含任何证书，请使用官方版本安装。
是还需要等待大佬适配安装包么？

**Comment by lisonge** [comment]
应该是没有打开 允许安装外部来源的 app，下面是一个简单的教程

<https://zhidao.baidu.com/question/1675177415940989427.html>

**Comment by 346673164** [comment]
鸿蒙4.0上面的配置已经没有了。而且其他github下载的apk的确是能正常安装的。
尝试了一下还是不行，估计是鸿蒙4.0有什么特殊的设置

**Comment by lisonge** [comment]
好的，我后续查一下

**Comment by Wudji** [comment]
![Screenshot_20230918_212532](https://github.com/gkd-kit/gkd/assets/93850120/d63845de-b8b4-4c3d-bf3e-5ac163e2eda4)
![Screenshot_20230918_212424_com huawei appmarket](https://github.com/gkd-kit/gkd/assets/93850120/068813bd-35d3-46f6-b0f8-7ee60e540f12)
![Screenshot_20230918_212609_li songe gkd](https://github.com/gkd-kit/gkd/assets/93850120/1678fc59-c6f9-4b0e-80c6-7db3ddba5963)
经测试，我这边可以正常使用

**Comment by czz404** [comment]
mate30pro 4.0系统，正常安装使用

**Comment by lisonge** [comment]
@346673164 

请问能正常安装了吗？

**Comment by lisonge** [comment]
@346673164 

如果使用在电脑上使用 adb 安装能否直接安装 ?
