### ISSUE TITLE
"activityIds": null, 这种是null值的元素会无效且丢失

### ISSUE THREAD

**Issue by JncJordan** [gkd-kit/gkd#310]
{
  "id": "com.ping.cimoc",
  "name": "芝士漫画",
  "groups": [
    {
      "key": 1,
      "name": "[ChangeMe]规则名称-2023-11-23 09:31:30",
      "desc": "[ChangeMe]本规则由GKD网页端审查工具生成",
      "rules": [
        {
          "activityIds": null,
          "matches": "[name$='.Image' && text='' && width<43]",
          "snapshotUrls": "https://i.gkd.li/import/13445396"
        }
      ]
    }
  ]
}

编辑时发现activityIds已经丢失

**Comment by lisonge** [comment]
保存机制就是这样

**Comment by JncJordan** [comment]
这种广告没法点击吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月23日 09:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [gkd-kit/gkd] "activityIds": null, 这种是null值的元素会无效且丢失 (Issue #310) |

Closed #310 as not planned.

**Comment by JncJordan** [comment]
升级到1.5.2后，没有 activityId 返回



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月23日 09:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [gkd-kit/gkd] "activityIds": null, 这种是null值的元素会无效且丢失 (Issue #310) |

保存机制就是这样

**Comment by lisonge** [comment]
> 这种广告没法点击吗？

选择器写错了

---

> 升级到1.5.2后，没有 activityId 返回

你的手机问题，无解
