### ISSUE TITLE
无障碍的授权后，提示此服务运行故障

### ISSUE THREAD

**Issue by XTUxiongda** [gkd-kit/gkd#311]
无障碍的授权后，提示此服务运行故障，是我手机问题么

**Comment by lisonge** [comment]
重启就行

另外请给出日志文件

**Comment by XTUxiongda** [comment]
> 重启就行
> 
> 另外请给出日志文件
重启了还是不行，这是日志
https://github.com/gkd-kit/inspect/files/13446403/file.zip

**Comment by XTUxiongda** [comment]
![89843eec373e15f5566e9f6bd341e19](https://github.com/gkd-kit/gkd/assets/38322373/c4c7280f-a5a4-4ffa-b681-0afb88fdc295)
![303eb5db6a43d6eb4e873efc7cbb13e](https://github.com/gkd-kit/gkd/assets/38322373/4eddba2b-609a-450a-8765-e190d3ff8bc5)

**Comment by lisonge** [comment]
日志里面没有任何错误

**Comment by XTUxiongda** [comment]
> 日志里面没有任何错误

情况就和我贴的截图这个一样，显示此服务出现故障。我在规则了里面把抢红包的勾上了，测了好几个人的，大家都不行，是我们使用方式不对么？

**Comment by lisonge** [comment]
> 情况就和我贴的截图这个一样，显示此服务出现故障。我在规则了里面把抢红包的勾上了，测了好几个人的，大家都不行，是我们使用方式不对么？

不同微信版本的规则不一样，估计是规则已经不适配你的微信版本

**Comment by lisonge** [comment]
无法给出错误，暂时关闭

**Comment by wei-z-git** [comment]
hello @lisonge 
miui14 安卓14(Android13也有)同样遇到此问题，重新开关无障碍后短暂恢复
日志:
https://github.com/gkd-kit/inspect/files/13539211/file.zip
