### ISSUE TITLE
每次点击广告后软件都会重新发送通知

### ISSUE THREAD

**Issue by Gardeniafa** [gkd-kit/gkd#313]
在Android13（iQOO origin OS3）中，每一次软件点击跳过之后，需要更新状态栏常驻通知的统计数据，然而好像不是直接更新常驻通知相关数据，而是重新发送了一条新的常驻通知，导致每一次点击跳过广告的时候，手机的通知铃声都会响起，希望大佬能够看一下~ @lisonge @lliioollcn

**Comment by lisonge** [comment]
你的手机问题，关闭通知权限里的发声权限
