### ISSUE TITLE
新版本快照太慢了

### ISSUE THREAD

**Issue by xyy5s** [gkd-kit/gkd#315]
新版本快照反应太慢了，比如开屏广告点快照，都进入主页了才快照成功，还有好多规则不生效

**Comment by lisonge** [comment]
> 新版本快照反应太慢了

这个和手机以及应用有关，无解

---

> 还有好多规则不生效

哪些规则不生效，你倒是说啊

**Comment by lisonge** [comment]
给出快照

**Comment by lisonge** [comment]
要不你就用旧版本，单纯的文字描述并不能解决问题

**Comment by lisonge** [comment]
还有问题吗？没有的话我直接关闭了

**Comment by lisonge** [comment]
补充信息后可重新打开

**Comment by lisonge** [comment]
请问你使用的是 v1.5.3 吗，你说的这个问题在 v1.5.2 存在，在 v1.5.3 被修复

**Comment by xyy5s** [comment]
对啊，最新版发自我的手机-------- 原始邮件 --------发件人： 二刺螈 ***@***.***>日期： 2023年11月24日周五 半夜12:57收件人： gkd-kit/gkd ***@***.***>抄送： 徐洋洋 ***@***.***>, Author ***@***.***>主    题： Re: [gkd-kit/gkd] 新版本快照太慢了 (Issue #315)
请问你使用的是 v1.5.3 吗，你说的这个问题在 v1.5.2 存在，在 v1.5.3 被修复
