### ISSUE TITLE
GKD在运行时，手机AOD界面无法使用指纹解锁

### ISSUE THREAD

**Issue by mxdlzg** [gkd-kit/gkd#318]
Oneplus 7Pro
类原生Project Elixir 3.13（Android 13）

只要GKD在后台运行，不管有没有打开“服务开启”按钮，AOD界面都不能指纹解锁，除非按电源键亮屏解锁。

**Comment by lisonge** [comment]
运行其它无障碍程序是否也表现相同的行为？

**Comment by mxdlzg** [comment]
> 运行其它无障碍程序是否也表现相同的行为？

没有，而且换李跳跳试了也没这个问题

**Comment by lisonge** [comment]
[debug.zip](https://github.com/gkd-kit/gkd/files/13454645/debug.zip)

使用此版本是否存在问题？

**Comment by lisonge** [comment]
有可能是设置-无障碍前台的问题，你把这个关闭试试

**Comment by mxdlzg** [comment]
> 有可能是设置-无障碍前台的问题，你把这个关闭试试

还没安debug，但是还真是无障碍前台的问题。系统设置关闭无障碍，或者授权无障碍后软件内关闭“无障碍前台”，都可以正常指纹识别了。
