### ISSUE TITLE
最近任务后台显示无法正确隐藏

### ISSUE THREAD

**Issue by GITHUAZHENHAOYONG** [gkd-kit/gkd#32]
魅族18，开启后台隐藏后上滑显示最近任务任然存在

**Comment by lisonge** [comment]
`最近任务后台显示` 上滑本来就存在的

你要正常 back(或者侧滑返回桌面) 退出然后 APP 会额外调用 `finishAndRemoveTask()` 这样才能在任务后台隐藏

**Comment by lisonge** [comment]
请问还有问题吗？没问题我就关闭了
