### ISSUE TITLE
在应用内部出现的广告无法自动关闭

### ISSUE THREAD

**Issue by mhy9989** [gkd-kit/gkd#321]
使用系统为鸿蒙OS 3.0
已经将GKD设置为后台。打开带开屏广告的应用能立刻跳过。但是当应用内部出现弹窗广告时候没办法立刻跳过。需要先手动切换到GKD，然后再切换回带弹窗广告的应用才能识别，这可能是什么问题呢？

**Comment by lisonge** [comment]
安装 shizuku 可以解决
