### ISSUE TITLE
新版本仍然耗电严重

### ISSUE THREAD

**Issue by 1400557585** [gkd-kit/gkd#325]
之前使用的1.41版本，耗电一般。然后1.5版本写了优化耗电问题，更新后却更严重了。而且是几率事件，有时耗电少一些，有时耗电异常严重
![Screenshot_2023-11-27-13-13-16-056-edit_com miui](https://github.com/gkd-kit/gkd/assets/152139084/999138ca-4759-40d1-85ec-fd73bb647f3d)

**Comment by 1400557585** [comment]
版本是最新版，1.54
手机是小米12Spro，MIUI13，安卓12

**Comment by 1400557585** [comment]
之前使用的是李跳跳，那个就非常好，耗电显示里面根本不会把李跳跳排上榜。现在GKD耗电可能是李跳跳的10倍

**Comment by lisonge** [comment]
觉得耗电就卸载吧

不同设备显示耗电不一样，我的耗电就很少

**Comment by lisonge** [comment]
或者你可以自己写代码优化，然后提 pr ，如果方案可行我会考虑合并
