### ISSUE TITLE
1.5.4跳过不稳定，失效

### ISSUE THREAD

**Issue by Ilmiotesoro** [gkd-kit/gkd#326]
不能稳定的跳过开屏广告和软件内广告。
华为鸿蒙3.0系统，具体现象为打开软件的开屏广告有时能跳过，有时跳不过。
电池优化已关闭，无障碍已打开，后台隐藏打开，无障碍前台已打开。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues

**Comment by mofei828** [comment]
红米也是一样，设置了没效果
