### ISSUE TITLE
希望能修复一下MIUI12.5音量条不会自动消失的问题

### ISSUE THREAD

**Issue by Da-baixiong** [gkd-kit/gkd#328]
李跳跳有个选项是可以设置的，但是不懂具体实现方法 如果不行的话只能手动点击一下屏幕了 希望大佬能看看 非常感谢！

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues/new?template=bug_report.yml

**Comment by Da-baixiong** [comment]
> 不知道你在说什么
> 
> 什么音量不会自动关闭？
> 
> 给出截图示例

大佬你好，抱歉之前没上github没看到，我所说的就是李跳跳里面的一项特殊选项，此选项可在miui12.5(开发者选项内开启MIUI优化后)解决音量条不消失的问题(不过随便点一下也可以让音量条自己消失)。

![李跳跳](https://github.com/gkd-kit/gkd/assets/83901371/49c0e1e8-3c01-415a-b0b0-e3448cbdb118)
![音量条](https://github.com/gkd-kit/gkd/assets/83901371/283776b9-1e25-40fa-b0ed-ff0cf01e2384)
