### ISSUE TITLE
集成高级选择器功能，简化自定义规则功能

### ISSUE THREAD

**Issue by lshilshi** [gkd-kit/gkd#329]
参照“/LGH1996/TapClick”实现（不知道有否违规）
1、集成高级选择器功能，而不是截图后再通过电脑（还得装脚本）分析增加规则
![image](https://github.com/gkd-kit/gkd/assets/36767310/1c0e5e6a-3bc6-4b27-be24-5c029ff21ef4)

2、简化自定义规则编制UI，类似李跳跳那样也行，现在这个我在网页端进行分析后，还得从wiki/readme中copy规则实例再来进行修改，可能有人很熟悉，但不是所有人都有编程基础，何况能更友好些不是更好么。
![image](https://github.com/gkd-kit/gkd/assets/36767310/a33a320b-817c-49e5-b300-b87ac84c1bd8)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/254#issuecomment-1794292849

不考虑支持

---

> 现在这个我在网页端进行分析后，还得从wiki/readme中copy规则实例再来进行修改

你完全可以通过类似李跳跳的方式在手机上的本地订阅实时输入提交修改

你完全可以通过 autojs 审查界面而不是通过 gkd 网页审查工具

**Comment by lisonge** [comment]
此外，快照本质只是一个包含 png 和 json 的 zip 文件

你完全可以自己开发一个在手机上的网页来解析这个 zip 文件

当然也欢迎合并到 https://github.com/gkd-kit/inspect 让其更好地适配手机页面
