### ISSUE TITLE
期望增加以下功能

### ISSUE THREAD

**Issue by Administrator6wyj** [gkd-kit/gkd#331]
期望在未来的版本中增加  
应用自动安装、验证码自动填充、apk.1安装器
这三个功能并给予用户以开关，如图所示，图中展示的是禅师APP的功能。
![Screenshot_20231129_191552](https://github.com/gkd-kit/gkd/assets/55020972/bde0522e-bf60-4acc-9956-8248ba5e2072)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
