### ISSUE TITLE
通知栏常驻

### ISSUE THREAD

**Issue by willow-god** [gkd-kit/gkd#332]
您好，尊敬的开发者，很抱歉打扰您，请问通知栏常驻的通知可以去掉吗？我已经掌握了应用后台保活的设置，可以保证他在后台一直运行，不需要通知栏的提醒，请问可以设置一个开关让用户自由的选择打开或者关闭吗？谢谢开发者，祝您工作顺利！
<img width="294" alt="屏幕截图 2023-11-29 203046" src="https://github.com/gkd-kit/gkd/assets/93815242/583a94b8-dd4b-43c7-ac00-f83438805342">

**Comment by lisonge** [comment]
你好，后期会加上这个功能

当前你可以打开通知管理，关闭默认的通知渠道即可
