### ISSUE TITLE
鸿蒙系统为什么会经常出现授权消失的情况？

### ISSUE THREAD

**Issue by 0x783kb** [gkd-kit/gkd#337]
鸿蒙系统为什么会经常出现授权消失的情况？作者有考虑添加一下360智慧生活的开屏广告么？

**Comment by lisonge** [comment]
> 鸿蒙系统为什么会经常出现授权消失的情况？

你可以把日志发出来看看

---

> 作者有考虑添加一下360智慧生活的开屏广告么？

https://github.com/gkd-kit/subscription/issues
