### ISSUE TITLE
华为手机无法正常实现跳过功能

### ISSUE THREAD

**Issue by lzl-hello** [gkd-kit/gkd#338]
我在我的华为手机上安装了该APP，并确保了默认的订阅规则开启；却发现不能实现任何“跳过”；我已经尝试过重启手机；设置，搜索启动，应用启动管理，搜索应用gkd，手动管理，允许自动启动，允许关联启动，允许后台活动；设置，搜索优化，电池优化，不允许那里点击所有应用，将gdk设为不允许；等建议，还是无法实现跳过功能；

这是我提取出来的log：
************* Log Head ****************
Date of Log        : 2023_11_30
Rom Info           : RomInfo{name=huawei, version=14.0.0}
Device Manufacturer: HUAWEI
Device Model       : ANG-AN00
Android Version    : 12
Android SDK        : 31
App VersionName    : 1.5.4
App VersionCode    : 14
************* Log Head ****************

09:19:03.585 D/SourceFile [main, li.songe.gkd.MainActivity$1.invoke(SourceFile:2)]: args[0] = MainActivity
args[1] = onCreate

09:19:28.949 D/SourceFile [main, li.songe.gkd.composition.CompositionExt$useLifeCycleLog$1.invoke(SourceFile:1)]: args[0] = MainActivity
args[1] = onDestroy

09:19:28.994 D/SourceFile [main, li.songe.gkd.MainActivity$1.invoke(SourceFile:2)]: args[0] = MainActivity
args[1] = onCreate

这是华为应用市场无法跳过的界面：（在这里只举了一个APP，其他app也确实不能跳过）
![0805417739d268d7da1c47d367ea3caf](https://github.com/gkd-kit/gkd/assets/96810799/3a7c4449-1d6a-43c0-8696-9f2cdf3206e2)

**Comment by lzl-hello** [comment]
刚刚卸载重装也不行，试了下旧版本也不行；求解答qwq

**Comment by lisonge** [comment]
请将 log 文件发出来，你提取出来的日志是无用的

**Comment by lzl-hello** [comment]
> 请将 log 文件发出来，你提取出来的日志是无用的

请问就是在APP的“分享日志”功能调用系统分享生成的log文件吧，我看了里面只有一个txt文件
[log.zip](https://github.com/gkd-kit/gkd/files/13512912/log.zip)

**Comment by lisonge** [comment]
此外，日志里显示是使用的你用的版本是 v1.5.3 并不是 v1.5.4

**Comment by lzl-hello** [comment]
> 从日志来看，无障碍服务都没有启动，你并没有授权无障碍

您好，感谢您的答复；
我刚刚更新了版本，并确定已经打开了无障碍权限，然而还是没有跳过功能；
不过这次的log里好像多了一些东西（我看log中的版本还是1.5.3，我想可能是因为我试的1.5.3版本，然后在APP中更新到最新版本，他的log生成有bug）
[log(2).zip](https://github.com/gkd-kit/gkd/files/13513192/log.2.zip)

**Comment by lisonge** [comment]
打开 哔哩哔哩 的 开屏广告 能否触发跳过？

**Comment by lzl-hello** [comment]
> > 华为应用市场无法跳过
> 
> 这个估计是没有完全适配，你可以到 https://github.com/gkd-kit/subscription/issues/new/choose

好的，我会提供一些没有的APP快照和没有适配的界面快照
