### ISSUE TITLE
GKD不能正常关闭广告

### ISSUE THREAD

**Issue by Tandent-zz** [gkd-kit/gkd#349]
微信朋友圈广告无法正常关闭，显示了跳过，也有点击情况，但是无法正常关闭，会反复点击
![Screenshot_20231205_093349](https://github.com/gkd-kit/gkd/assets/16612843/e323a83a-18f3-4c02-9e27-da38fd03533a)
![Screenshot_20231205_093401_li songe gkd](https://github.com/gkd-kit/gkd/assets/16612843/a6f996fb-4c15-46f7-bb46-b63dec977e3e)
![Screenshot_20231205_093413_li songe gkd](https://github.com/gkd-kit/gkd/assets/16612843/c69edb1d-3018-48aa-ae5f-2344f3fa224a)
。
这是生成的日志https://github.com/gkd-kit/inspect/files/13553746/file.zip

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
