### ISSUE TITLE
解决方案: 受限制的设置 - 出于安全考虑，此设置目前不可用

### ISSUE THREAD

**Issue by z1046804521** [gkd-kit/gkd#35]
![Screenshot_2023-09-18-20-54-06-482_com android settings](https://github.com/gkd-kit/gkd/assets/128625001/de61e749-6bfb-4839-aeb3-d9e2aa7defdd)
MIUI14，安卓13，环境下无法授权应用无障碍。
在开发者模式下关闭MIUI优化依然不行。
在两个相同环境下的小米设备中成功复现，重启也复现。

**Comment by lisonge** [comment]
是所有无障碍都不可用吗？还是只有 GKD 不可用？

**Comment by z1046804521** [comment]
> 是所有无障碍都不可用吗？还是只有 GKD 不可用？

只有gkd是灰色的不可用。我后来查攻略已经知道原因了。必须要打开gkd的应用设置，找到“受限制的设置”，打开开关就可以打开无障碍模式了。 可惜软件已经卸载了，还是用李跳跳了，不想再折腾了。软件是个好软件。希望能增加一个提示。真是纳闷儿了，安卓13什么时候加的新特性。

**Comment by lisonge** [comment]
好的，后续会在软件中内置问题解决方案

**Comment by lisonge** [comment]
一些补充

<https://support.google.com/android/answer/12623953?hl=zh-Hans>

![image](https://github.com/gkd-kit/gkd/assets/38517192/cd722d0e-7463-4e74-96ca-1731e332b009)

![image](https://github.com/gkd-kit/gkd/assets/38517192/8a90e623-3eb9-4b60-a9b8-af6cdd5c46cb)

**Comment by twoone-3** [comment]
这个需要无障碍或者别的呈现灰色，点一下触发那个受限制的设置弹窗，应用信息内右上角才会有三个点，来给你解除限制
