### ISSUE TITLE
建议在默认订阅规则更新时弹出更新简介

### ISSUE THREAD

**Issue by DuskLights** [gkd-kit/gkd#350]
很多时候提示订阅更新了，但是并不知道更新了什么规则，需要一个应用一个应用点开查找。更新了一些实用的功能也不弹出提示，导致很多时候有的规则已经更新了但是默认不开启，需要手动开启但是又不提示是什么规则更新，很难找。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription
