### ISSUE TITLE
HTTP 服务显示的ip地址错误

### ISSUE THREAD

**Issue by jiuqianyuan** [gkd-kit/gkd#351]
真实IP：
![2124](https://github.com/gkd-kit/gkd/assets/39406781/9c1b3434-e641-4ef3-9d69-e9e69fe63b59)

错误ip：
![eqwd](https://github.com/gkd-kit/gkd/assets/39406781/bc17bc55-3f9c-491e-8812-ba0f1e27dd88)

以上情况在某公共场所时出现，在家庭网络中又是正常的

**Comment by lisonge** [comment]
无解，系统获取到的 ip 地址就是这样的

**Comment by lisonge** [comment]
这种情况出现在先打开 HTTP 服务器，然后换一个 WIFI 或者从 流量切换到 WIFI 的时候会出现

请问点击两次开关按钮来重启内部的 HTTP 服务器是否仍然出现相同的地址呢？

**Comment by jiuqianyuan** [comment]
> 这种情况也会在 先打开 HTTP 服务器，然后换一个 WIFI 或者从 流量切换到 WIFI 的时候 出现
> 
> 请问点击两次开关按钮来重启内部的 HTTP 服务器是否仍然出现相同的地址呢？

多次开关"HTTP服务"按钮，情况并没有改善，依然显示错误的ip。另外我确认了这个ip是蜂窝网络的IP地址。而且把蜂窝网络关闭时，GKD的ip地址也不显示了。
