### ISSUE TITLE
华为设备 无障碍权限 无故关闭

### ISSUE THREAD

**Issue by danielesk** [gkd-kit/gkd#357]
是什么原因导致的？
harmonyos4.0.0系统

**Comment by lisonge** [comment]
请给出日志

**Comment by danielesk** [comment]
@lisonge 

https://github.com/gkd-kit/inspect/files/13575489/file.zip

**Comment by lisonge** [comment]
日志中没有发现错误，你将设置-无障碍前台 关闭后再开启无障碍试试呢

**Comment by danielesk** [comment]
没有显示此服务出现异常/错误/不能运行之类的提示

**Comment by lisonge** [comment]
那就是没有异常崩溃，你是否允许此应用在后台使用，最近任务界面此应用卡片是否加锁，是否忽略电池优化？

**Comment by danielesk** [comment]
只有忽略电池优化没有开启，现在开启了互联电池优化，一会在看看

**Comment by guoxiaolongonly** [comment]
保活弄好就行了，我已经在后台挂了两周了。真的好用，感谢作者大大提供这么好用的APP。虽然也把我们家的软件广告跳过了~

华为的设置如下：手机的系统设置—应用和服务—应用启动管理—找到GKD—关闭自动管理—开启允许自启动允许后台运行。

![微信图片_20231206175504](https://github.com/gkd-kit/gkd/assets/32827485/95eb7ecf-330a-40c5-bf79-a0b327eb22bc)


我们也是做手机APP的，应用也有后台常驻需求。

大家其他机型有遇到问题也可以参考我们兔小巢的问题内的后台常驻配置哈~

https://txc.qq.com/dashboard/faqs/faq-list?pid=0&cid=94500

**Comment by lisonge** [comment]
说实话这个自启动我真不知道咋回事，我的 miui 只需要最近人物界面加个锁就行了，从来没掉过，手机重启也是跟随自启动

**Comment by tiann** [comment]
据我所知，Android 系统的某些版本中，如果无障碍服务所在的应用被 force-stop，系统会将无障碍权限收回；很不幸的是，很多国产 ROM 杀进程都会使用 force-stop，导致无障碍功能权限很容易失效；这个问题在 Android 12 以上得到了解决，但不排除国产ROM 对其进行了魔改。建议为这部分用户增加 adb / shizuku 授权的方式，可以一劳永逸地解决问题。

**Comment by lisonge** [comment]
让他们安装第三方授权工具，api 的适配和处理交给其它软件来做，gkd 不处理这个

**Comment by lisonge** [comment]
> 但不排除国产ROM 对其进行了魔改

@tiann 

请问那是否可能隐藏的 api 也被魔改呢？

因为目前使用的这个获取当前 activity 的 api 都有三种签名

<https://github.com/gkd-kit/gkd/blob/2ea42429661a0487af98dfcf54200e929d3f28b3/app/src/main/kotlin/li/songe/gkd/shizuku/ShizukuApi.kt#L43-L82>

**Comment by tiann** [comment]
> 请问那是否可能隐藏的 api 也被魔改呢？

授予无障碍权限不会直接使用隐藏 API，而是使用 Settings.Secure.putString 这个公开 API；授予 `android.permission.WRITE_SECURE_SETTINGS` 这个权限也是通过 `pm grant` 这个标准的命令。
