### ISSUE TITLE
shizuku模式开启失败，提示toast null

### ISSUE THREAD

**Issue by hzinchengdu** [gkd-kit/gkd#358]
非小米手机，刷的miui10.3，安卓8.1.0

https://github.com/gkd-kit/inspect/files/13578540/file.zip

![Screenshot_2023-12-06-16-41-05-166_li songe gkd](https://github.com/gkd-kit/gkd/assets/126546789/be4a511f-9d9e-46f8-8d76-64b7f8ad2026)

**Comment by lisonge** [comment]
你的设备无法通过 shizuku 获取系统某个服务权限，无解
