### ISSUE TITLE
请问各位更新到 v1.5.4 后是否仍然出现相同的问题？

### ISSUE THREAD

**Issue by baaa1232007** [gkd-kit/gkd#359]
请问各位更新到 v1.5.3 后是否仍然出现相同的问题？

_Originally posted by @lisonge in https://github.com/gkd-kit/gkd/issues/309#issuecomment-1824660282_
            1.5.4 仍有此问题。
汽水音乐启动广告未跳
https://github.com/gkd-kit/inspect/files/13594305/file.zip

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
