### ISSUE TITLE
自动更新订阅失效

### ISSUE THREAD

**Issue by yuchen0010** [gkd-kit/gkd#360]
rt，开了自动更新订阅，一开始可以的，不知道哪个版本开始就不自动更新了。另外希望可以添加订阅的手动更新，就不用删除订阅重新添加后之前关闭的规则还会打开了。

**Comment by colourjwh** [comment]
刚想反馈这个问题
另外能不能加入配置备份的功能呢
一个是软件设置的备份
一个是订阅规则设置的备份
这样在重新添加的时候可以省去很多操作
