### ISSUE TITLE
v174默认订阅怎么把很多规则默认关了？

### ISSUE THREAD

**Issue by DearZack** [gkd-kit/gkd#366]
v174默认订阅怎么把很多规则默认关了？

**Comment by DearZack** [comment]
https://github.com/gkd-kit/subscription  看到这里的新介绍了，
那请问可以直接下载最后一个**非** “仅启用 开屏广告 一类规则”的版本吗

**Comment by lisonge** [comment]
找到指定的 tag 获取 dist 目录下的 gkd.json5 链接即可

但是这个链接的订阅是不会自动更新的
