### ISSUE TITLE
建议,内存订阅可以直接添加到本地规则

### ISSUE THREAD

**Issue by poprains** [gkd-kit/gkd#370]
自己通过快照弄好规则后,添加到内存订阅测试没问题,还需要手动复制添加到本地订阅,同时删除内存订阅,建议可以一键添加到本订阅则,这个功能用的挺频繁,很多小众app都需要自定义规则

**Comment by lisonge** [comment]
网页端更新内存订阅为替换更新即不保留旧规则

你可以在内存订阅界面点击菜单图标后直接复制后粘贴到本地订阅

**Comment by poprains** [comment]
> 内存订阅界面点击菜单图标后直接复制后粘贴到本地订阅，没感觉有多麻烦

你好,我的意思就是感觉每次都要复制内存订阅到本地比较繁琐.不过这不是问题,只是一个体验优化建议.

另外还有个问题,不知道是不是已经有方案我没找到,有些app是整屏滑动广告,比如红果免费短剧,视频流里面插播广告,需要滑动才可以跳过,好像执行选择器内的动作没有上滑或者下滑这个动作,不能通过整屏滑动跳过广告

**Comment by lisonge** [comment]
目前不支持滑动操作，你可以使用 autojs 这类 app 实现
