### ISSUE TITLE
请求适配

### ISSUE THREAD

**Issue by yangone1** [gkd-kit/gkd#385]
[snapshot-1702539226261.zip](https://github.com/gkd-kit/gkd/files/13670660/snapshot-1702539226261.zip)
[snapshot-1702538775031.zip](https://github.com/gkd-kit/gkd/files/13670662/snapshot-1702538775031.zip)
阿里云盘的蓝圆圈
番茄阅读中立即领取

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
