### ISSUE TITLE
gkd app  默认订阅 是否可以增加一个搜索框  方便检索某一app

### ISSUE THREAD

**Issue by tiyuban123** [gkd-kit/gkd#39]
默认订阅 是否可以增加一个搜索框
![IMG_20230919_075517](https://github.com/gkd-kit/gkd/assets/128196345/91f89cda-b697-447e-8979-c4df8542b249)

**Comment by lisonge** [comment]
后续增加

**Comment by PYUDNG** [comment]
感谢。同需求此功能。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
