### ISSUE TITLE
单规则模板

### ISSUE THREAD

**Issue by k2y1982** [gkd-kit/gkd#394]
//单规则模板
{
  id: '复制AppId替换我',
  name: '复制Name替换我',
  groups: [
    {
      key: 1,
      name: '自己写一个规则名字',
      activityIds: ['复制ActivityId替换我'],//只修改['内的内容']
      rules: [
        {
          matches: '[在右边复制一个要点击的替换我]',
          snapshotUrls: '复制链接快照替换我',//需登录github账号才能分享复制链接
        },
      ],
    },
  ],
}

**Comment by k2y1982** [comment]
![image](https://github.com/gkd-kit/gkd/assets/5109711/068bc5bd-cdd2-4c8b-a522-70e8008ec1f6)

**Comment by k2y1982** [comment]
//单规则模板
{
  id: 'com.tencent.mm',
  name: '微信',
  groups: [
    {
      key: 1,
      name: '微信小程序卡片广告1',
      activityIds: ['com.tencent.mm.ui.LauncherUI'],//只修改['内的内容']
      rules: [
        {
          matches: '[text="feedback_icon"]',
          snapshotUrls: 'https://i.gkd.li/import/13694604',//需登录github账号才能分享复制链接
        },
      ],
    },
  ],
}

**Comment by lisonge** [comment]
？
