### ISSUE TITLE
建议添加向kde connect一样的保活机制

### ISSUE THREAD

**Issue by cpromax** [gkd-kit/gkd#395]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

建议添加向kdeconnect一样的持久化通知
![Screenshot_20231217_191923](https://github.com/gkd-kit/gkd/assets/105175150/1f479b86-081b-42b1-97ac-2d1f5a98f6c2)

**Comment by lisonge** [comment]
不考虑增加
