### ISSUE TITLE
网易邮箱无法跳过

### ISSUE THREAD

**Issue by guanjian1212** [gkd-kit/gkd#397]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13710784/file.zip

### Bug 描述

![Screenshot_2023-12-19-11-17-50-866_com netease mobimail](https://github.com/gkd-kit/gkd/assets/117835543/90bc936d-122a-4f64-aeca-0571848d4ca5)
我在使用GKD时遇到了网易邮箱开屏广告无法跳过的问题，我期望广告可以跳过，实际有时网易邮箱开屏广告可以跳过，有时又不可以跳过，比较不稳定

**Comment by lentikr** [comment]
解决了吗？朋友

**Comment by guanjian1212** [comment]
> 解决了吗？朋友

现在用回李跳跳，能跳过网易邮箱
