### ISSUE TITLE
腾讯视频

### ISSUE THREAD

**Issue by WenmuZhou** [gkd-kit/gkd#398]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

[1702973481266.zip](https://github.com/gkd-kit/gkd/files/13712863/1702973481266.zip)

### Bug 描述

腾讯视频开屏广告，弹了跳过提示，但是没有跳过广告

**Comment by lisonge** [comment]
日志文件错误，这是快照文件

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
