### ISSUE TITLE
软件在通知栏建议

### ISSUE THREAD

**Issue by gankumangcao** [gkd-kit/gkd#399]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

软件在通知栏划不掉比较碍眼，长按可以关闭GKD软件的所有通知，但所有都关了又不好，希望加个设置能开关常驻或不常住在通知栏，以前用李跳跳现在用GKD后觉得GKD更不错，希望开发者大大能弄个开关就好了。虽然前面有人提过，这开关挺重要的所以+1反馈
![5cb7d90900ea7bc182fadbdc850fa1d439601387](https://github.com/gkd-kit/gkd/assets/85823141/4473d6ac-330a-4cad-af73-61a01814b236)
![f9995568937edf1dbd015cc5cd7179c039601387](https://github.com/gkd-kit/gkd/assets/85823141/98e33905-8746-417e-865d-e0271e1e1660)
![dd8d755779b8e573aac13e9ca2c64e7139601387](https://github.com/gkd-kit/gkd/assets/85823141/f29bef6e-9dad-40e0-94fe-8fd2d2ffa3d0)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/382
