### ISSUE TITLE
有关无障碍授权问题

### ISSUE THREAD

**Issue by xianren152** [gkd-kit/gkd#401]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13734383/file.zip

### Bug 描述

GKD的无障碍授权经常会被自动关闭，导致功能失效
bug来自一加9，ColorOS13.1，安卓13

**Comment by lisonge** [comment]
机型问题，无法解决
