### ISSUE TITLE
小米 HyperOS 或许需要适配 Toast

### ISSUE THREAD

**Issue by oahnaLiew** [gkd-kit/gkd#404]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

![IMG_20231222_174802](https://github.com/gkd-kit/gkd/assets/26448604/14ae9277-a562-4462-8b13-ac7ef7641a98)

如图，更新到小米的 HyperOS 后，应用自定义的 Toast 会沉到很靠下的位置。
或许需要适配一下？

**Comment by Shounaonao** [comment]
是的太低了，我也想反馈下，然后看到了你的反馈 🤣

**Comment by MagiciSource** [comment]
确实低

**Comment by jiuban590** [comment]
顶一下，确实有点低

**Comment by fujie-xiyou** [comment]
为啥gkd没用系统自带的toast，而是自己绘制的这种？如果改成系统自带的toast就不会有这类问题了

**Comment by dingTony** [comment]
请问你们用这个有没有一种卡系统的感觉，比李跳跳卡，hyperos

**Comment by Dystnine** [comment]
> 请问你们用这个有没有一种卡系统的感觉，比李跳跳卡，hyperos

有，miui10也是，而且喜欢在浏览器里面跳过这两个字的地方一直摁

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases

**Comment by fujie-xiyou** [comment]
> https://github.com/gkd-kit/gkd/releases

👍👍👍  老板为啥不直接用系统自带的toast? 这样还不用悬浮窗权限

**Comment by lisonge** [comment]
应用内使用自定义 toast，因为系统自带 toast 限制显示长度，我需要显示某些错误信息如错误选择器的长度就超过这个限制

应用外部使用你说的系统自带 toast，因为它只会显示你的触发提示

**Comment by fujie-xiyou** [comment]
意思是最新的这个版本，不需要悬浮窗权限也可以显示跳过提示了？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月9日(周六) 凌晨1:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gkd-kit/gkd] 小米 HyperOS 或许需要适配 Toast (Issue #404)




 
应用内使用自定义 toast，因为系统自带 toast 限制显示长度，我需要显示某些错误信息如错误选择器的长度就超过这个限制
 
应用外部使用你说的系统自带 toast，因为它只会显示你的触发提示

**Comment by fujie-xiyou** [comment]
另外 新版的app图标就是上半部分灰色的吗？我以为我系统出问题图标损坏了，哈哈哈

**Comment by lisonge** [comment]
图标目前就是这样，但是还是有点不符合纯色大背景，可能后续还会改

**Comment by fujie-xiyou** [comment]
> 图标目前就是这样，但是还是有点不符合纯色大背景，可能后续还会改

好的 谢谢老板解答✌ 早点休息
