### ISSUE TITLE
△无标签配置，请添加配置或关闭多语音选项！

### ISSUE THREAD

**Issue by alanOO7** [gkd-kit/gkd#405]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

![Screenshot_20231223_064751_com tencent mm](https://github.com/gkd-kit/gkd/assets/10321054/f3b598a8-7ef5-4d87-9617-7f6a5832a09b)
这个是gkd 的提示吗，怎么关闭呢😂

### Bug 描述

△无标签配置，请添加配置或关闭多语音选项！
弹出标签

**Comment by lisonge** [comment]
不是
