### ISSUE TITLE
点击规则开关无响应

### ISSUE THREAD

**Issue by uiiang** [gkd-kit/gkd#410]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

日志文件已上传网盘
https://www.alipan.com/s/fin1BUoFJmC

### Bug 描述

点击规则开关，经常没有反应，有时连续点击后应用内所有开关都打开或关闭，再次进入规则后开关位置还是处于关闭状态，机型小米9和小米11

效果演示 ： https://www.alipan.com/s/fin1BUoFJmC

**Comment by lisonge** [comment]
结束应用后重启呢？

**Comment by uiiang** [comment]
> 结束应用后重启呢？

试过也不行，重启gkd或者重启手机都不行，在gkd的主页里重新开关服务也不行，但是点击“服务开启”响应很顺利。只有在订阅tab的一二三级界面会出现这些问题

**Comment by uiiang** [comment]
刚才试了一下卸载重装，刚安装上的时候点击规则开关都很顺利，但重启手机后又会复现问题，不知道和重启有没有关系

**Comment by lisonge** [comment]
看起来是 Android Room 的在特定机型的 BUG，无法复现和解决，先这样吧
