### ISSUE TITLE
本地导入同名规矩

### ISSUE THREAD

**Issue by yechen2018** [gkd-kit/gkd#411]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

可以添加个是否替换规矩弹窗

**Comment by lisonge** [comment]
不支持
