### ISSUE TITLE
【项目编译问题】添加@Preview注解后，无法正常预览布局，作者有什么解决方案或者建议么？

### ISSUE THREAD

**Issue by hanxiaofeng** [gkd-kit/gkd#413]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

<img width="1428" alt="image" src="https://github.com/gkd-kit/gkd/assets/10582931/ec717f30-3bb1-4ef5-8d00-3ea034e72ffa">

### Bug 描述

添加@Preview注解后，无法正常预览布局，作者有什么解决方案或者建议么？

**Comment by lisonge** [comment]
没有
