### ISSUE TITLE
三星s20+ 系统oneui5.1，酷安广告跳过缓慢

### ISSUE THREAD

**Issue by silverblade7246** [gkd-kit/gkd#414]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13764375/file.zip

### Bug 描述

GKD版本最新，订阅也是最新，酷安也是最新版本。GKD在酷安内点完关闭广告，在这个地方会停留一到两秒才会继续点击屏蔽广告，我的另一台老三星设备note9 oneui2.5就正常
![Screenshot_20231225_142436_CoolApk](https://github.com/gkd-kit/gkd/assets/67468014/e9d5a82a-f68c-4093-b330-f2579bc2d59d)

**Comment by boiyun** [comment]
我也发现了，好像是得页面停止滑动后，才会触发跳过吧？

**Comment by silverblade7246** [comment]
> 我也发现了，好像是得页面停止滑动后，才会触发跳过吧？

停止滑动也不行，就是必须的等待一到两秒才会点掉这个页面框。

**Comment by sorrymaker0122** [comment]
我是根本跳不了，小米14，现在酷安开屏也跳不了了

**Comment by zjpllll** [comment]
我直接就停在你截图的页面了 要自己点不感兴趣

**Comment by lisonge** [comment]
我的设备无法复现，无法修复你的问题

建议换个设备或者不要使用此规则
