### ISSUE TITLE
B站客户端开屏广告无法跳过

### ISSUE THREAD

**Issue by l1090921084** [gkd-kit/gkd#416]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

[util_2023_12_25_li.songe.gkd.txt](https://github.com/gkd-kit/gkd/files/13765325/util_2023_12_25_li.songe.gkd.txt)

### Bug 描述

手机版本系统是MIUI 14.0.19 ，B站版本是7.60.0
GKD点击记录里面没有跳过B站开屏广告的记录，日志里面打印的是active:false
`13:13:36.217 D/SourceFile [DefaultDispatcher-worker-1, li.songe.gkd.service.GkdAbService$1$7$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=tv.danmaku.bili, activityId=com.bilibili.ship.theseus.detail.UnitedBizDetailsActivity)
args[1] = subsId:0, gKey=-1, gName:开屏广告, ruleIndex:0, rKey:null, active:false`

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
