### ISSUE TITLE
希望在首页的订阅那里添加一个手动更新的列表

### ISSUE THREAD

**Issue by freedomspiritJohn** [gkd-kit/gkd#417]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

![Screenshot_2023-12-25-21-03-49-024_li songe gkd](https://github.com/gkd-kit/gkd/assets/129288685/97a4e5e4-67b4-47c3-b1f4-e419111078b6)
比如这里的订阅显示一个月前，我不知道是一个月前添加的订阅还是一个月钱更新的订阅。
![Screenshot_2023-12-25-21-07-25-372_li songe gkd](https://github.com/gkd-kit/gkd/assets/129288685/bcf8c52f-fdd6-46a7-aa12-3a87f53c236f)
所以希望在这个列表里添加一个更新当前订阅的列表

**Comment by lisonge** [comment]
下拉刷新
