### ISSUE TITLE
腾讯视频

### ISSUE THREAD

**Issue by liuxiaoqigui** [gkd-kit/gkd#420]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13768101/file.zip
https://i.gkd.li/import/13768076
https://i.gkd.li/import/13768076

### Bug 描述

腾讯视频广告无法跳过

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
