### ISSUE TITLE
繁中語言下朋友圈不能跳過廣告

### ISSUE THREAD

**Issue by wonghouwing** [gkd-kit/gkd#429]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

手機語言是中文（香港），微信顯示語言自動跟隨，朋友圈廣告不能跳過

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/issues
