### ISSUE TITLE
通知栏权限失去

### ISSUE THREAD

**Issue by mmmm708090** [gkd-kit/gkd#436]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

时不时会失去通知栏权限，所有的权限，自启动，通知栏，电池优化，无限制，全部给了，还会丢失。上一个版本就没问题。

### Bug 描述

时不时会失去通知栏权限，所有的权限，自启动，通知栏，电池优化，无限制，全部给了，还会丢失。上一个版本就没问题。

**Comment by mmmm708090** [comment]
时不时会失去通知栏权限，所有的权限，自启动，通知栏，电池优化，无限制，全部给了，还会丢失。上一个版本就没问题。

**Comment by lisonge** [comment]
无日志文件

**Comment by lisonge** [comment]
你好，可以试试 <https://github.com/gkd-kit/gkd/actions/runs/7365326476/artifacts/1140423205> 这个版本
