### ISSUE TITLE
荣耀magicos 8.0系统无法对gkd进行无障碍授权

### ISSUE THREAD

**Issue by 1LL23** [gkd-kit/gkd#437]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/gkd/assets/155221574/f539fba0-4bb7-42b2-a475-c0f989efcfbe

### Bug 描述

我在使用gkd进行更新1.6.2版本后，在荣耀MagicOS8.0系统无法对gkd进行无障碍授权，期望能够解决。

**Comment by lisonge** [comment]
不知道，无法复现
