### ISSUE TITLE
重新加入 一键启用/关闭所有规则 开关

### ISSUE THREAD

**Issue by DeveloperEmber** [gkd-kit/gkd#438]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

此开关在新版本中被移除,导致开关规则十分不便,希望可以在下个版本重新加入

**Comment by lisonge** [comment]
不支持

**Comment by DeveloperEmber** [comment]
能问一下这是为什么吗?

**Comment by Ember-Developer** [comment]
> 不支持

能问一下这是为什么吗?

**Comment by lisonge** [comment]
不想把规则的启用/禁用搞得太复杂

---

你可以对 <https://registry.npmmirror.com/@gkd-kit/subscription/latest/files> 代理

然后将所有规则的 enable 设置为 true

可以参考 <https://github.com/gkd-kit/gkd/issues/255#issuecomment-1797474482>

**Comment by Ember-Developer** [comment]
> 不想把规则的启用/禁用搞得太复杂
> 
> 你可以对 https://registry.npmmirror.com/@gkd-kit/subscription/latest/files 代理
> 
> 然后将所有规则的 enable 设置为 true
> 
> 可以参考 [#255 (comment)](https://github.com/gkd-kit/gkd/issues/255#issuecomment-1797474482)

好的,谢谢

**Comment by Anivie** [comment]
> 不想把规则的启用/禁用搞得太复杂
> 
> 你可以对 https://registry.npmmirror.com/@gkd-kit/subscription/latest/files 代理
> 
> 然后将所有规则的 enable 设置为 true
> 
> 可以参考 [#255 (comment)](https://github.com/gkd-kit/gkd/issues/255#issuecomment-1797474482)

是否可以考虑官方提供全部启用的版本，用户可以直接添加而不需要自己搭建代理
