### ISSUE TITLE
Vivo手机授权无障碍服务后软件出现崩溃 

### ISSUE THREAD

**Issue by suchenup** [gkd-kit/gkd#44]
1、Vivo X21 安卓9版本，gkd软件版本1.2.0。
2、自启动，省电策略都打开了，使用shizuku保活都不行。

**Comment by xchaix** [comment]
同vivo，装了shiziku也不行

**Comment by lisonge** [comment]
试试 https://github.com/gkd-kit/gkd/releases/tag/v1.2.1 呢

**Comment by suchenup** [comment]
@lisonge 
![Screenshot_20230920_234943](https://github.com/gkd-kit/gkd/assets/52001271/920ef2a6-550a-4c82-81fc-a3bebd4865ce)
还是会崩溃哦！

**Comment by lisonge** [comment]
感谢反馈，会尽快修复

**Comment by suchenup** [comment]
> 试试https://github.com/gkd-kit/gkd/releases/tag/v1.2.1呢



> 试试https://github.com/gkd-kit/gkd/releases/tag/v1.2.1呢



> 感谢反馈，会尽快修复

好的，辛苦啦！

**Comment by lisonge** [comment]
@suchenup 

试试这个呢，重新构建了一下，https://lisonge.lanzouy.com/iAHqL198neja

**Comment by suchenup** [comment]
@lisonge **问题依然重现！**

**Comment by lisonge** [comment]
@suchenup 请问你开启 shizuku 了吗，如果你把 shizuku 授权关掉呢

**Comment by suchenup** [comment]
@lisonge 两种情况都测试过了，还是会崩溃。

**Comment by lisonge** [comment]
@suchenup 

https://lisonge.lanzouy.com/iDfqK198p87e

这次直接判断是 Android 9 和 vivo 就跳过报错的方法调用，可以试试

**Comment by lisonge** [comment]
搞错了，应该是 https://lisonge.lanzouy.com/iLPtu198piqd
