### ISSUE TITLE
添加功能

### ISSUE THREAD

**Issue by qimlisky** [gkd-kit/gkd#440]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

我希望gkd添加个配置修改和单个配置修改的地方，就例如上面的图片，因为网络和加载原因，15s可能有点不够，也因人而异，给个修改的地方用户自行完善

**Comment by lisonge** [comment]
不支持

会延长加载超时判断
