### ISSUE TITLE
最新版不支持Magic OS 8.0

### ISSUE THREAD

**Issue by binkwong** [gkd-kit/gkd#445]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

无法开启无障碍权限

### Bug 描述

1.5.4还没有问题，升级1.6.2后，无障碍权限无法开启，没有任何提示

**Comment by lisonge** [comment]
无法复现

建议换个手机

**Comment by binkwong** [comment]
可能是系统bug，我已经反馈给荣耀论坛，但是李跳跳打开是没有问题的
