### ISSUE TITLE
GKD导致多任务界面手势操作卡顿

### ISSUE THREAD

**Issue by noahhhi** [gkd-kit/gkd#447]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13814865/file.zip

### Bug 描述

开启gkd无障碍服务导致多任务界面手势操作卡顿，例如小横条切换应用，上滑悬停等，关闭后流畅度恢复正常。一加11运行namelessAOSP。

**Comment by lisonge** [comment]
使用 v1.6.3 即可
