### ISSUE TITLE
一加7：全局开屏广告规则会将闹钟给取消掉

### ISSUE THREAD

**Issue by z1030** [gkd-kit/gkd#448]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

![image](https://github.com/gkd-kit/gkd/assets/93397238/147aa27c-6461-4ad9-8f70-6a54fe0b4580)

### Bug 描述

一加7：全局开屏广告规则会将闹钟给取消掉

**Comment by Duanzh** [comment]
+1
