### ISSUE TITLE
[bug] gkd Activity 叠加在网易邮箱大师上方

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/gkd#45]
复现步骤：
1. 打开网易邮箱大师
2. 点击“我”→“关于网易邮箱大师”→“发现新版本”
3. 切换至后台，打开 GKD
4. 切换至后台，返回网友邮箱大师
5. 此时打一个快照，发现 ActivityId 为 li.songe.gkd.MainActivity

APP 版本：7.14.3

设备：Xiaomi 13 MIUI14.0.23.8.28.DEV 开发版

bug 快照：https://gkd-kit.gitee.io/import/12664194

**Comment by lisonge** [comment]
是手机无障碍的局限性，使用 shizuku 可以解决
