### ISSUE TITLE
全局规则导致部分网页卡顿

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#451]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13816844/file.zip

### Bug 描述

情景描述：开启全局规则后，使用无内核的浏览器（如via，x浏览器）打开GitHub主页，此时返回桌面再从后台进入浏览器，上下滑动一会儿就会变得非常卡顿，关闭全局规则后就不会出现上述卡顿的情况。
我测试了4款浏览器，分别是via，x浏览器，soul browser，可拓浏览器（自带内核），发现只有自带内核的可拓浏览器不会出现卡顿，无内核浏览器均会出现卡顿，不清楚这是规则的问题还是gkd本身的问题。
测试网站（均出现卡顿）：
https://m.chinaz.com/ 
https://github.com/
https://clashios.com/latest/
浏览器搜索结果页

**Comment by lisonge** [comment]
https://github.com/gkd-kit/subscription/commit/d96eabc66c4434f3fafef7b75e2624decc38c03a
