### ISSUE TITLE
v1.6.3 用后有以下建议

### ISSUE THREAD

**Issue by l0001-repo** [gkd-kit/gkd#453]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

1. snapshotUrls能支持本地预载，例如/gkd/import/11111111.zip
2. 关闭了Http服务后自动把内存订阅拷贝到本地订阅
3. 提供本地订阅的汇入和汇出功能
4. Http服务可以绕过https://i.gkd.li/device而直达http://*:8888
Thanks

**Comment by lisonge** [comment]
1.这个需要解析里面的zip文件，而且图片文件很大，不考虑
2.不支持
3.不支持
4.http服务必须要在 https 下运行，否则某些 js api无法使用
