### ISSUE TITLE
应用JavDB无法正确跳过公告弹窗

### ISSUE THREAD

**Issue by zhenxiaoxiang** [gkd-kit/gkd#454]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13819992/file.zip

### Bug 描述

我在使用GKD时遇到了应用JavDB公告弹窗无法跳过的问题
我期望的行为是跳过开屏广告之后连带跳过公告弹窗
实际的行为是可以正确跳过开屏广告，但是无法跳过公告弹窗，需要手动切换应用后台GKD才能感知到公告弹窗并跳过

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/375
