### ISSUE TITLE
更新规则

### ISSUE THREAD

**Issue by Bitm-m** [gkd-kit/gkd#455]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

我每次更新规则，这个选项都会恢复默认的配置，要重新选择很麻烦，希望不会覆盖之前的选项
![Screenshot_2024-01-04-14-35-03-242_li songe gkd](https://github.com/gkd-kit/gkd/assets/77094782/a4fc5eec-695f-4dd7-8d6e-13a5bc50871a)

**Comment by lisonge** [comment]
你是怎么更新规则的？

**Comment by lisonge** [comment]
无日志文件
