### ISSUE TITLE
最新版本无障碍点击不完全生效

### ISSUE THREAD

**Issue by uu19** [gkd-kit/gkd#458]
### 一些验证

- [x] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

************* Log Head ****************
Date of Log        : 2024_01_04
Rom Info           : RomInfo{name=huawei, version=13.0.0}
Device Manufacturer: HUAWEI
Device Model       : PCT-AL10
Android Version    : 10
Android SDK        : 29
App VersionName    : 1.6.2
App VersionCode    : 17
************* Log Head ****************

09:42:19.577 D/SourceFile [DefaultDispatcher-worker-4, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.android.launcher, activityId=com.huawei.android.launcher.unihome.UniHomeLauncher, number=2)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:42:22.219 D/SourceFile [DefaultDispatcher-worker-2, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=com.android.systemui, activityId=null, number=0)
09:42:38.467 D/SourceFile [DefaultDispatcher-worker-7, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.android.mms, activityId=null, number=0)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:42:40.667 D/SourceFile [DefaultDispatcher-worker-2, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=com.android.systemui, activityId=null, number=0)
09:42:43.169 D/SourceFile [DefaultDispatcher-worker-3, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.android.mms, activityId=null, number=0)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:42:44.891 D/SourceFile [DefaultDispatcher-worker-3, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.android.launcher, activityId=com.huawei.android.launcher.unihome.UniHomeLauncher, number=3)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:42:46.846 D/SourceFile [DefaultDispatcher-worker-5, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=com.android.systemui, activityId=null, number=0)
09:42:47.422 D/SourceFile [DefaultDispatcher-worker-8, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.android.launcher, activityId=com.huawei.android.launcher.unihome.UniHomeLauncher, number=3)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:42:48.021 D/SourceFile [DefaultDispatcher-worker-5, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=li.songe.gkd, activityId=li.songe.gkd.MainActivity, number=4)
09:42:54.251 D/BaseContinuationImpl [main, kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:11)]: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
 Caused by: java.net.UnknownHostException: Unable to resolve host "registry.npmmirror.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at w6.c0.b(Unknown Source:5)
	at b9.f.a(Unknown Source:437)
	at b9.a.a(Unknown Source:81)
	at c9.f.b(Unknown Source:132)
	at z8.a.a(Unknown Source:165)
	at c9.f.b(Unknown Source:132)
	at c9.a.a(Unknown Source:239)
	at c9.f.b(Unknown Source:132)
	at c9.g.a(Unknown Source:160)
	at c9.f.b(Unknown Source:132)
	at b9.j.g(Unknown Source:95)
	at b9.g.run(Unknown Source:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

09:42:56.306 D/SourceFile [DefaultDispatcher-worker-8, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=com.android.systemui, activityId=null, number=0)
09:42:57.694 D/SourceFile [DefaultDispatcher-worker-8, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=li.songe.gkd, activityId=li.songe.gkd.MainActivity, number=4)
09:43:29.831 D/SourceFile [DefaultDispatcher-worker-5, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=li.songe.gkd, activityId=li.songe.gkd.MainActivity, number=5)
09:43:33.582 D/SourceFile [DefaultDispatcher-worker-8, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=com.android.systemui, activityId=null, number=0)
09:43:35.874 D/SourceFile [DefaultDispatcher-worker-8, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=li.songe.gkd, activityId=li.songe.gkd.MainActivity, number=5)
09:43:37.494 D/SourceFile [DefaultDispatcher-worker-2, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=li.songe.gkd, activityId=li.songe.gkd.MainActivity, number=6)
09:43:55.972 D/SourceFile [DefaultDispatcher-worker-2, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=li.songe.gkd, activityId=li.songe.gkd.MainActivity, number=7)
09:44:13.466 D/SourceFile [DefaultDispatcher-worker-8, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=li.songe.gkd, activityId=li.songe.gkd.MainActivity, number=8)
09:44:21.939 D/SourceFile [DefaultDispatcher-worker-5, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.android.packageinstaller, activityId=com.android.packageinstaller.InstallStaging, number=9)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:44:23.415 D/SourceFile [DefaultDispatcher-worker-9, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.appmarket, activityId=com.huawei.appgallery.systeminstalldistservice.ui.activity.InstallDistActivity, number=1)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:44:24.756 D/SourceFile [DefaultDispatcher-worker-9, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.appmarket, activityId=com.huawei.appgallery.systeminstalldistservice.ui.activity.InstallDistActivity, number=2)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:44:26.672 D/SourceFile [DefaultDispatcher-worker-9, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.coauthservice, activityId=com.huawei.unifiedauthwidget.dialog.UnifiedAuthenticationDialogActivity, number=3)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:44:35.644 D/SourceFile [DefaultDispatcher-worker-5, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.appmarket, activityId=com.huawei.appgallery.systeminstalldistservice.ui.activity.InstallDistActivity, number=4)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:44:36.152 D/SourceFile [DefaultDispatcher-worker-1, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=com.android.systemui, activityId=null, number=0)
09:44:36.778 D/SourceFile [DefaultDispatcher-worker-1, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.appmarket, activityId=com.huawei.appgallery.systeminstalldistservice.ui.activity.InstallDistActivity, number=4)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:44:37.382 D/SourceFile [DefaultDispatcher-worker-9, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=com.android.systemui, activityId=null, number=0)
09:44:38.494 D/SourceFile [DefaultDispatcher-worker-1, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: args[0] = TopActivity(appId=com.huawei.appmarket, activityId=com.huawei.appgallery.systeminstalldistservice.ui.activity.InstallDistActivity, number=5)
args[1] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:0, key:0, status:ok
args[2] = id:0, v:182, type:global, gKey=0, gName:开屏广告, index:1, key:-1, status:ok

09:44:42.423 D/SourceFile [main, li.songe.gkd.service.GkdAbService$1.invoke(SourceFile:2)]: args[0] = GkdAbService
args[1] = onCreate

09:44:42.439 D/SourceFile [main, li.songe.gkd.service.ManageService$1.invoke(SourceFile:2)]: args[0] = ManageService
args[1] = onCreate

09:44:42.732 D/SourceFile [DefaultDispatcher-worker-6, li.songe.gkd.service.GkdAbService$1$6$1.emit(SourceFile:1)]: TopActivity(appId=, activityId=null, number=0)
09:44:42.876 D/SourceFile [main, li.songe.gkd.composition.CompositionExt$useLifeCycleLog$3.invoke(SourceFile:1)]: args[0] = GkdAbSer

### Bug 描述

旧版本可以100%执行点击，新版本偶尔不生效

**Comment by lisonge** [comment]
需要日志文件

**Comment by lisonge** [comment]
哪个规则在哪个界面不生效？

**Comment by uu19** [comment]
> 哪个规则在哪个界面不生效？

同样的规则在旧版生效，新版偶尔不生效

**Comment by lisonge** [comment]
请给出完整的日志 zip 文件

哪个规则在哪个界面不生效？

这个界面的快照是什么？

请正确回答以上问题，否则 issue 将被直接关闭

**Comment by uu19** [comment]
> 请给出完整的日志 zip 文件
> 
> 哪个规则在哪个界面不生效？
> 
> 这个界面的快照是什么？
> 
> 旧版本是哪个版本？
> 
> 请正确回答以上问题，否则 issue 将被直接关闭

好像是无障碍的问题，无障碍没掉但是重新开启了一下正常了
