### ISSUE TITLE
FR: 应用黑名单

### ISSUE THREAD

**Issue by Miuzarte** [gkd-kit/gkd#459]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

浏览网页也帮我点跳过，因为属于全局规则还没法禁用
![f5523d468926fc50779b816a7d9b44cb](https://github.com/gkd-kit/gkd/assets/66856838/cd64c6b4-1d8d-478d-99fd-9b22c80ac2c9)

**Comment by lisonge** [comment]
点击记录，在此应用禁用
