### ISSUE TITLE
增加action动作（action:check）

### ISSUE THREAD

**Issue by emutony** [gkd-kit/gkd#461]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

目前的action有如下功能：
  action?:
    | 'click'
    | 'clickNode'
    | 'clickCenter'
    | 'back'
    | 'longClick'
    | 'longClickNode'
    | 'longClickCenter';
希望增加如check功能，当checkable为true，且checked为false时，把checked状态改为true。
该功能可解决此问题 https://i.gkd.li/import/13848732
该问题中clickable为false，只能用clickCenter，但这样会点到《用户协议》，目前无解。
![PixPin_2024-01-06_15-59-57](https://github.com/gkd-kit/gkd/assets/36655494/7fe6ef51-0f01-4f36-b736-e877536b1895)

**Comment by lisonge** [comment]
你可以使用 autojs
