### ISSUE TITLE
小米14Pro中VIPER Hifi APP界面会乱跳

### ISSUE THREAD

**Issue by HaojunRen** [gkd-kit/gkd#462]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

没有日志文件，直接可以从界面感受到

### Bug 描述

点VIPER Hifi -> 我的，进入到该页面后，会乱跳到“下载管理”页面，原因是“下载管理”的按钮会被自动点击一下。请帮忙解决，谢谢!

**Comment by lisonge** [comment]
点击记录-在此页面禁用此规则
