### ISSUE TITLE
一加软件商店误触问题

### ISSUE THREAD

**Issue by Fantasy0516** [gkd-kit/gkd#467]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13855452/file.zip

### Bug 描述

ver 1.64   规则v183
打开一加软件商店后，会自动点击首页排在第一位的软件页面
![选定的照片 (1)](https://github.com/gkd-kit/gkd/assets/7041977/9218f7eb-98da-4429-b5d5-b70b3deae4bd)
![选定的照片 (2)](https://github.com/gkd-kit/gkd/assets/7041977/a0d5243a-c0cd-43a6-962d-9b5e1c801a13)
![选定的照片 (3)](https://github.com/gkd-kit/gkd/assets/7041977/5191f5c2-d9ba-4448-a068-0d673382f793)

**Comment by lisonge** [comment]
点击记录禁用

**Comment by Fantasy0516** [comment]
> 点击记录禁用

禁用之后是不是开屏广告也不起作用了  也就是说对软件商店不起作用了

**Comment by lisonge** [comment]
禁用单个页面

**Comment by Fantasy0516** [comment]
> 禁用单个页面

那我整错了。。。。怎么把之前禁用的规则再给加回来啊

**Comment by Fantasy0516** [comment]
> 进入规则-点击此项规则-编辑禁用-把你刚刚禁用的appId的那行去掉

可以了 感谢解答！！
