### ISSUE TITLE
gkd能否支持复杂一点的规则？

### ISSUE THREAD

**Issue by squkw** [gkd-kit/gkd#468]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

比如想点击的是
`
LinearLayout + LinearLayout > @ImageView
`
如果只是这样的写法，或许会有很多误触，但是后面的
`LinearLayout > @ImageView`
这一段，没有什么参数可以定位。
然后发现实际上在第一个LinearLayout,，假定为LinearLayout1，的子元素有个TextView[text=`恭喜你`]之类的
那么，我想写的就是
`
 (LinearLayout1 > TextView[text=`恭喜你`]) && (LinearLayout1 + LinearLayout > @ImageView)
`

**Comment by lisonge** [comment]
你可以自行 fork 更改，或者直接使用 autojs 这类软件
