### ISSUE TITLE
开屏广告有时跳过慢

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#469]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13876320/file.zip

### Bug 描述

有时候开屏广告会跳过缓慢，可能会在广告出现一秒后才跳过。某些摇晃广告会在跳过之前跳转

**Comment by lisonge** [comment]
机型问题，无法解决
