### ISSUE TITLE
规则恢复默认

### ISSUE THREAD

**Issue by msola-ht** [gkd-kit/gkd#470]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13881585/file.zip

### Bug 描述

偶尔发现规则会恢复默认设置，强制关闭后启动才会恢复

**Comment by lisonge** [comment]
无法复现
