### ISSUE TITLE
添加不带联网功能的支线构建

### ISSUE THREAD

**Issue by mike-brown8** [gkd-kit/gkd#474]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

### 新功能描述

目前版本的gkd被某些平台报银行软件病毒，这让我很不放心，希望能在主构建之外添加一个不带联网功能的支线构建。

**Comment by lisonge** [comment]
不支持

**Comment by lisonge** [comment]
你可以自行 fork 构建
