### ISSUE TITLE
所有无需二次确认的规则全部默认开启

### ISSUE THREAD

**Issue by DrDzy01** [gkd-kit/gkd#478]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

使用一段时间后，我认为其实除了需要二次确人的广告会在关闭时影响使用体验外，其它只需要一次点击即可关闭的广告（弹窗）完全可以默认开启规则，这样既能实现最清爽的效果也完全不影响使用体验。

**Comment by lisonge** [comment]
不支持

https://github.com/gkd-kit/gkd/issues/255#issuecomment-1797474482
