### ISSUE TITLE
开屏广告规则误触发桌面的音乐播放器组件

### ISSUE THREAD

**Issue by quantumfallout** [gkd-kit/gkd#479]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13905720/file.zip

### Bug 描述

在回到主页的动画中，会误触发位于桌面的音乐播放器

https://github.com/gkd-kit/gkd/assets/16105768/463010f2-466e-40c3-88e3-9ae008b78ec4

**Comment by lisonge** [comment]
点击记录-禁用

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/465

**Comment by lisonge** [comment]
请问使用此版本后 https://github.com/gkd-kit/gkd/actions/runs/7475623801/artifacts/1159554429 是否仍然存在此问题？

**Comment by quantumfallout** [comment]
已经禁用过了效果不佳，从点击记录来看他识别为是上一个应用的广告。
![Screenshot_20240112-003934_GKD](https://github.com/gkd-kit/gkd/assets/16105768/0671b398-c161-492b-811d-599995460f46)

**Comment by quantumfallout** [comment]
> 请问使用此版本后 https://github.com/gkd-kit/gkd/actions/runs/7475623801/artifacts/1159554429 是否仍然存在此问题？

我试试

**Comment by quantumfallout** [comment]
> 请问使用此版本后 https://github.com/gkd-kit/gkd/actions/runs/7475623801/artifacts/1159554429 是否仍然存在此问题？

试用过后问题确实缓解了
