### ISSUE TITLE
[feat]通用规则

### ISSUE THREAD

**Issue by 1392726643** [gkd-kit/gkd#48]
如题

**Comment by drw2005** [comment]
确实，弄个通用规则，subscription那边会减少很多适配请求。

**Comment by jiuqianyuan** [comment]
建议列为优先项

**Comment by haohennia** [comment]
确实，我不懂编程。。看添加规则是完全看不懂，想要自己弄规则不实际

**Comment by poprains** [comment]
你看下文档,他是有一套方法的,电脑上开浏览器安装油猴脚本,gkd app打开http服务,就可以通过电脑抓取app快照自己适配规则,不过手册写的太繁琐,不容易明白.我也是折腾了一天摸透了,我都是自己给自己适配规则

**Comment by kiss2u** [comment]
> 你看下文档,他是有一套方法的,电脑上开浏览器安装油猴脚本,gkd app打开http服务,就可以通过电脑抓取app快照自己适配规则,不过手册写的太繁琐,不容易明白.我也是折腾了一天摸透了,我都是自己给自己适配规则

手册里都要求按钮id，但是如果无按钮id，该如何适配规则？

**Comment by lisonge** [comment]
@kiss2u 

> 手册里都要求按钮id，但是如果无按钮id，该如何适配规则？

我没有写过手册，也没有要求按钮id，我目前只写过 [CONTRIBUTING.md](https://github.com/gkd-kit/subscription/blob/main/CONTRIBUTING.md)

你可以参考默认订阅的规则，比如 [com.baidu.tieba.ts](https://github.com/gkd-kit/subscription/blob/main/src/apps/com.baidu.tieba.ts)
