### ISSUE TITLE
刷抖音的时候跳过软件占用直接拉满

### ISSUE THREAD

**Issue by jiangfeiyang0228** [gkd-kit/gkd#480]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13910887/file.zip

### Bug 描述

![Screenshot_2024-01-12-10-32-26-842_com ss android ugc aweme](https://github.com/gkd-kit/gkd/assets/68383449/c3c2954c-29d2-4926-9401-8d1329295a86)
![Screenshot_2024-01-12-10-36-39-195_com ss android ugc aweme](https://github.com/gkd-kit/gkd/assets/68383449/b1c70cef-9ad1-4a48-bfcf-82deb15cb021)
![Screenshot_2024-01-12-10-39-59-346_com miui securitycenter](https://github.com/gkd-kit/gkd/assets/68383449/4b4f8d67-89d8-4e53-bf96-27d98811f19a)

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/gkd/assets/38517192/bb83e8b2-4f44-4f1c-9068-0fbd91776cc6)


把你开启的规则全部关闭

**Comment by jiangfeiyang0228** [comment]
全部关闭是正常了， 但是只要开启哪怕只开了一个规则，它的占用就不对

**Comment by lisonge** [comment]
那你别开就行了

**Comment by jiuban590** [comment]
什么软件看的占用
