### ISSUE TITLE
在VIVO自带应用商店里面会乱跳（自己点击打开应用详情下载界面）

### ISSUE THREAD

**Issue by shuirou520** [gkd-kit/gkd#482]
### 一些验证

- [x] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [ ] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [x] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13927235/file.zip

### Bug 描述

在VIVO自带应用商店里面会乱跳（自己点击打开应用详情下载界面）

**Comment by lisonge** [comment]
点击记录  禁用
