### ISSUE TITLE
建议：规则类别点进去后能够显示出具体规则

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#484]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

规则分类点进去后能够显示出具体规则，并且有规则开关按钮，像应用规则点进去那样，为了区别分类里的规则，可以在规则前面加上此规则所属软件的图标

**Comment by lisonge** [comment]
不支持
