### ISSUE TITLE
规则不起作用

### ISSUE THREAD

**Issue by damieai** [gkd-kit/gkd#489]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13985757/file.zip

### Bug 描述

广告换个图片就没用了
[能写出通用么，似乎换个图片就不起作用.zip](https://github.com/gkd-kit/gkd/files/13985710/default.zip)

**Comment by lisonge** [comment]
![img_v3_0278_f5321f5a-6c21-4d14-bba8-c141b840628g](https://github.com/gkd-kit/gkd/assets/38517192/711ced04-569d-40f3-a0bc-81d52858d765)

你好，我这边无法复现，我不知道怎么解决

**Comment by damieai** [comment]
如果方便的话，可以下载网易有道词典，这个弹窗就会弹出来

**Comment by lisonge** [comment]
你好，我上面已经给出了，我在网易有道词典规则在我的手机的触发记录，是正常触发的

**Comment by damieai** [comment]
我是小米手机 我刚刚清除了数据重进，它还是无法工作

**Comment by lisonge** [comment]
你好，我不知道
