### ISSUE TITLE
小米13 hyperos1.0.6.2 会失效

### ISSUE THREAD

**Issue by grantting** [gkd-kit/gkd#490]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13989320/file.zip

### Bug 描述

打开了自启动，无限制和后台启动还是无法保活后台，一退到后台就无法跳过必须重新启动软件授予无障碍权限

**Comment by lisonge** [comment]
你好，无法复现，我不知道怎么解决

如果实在不能使用，建议卸载
