### ISSUE TITLE
最新测试版无法正确读取已安装应用列表

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#491]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13996185/file.zip

### Bug 描述

![Screenshot_20240120_094826](https://github.com/gkd-kit/gkd/assets/98690669/781895e0-fcf6-4c2e-9d6d-b0fa9b493faa)
![Screenshot_20240120_094851](https://github.com/gkd-kit/gkd/assets/98690669/98baae3a-8bbf-4095-932e-7004171be6fd)
![Screenshot_20240120_095144](https://github.com/gkd-kit/gkd/assets/98690669/c40281a4-4b88-454f-9d66-3d478be82b79)

**Comment by lisonge** [comment]
你好，使用这个版本试试 <https://github.com/gkd-kit/gkd/actions/runs/7592538329>

**Comment by jiuban590** [comment]
> 你好，使用这个版本试试 https://github.com/gkd-kit/gkd/actions/runs/7592538329

这个版本没有问题了。👍🏻
