### ISSUE TITLE
最新测试版没有点击提示

### ISSUE THREAD

**Issue by MengNianxiaoyao** [gkd-kit/gkd#493]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/13998042/file.zip

### Bug 描述

点击提示是开启的，但gdk操作点击没有提示弹出

**Comment by lisonge** [comment]
无法复现，我不知道怎么解决

**Comment by MengNianxiaoyao** [comment]
已经解决，发现是通知权限被关闭导致
