### ISSUE TITLE
加入更多执行动作

### ISSUE THREAD

**Issue by jiemo9527** [gkd-kit/gkd#495]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

除了点击以外；希望加入文本输入，文本清除，滑动屏幕，开关网络，唤醒屏幕等执行动作，提高实际应用的便利性
此外，元素匹配除了action广播以外，是否考虑加入其他广播（如：系统的、设置的）

**Comment by lisonge** [comment]
不支持，你可以使用其它软件实现
