### ISSUE TITLE
AH视频，一直点击主页

### ISSUE THREAD

**Issue by letuplus** [gkd-kit/gkd#496]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/14001755/file.zip

### Bug 描述

AH视频，进去主页后，一直在点击主页，无法去其他页面。

**Comment by lisonge** [comment]
点击记录，禁用
