### ISSUE TITLE
功能优化：设置中点击HTTP服务的IP地址可直接复制

### ISSUE THREAD

**Issue by emutony** [gkd-kit/gkd#497]
我习惯在手机上用KIWI浏览器打开[(https://i.gkd.li/device)]写规则，但是左上角的IP地址经常会变，每次都要手动输入。
希望能在GKD设置中的HTTP服务处，点击IP地址（下图黄框处）可以直接复制。
![PixPin_2024-01-22_11-16-13](https://github.com/gkd-kit/gkd/assets/36655494/2d0064d1-464a-4c30-9570-b1bceb18a627)

**Comment by lisonge** [comment]
> 在手机上用

把你的 ip 地址改成 127.0.0.1 ，这样油猴脚本都不用安装

**Comment by yjt123789** [comment]
这个联网吗？
