### ISSUE TITLE
希望开发屏蔽VX订阅号文章列表（订阅号消息）的广告，VX的广告已经无处不在无孔不入！

### ISSUE THREAD

**Issue by huangjianye** [gkd-kit/gkd#499]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

![image](https://github.com/gkd-kit/gkd/assets/49425015/93d086e8-eec6-49ff-9b25-35bf46996407)

**Comment by lisonge** [comment]
不按规范，直接关闭
