### ISSUE TITLE
荣耀升级7.0.0.236版本后规则失效

### ISSUE THREAD

**Issue by obimg** [gkd-kit/gkd#502]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

[util_2024_01_25_li.songe.gkd.txt](https://github.com/gkd-kit/gkd/files/14045606/util_2024_01_25_li.songe.gkd.txt)

### Bug 描述

荣耀MagicOS系统自动更新至7.0.0.236版本后，原本运行正常的规则都失效了。

**Comment by lisonge** [comment]
无法复现

而且你也没说是哪个规则在哪个界面失效

**Comment by obimg** [comment]
我不是开发者，所以不太懂如何描述bug。目前问题是升级系统后，原本的”跳过开屏“全局规则都无法正常生效，重启后可能会生效一两次，之后依然是失效状态。

**Comment by lisonge** [comment]
不知道怎么解决，建议换个手机或者卸载gkd吧

**Comment by obimg** [comment]
MagicOS又更新了补丁，更新后没问题了，应该是系统的问题
