### ISSUE TITLE
开启gkd服务后导致netflix的播放进度条不自动消失

### ISSUE THREAD

**Issue by lihaobaba** [gkd-kit/gkd#505]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

[log.zip](https://github.com/gkd-kit/gkd/files/14073211/log.zip)

### Bug 描述

开启gkd服务后导致netflix的播放进度条不自动消失。
手动点击空白地方，精度条也没有反应。

**Comment by lisonge** [comment]
卸载gkd

**Comment by lisonge** [comment]
如果你用的是 YouTube ，可以在 我-设置-无障碍功能 控制类似的行为

但是我不知道 Netflix 有没有类似的功能
