### ISSUE TITLE
微信视频号评论区广告

### ISSUE THREAD

**Issue by RaynerLi** [gkd-kit/gkd#506]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

https://i.gkd.li/import/14074930
https://i.gkd.li/import/14074932
https://i.gkd.li/import/14074933

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/gkd/assets/38517192/6b5046bb-3453-43fc-b8d2-17128a1b236c)

你好，请不要再发不规范的 issue，否则将 block 你的账号
