### ISSUE TITLE
最新版ci更新规则会导致闪退

### ISSUE THREAD

**Issue by MengNianxiaoyao** [gkd-kit/gkd#508]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/14079456/file.zip

### Bug 描述

在订阅规则界面下拉更新，软件会直接闪退

**Comment by lisonge** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/4157

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/commit/51f4e8ae133e7e03d633ed06b1ab0ef1da4d8f5e
