### ISSUE TITLE
[feat]添加“拦截统计”功能，让拦截更有趣

### ISSUE THREAD

**Issue by AllenPu2020** [gkd-kit/gkd#509]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

效果如下：
<img width="757" alt="image" src="https://github.com/gkd-kit/gkd/assets/32997662/29318767-269d-4f9d-af23-80f886b3dfca">
圆环从“12 点”位置，逆时针旋转，数量“从大到小”排列，下方的“图例”也是这个顺序。图例可以竖着排布更加美观。
当 item 超过一定数量（如 10 个）剩下的可以归纳为“其余”
筛选时间的范围：默认“最近一周”，可以切换成“最近 24h”/ “最近30 天” / “最近一年” / “自定义时间范围”等等筛选。

子项目显示：如点击“蓝色的 88 这个弧形”就会进入“知乎”这个类别统计，这里“时间尺度”和上一级一致。分别统计“开屏广告”/“广告弹窗”/“分段广告”/“首页广告”/“推荐”等等类别的统计。这个页面有个“返回”按钮，可以返回上一级，此时仍然需要保持“时间尺度”的筛选项，除非手动更改。

**Comment by lisonge** [comment]
不支持
