### ISSUE TITLE
增加一个字段限制节点被遮罩时是否触发点击

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#511]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

目前有少量广告会在节点被遮罩时触发点击造成误触：
网易云音乐评论区广告：https://i.gkd.li/import/14070500
选择器：[id="com.netease.cloudmusic:id/adTagView"]
奇妙应用：https://i.gkd.li/import/14095316
选择器：FrameLayout[childCount=5] > FrameLayout[childCount=1] > ImageView[visibleToUser=true]

**Comment by lisonge** [comment]
android 并没有提供 z 轴层级的获取接口，无法判断
