### ISSUE TITLE
远程订阅的*.version.json更新，而GKD下拉刷新显示暂无更新

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/gkd#513]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/14119980/file.zip

### Bug 描述

远程订阅的*.version.json如下图：
<img width="1247" alt="{FBF4013C-6676-4b66-9408-63603D75DA1E}" src="https://github.com/gkd-kit/gkd/assets/101449500/b305d5c6-af2e-4ad5-bd69-a9aa22a99eb4">

**Comment by adproqwq** [comment]
> 这不是我的订阅，我不知道

想问下GKD的检测更新方式是怎样的？

**Comment by lisonge** [comment]
<https://github.com/gkd-kit/subscription/blob/486411de82c5c0771d8085b6fdd9fa8ffe253616/src/types.ts#L409-L428>

**Comment by adproqwq** [comment]
> https://github.com/gkd-kit/subscription/blob/486411de82c5c0771d8085b6fdd9fa8ffe253616/src/types.ts#L409-L428

那GKD请求的返回结果为什么与浏览器请求的返回结果不同？

**Comment by lisonge** [comment]
我不知道

**Comment by adproqwq** [comment]
巧了，我也不知道

**Comment by adproqwq** [comment]
还是感谢你的解答。

**Comment by lisonge** [comment]
<https://github.com/gkd-kit/gkd/blob/0c1a13c3922ca583ea55b2d76dbe436f90b10d68/app/src/main/kotlin/li/songe/gkd/util/Singleton.kt#L43-L52>

我已经在此处禁用缓存了，但是不知道为什么这个 gkd 缓存刷新时间还是不及时

**Comment by adproqwq** [comment]
> https://github.com/gkd-kit/gkd/blob/0c1a13c3922ca583ea55b2d76dbe436f90b10d68/app/src/main/kotlin/li/songe/gkd/util/Singleton.kt#L43-L52
> 
> 我已经在此处禁用缓存了，但是不知道为什么这个 gkd 缓存刷新时间还是不及时

那这个问题挺玄学的

**Comment by lisonge** [comment]
看起来和 jsdelivr 的缓存策略有点关系，你可以考虑换一个链接

**Comment by adproqwq** [comment]
> 看起来和 jsdelivr 的缓存策略有点关系，你可以考虑换一个链接

我试一下，感谢建议

**Comment by aoguai** [comment]
jsdelivr 缓存的问题，关于 jsdelive 的缓存机制，jsdelivr 官网是这么叙述的：

> We use a permanent S3 storage to ensure all files remain available even if GitHub goes down, or a repository or a release is deleted by its author. Files are fetched directly from GitHub only the first time, or when S3 goes down.

## 解决办法：

1. 每改动一次代码，就 releases 一次，用更换版本号的形式来解决：
```
cdn.jsdelivr.net/gh/XXX/XXX@X.X.X/dist/XXX
```

2. 每次手动`purge.jsdelivr.net/gh/XXX/XXX@X.X.X/dist/XXX`访问清理 jsdelivr 缓存。
    但是不稳定，时好时不好。
3. 换其他的加速源

**Comment by adproqwq** [comment]
> 2. 每次手动`purge.jsdelivr.net/gh/XXX/XXX@X.X.X/dist/XXX`访问清理 jsdelivr 缓存。
>    但是不稳定，时好时不好。
这我深有体会，purge刷新不及时。
> 3. 换其他的加速源
我已经换用gitmirror，是对github raw的镜像，刷新速度在一分钟以内
