### ISSUE TITLE
GKD后台时间久后，部分APP的触发会失效

### ISSUE THREAD

**Issue by jim4ever** [gkd-kit/gkd#514]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/14121973/file.zip

### Bug 描述

GKD后台时间久后，部分APP的触发会失效，比如腾讯新闻的信息流广告，手动开启GKD后，再开启腾讯新闻，会触发关闭信息流广告。GKD放置后台，一段时间后，开启腾讯新闻，不会关闭信息流广告，此时重复开启GKD操作，再开启腾讯新闻，关闭正常。目前仅发现腾讯新闻有此问题。
GKD的电池优化已关闭。后台已锁，自启动均开启。手机系统为小米的hyperOS，华为鸿蒙4.0同样出现过。

**Comment by egmkang** [comment]
荣耀也有这个问题, 点一下通知栏重新打开应用, 速度又会快起来

**Comment by Neil-2322** [comment]
俺也一样…vivo x90 Origin os 4

**Comment by Dystnine** [comment]
一样，小米，miui10

**Comment by lisonge** [comment]
可以试试最新版本 https://github.com/gkd-kit/gkd/releases 是否仍然存在此问题

**Comment by PLiGang** [comment]
一样 荣耀 magicOs 8  版本1.6.4

**Comment by lisonge** [comment]
若一周内再无反馈将直接关闭此问题
