### ISSUE TITLE
添加订阅的按钮没了

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#518]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/14164586/file.zip

### Bug 描述

版本1.6.4-0c1c617
如图 添加订阅的按钮没了。我不知道是新设计还是bug
![Screenshot_20240205_185328](https://github.com/gkd-kit/gkd/assets/98690669/1acd3f6c-1e33-45f5-9c17-51373c90e98d)

**Comment by lisonge** [comment]
都没做好，你着什么急？

**Comment by lisonge** [comment]
感谢反馈，已修复

https://github.com/gkd-kit/gkd/commit/b753054ef1216d4ec351c502c16aa47d2a1bd56e
