### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by Dystnine** [gkd-kit/gkd#519]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [ ] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/14235191/file.zip

### Bug 描述

1.使用自带规则在浏览器浏览网页时候会一直点按跳过两个字如视频1
2.点开软件里面的选项不能开关，如视频2

https://github.com/gkd-kit/gkd/assets/123282693/30bc33b3-7b4f-47bd-a5f5-9d421a2eec86
https://github.com/gkd-kit/gkd/assets/123282693/f1d39a17-6a2d-4c51-bbb0-362039315649

**Comment by lisonge** [comment]
> 使用自带规则在浏览器浏览网页时候会一直点按跳过两个字

点击记录禁用应用

---

> 点开软件里面的选项不能开关

看起来是数据库引擎崩溃了，结束应用重启可以解决，这个问题我从来没有复现过不知道怎么解决
