### ISSUE TITLE
705d931开始会导致某些规则失效

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#521]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/14256520/file.zip

### Bug 描述

大多数是activityids变化后延迟出现的广告。比如日志中的自动安装。如果是规则没适配新版本问题你可以直接关闭此issue。

**Comment by lisonge** [comment]
请问其它的失效的规则还有哪些，你说的这个自动安装我的手机上没有安装这个应用导致不能复现

**Comment by jiuban590** [comment]
> 请问其它的失效的规则还有哪些，你说的这个自动安装我的手机上没有安装这个应用导致不能复现

暂时想不起来别的，我继续留意一下。这个自动安装的就是系统带的安装软件的那个，安装小点的软件第二步能正常点击，稍微大点的软件就不行了。具体为：点击继续安装后，界面跳转 显示正在安装（此界面activityid和第二步需要点击完成的activityid一致）安装过程快的话第二步就能正常点击，如果这个过程慢了第二步就不行，需要切屏才能触发。

**Comment by jiuban590** [comment]
昨日发现一个：抖音的休息提醒弹出来不会触发，需要切屏才能。
