### ISSUE TITLE
提交5e58901 订阅页面订阅滑动排序过于灵敏

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/gkd#523]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

https://github.com/gkd-kit/inspect/files/14280998/file.zip

### Bug 描述

如题，滑动排序过于灵敏，导致下滑刷新时，总是使订阅重新排序，而不是检查更新订阅，无法达成预期行为。
如需录屏视频请说明

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/commit/2eb76cd1cdef2694c80d5c96659b0459627c70c4
