### ISSUE TITLE
[BUG]各个界面上的选项经常性卡顿，无法打开或者关闭

### ISSUE THREAD

**Issue by lxr760** [gkd-kit/gkd#525]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

[BUG]各个界面上的选项经常性卡顿，无法打开或者关闭

### Bug 描述

[BUG]各个界面上的选项经常性卡顿，无法打开或者关闭

此时必须到设置里把无障碍关闭，这时候设置的开关或者订阅里的app选项才能选择

**Comment by lisonge** [comment]
无法复现

**Comment by lxr760** [comment]
> 没有日志
> 
> > 我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
> 
> > 各个界面上的选项经常性卡顿，无法打开或者关闭
> 
> 无法复现


日志来了，还请帮忙分析分析是什么造成的界面卡死

特意把手机后台清空然后重启设置，重启以后进GKD，此时主页和设置里的开关都能正常打开或关闭。但是订阅里的按钮都无法点击，包括选择某个订阅或者取消，进入订阅选择某个app，app里具体的广告设置，这几个地方按钮点了都卡顿

https://github.com/gkd-kit/inspect/files/14317998/file.zip
