### ISSUE TITLE
请问如何新增本地规则, 规则规范是什么的?我想自定义一些规则,去除广告

### ISSUE THREAD

**Issue by Ym-wei** [gkd-kit/gkd#529]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

请问如何新增本地规则, 规则规范是什么的?我想自定义一些规则,去除广告
![微信图片_20240223103253](https://github.com/gkd-kit/gkd/assets/81805625/b2c05ec6-7134-455a-8c0f-cf8e2220f20b)

**Comment by lisonge** [comment]
本地订阅
