### ISSUE TITLE
本地订阅会莫名其妙的丢失

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#532]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14429057/file.zip

### BUG描述及其复现步骤(视频/截图)

4c1eb30开始 本地订阅会莫名其妙丢失（具体是开自启然后后台划掉在打开就没了）

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/commit/99f6684ce44d814b41c460f5c043a99ee758d648
