### ISSUE TITLE
多订阅相同规则有几率同时触发导致误触

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#535]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14448190/file.zip

### BUG描述及其复现步骤(视频/截图)

![Screenshot_2024_0229_205555](https://github.com/gkd-kit/gkd/assets/98690669/fc5a9f95-2d9a-42cb-9d40-9f9aeedaaafa)
例如这个

**Comment by lisonge** [comment]
呃呃这不是很正常吗？哪里有问题？

**Comment by jiuban590** [comment]
> 呃呃这不是很正常吗？哪里有问题？

第一次会把弹窗关闭然后第二次就会点到弹窗下面的地方

**Comment by lisonge** [comment]
弹窗被点击后的短时间内仍然被其它规则查询到

所以其它规则去触发点击，但是此时弹窗位置已经偏移/消失导致误触

**Comment by jiuban590** [comment]
> 呃呃这不是很正常吗？哪里有问题？

看了下 好像跟aoguai提的issues差不多情况。
两条一样的规则第一个规则正确的把弹窗关闭（正确选择），但第二次的规则还在执行导致第二次规则会点到别的地方。
