### ISSUE TITLE
resetMatch: activity相关问题

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#537]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14468938/file.zip
https://github.com/gkd-kit/inspect/files/14468984/file.zip

### BUG描述及其复现步骤(视频/截图)

activityId变化是否属于此参数。加了actionMaximum 如果activityid变化会不会唤醒规则。如果此参数仅为activity刷新您可以直接关闭此issues。如果不是我这种是否属于bug：规则执行后因actionMaximum失眠，然后切换别的activityid在切换回执行规则的activityid不会唤醒规则，必须切换app或者刷新activity才能重新唤醒。
此规则在加了actionMaximum后，如果进入com.mihoyo.hyperion.web2.MiHoYoWebActivity不管执行没执行切换到别的activityid在切换回该执行的com.mihoyo.hyperion.web2.MiHoYoWebActivity也不会唤醒规则。如日志。

```json5
{
  id: 'com.mihoyo.hyperion',
  name: '米游社',
  groups: [
    {
      name: '星铁每日签到',
      key: 0,
      desc: '星铁每日签到',
      rules: [
        {
          key: 0,
          matches: [
            '[text="签到提醒"] <<n WebView[text="《崩坏：星穹铁道》签到福利"] >n View + TextView[text*="第"]'
          ],
          actionMaximum: 1,
          snapshotUrls: [
            'https://i.gkd.li/i/14384152'
          ],
          exampleUrls: [
            'https://m.gkd.li/98690669/367f596c-2888-4f17-bb2a-79ab3d8c744e'
          ],
          activityIds: [
            'com.mihoyo.hyperion.web2.MiHoYoWebActivity'
          ]
        },
        {
          key: 2,
          matches: [
            '[text="恭喜你，今日签到成功！"] <<n View + TextView'
          ],
          snapshotUrls: [
            'https://i.gkd.li/i/14385445'
          ],
          exampleUrls: [
            'https://m.gkd.li/98690669/25b8f553-1b4a-4ef6-b847-a80ae35681b9'
          ],
          activityIds: [
            'com.mihoyo.hyperion.web2.MiHoYoWebActivity'
          ]
        }
      ]
    }
  ]
}
```

**Comment by lisonge** [comment]
从你的日志来看，你只触发了一次，并且我也没有在任意界面看到 `达到最大执行次数` 的日志输出

我不知道怎么回事

**Comment by jiuban590** [comment]
> 我的猜测是选择器没有选上，你可以使用网页审查工具实时执行选择器看看

好的

**Comment by jiuban590** [comment]
> 我的猜测是选择器没有选上，你可以使用网页审查工具实时执行选择器看看

用实时选择器测试了一下可以正常选择。感觉就是识别不到页面变化，不过不影响使用也可能是此应用的问题。

**Comment by lisonge** [comment]
你可以使用 matchDelay 来让规则延迟一段时间后强制执行

**Comment by jiuban590** [comment]
> 你可以使用 matchDelay 来让规则延迟一段时间后强制执行

感谢！，有用。
