### ISSUE TITLE
跳过时报错，提示“Cannot perform this operationbecause the connection pool has been closed”

### ISSUE THREAD

**Issue by Matrix-bak** [gkd-kit/gkd#540]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

[util_2024_03_05_li.songe.gkd.txt](https://github.com/gkd-kit/gkd/files/14490795/util_2024_03_05_li.songe.gkd.txt)

### BUG描述及其复现步骤(视频/截图)

![Screenshot_20240305_125332](https://github.com/gkd-kit/gkd/assets/65644040/8d9befd3-593c-498e-ad77-b88fbd40f73a)

**Comment by Matrix-bak** [comment]
已上传有效日志

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/533
