### ISSUE TITLE
编译出错 不太懂 android,为什么这样。。

### ISSUE THREAD

**Issue by duHtiGGitHub** [gkd-kit/gkd#541]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

![图片](https://github.com/gkd-kit/gkd/assets/18080868/536fb519-21ef-47e7-b5f7-27e7bb83738d)

### BUG描述及其复现步骤(视频/截图)

![图片](https://github.com/gkd-kit/gkd/assets/18080868/c52f24dd-e70a-4041-8c16-fe74dd94b33f)

**Comment by lisonge** [comment]
你好，我不知道
