### ISSUE TITLE
您好, 开屏广告, 识别不到广告

### ISSUE THREAD

**Issue by Ym-wei** [gkd-kit/gkd#542]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

![image](https://github.com/gkd-kit/gkd/assets/81805625/c1224bc6-4c3d-48d1-ac01-8a81b8e2cccc)

### BUG描述及其复现步骤(视频/截图)

![image](https://github.com/gkd-kit/gkd/assets/81805625/9302782b-b114-4d70-91cb-10ef027fc2d8)
![image](https://github.com/gkd-kit/gkd/assets/81805625/60fb57d6-12e2-4c2c-a12d-88e609a9ed7f)

快照地址
https://i.gkd.li/snapshot/1709266329374

**Comment by lisonge** [comment]
你好，我不知道怎么解决

**Comment by lisonge** [comment]
你可以看文档里的字段解决

**Comment by Ym-wei** [comment]
> 我看这个快照是识别不到广告的按钮组件, 这样是解决不了吗?

**Comment by lisonge** [comment]
<https://gkd.li/api/interfaces/RawAppRule.html#position>

需要 1.7.0 ，但是还没发布

**Comment by Ym-wei** [comment]
> https://gkd.li/api/interfaces/RawAppRule.html#position
> 
> 需要 1.7.0 ，但是还没发布

position可以用, 谢谢,
