### ISSUE TITLE
应用列表无法正常获取

### ISSUE THREAD

**Issue by Dusk0531** [gkd-kit/gkd#543]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14541279/file.zip

### BUG描述及其复现步骤(视频/截图)

无法获取gkd更新之前的应用列表 需要在gkd安装后安装应用才可正常显示在列表内
系统权限并未发现读取应用列表权限
安装某个应用 某个应用才会显示在列表内
![Screenshot_2024-03-09-01-24-45-55_befd3b55c4270226022f86e9f9cafb33](https://github.com/gkd-kit/gkd/assets/130734435/b4dd9c33-1261-4c15-9d98-9db8efaaeace)

**Comment by lisonge** [comment]
结束应用后重启呢？

**Comment by Dusk0531** [comment]
> 结束应用后重启呢？

谢谢 已恢复正常使用

**Comment by lisonge** [comment]
我之前也偶然复现过这个问题，我查查是怎么回事吧

**Comment by Dusk0531** [comment]
> 我之前也偶然复现过这个问题，我查查是怎么回事吧

我目前正常了 强行停止第一次会弹出应用列表授权 第二次强行停止也会空 第三次正常了

**Comment by ypxun** [comment]
奇怪，我这一开始也是读不到应用，读取应用列表的权限已给。重启几次应用都不行后，我又重新授权了下无障碍和shizuku，这下读到了。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
