### ISSUE TITLE
从软件返回到桌面，再次进入软件会强制回到主页，此时按返回会回到上一次退出的页面

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#544]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14541475/file.zip

### BUG描述及其复现步骤(视频/截图)

如果设定是按两次退出软件的话应该第一次返回时出现toast提示`

https://github.com/gkd-kit/gkd/assets/57941037/b937b5b7-f78c-473b-a71d-8a6b9cc780c3

`

**Comment by AIsouler** [comment]
https://github.com/gkd-kit/inspect/files/14541549/file.zip

https://github.com/gkd-kit/gkd/assets/57941037/1068ec4e-389a-48c1-9c93-c259ed6ca5a7

**Comment by lisonge** [comment]
我不能复现，你重启应用后是否还会出现这个问题？

**Comment by AIsouler** [comment]
> 我不能复现，你重启应用后是否还会出现这个问题？

重启应用后正常了

**Comment by lisonge** [comment]
我猜测是升级应用时我没有变更 versionCode 仅仅变更 versionName 导致的

这可能会让系统不会完全销毁进程，导致进程里面的数据错乱

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases

**Comment by lisonge** [comment]
请问还能复现问题吗？ 感觉是系统问题，无法复现修复不了，我要关闭了
