### ISSUE TITLE
从应用页面进入软件规则，点击规则开启或关闭会回到顶部，从订阅页面进入软件规则则不会出现这个问题

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#545]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14541768/file.zip

### BUG描述及其复现步骤(视频/截图)

https://github.com/gkd-kit/gkd/assets/57941037/e0a22afa-f86f-4a65-88a6-baf9edd64bbf

**Comment by AIsouler** [comment]
还有一个问题，虽然软件图标更换了但是通知栏图标和toast提示图标并没有更换

**Comment by AIsouler** [comment]
> 还有一个问题，虽然软件图标更换了但是通知栏图标和toast提示图标并没有更换

这个问题我重启手机后正常了

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
