### ISSUE TITLE
应用页面随机出现应用大图标，以及部分应用图标错误

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/gkd#546]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14542515/file.zip

### BUG描述及其复现步骤(视频/截图)

随机出现的应用大图标：
![Screenshot_2024-03-09-03-39-47-99_befd3b55c4270226022f86e9f9cafb33](https://github.com/gkd-kit/gkd/assets/101449500/35fc74a3-4993-4f80-b08b-11dd3f96c5ee)
---
错误的应用图标：
![Screenshot_2024-03-09-03-39-56-02_befd3b55c4270226022f86e9f9cafb33](https://github.com/gkd-kit/gkd/assets/101449500/19f486a9-180e-4dac-b368-4078ec83e5e1)
![Screenshot_2024-03-09-03-42-30-17_b783bf344239542886fee7b48fa4b892](https://github.com/gkd-kit/gkd/assets/101449500/68e9bf67-4599-44be-b1b2-8cf4700f5ca5)

**Comment by lisonge** [comment]
我不能复现，你尝试在设置页面结束应用后重启呢？

**Comment by adproqwq** [comment]
> 我不能复现，你尝试在设置页面结束应用后重启呢？

依然存在该问题

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases

使用最新版本试试呢

**Comment by adproqwq** [comment]
> https://github.com/gkd-kit/gkd/releases
> 
> 使用最新版本试试呢

依然存在

**Comment by lisonge** [comment]
你的系统是不是有自定义图标？，你暂时将图标重置到默认主题后是否还会出现？

**Comment by lisonge** [comment]
[release.zip](https://github.com/gkd-kit/gkd/files/14545070/release.zip)

试试这个呢，安装后结束应用后重启试试

**Comment by adproqwq** [comment]
> [release.zip](https://github.com/gkd-kit/gkd/files/14545070/release.zip)
> 
> 试试这个呢，安装后结束应用后重启试试

没有问题了

**Comment by lisonge** [comment]
请问是大小正常了是吗？但是图标仍然是获取错误

**Comment by adproqwq** [comment]
> 请问是大小正常了是吗？但是图标仍然是获取错误

对

**Comment by lisonge** [comment]
如果你在冰箱、酷安这类能获取应用列表并展示图标的应用看这些图标也是错误的吗

**Comment by adproqwq** [comment]
> 如果你在冰箱、酷安这类能获取应用列表并展示图标的应用看这些图标也是错误的吗

在酷安是正常的

**Comment by lisonge** [comment]
我确实不知道什么原因，因为这个获取应用信息API调用非常简单吗，并且没有任何图标相关的处理

你是否能重新安装显示异常的应用，或者卸载 GKD 后重新安装

**Comment by adproqwq** [comment]
> 你是否能重新安装显示异常的应用，或者卸载 GKD 后重新安装

重新安装应用可以解决问题。同时我在MT管理器发现了相同问题，这个问题不止出现在GKD中。

**Comment by lisonge** [comment]
算了就这样吧，我只能解决图标大小异常的问题，这个问题更多是你的设备的问题

**Comment by adproqwq** [comment]
> 算了就这样吧，我只能解决图标大小异常的问题，这个问题更多是你的设备的问题

好的
