### ISSUE TITLE
本地订阅编辑时会自动返回顶部

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#547]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14545211/file.zip

### BUG描述及其复现步骤(视频/截图)

![Screenshot_2024_0309_141044](https://github.com/gkd-kit/gkd/assets/98690669/f90b9f34-e09e-4c5d-a428-2c93ae43bd52)
如图，编辑本地订阅，往下滑，然后在点击就会回到顶部

**Comment by lisonge** [comment]
不好意思我看不清你的触摸位置

你可以打开 开发者设置-输入(小标题)-显示点按操作反馈 后重新发送示例

**Comment by jiuban590** [comment]
> 不好意思我看不清你的触摸位置
> 
> 你可以打开 开发者设置-输入(小标题)-显示点按操作反馈 后重新发送示例

视频太大了 放到云盘了。https://www.lanzoub.com/iZg171qsmibc

**Comment by lisonge** [comment]
说实话，我没看懂，你用期望表现/实际表现的语言描述吧

**Comment by jiuban590** [comment]
> 说实话，我没看懂，你用期望表现/实际表现的语言描述吧
> 
> 就是你进行了什么操作，然后GKD如何表现，你期望的表现是什么

我想编辑已有的本地订阅规则，但不是重头开始编辑，找到规则然后点击编辑，首先往下滑找到我想改的代码，然后点击编辑框 弹出输入法，此时编辑框里面的代码自动回到的顶部，但是输入光标还是在点击的位置。我期望是点击编辑位置然后弹出输入法并代码保持在我点击的位置而不是自动回到顶部。

**Comment by jiuban590** [comment]
感谢，已正常
