### ISSUE TITLE
规则编辑框长按按钮后文本显示异常

### ISSUE THREAD

**Issue by JPLiu** [gkd-kit/gkd#55]
规则编辑框，长按时，剪切粘贴等按钮文本显示异常。

测试机型：小米13 ＋ MIUI 14，具体如图。

![Screenshot_2023-09-22-14-43-17-659_li songe gkd](https://github.com/gkd-kit/gkd/assets/13379952/2a9a778f-0ca7-4f8e-bf43-3d2c9ef201b2)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
