### ISSUE TITLE
建议添加创建控件规则和坐标规则功能

### ISSUE THREAD

**Issue by ljqjy** [gkd-kit/gkd#550]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

您好，开屏广告五花八门，有开屏广告的APP实在太多，维护人员工作量很大。能否添加创建控件规则和坐标规则的功能从而方便小白用户达到跳过广告的目的。具体可看看https://www.youxiguancha.com/app/26574.html这个APP的功能。谢谢。

**Comment by lisonge** [comment]
> 维护人员工作量很大

不支持

**Comment by lisonge** [comment]
界面信息都保存着 gkd 的快照里面，它是可保存和传输的，别啥事都往我这问啊

你完全可以自己做一个手机版本页面快照解析页面来创建规则，期待你的开源作品

**Comment by ljqjy** [comment]
多谢回复。我能力有限，希望GKD越来越好。




蓝天
***@***.***







                       
原始邮件
                       
                     

发件人："二刺螈"< ***@***.*** &gt;;

发件时间：2024/3/9 16:54

收件人："gkd-kit/gkd"< ***@***.*** &gt;;

抄送人："ljqjy"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [gkd-kit/gkd] 建议添加创建控件规则和坐标规则功能 (Issue #550)




 
界面信息都保存在 gkd 的快照里面，它是可保存和传输的，别啥事都往我这问啊
 
你完全可以自己做一个手机版本页面快照解析页面来创建规则，期待你的开源作品

**Comment by hds1992012011** [comment]
巧了，我也打算提需求呢，结果发现你提过了，并且关闭了。。。
![image](https://github.com/gkd-kit/gkd/assets/33214567/59b18519-b4da-4210-a640-3a5e342c018f)

**Comment by ljqjy** [comment]
你也可以再提试试，当时提后，开发人员说暂不开发这样的功能。




蓝天
***@***.***







                       
原始邮件
                       
                     

发件人："hds1992012011"< ***@***.*** &gt;;

发件时间：2024/4/30 15:09

收件人："gkd-kit/gkd"< ***@***.*** &gt;;

抄送人："ljqjy"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [gkd-kit/gkd] 建议添加创建控件规则和坐标规则功能 (Issue #550)




 
巧了，我也打算提需求呢，结果发现你提过了，并且关闭了。。。
 image.png (view on web)
