### ISSUE TITLE
王者荣耀不跟手 

### ISSUE THREAD

**Issue by Dusk0531** [gkd-kit/gkd#554]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14562392/file.zip

### BUG描述(文字/截图/视频)

王者荣耀不跟手 滑动后反应缓慢 关闭GKD后恢复正常

### 期望行为(文字/截图/视频)

王者荣耀滑动跟手 并非手离开屏幕后还在响应刚才的操作

### 实际行为(文字/截图/视频)

王者荣耀滑动不跟手 手离开屏幕后还在响应刚才的操作

**Comment by lisonge** [comment]
卸载 gkd
