### ISSUE TITLE
1.7.0 beta版本不支持以前的订阅规则吗？

### ISSUE THREAD

**Issue by cycle2zhou** [gkd-kit/gkd#556]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

[log.zip](https://github.com/gkd-kit/gkd/files/14595847/log.zip)

### BUG描述(文字/截图/视频)

订阅规则全部没了

### 期望行为(文字/截图/视频)

能显示订阅规则

### 实际行为(文字/截图/视频)

未显示

**Comment by lisonge** [comment]
支持的

你可以接受应用后重启试试
