### ISSUE TITLE
后台隐藏功能失效

### ISSUE THREAD

**Issue by g1fts** [gkd-kit/gkd#56]
后台隐藏这个功能好像有异常，只有第一次安装设置的时候有用。后面都没用。

**Comment by lisonge** [comment]
请问你是怎么退出 GKD 的？是按 HOME/MENU 还是按 BACK ？

**Comment by lisonge** [comment]
你要按下 BACK 键才能后台隐藏，在我的红米k50u 上就是侧滑正常退出APP返回到桌面

不是从底部上滑悬停到最近任务界面(相当于按下MENU)，也不是从底部上滑直接回到桌面(相当于按下HOME)

**Comment by g1fts** [comment]
哦哦，我刚才试了一下。直接上滑返回桌面，任务是还在的。然后尝试了下在任务列表直接上滑结束GKD的任务，再进别的app还可以跳过。是我搞错了，不好意思。

**Comment by lisonge** [comment]
这个App其实也才开源不到3个星期，文档啥的都不全，后期会统一弄成文档供用户查询反馈的

**Comment by g1fts** [comment]
> 这个App其实也才开源不到3个星期，文档啥的都不全，后期会统一弄成文档供用户查询反馈的

加油！![img-166631359785910b2b30239877c85826a44c8ef7ba1a31bda486179dc93ed2525680b726d91e2.jpg](https://github.com/gkd-kit/gkd/assets/20061353/cbce87d6-b01b-42da-b003-7903b334f76a)
