### ISSUE TITLE
[bug] 全局规则使用 matchSystemApp: false 仍然在时钟应用中触发开屏广告规则

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/gkd#560]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14622597/file.zip

### BUG描述(文字/截图/视频)

全局规则误触快照：https://i.gkd.li/i/14622576

内存订阅中的全局规则如下：
```json5
{
    key: 0,
    name: '开屏广告',
    matchTime: 10000,
    actionMaximum: 2,
    resetMatch: 'app',
    actionCdKey: 0,
    actionMaximumKey: 0,
    rules: [
      {
        key: 0,
        quickFind: true,
        matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
        matchSystemApp: false,
      },
      {
        key: 1,
        matches:
          '[childCount=0][visibleToUser=true][(text.length<10 && (text*="跳过" || text*="跳過" || text*="skip" || text*="Skip")) || id$="tt_splash_skip_btn" || vid*="skip" || vid*="Skip" || desc*="跳过" || desc*="skip" || (vid*="count" && vid*="down" && vid!*="countdown" && vid!*="load" && vid!*="add" && vid!*="ead" && vid!*="time")]',
        matchSystemApp: false,
      },
    ],
}
```

已关闭其他订阅的全局规则。

### 期望行为(文字/截图/视频)

在上述快照中不触发全局规则

### 实际行为(文字/截图/视频)

触发了内存订阅中全局规则的开屏广告规则

**Comment by lisonge** [comment]
你好，不能复现

![image](https://github.com/gkd-kit/gkd/assets/38517192/dbd0a6c8-09af-4fc6-a743-c000b6c59635)

你可以将 db 这个目录压缩为 db.zip 后上传到这里

**Comment by Snoopy1866** [comment]
[db.zip](https://github.com/gkd-kit/gkd/files/14623387/db.zip)

**Comment by lisonge** [comment]
重启后也是这样吗

**Comment by lisonge** [comment]
你在 时钟 这个应用的界面的全局规则是否显示开启呢？

**Comment by Snoopy1866** [comment]
> 重启后也是这样吗

重启后也是这样



> 你在 时钟 这个应用的界面的全局规则是否显示开启呢？

开启

https://github.com/gkd-kit/gkd/assets/45487685/88408596-e471-4a0a-a102-8c0dd3db20cd

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/actions/runs/8307676388\

使用此版本重新上传 log.zip 再看看

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/inspect/files/14623640/file.zip

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/gkd/assets/38517192/55cf7039-b061-46e7-80d2-db5456ededdd)

你的 时钟 不是系统应用

**Comment by lisonge** [comment]
你可以使用 冰箱 这类软件的 APP 列表看看，它有两个 TAB `APP`/`系统` ，你看看你的 时钟 在哪个tab
