### ISSUE TITLE
通知栏图标适配黑白色风格

### ISSUE THREAD

**Issue by fengzzyun** [gkd-kit/gkd#562]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

![Screenshot_20240320_113504](https://github.com/gkd-kit/gkd/assets/4385683/a94565ac-e8fd-4deb-8fa0-6afc8470f190)
GKD需要常驻通知栏，希望可以适配黑白风格的通知栏图标，与其他应用和系统图标风格统一。谢谢。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
