### ISSUE TITLE
希望能支持root直接获取权限

### ISSUE THREAD

**Issue by hunyanjie** [gkd-kit/gkd#565]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

shizuku经常被我误杀后台搞得我又得重新搞😂

**Comment by lisonge** [comment]
额外补充未计划的原因

- 我没有 root，也懒得弄
- 你的问题只是杀后台，我的手机上最近一个月在 shizuku/gkd 上从来没有出现过杀后台，无法复现
