### ISSUE TITLE
```显示未安装应用```勾选问题

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#567]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14697257/file.zip

### BUG描述(文字/截图/视频)

点击订阅-应用规则-右上角勾选```显示未安装应用```，退出应用规则页面后会重置为```未勾选```状态
![Screenshot_2024-03-21-23-16-27-555_li songe gkd-e](https://github.com/gkd-kit/gkd/assets/57941037/f05e8d60-f566-4140-8656-39cb4ffaaec6)

### 期望行为(文字/截图/视频)

退出应用规则页面后不会重置为```未勾选```状态

### 实际行为(文字/截图/视频)

退出应用规则页面后重置为```未勾选```状态

**Comment by lisonge** [comment]
次级页面的所有筛选状态均不会保留
