### ISSUE TITLE
gkd 查看订阅的应用规则，没有显示应用

### ISSUE THREAD

**Issue by XiaooHu2002** [gkd-kit/gkd#568]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

日志文件：https://github.com/gkd-kit/inspect/files/14730837/file.zip

### BUG描述(文字/截图/视频)

就是我点应用规则之后没有显示应用导致我无法查看订阅
![Screenshot_2024-03-23-16-23-27-537_li songe gkd](https://github.com/gkd-kit/gkd/assets/90300662/7ba50eda-8cc0-40b2-8633-04e0370444cc)

### 期望行为(文字/截图/视频)

我希望我可以点击应用规则去设置某个 App 的订阅规则

### 实际行为(文字/截图/视频)

但实际是一打开没有 App 供我选择，我的机型是红米 k40 游戏增强版，但是在我的小米平板 6pro 是可以查看 App 应用规则的
![Uploading IMG_20240323_164118.jpg…]()

**Comment by lisonge** [comment]
你没有授权应用列表读取权限
