### ISSUE TITLE
后台经常被杀进程

### ISSUE THREAD

**Issue by g1fts** [gkd-kit/gkd#57]
锁任务也没用，建议把自启动打开，这样可以保活。

**Comment by lisonge** [comment]
自启动不应该是用户去配置手动打开吗？

![78962760ed6744840cd362d94194c2d](https://github.com/gkd-kit/gkd/assets/38517192/70cdbc86-97db-4013-9fcf-248cd4270639)

**Comment by g1fts** [comment]
对，我的意思是在初次打开软件设置的时候，提示下把自启动打开，另外根据各家系统情况把省电策略改成无限制。这样可以避免杀后台的情况出现。

**Comment by lisonge** [comment]
好的好的，后期会加滴

抱歉，主要是我最近比较忙

后面会逐渐完善的
