### ISSUE TITLE
`A -2 B` 通过快照选择器查询，却不能执行。

### ISSUE THREAD

**Issue by zhaocai** [gkd-kit/gkd#571]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

[log-1711247824752.zip](https://github.com/gkd-kit/gkd/files/14734189/log-1711247824752.zip)

### BUG描述(文字/截图/视频)

快照：`https://i.gkd.li/i/14734199`

选择：`TextView[text*="点击了解更多内容"] <(1,2) LinearLayout < LinearLayout < FrameLayout -2 FrameLayout > ImageView[width<80][height<80]`

如下图示，选择器是合法的，但是`执行选择器`显示没有查询到节点，写入内存订阅也无法成功执行。调试后上面选择中的`FrameLayout -2 FrameLayout` 改为`FrameLayout - FrameLayout - FrameLayout` 可正常执行，这应该是选择器的Bug吧？

![20240324_104503](https://github.com/gkd-kit/gkd/assets/341473/546cabe9-7b9d-4ff9-9aff-94f26b7371a1)

### 期望行为(文字/截图/视频)

如上

### 实际行为(文字/截图/视频)

如上

**Comment by lisonge** [comment]
你好，麻烦将这个 应用 的 apk 上传到这里，我在 小米应用商店/play商店 均无法找到正确的包名和版本

**Comment by zhaocai** [comment]
> 你好，麻烦将这个 应用 的 apk 上传到这里，我在 小米应用商店/play商店 均无法找到正确的包名和版本

https://www.123pan.com/s/iUvkjv-A7wmH.html

这是个听小说的app，广告通常是在播放时点暂停时出现，但每次出现的广告不一样（可能有3、4种），未必是上面快照的这个，可能要多试几次才会出现。

**Comment by lisonge** [comment]
感谢反馈，确实是这样，当你使用 `-`/`+` 时，选择器内部会使用 Map 记录每个节点的 index 避免重复查询

目前应该是这个 Map 记录有问题，网页端没有这个问题是因为在网页端没有耗时操作，自然也不需要这个 Map

这个可能也导致之前某些规则不执行了，我后续修复一下

**Comment by lisonge** [comment]
你好，麻烦试试 https://github.com/gkd-kit/gkd/actions/runs/8406899771 中的 release 是否正确工作呢

**Comment by zhaocai** [comment]
> 你好，麻烦试试 [gkd-kit/gkd/actions/runs/8406899771](https://github.com/gkd-kit/gkd/actions/runs/8406899771) 中的 release 是否正确工作呢

应该是可以了，点了一会儿没有重现之前的广告，不过点到一个这样的广告是可以的。`TextView[text="淘宝精选"] < FrameLayout -3 FrameLayout > ImageView[width<80][height<80]`
