### ISSUE TITLE
添加订阅按钮挡住了最后一个订阅的开关按钮

### ISSUE THREAD

**Issue by leic4u** [gkd-kit/gkd#572]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

GUI 问题，不需要日志

### BUG描述(文字/截图/视频)

![image](https://github.com/gkd-kit/gkd/assets/32786903/8767e98a-4538-4b38-b481-9c7ec91a9781)

### 期望行为(文字/截图/视频)

添加订阅按钮换个位置？

### 实际行为(文字/截图/视频)

添加订阅按钮挡住了最后一个订阅的开关按钮

**Comment by lisonge** [comment]
你可以暂时长按拖动排序，把要编辑的拖到上面去

**Comment by leic4u** [comment]
> 你可以暂时长按拖动排序，把要编辑的拖到上面去

现在确实是这样操作的，但是还是希望大佬空了能优化一下。

**Comment by kittyzero520** [comment]
> > 你可以暂时长按拖动排序，把要编辑的拖到上面去
> 
> 现在确实是这样操作的，但是还是希望大佬空了能优化一下。

可以分享下规则不？

**Comment by leic4u** [comment]
> 可以分享下规则不？

https://github.com/Adpro-Team/GKD_THS_List
都在这里
