### ISSUE TITLE
首次添加规则始终默认为开启

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/gkd#575]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14743513/file.zip

### BUG描述(文字/截图/视频)

当某个规则订阅更新针对某个APP的新规则时，首次新添加规则的始终默认为开启，即`enable`字段失效

举例：
![image](https://github.com/gkd-kit/gkd/assets/34203474/c57b0c00-2d0b-4f4a-ac85-ecb26e1e0160)
自己编写的规则这次更新了俩个规则，且`enable`字段默认为`false`。
![image](https://github.com/gkd-kit/gkd/assets/34203474/a294be37-7a9c-4f6a-959e-49e02a654ecc)
更新后却默认开启
![0409089186c2920e2df9d6af2f31034](https://github.com/gkd-kit/gkd/assets/34203474/b85c9656-f92f-4271-b9a9-7370abeaa598)

### 期望行为(文字/截图/视频)

更新规则订阅，出现新增规则时，新增规则开启应遵循`enable`字段

### 实际行为(文字/截图/视频)

更新规则订阅，出现新增规则时，新增规则默认开启

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/gkd/assets/38517192/4d2acac1-bd81-41a1-b869-8a03d877e6fb)

因为你用规则分类把此类规则强制开启了

**Comment by aoguai** [comment]
> 因为你用规则分类把此类规则强制开启了

有点没明白，符合 categories 的规则都会强制开启？

**Comment by lisonge** [comment]
优先级: 规则手动配置 > 分类手动配置 > 批量默认 > 规则默认

你现在的情况是 `分类手动配置 > 规则默认`

**Comment by aoguai** [comment]
> 你现在的情况是 `分类手动配置 > 规则默认`

懂了，感谢🙏🏻

**Comment by lisonge** [comment]
没看懂你说的啥

> 规则手动配置 > 分类手动配置 > 分类默认 > 规则默认

反正规则更不更新都按照这个优先级控制，更新订阅后新增的规则没有 规则手动配置，被 `分类手动配置` 控制

如果你不想让它被先前配置控制，那你换一个分类或者不被分类捕获就行

**Comment by aoguai** [comment]
好的，谢谢
