### ISSUE TITLE
无障碍服务无法运行

### ISSUE THREAD

**Issue by Lp0307** [gkd-kit/gkd#576]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14787149/file.zip

### BUG描述(文字/截图/视频)

第一次打开应用并授权无障碍，应用正常可以使用，但是在清除后台之后，应用无法使用，打开应用会显示需要授权无障碍权限，但是点进去无障碍权限是开着的，只有重新关闭无障碍权限再次重新开启才可使用，无障碍服务报错如下
![Screenshot_20240328_173543](https://github.com/gkd-kit/gkd/assets/95898487/9b64e09d-d421-40cd-bc2c-3b18d35e35d7)

### 期望行为(文字/截图/视频)

希望能修复一下无障碍服务

### 实际行为(文字/截图/视频)

手机系统升级后出现该情况

**Comment by Lp0307** [comment]
![Screenshot_20240328_174521](https://github.com/gkd-kit/gkd/assets/95898487/272339ab-740c-465c-8c73-78fef1eb2edf)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/570

**Comment by lisonge** [comment]
日志中没有任何报错，无法解决

**Comment by Lp0307** [comment]
> 日志中没有任何报错，无法解决

我感觉像是兼容性的问题，每次系统更新到另外一个版本的Android，就会出现这种问题，没法解决就算了🌹 🌹 🌹
