### ISSUE TITLE
图标太丑了，还不如原来那个

### ISSUE THREAD

**Issue by din1028** [gkd-kit/gkd#577]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

原来的小机器人多好

**Comment by lisonge** [comment]
你可以 fork 后自行修改，没人拦着你改

**Comment by lisonge** [comment]
或者你也可以给我转账 648 提付费需求
