### ISSUE TITLE
全局规则黑白名单模式

### ISSUE THREAD

**Issue by StrayJoker** [gkd-kit/gkd#578]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

目前app开关全局规则如果app数量多，就不太够方便了
希望做个黑白名单模式，满足不同的需求
对误触不敏感、全局规则适用多的用户
将全局规则更多的希望作为少量跳不了广告场景的补充的用户

**Comment by lisonge** [comment]
https://gkd.li/api/interfaces/RawGlobalApp.html#enable

**Comment by lisonge** [comment]
将你想要加入黑名单的应用的 enable 设置为 false 就是黑名单模式

**Comment by lisonge** [comment]
黑名单模式
- matchAnyApp=true
- 将要配置的应用放入 apps 即可，并设置每个 app 的 enable=false

白名单模式
- matchAnyApp=false
- 将要配置的应用放入 apps 即可

**Comment by Jieoz** [comment]
> 将你想要加入黑名单的应用的 enable 设置为 false 就是黑名单模式

这个是修改订阅规则的配置吗？如果要是使用别人的订阅链接的话要怎么修改呢？
