### ISSUE TITLE
Sui授权后提示错误

### ISSUE THREAD

**Issue by JackA1ltman** [gkd-kit/gkd#58]
我采用Sui方式授权Shizuku选项后报错如图![Screenshot_20230923-102928.jpg](https://github.com/gkd-kit/gkd/assets/82563979/d35f8edf-e3ea-415d-945c-c712a42e1b42)

![Screenshot_20230923-102936.jpg](https://github.com/gkd-kit/gkd/assets/82563979/1a9486f0-b803-4804-ad91-bb31e8546012)

**Comment by lisonge** [comment]
因为不同手机的系统隐藏 api 不一样，你这个是隐藏 api 暂时未适配

APP 已经将你的机型和方法签名输出到日志了

可以将 /sdcard/Android/data/li.songe.gkd/files/log 压缩成一个 zip 发送到 issue 即可

我会尽快适配

**Comment by JackA1ltman** [comment]
> 因为不同手机的系统隐藏 api 不一样，你这个是隐藏 api 暂时未适配
> 
> APP 已经将你的机型和方法签名输出到日志了
> 
> 可以将 /sdcard/Android/data/li.songe.gkd/files/log 压缩成一个 zip 发送到 issue 即可
> 
> 我会尽快适配

[](https://wwmk.lanzouj.com/iMBk819job5a)
[](https://wwmk.lanzouj.com/iEXUh19job7c)
有两个，我不知道哪个是我就都发了

**Comment by JackA1ltman** [comment]
> 因为不同手机的系统隐藏 api 不一样，你这个是隐藏 api 暂时未适配
> 
> APP 已经将你的机型和方法签名输出到日志了
> 
> 可以将 /sdcard/Android/data/li.songe.gkd/files/log 压缩成一个 zip 发送到 issue 即可
> 
> 我会尽快适配

https://wwmk.lanzouj.com/iMBk819job5a
https://wwmk.lanzouj.com/iEXUh19job7c

**Comment by JackA1ltman** [comment]
> 因为不同手机的系统隐藏 api 不一样，你这个是隐藏 api 暂时未适配
> 
> APP 已经将你的机型和方法签名输出到日志了
> 
> 可以将 /sdcard/Android/data/li.songe.gkd/files/log 压缩成一个 zip 发送到 issue 即可
> 
> 我会尽快适配

https://wwmk.lanzouj.com/ipf7A19jpphc

**Comment by lisonge** [comment]
已查清 api， 后续适配

![image](https://github.com/gkd-kit/gkd/assets/38517192/12d7a995-5e46-42bc-aef5-3b6eccf91a9d)

**Comment by FW27623** [comment]
> 已查清 api， 后续适配
> 
> ![image](https://user-images.githubusercontent.com/38517192/270096301-12d7a995-5e46-42bc-aef5-3b6eccf91a9d.png)

开发者您好，我使用shizuku授权报同样错误，下面是log文件

[util_2023_09_23_li.songe.gkd_remote.zip](https://github.com/gkd-kit/gkd/files/12706296/util_2023_09_23_li.songe.gkd_remote.zip)

**Comment by PYUDNG** [comment]
这里也是同样的问题，log附上
[log.zip](https://github.com/gkd-kit/gkd/files/12721833/log.zip)

**Comment by earoftoast** [comment]
相同的问题，log如下，谢谢开发者适配🙏
[log.zip](https://github.com/gkd-kit/gkd/files/12739197/log.zip)

**Comment by Hard2crossWa11** [comment]
魅族17pro也是，麻烦大佬适配， 链接:https://pan.baidu.com/s/1EcrQmPbZ4eMcOc3caTfqMw 提取码:v78d

**Comment by DerekH-233** [comment]
这里也是同样的问题，麻烦大佬适配
[log.zip](https://github.com/gkd-kit/gkd/files/12779459/log.zip)

**Comment by themql** [comment]
相同的问题，log如下，谢谢开发者适配🙏
三星s9p
[util_2023_10_02_li.songe.gkd_remote.zip](https://github.com/gkd-kit/gkd/files/12780764/util_2023_10_02_li.songe.gkd_remote.zip)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0
