### ISSUE TITLE
订阅文件放置于GKD Android/data私有目录中对应位置，重启GKD后没有识别到该订阅

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/gkd#580]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14812472/file.zip

### BUG描述(文字/截图/视频)

如题。是根据[您在这里的回复](https://github.com/gkd-kit/gkd/issues/430#issuecomment-1871201969)执行的操作。该订阅从来没有通过网络链接导入GKD（说明这个是因为，如果在GKD通过网络链接的方式导入过同id的订阅，替换进去就有效）。重启使用的是“强行停止”。

### 期望行为(文字/截图/视频)

重启GKD后能够读取到该订阅，并显示

### 实际行为(文字/截图/视频)

如题。

**Comment by lisonge** [comment]
你这种方法越过了正常的操作逻辑

我不知道如何解决

**Comment by adproqwq** [comment]
> 你这种方法越过了正常的操作逻辑
> 
> 我不知道如何解决

那么，你在 #430 中提到的解决方法必须是GKD识别到的订阅才能成功是吗？

**Comment by lisonge** [comment]
订阅被正确识别的初始条件是 数据库表中有数据行，你没有这个数据行，无论 subscription 有多少文件都不会识别

**Comment by adproqwq** [comment]
好的。另外，1.8有希望出导入/导出配置吗？

**Comment by lisonge** [comment]
配置的导入/导入会有

---

规则的批量导入不会有了，因为我最近看到相关短视频有 10000李跳跳规则 这种无量营销号标题

但是实际上全是批量重复的空规则，我不想 GKD 出现这种情况

**Comment by adproqwq** [comment]
我也刷到了，为了网盘的那些下载分红之类的，下限都没有了

**Comment by lisonge** [comment]
> 重启GKD后能够读取到该订阅，并显示

只需要先在订阅列表添加远程订阅，这样数据库中就有新的 数据行 了，然后执行你刚刚的操作

**Comment by lisonge** [comment]
可以在 <https://gist.github.com/> 随便新建一个 id 对应的 json5 文件，然后添加 raw 链接，使用此链接添加订阅

然后执行你刚刚的操作

**Comment by adproqwq** [comment]
明白了
