### ISSUE TITLE
bug: 删除订阅后，订阅界面的两个bug

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/gkd#581]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14812740/file.zip

### BUG描述(文字/截图/视频)

![Screenshot_2024-03-31-01-04-11-04_befd3b55c4270226022f86e9f9cafb33](https://github.com/gkd-kit/gkd/assets/101449500/c435b886-e5c9-467f-ae14-7dc8725d61a5)

下图是上图的基础上，导入订阅出现的

![Screenshot_2024-03-31-01-09-22-82_befd3b55c4270226022f86e9f9cafb33.jpg](https://github.com/gkd-kit/gkd/assets/101449500/b5ca9874-75b7-401a-8c26-6159d218e5b9)

关掉后台后重新打开后，恢复正常且最底端订阅没有被覆盖

### 期望行为(文字/截图/视频)

删除后，下面的订阅上移补位。且导入新订阅时不会覆盖最底端订阅。

### 实际行为(文字/截图/视频)

如上方图

**Comment by lisonge** [comment]
related to  https://github.com/Calvin-LL/Reorderable/issues/27#issuecomment-2075764725

**Comment by adproqwq** [comment]
> related to [Calvin-LL/Reorderable#27 (comment)](https://github.com/Calvin-LL/Reorderable/issues/27#issuecomment-2075764725)

所以现阶段可以修复吗？

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
