### ISSUE TITLE
matches: 'View[_id=17]',非法,微信使用_id定位

### ISSUE THREAD

**Issue by beisimm** [gkd-kit/gkd#582]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

matches: 'View[_id=17]',非法,微信使用_id定位

**Comment by lisonge** [comment]
你好，你想表达什么 ？
