### ISSUE TITLE
头条里总是“误点”，在搜索框总是命中带有“跳过”的搜索词条，并且这个还归类到开屏广告里，不能单独关闭

### ISSUE THREAD

**Issue by Kurt-Shiwz** [gkd-kit/gkd#587]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14860269/file.zip

### BUG描述(文字/截图/视频)

点击搜索框时 如果有“跳过”，就会直接点击然后触发搜索
https://github.com/gkd-kit/gkd/assets/7554917/9e4ad27b-1d98-44ca-816e-4afd1c08b266

### 期望行为(文字/截图/视频)

点击搜索框时 即使有“跳过”字样的词条，也不做操作
![Screenshot_20240404_102234_com ss android article news](https://github.com/gkd-kit/gkd/assets/7554917/fba092d6-0a08-4c98-a95e-6277ff009e03)

### 实际行为(文字/截图/视频)

https://github.com/gkd-kit/gkd/assets/7554917/9e4ad27b-1d98-44ca-816e-4afd1c08b266

**Comment by lisonge** [comment]
这又不是我写的规则，谁写的规则你找谁啊

**Comment by adproqwq** [comment]
事实上这是全局开屏的误触。全局开屏规则识别到了跳过，所以点击了，在点击记录点击在此页面禁用即可。
