### ISSUE TITLE
规则直接加在主页吧

### ISSUE THREAD

**Issue by nirbusan** [gkd-kit/gkd#588]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

无

### BUG描述(文字/截图/视频)

提供规则订阅

### 期望行为(文字/截图/视频)

点击下方的「订阅」-右下角“+”，输入订阅链接（以下三个地址，任选一个即可）：

    https://registry.npmmirror.com/@aoguai/subscription/latest/files

    https://raw.gitmirror.com/Adpro-Team/GKD_subscription/main/dist/Adpro_gkd.json5

    https://raw.gitmirror.com/AIsouler/GKD_subscription/main/dist/AIsouler_gkd.json5

### 实际行为(文字/截图/视频)

提供了3个订阅

**Comment by EchoGroot** [comment]
第二个好用
