### ISSUE TITLE
疑似bug: matches字段中包含多个选择器时无法触发点击

### ISSUE THREAD

**Issue by Sunsetra** [gkd-kit/gkd#590]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [x] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

[log-1712303078944.zip](https://github.com/gkd-kit/gkd/files/14881732/log-1712303078944.zip)

### BUG描述(文字/截图/视频)

APP版本：`1.7.3`

按API docs里的描述，规则中的`matches`字段可以是包含多个选择器的`IArray`：
<https://gkd.li/api/interfaces/RawRuleProps#matches>

但以下规则无法触发点击事件（快照节点满足`key: 0`的第一条选择器）：
<details>

```
{
  id: 'com.zhihu.android',
  name: '知乎',
  groups: [
    {
      key: 1,
      name: '分段广告-推荐页-问题广告卡片',
      activityIds: 'com.zhihu.android.app.ui.activity.MainActivity',
      rules: [
        {
          key: 0,
          matches: [
            '@ImageView[id=`com.zhihu.android:id/menu`] < FrameLayout - * > TextView[text^=`广告`]',
            '@ImageView < ViewGroup -3 TextView[text^=`广告`]',
          ],
          snapshotUrls: 'https://i.gkd.li/import/14881985',
        },
        {
          key: 1,
          quickFind: true,
          matches:
            '@ViewGroup[clickable=true] <3 ViewGroup < ViewGroup -n ViewGroup > ViewGroup > TextView[text=" 的广告"]',
        },
        {
          key: 90,
          preKeys: [0],
          quickFind: true,
          matches: [
              '@FrameLayout[clickable=true] >3 TextView[text="屏蔽该内容"][id="com.zhihu.android:id/tv_content"]',
              '@LinearLayout[clickable=true] >3 TextView[text="不感兴趣"][id="com.zhihu.android:id/title"]',
          ],
        },
        {
          key: 91,
          preKeys: [1],
          quickFind: true,
          matches:
            '@FrameLayout > LinearLayoutCompat[id="com.zhihu.android:id/ll_container"] >2 TextView[text="内容不感兴趣"][id="com.zhihu.android:id/tv_content"]',
        },
      ],
    },
  ],
}
```
</details>

如果将`matches`改为只有一条选择器，则可以正确触发点击事件：
<details>

```
{
  id: 'com.zhihu.android',
  name: '知乎',
  groups: [
    {
      key: 1,
      name: '分段广告-推荐页-问题广告卡片',
      activityIds: 'com.zhihu.android.app.ui.activity.MainActivity',
      rules: [
        {
          key: 0,
          matches: '@ImageView[id=`com.zhihu.android:id/menu`] < FrameLayout - * > TextView[text^=`广告`]',
          snapshotUrls: 'https://i.gkd.li/import/14881985',
        },
        {
          key: 1,
          quickFind: true,
          matches:
            '@ViewGroup[clickable=true] <3 ViewGroup < ViewGroup -n ViewGroup > ViewGroup > TextView[text=" 的广告"]',
        },
        {
          key: 90,
          preKeys: [0],
          quickFind: true,
          matches: '@LinearLayout[clickable=true] >3 TextView[text="不感兴趣"][id="com.zhihu.android:id/title"]',
        },
        {
          key: 91,
          preKeys: [1],
          quickFind: true,
          matches:
            '@FrameLayout > LinearLayoutCompat[id="com.zhihu.android:id/ll_container"] >2 TextView[text="内容不感兴趣"][id="com.zhihu.android:id/tv_content"]',
        },
      ],
    },
  ],
}
```
</details>

请问这是`matches`的特性还是一个bug？

### 期望行为(文字/截图/视频)

包含多个选择器的`matches`字段在满足其中一个选择器时可以正常触发点击事件

### 实际行为(文字/截图/视频)

包含多个选择器的`matches`字段在满足其中一个选择器时无法触发点击事件

**Comment by lisonge** [comment]
<https://gkd.li/api/interfaces/RawRuleProps#matches> 的注释是

> 一个或者多个合法的 GKD 选择器, 如果每个选择器都能匹配上节点, 那么点击最后一个选择器的目标节点

![image](https://github.com/gkd-kit/gkd/assets/38517192/7d98935f-7ae7-42a9-8fe7-dceaeb95c294)

在 <https://i.gkd.li/import/14881985> 中并不能选择到 `@ImageView < ViewGroup -3 TextView[text^='广告']`

![image](https://github.com/gkd-kit/gkd/assets/38517192/4d273470-a754-4317-a433-75a1f1905aac)

不满足 `如果每个选择器都能匹配上节点` 这个条件

**Comment by Sunsetra** [comment]
我之前的理解是二者都能匹配时，点击最后一个选择器的目标节点；而在其中一种匹配时使用匹配的那个选择器。
看来是我理解错了，感谢解惑

**Comment by Sunsetra** [comment]
> https://gkd.li/api/interfaces/RawRuleProps#matches 的注释是
> 
> > 一个或者多个合法的 GKD 选择器, 如果每个选择器都能匹配上节点, 那么点击最后一个选择器的目标节点
> 
> ![image](https://private-user-images.githubusercontent.com/38517192/319973069-7d98935f-7ae7-42a9-8fe7-dceaeb95c294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMTYwMTEsIm5iZiI6MTcxMjMxNTcxMSwicGF0aCI6Ii8zODUxNzE5Mi8zMTk5NzMwNjktN2Q5ODkzNWYtN2FlNy00MmE5LThmZTctZGNlYWViOTVjMjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDExMTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjM2M3MmI1MTc5Y2MyMWJlMDQxNWVkZGNmZWFmNTA1OGJmYjM5NmJlZWQ1OGUwZTA3MmFlNGE4NTNiMjJhZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uj7lyhhGKNovRClBHftlLRne0u52uYwTlRw8wPooVnE)
> 
> 在 https://i.gkd.li/import/14881985 中并不能选择到 `@ImageView < ViewGroup -3 TextView[text^='广告']`
> 
> ![image](https://private-user-images.githubusercontent.com/38517192/319973438-4d273470-a754-4317-a433-75a1f1905aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMTYwMTEsIm5iZiI6MTcxMjMxNTcxMSwicGF0aCI6Ii8zODUxNzE5Mi8zMTk5NzM0MzgtNGQyNzM0NzAtYTc1NC00MzE3LWE0MzMtNzVhMWYxOTA1YWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDExMTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYWM0NmRhNGE4ODE2NGY4ODUxMWUxY2Y2N2Q1OGM5NzQ3Y2NjNzEzYTEwZmE5MzM5MzZjZjQ1MjdkZjI0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VgtDf-Xrt6-shRUaEspfTSWz8xLvCJ5250oQyy9szRQ)
> 
> 不满足 `如果每个选择器都能匹配上节点` 这个条件

我之前的理解是：当二者都能匹配时，点击最后一个选择器的目标节点；当其中一种匹配时，使用匹配的那个选择器。
看来是我理解错了，感谢解惑

**Comment by lisonge** [comment]
你说的那种叫 `anyMatches` 我还没考虑支持

因为它可以通过多个 rule 的单个 matches 去实现

**Comment by adproqwq** [comment]
> 因为它可以通过多个 rule 的单个 matches 去实现

但是的确精简了规则代码

**Comment by lisonge** [comment]
你使用的是哪个版本？要使用最新版本才有效

**Comment by NXY666** [comment]
> 你使用的是哪个版本？要使用最新版本才有效

1.7.3，但是检查更新似乎没有新版本，是Beta版本吗？

**Comment by lisonge** [comment]
你可以查看 github release 列表
