### ISSUE TITLE
替换私有目录中的订阅文件，重启GKD后被还原

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/gkd#591]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14885109/file.zip

### BUG描述(文字/截图/视频)

根据[你的指引](https://github.com/gkd-kit/gkd/issues/580#issuecomment-2028201039)
在GKD中导入了同id的空订阅，然后在私有目录中将同id的订阅文件替换进去。
强行停止GKD，重启后，订阅列表显示本地无订阅文件，再次刷新后，订阅被还原成导入时的空状态，并提示：更新了1条订阅

另外问一句：链接指向的订阅文件version为0，本地的订阅文件version为1，替换进去后为什么能触发更新？

### 期望行为(文字/截图/视频)

订阅文件成功被替换，应用规则变为本地订阅文件中的规则

### 实际行为(文字/截图/视频)

如题

**Comment by lisonge** [comment]
你好，我不知道，你可以自行查看源码解决

**Comment by adproqwq** [comment]
> 你可以检查一下你的订阅文件是否合法

好的，我去确认一下
