### ISSUE TITLE
MIUI14 安卓13 关闭广告的速度有些慢

### ISSUE THREAD

**Issue by QianMoXi** [gkd-kit/gkd#60]
系统：MIUI14 安卓13
程序版本：1.2.1（好像一直有这个问题）
已经授权GKD开机自启、省电策略无限制

打开其它软件时，如B站、网易云音乐，需要等待一秒多才能自动关闭开屏广告，速度有些慢，让我经常性怀疑没能跳过广告，想手动去点击
之前用李跳跳的时候， 是能在广告出来的一瞬间就点击跳过的

但是，比较奇怪的是，如果是在朋友圈这种地方，关闭朋友圈的广告的速度倒是很快的，我都没能看到是广告，就已经帮忙关闭了

https://github.com/gkd-kit/gkd/assets/26250460/78552346-d842-48f5-a8e5-da1d46e69893

**Comment by lisonge** [comment]
我的手机和你的一样，我后续排查一下

**Comment by Saeviome** [comment]
我也有这个问题。李跳跳开票跳过秒点。gkd这个延迟特别高。

**Comment by Pa55w0rd** [comment]
+1，从李跳跳自定义规则的项目跳过来的，李跳跳秒点，gkd延迟特别高

**Comment by lshilshi** [comment]
> +1，从李跳跳自定义规则的项目跳过来的，李跳跳秒点，gkd延迟特别高

同样问题

**Comment by lisonge** [comment]
可以了，找到解决方案了

我之前是用协程轮询 `rootInActiveWindow` ，但是这个在 哔哩哔哩/其它APP 开屏的时候有延迟导致找不到跳过节点

然后我改成在 `onAccessibilityEvent` 里通过 `event.source` 这个节点去查询，这个延迟就不见了，哔哩哔哩的开屏广告基本就是一闪而过了

另外其它APP的类似问题也将得到解决，这个问题将在下个版本修复

**Comment by huanghaobaobao** [comment]
妨碍我从李跳跳转过来的最大麻烦终于要解决了，我也是MIUI14+小米13，知乎跳过一直延迟很高，只有打开悬浮窗才能立马跳过，很奇怪的bug

**Comment by Saeviome** [comment]
（爱奇艺）也是跳过很慢。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0

我更新了 哔哩哔哩  的订阅规则，它的 开屏广告 之前在我的手机上是要等待 1-2s ，现在是出现开屏页面就立马点击

你们的设备上的 哔哩哔哩 开屏广告 如何?

**Comment by RouRouX** [comment]
> https://github.com/gkd-kit/gkd/releases/tag/v1.3.0
> 
> 我更新了 哔哩哔哩 的订阅规则，它的 开屏广告 之前在我的手机上是要等待 1-2s ，现在是出现开屏页面就立马点击
> 
> 你们的设备上的 哔哩哔哩 开屏广告 如何?

速度很快，只是不开悬浮按钮的时候有问题，已经在别的issue里面说了，k40 miui14。

**Comment by lisonge** [comment]
好的，其它应用的规则后续也会使用 `quickFind` 优化

**Comment by wy353208214** [comment]
miui 14 , Android 13
GKD 1.3.0

以下app测试：
知乎，腾讯，爱奇艺，头条，直播吧，36kr，小红书，小米商城等
李跳跳秒过；GKD要等1s左右，有提示跳过

**Comment by lonble** [comment]
quickFind默认是true还是false

**Comment by 1314id** [comment]
荣耀手机，magic os 8，京东 咸鱼基本4秒才跳，广告一共5秒。。。

**Comment by lisonge** [comment]
这个建议自己写规则来实现点击，不会可以学，再不会建议换其他软件了
