### ISSUE TITLE
手动添加订阅后一直订阅失败

### ISSUE THREAD

**Issue by junexus** [gkd-kit/gkd#602]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/15022690/file.zip

### BUG描述(文字/截图/视频)

在订阅界面点击+号后, 一直无法完成订阅下载, 网络确认没有问题

### 期望行为(文字/截图/视频)

手动添加订阅链接后应能下载成功

### 实际行为(文字/截图/视频)

无法下载订阅

**Comment by lisonge** [comment]
根据你提供的日志文件
```txt
java.net.SocketTimeoutException: timeout
```
判断是网络加载超时，换个好点的网络或者开梯子
