### ISSUE TITLE
求大大出鸿蒙next版本

### ISSUE THREAD

**Issue by dowdyboy** [gkd-kit/gkd#604]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

下半年next就出了，大大能否适配下呀？

**Comment by lisonge** [comment]
你好，既然你想要，你可以给我买一个 华为 mate 60 帮助我开发

更多信息可以查看 <https://github.com/gkd-kit/gkd/issues/498>

**Comment by Snowwhite-cute** [comment]
> 你好，既然你想要，你可以给我买一个 华为 mate 60 帮助我开发
> 
> 更多信息可以查看 [#498](https://github.com/gkd-kit/gkd/issues/498)

刚去498爬了楼，没想到这么刺激...有种逛小破站评论区的赶脚~
