### ISSUE TITLE
酷安 关闭广告

### ISSUE THREAD

**Issue by Elin-lin** [gkd-kit/gkd#605]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

酷安关闭广告后，会出现 “您可选择点击【今日免广告】”界面，自动关闭弹出的界面

**Comment by lisonge** [comment]
？看不懂上面第二条须知？

**Comment by adproqwq** [comment]
如果你用的是第三方订阅，请到对应仓库反馈。
