### ISSUE TITLE
excludeMatches相关问题

### ISSUE THREAD

**Issue by LingEmberMaple** [gkd-kit/gkd#607]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

[log-1714202452314.zip](https://github.com/gkd-kit/gkd/files/15137435/log-1714202452314.zip)

### BUG描述(文字/截图/视频)

<details><summary>示例规则</summary>
<p>

```
{
  id: 'com.sina.weibo',
  name: '微博',
  groups: [
    {
      name: '功能类-超话自动签到',
      key: 20,
      enable: false,
      quickFind: true,
      rules: [
        {
          name: '点击签到',
          key: 0,
          matches: [
            '[text="签到" || text="Sign in"] < [vid="right_button"]'
          ],
          excludeMatches: [
            '[text="关注"]',
            '[text="Follow"]'
          ],
          snapshotUrls: [
            'https://i.gkd.li/i/15092999',
            'https://i.gkd.li/i/15092970',
            'https://i.gkd.li/i/15136801'
          ],
          activityIds: [
            'com.sina.weibo.supergroup.SGPageActivity'
          ]
        }
      ]
    }
  ]
}
``` 

</p>
</details> 

在excludeMatches选择器匹配上节点的情况下，有概率依然继续匹配此规则

### 期望行为(文字/截图/视频)

excludeMatches选择器匹配上节点, 停止匹配此规则

### 实际行为(文字/截图/视频)

excludeMatches选择器匹配上节点, 有概率依然继续匹配此规则

**Comment by LingEmberMaple** [comment]
页面加载稍慢的时候大概率会继续匹配规则

**Comment by LingEmberMaple** [comment]
[log-1714205329216.zip](https://github.com/gkd-kit/gkd/files/15137585/log-1714205329216.zip)

https://weibo.com/p/10080845bb403e6f6aeb6192eb4e337d4aa9fe
此页面大概率误触
https://i.gkd.li/i/15137550

**Comment by LingEmberMaple** [comment]
是节点加载顺序的问题吗

**Comment by LingEmberMaple** [comment]
加入actionDelay和actionMaximum可解决

**Comment by LingEmberMaple** [comment]
如果一定要使用excludeMatches的话，解决办法只能是添加延迟吗

**Comment by lisonge** [comment]
看起来是页面刚打开时候要排除的节点是延迟创建的导致的
