### ISSUE TITLE
内置规则合并功能

### ISSUE THREAD

**Issue by night2049** [gkd-kit/gkd#608]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

目前订阅多个远程规则后，规则间未根据界面id或其他唯一标识进行规则合并，在应用栏点击进入某一应用所有规则时使用不友好，建议根据界面id或其他唯一标识进行规则合并，合并后规则介绍可将多个远程规则中的描述进行合并显示，方便用户开关具体规则。另外全局规则在应用详情中建议默认收起。

**Comment by adproqwq** [comment]
不现实
