### ISSUE TITLE
更新版本后，本地订阅消失

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#609]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/15157258/file.zip

### BUG描述(文字/截图/视频)

更新版本后，立即打开软件进入订阅界面然后本地订阅就会消失。消失后订阅界面还显示规则数量但是进入里是空的，如图
![Screenshot_20240430_110252](https://github.com/gkd-kit/gkd/assets/98690669/c78a2d63-fdc3-4455-9eac-f90d9042e82c)
![Screenshot_20240430_110256](https://github.com/gkd-kit/gkd/assets/98690669/b82c15fd-8f19-4ed2-a52e-ec2696bba421)

### 期望行为(文字/截图/视频)

本地订阅维持原样

### 实际行为(文字/截图/视频)

本地订阅自己清空

**Comment by lisonge** [comment]
根据 `appList.json` 来看，你没有授权应用列表权限
