### ISSUE TITLE
三星手机无法保存快照

### ISSUE THREAD

**Issue by Chengxcy** [gkd-kit/gkd#61]
测试了两部三星手机，三星note10，系统版本：安卓12
三星S23 Ultra，系统版本：安卓13。
均开启了悬浮窗服务，也能看到红色的取框。![Screenshot_20230924_174942.jpg](https://github.com/gkd-kit/gkd/assets/91258009/ebb5a698-01cb-4a98-92ca-91ec9998c4cc)

打开需要取快照的APP，点击这个，没有任何反应，没有出现“快照成功”的提示。快照记录里也是空的。
测试了很老的手机小米8，上面字体显示不全，能提取快照，所以操作上应该没问题。但是小米8上最下方没有“快照记录”的按钮。

**Comment by lelexcv** [comment]
我用fold5也是这样不能快照

**Comment by yybcx** [comment]
note20u也不行，解决了吗

**Comment by lisonge** [comment]
试试这个版本呢

https://github.com/gkd-kit/gkd/issues/115#issuecomment-1751026613

**Comment by yybcx** [comment]
用最新版多点几次就行了


二刺螈 ***@***.***> 于 2023年10月7日周六 10:30写道：

**Comment by lisonge** [comment]
> 用最新版多点几次就行了

还要多点几次吗？不能点一次成功吗？

**Comment by yybcx** [comment]
很玄学，就是一直点总有一次能成功

二刺螈 ***@***.***> 于 2023年10月7日周六 10:59写道：

**Comment by lisonge** [comment]
有点奇怪

不过之前有一个功能叫 `按键快照` 用无障碍监听按下音量键时就能触发快照，但是后面有人反馈导致音量变化出现延迟就去掉了

但是我刚刚发现应该可以改进为 监听音量变化 ，这个就是普通的不依赖无障碍的数据变化，应该就不会出现 bug 了

你可以在后续使用这个来打快照

**Comment by yybcx** [comment]
还是等后续更新优化吧

二刺螈 ***@***.***> 于 2023年10月7日周六 11:14写道：

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0
