### ISSUE TITLE
本地订阅数量显示错误

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#611]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/15199071/file.zip

### BUG描述(文字/截图/视频)

订阅界面显示2应用/2规则组，但实际上本地订阅只有一个应用一个规则组，重启GKD该问题依然存在

https://github.com/gkd-kit/gkd/assets/57941037/f1e5e6ce-39f3-46ba-8bed-e7c517890ba1

### 期望行为(文字/截图/视频)

订阅界面正确显示应用/规则数量

### 实际行为(文字/截图/视频)

订阅界面错误显示应用/规则数量

**Comment by AIsouler** [comment]
添加本地规则不显示
https://github.com/gkd-kit/inspect/files/15199147/file.zip

https://github.com/gkd-kit/gkd/assets/57941037/f8eb1cb8-36c2-48d9-b197-e10dd8d57c39

**Comment by AIsouler** [comment]
重启手机后以上问题依然存在

**Comment by lisonge** [comment]
仅显示已安装应用规则
