### ISSUE TITLE
能否增加支持工作空间app

### ISSUE THREAD

**Issue by galenzhao** [gkd-kit/gkd#613]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

仅存在工作空间内的app在gkd里识别不到

**Comment by lisonge** [comment]
你需要在未安装列表里手动打开

**Comment by galenzhao** [comment]
> 你需要在未安装列表里手动打开

在有shizuku的情况下，是可以通过list其他user的package来完整显示所有安装的app。
这样会更方便一些

**Comment by lisonge** [comment]
不支持
