### ISSUE TITLE
可以增加32位v7a设备的支持吗？

### ISSUE THREAD

**Issue by DKVHDARF** [gkd-kit/gkd#616]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

作者可以添加对于32位设备的版本支持吗，手里有一个几年前的三星平板无法安装现在的版本

**Comment by lisonge** [comment]
你好，你可以 fork 后自行构建

**Comment by lisonge** [comment]
你好，这个我这边应该是实现不了，因为我使用的持久化存储库 mmkv 已经移除了 32 位的支持

https://github.com/Tencent/MMKV/releases/tag/v1.3.5

**Comment by huxc573** [comment]
> 你好，这个我这边应该是实现不了，因为我使用的持久化存储库 mmkv 已经移除了 32 位的支持
> 
> https://github.com/Tencent/MMKV/releases/tag/v1.3.5

请问有旧版本是支持v7a的吗？

**Comment by daidaiworm** [comment]
我也同求一个旧版本，只要能在32位上使用即可。

我是红米9A，估计市面保有量最大的32位机。
MIUI12.5.21，安卓11
