### ISSUE TITLE
微信公众号文尾广告跳过失效，需要更新订阅规则

### ISSUE THREAD

**Issue by sterlingzd** [gkd-kit/gkd#618]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

最近wechat软件升级，公众号文尾广告不能顺利跳过了。
发现时间：2024年5月11日

### BUG描述(文字/截图/视频)

![image](https://github.com/gkd-kit/gkd/assets/92794557/25a5f5ac-7cf4-4855-b0df-49d770993410)

### 期望行为(文字/截图/视频)

通过升级规则或者gkd的app，重新实现公众号文尾广告跳过，当然中间广告也希望跳过哦。

### 实际行为(文字/截图/视频)

最近各大电商促销预热将近，平台都在升级，广告满天飞。

**Comment by sterlingzd** [comment]
希望采取措施，不然他们广告太嚣张。

二刺螈 ***@***.***> 于2024年5月12日周日 16:27写道：

**Comment by lisonge** [comment]
你是看不懂上面的第二条吗？

**Comment by adproqwq** [comment]
这里并不是订阅规则反馈的地方。而且，部分订阅已经在仓库里说明不再编写相关规则，移除现有规则并不再接受相关适配请求。你可以去使用还有相关规则的订阅。

**Comment by sterlingzd** [comment]
谢谢，看到了。Sorry，请原谅我的仓促。

Adpro ***@***.***> 于2024年5月13日周一 12:37写道：
