### ISSUE TITLE
内置禁用的规则会莫名其妙执行

### ISSUE THREAD

**Issue by jiuban590** [gkd-kit/gkd#619]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/15286675

### BUG描述(文字/截图/视频)

gkd开启自启，设置里面的触发提示为：跳过，全局规则gkd规则为内置禁用，然后清除gkd后台，在打开gkd然后进入设置会执行已禁用的规则。

### 期望行为(文字/截图/视频)

不执行已禁用的规则

### 实际行为(文字/截图/视频)

执行已禁用的规则

**Comment by lisonge** [comment]
我这边无法复现，你用下面这个版本复现一遍之后把日志发出来看看

[app-release.zip](https://github.com/gkd-kit/gkd/files/15287062/app-release.zip)

**Comment by jiuban590** [comment]
> 我这边无法复现，你用下面这个版本复现一遍之后把日志发出来看看
> 
> [app-release.zip](https://github.com/gkd-kit/gkd/files/15287062/app-release.zip)

https://f.gkd.li/15288001

**Comment by lisonge** [comment]
在你 `清除gkd后台` 后，直接从桌面打开其它应用，如 知乎，是否会触发规则？

简单来说我想知道 gkd 的进程在你 `清除gkd后台` 后是否还在运行？

**Comment by jiuban590** [comment]
> 在你 `清除gkd后台` 后，直接从桌面打开其它应用，如 知乎，是否会触发规则？
> 
> 简单来说我想知道 gkd 的进程在你 `清除gkd后台` 后是否还在运行？

因为开着自启动，清除后台卡片后还是在运行别的开着的规则可以正常执行。

**Comment by lisonge** [comment]
从你的设备日志来看，gkd 存在 4 次重启，也就是你清除卡片后再打开 gkd 会让 gkd 的进程所有数据重置

从而导致 gkd 获取到的应用列表为默认的空，全局规则就识别不到 gkd 是已经安装的应用，在禁用列表就会把这个丢弃掉，从而导致禁用失效

**Comment by jiuban590** [comment]
> 从你的设备日志来看，gkd 存在 4 次重启，也就是你清除卡片后再打开 gkd 会让 gkd 的进程所有数据重置
> 
> 从而导致 gkd 获取到的应用列表为默认的空，全局规则就识别不到 gkd 是已经安装的应用，在禁用列表就会把这个丢弃掉，从而导致禁用失效

原来如此，暂时没发现别的软件存在相同问题，这个也不影响使用。

**Comment by lisonge** [comment]
试试这个呢

[app-release.zip](https://github.com/gkd-kit/gkd/files/15289442/app-release.zip)

**Comment by jiuban590** [comment]
> 试试这个呢
> 
> [app-release.zip](https://github.com/gkd-kit/gkd/files/15289442/app-release.zip)

OK，这个没有这个问题了

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
