### ISSUE TITLE
打快照成功率低

### ISSUE THREAD

**Issue by TG6** [gkd-kit/gkd#62]
我用的手机是magic5 pro（系统是安卓13），在打快照的时候，有时点击一次就成功，也有点击多次都不成功的情况。我的荣耀平板v8pro（系统是安卓12）也存在这个情况。

**Comment by lisonge** [comment]
感觉和机型有关，后续我排查一下

**Comment by Sec-ant** [comment]
我之前提交规则的时候也经常遇到这种情况

**Comment by lsxuan12138** [comment]
我要遇到了这个情况，设备是华为mate40pro，系统是鸿蒙4，基本就没有一次成功的时候，都要点击很多次

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0
