### ISSUE TITLE
resetMatch: 'app',未正常唤醒规则

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#622]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/15306245

### BUG描述(文字/截图/视频)

规则如下，从系统桌面进入软件，再进入设置页，并不能唤醒规则，如果从设置页回到系统桌面则可唤醒规则，看了下日志从主页进入设置时显示```达到最大执行次数```
```
{
  id: 'com.coolapk.market',
  name: '酷安',
  groups: [
    {
      key: 1,
      name: '功能类',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          quickFind: true,
          activityIds: 'com.coolapk.market.view.base.SimpleActivity',
          matches: '@[clickable=true] >2 [text="界面显示"]',
          snapshotUrls: 'https://i.gkd.li/i/15305694',
        },
      ],
    },
  ],
}
```

https://github.com/gkd-kit/gkd/assets/57941037/46937275-ea54-49f7-9a3d-7d54c93b7cfb

### 期望行为(文字/截图/视频)

重新进入软件后从其他页面进入设置页能正常唤醒规则

### 实际行为(文字/截图/视频)

重新进入软件后从其他页面进入设置页不能正常唤醒规则

**Comment by lisonge** [comment]
试试这个版本呢？

[app-release.zip](https://github.com/gkd-kit/gkd/files/15308024/app-release.zip)

**Comment by AIsouler** [comment]
> 试试这个版本呢？
> 
> [app-release.zip](https://github.com/gkd-kit/gkd/files/15308024/app-release.zip)

该版本没有问题，能正常触发点击

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases

**Comment by AIsouler** [comment]
貌似又出现了这个问题（不确定是不是，因为只在nga这个软件出现）
日志：https://f.gkd.li/17083094
nga开屏广告有时候会在启动软件后过几秒才加载出来，此时使用如下规则无法跳过，但是去掉```actionMaximum: 1,```就能稳定跳过，触发记录显示没有多次点击
```
{
  id: 'gov.pianzong.androidnga',
  name: 'NGA玩家社区',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchRoot: true,
      fastQuery: true,
      matchTime: 20000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          matches: '[vid="tv_tiaoguo" || vid="iv_tg_ad"]',
          exampleUrls: 'https://e.gkd.li/d7520bc7-588b-4654-b6aa-d2736ac200bf',
          snapshotUrls: 'https://i.gkd.li/i/17082872',
        },
      ],
    },
  ],
}
```

https://github.com/user-attachments/assets/15f097b1-8d9c-456f-bd14-d10d063c50f4

**Comment by lisonge** [comment]
这个问题是 获取节点耗时过长阻塞无法处理新事件 导致 appId 没有更新重置规则状态造成的

[release.zip](https://github.com/user-attachments/files/17178733/release.zip)

 可以试试这个版本

**Comment by AIsouler** [comment]
> 这个问题是 获取节点耗时过长阻塞无法处理新事件 导致 appId 没有更新重置规则状态造成的
> 
> [release.zip](https://github.com/user-attachments/files/17178733/release.zip)
> 
> 可以试试这个版本

还是不行，而且这个版本的本地订阅好像不起作用（开关是开启状态）
日志：https://f.gkd.li/17178797

**Comment by lisonge** [comment]
什么叫不起作用？

**Comment by AIsouler** [comment]
> 什么叫不起作用？

就是本地规则是开启状态，但是无法匹配，我看日志也没有记录这条本地规则

刚重新安装了一下，删除本地规则重新导入了，没出现不起作用的情况了

原问题有一定改善，但还是有概率跳不过

**Comment by lisonge** [comment]
关闭全部规则，然后只开启一个规则也是这样吗？因为规则是会阻塞的

我这边基本没出现这种情况了

**Comment by AIsouler** [comment]
我这边只开一个规则反而跳不过了，日志：https://f.gkd.li/17178953
时间从```18:52:44.667```开始

**Comment by lisonge** [comment]
我把你的规则复制出来，相同版本的 nga，试了 30多次，没复现你说的情况，每次都是跳过的

**Comment by lisonge** [comment]
nga 有两个 9.9.36 和 9.9.37 我这边都是能跳过的

**Comment by lisonge** [comment]
https://github.com/user-attachments/assets/ba973bc2-11af-47aa-af4c-9d651356d481

**Comment by lisonge** [comment]
有两种情况，一种是直接跳，一种是由于 nga 加载慢，导致的延迟 2s 跳，总之都是出来后立马跳

你可以试试卸载 gkd 后重装看看

**Comment by AIsouler** [comment]
卸载重装还是不行

https://github.com/user-attachments/assets/188d7c2e-c4bc-46b2-871c-653a96267b53
