### ISSUE TITLE
功能优化: 在主页增加一个快速生成快照按钮

### ISSUE THREAD

**Issue by Ym-wei** [gkd-kit/gkd#625]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

大佬, 您好, 首先很感谢你给大伙提供这么便捷好用的工具, 

场景是这样的: 
       有时候我发现某些app有开屏广告, 我想生成一个快照. 此时我需要进入GKD程序打开悬浮按钮,需哟点4步操作, 当我点进来的时候,广告已经消失了(由于开屏广告有很多不同的规则), 当我下次打开就是另外一个规则了
![image](https://github.com/gkd-kit/gkd/assets/81805625/53c58ee9-c704-4b21-891d-6cc760897c24)

建议: 
     如果在主页增加一个快速生成快照按钮就非常方便了

**Comment by Ym-wei** [comment]
或者可以把高级模式-悬浮窗服务 放在主页上么

**Comment by lisonge** [comment]
![img_v3_02b3_f9b202a4-a8db-4213-80d2-84836fc6a7dg](https://github.com/gkd-kit/gkd/assets/38517192/097d1a67-9a24-43cb-b465-e88ca4107098)

**Comment by Ym-wei** [comment]
好的, 我看看, 谢谢
