### ISSUE TITLE
希望规则编写方式能更简单化一点

### ISSUE THREAD

**Issue by mufengyouyang** [gkd-kit/gkd#630]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

李跳跳虽然规则查看不如gkd，gkd自带查看应用布局的功能，但是编写规则方式貌似有些繁琐。希望编写规则的方式能更简洁一些，例如直接在对应应用下，新增规则的id或者坐标，就可以拦截。甚至直接在浏览器中点击快照中的截图，就可以直接生成对应规则，这样子规则编辑的门槛降低，使用的人也会更多

**Comment by mufengyouyang** [comment]
语言组织能力不是很强，大致是这么个意思

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/254
