### ISSUE TITLE
编辑规则功能有bug,编辑更新后会被复原成初始状态.请看视频

### ISSUE THREAD

**Issue by yuuouu** [gkd-kit/gkd#632]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

[
[错误日志.txt](https://github.com/user-attachments/files/15509430/default.txt)
](url)
2024-05-31 14:43:22.937 ImeBackDispatcher   E  Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 41431012

### BUG描述(文字/截图/视频)

通过pc复制规则到手机,先复制到记事本再粘贴到输入框也出现这样的错误
https://github.com/gkd-kit/gkd/assets/152465495/c81846b2-9476-4efc-a21d-e15311df56f7

### 期望行为(文字/截图/视频)

复制正常的规则,如果有错误的话应该给出提示.

### 实际行为(文字/截图/视频)

以视频为准,新建一个复制没有问题

**Comment by lisonge** [comment]
需要 gkd 导出的日志 zip 文件

**Comment by yuuouu** [comment]
> 需要 gkd 导出的日志 zip 文件
https://github.com/user-attachments/files/15510302/file.zip

**Comment by lisonge** [comment]
```txt
Expected to find '}' to end an object, found EOF instead.
```

我在日志文件看到这样的错误，你输入的文本不是合法的 json5 

--

还有你上面发的视频链接根本无法打开

**Comment by yuuouu** [comment]
同样的内容,右下角新建规则组可以成功.编辑不行
如果是不合法的内容应该有toast提示,

我这边换游览器能正常打开视频
https://github.com/gkd-kit/gkd/assets/152465495/22aef83f-0334-4996-aaa1-ecd613a541e4

**Comment by lisonge** [comment]
这个也不算 bug，是本来就有的行为，添加规则组的时候，可以接收 App 对象，也可以接收 Group 对象

然后你后续编辑单个规则组的时候，你的编辑目标是 Group，但是你粘贴的内容是 App 对象，gkd 按照 Group 的类型去解析你粘贴的 App 对象，自然就会缺失属性

**Comment by yuuouu** [comment]
这个json对象能识别的吧,判断一下是Group还是APP对象应该不是很大问题

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
