### ISSUE TITLE
能否考虑增加自动取消升级、自动安装应用等功能。

### ISSUE THREAD

**Issue by vimbackground** [gkd-kit/gkd#636]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

不少app都有骚扰性的升级提醒，每次都要点击取消也是蛮麻烦的；再就是安装第三方app时，要点击蛮多次鼠标，也是挺麻烦的。

能否增加这种场景的自动点击。

非刚需，但确实能提高体验。

**Comment by adproqwq** [comment]
你或许需要添加规则
