### ISSUE TITLE
触发提示有概率不显示

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#637]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/15796255

### BUG描述(文字/截图/视频)

多位用户反馈存在此问题，貌似是适配系统提示后出现的，捕获快照时也有概率没有提示

https://github.com/gkd-kit/gkd/assets/57941037/a9d4d39f-312e-46ca-b499-ba28c54cbcc3

### 期望行为(文字/截图/视频)

每次触发规则都出现提示

### 实际行为(文字/截图/视频)

触发规则有概率不显示提示

**Comment by AIsouler** [comment]
另外，能否给触发提示增加一个冷却时间？短时间内触发多次规则会出现广告跳过了但一直出现触发提示的情况

**Comment by aeneask** [comment]
beta8也有这个问题，确实跳过了，但不显示跳过提示

**Comment by lisonge** [comment]
```text
2504-11061 NotificationService     system_server                        W  Package li.songe.gkd.debug is above allowed toast quota, the following toast was blocked and discarded: TextToastRecord{e0f518b 1439:li.songe.gkd.debug/u0a600 isSystemToast=false token=android.os.BinderProxy@3e04268 text=GKD duration=0}
```

<https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/notification/NotificationManagerService.java;drc=93193a6a7601efab4b21b57a1ffa6973a957ab80;l=484>

```java
private static final MultiRateLimiter.RateLimit[] TOAST_RATE_LIMITS = {
            MultiRateLimiter.RateLimit.create(3, Duration.ofSeconds(20)),
            MultiRateLimiter.RateLimit.create(5, Duration.ofSeconds(42)),
            MultiRateLimiter.RateLimit.create(6, Duration.ofSeconds(68)),
    };
```
系统 toast 的限制，无解

需要使用悬浮窗弹才行

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
