### ISSUE TITLE
折叠屏改变使用形态后功能失效

### ISSUE THREAD

**Issue by jwqwuming** [gkd-kit/gkd#639]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 新功能描述

如题，希望能适配折叠屏手机

**Comment by lisonge** [comment]
什么是功能失效？起码给个截图/视频，就一个功能失效我怎么知道哪里失效了呢

另外我没有折叠屏，无法适配
