### ISSUE TITLE
应用运行一段时间后，突然不执行任何点击

### ISSUE THREAD

**Issue by longm21** [gkd-kit/gkd#64]
应用已经平稳工作几天了，今天13:20执行了最后一次点击，之后我把手机放在一边，约14:30再使用手机时，发现gkd不再执行任何点击操作。期间没有改动任何地方，包括订阅、后台、服务开启/关闭、订阅开启关闭、订阅更新等。期间未开启shizuku, http, 截屏服务和悬浮窗服务。
之后尝试开启/关闭服务，开启/关闭订阅，更新订阅，没有解决。直接取消应用启动手动管理并删后台，并重新打开软件并赋予无障碍权限后解决问题。
android 版本 12，MagicOS 版本 7.0，机型 HONOR 50 Pro. 
还需要哪些信息，能帮助大佬找到原因？

**Comment by lisonge** [comment]
你好，可以将 /sdcard/Android/data/li.songe.gkd.debug/files/log 压缩为 log.zip 发送到 issue

**Comment by longm21** [comment]
[log.zip](https://github.com/gkd-kit/gkd/files/12712867/log.zip)

**Comment by longm21** [comment]
![a0f1a9ba8122141269a9b77e2c6edfc](https://github.com/gkd-kit/gkd/assets/145310263/dfaa865f-3626-4a7a-b6e0-16a94aa62c84)

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/gkd/assets/38517192/a8cb967d-e0db-424b-9e35-4086610e6bff)

不知道为啥  `13:33:49` 的时候，无障碍被暂停了

它的前面一条记录是 

```
appId=com.hihonor.deskclock, activityId=com.android.deskclock.AlarmsMainActivity
```

**Comment by lisonge** [comment]
当前的逻辑是当回调 `onInterrupt` 后，就进入暂停状态，当回调 `onServiceConnected` 时，就进入正常状态

但是我对 `onInterrupt` 的理解貌似有点错误，就算 onInterrupt 回调，好像无障碍也能正常访问界面节点和执行点击

我一会放开这个限制看看

**Comment by jmui114** [comment]
[log.zip](https://github.com/gkd-kit/gkd/files/12713962/log.zip)
![image](https://github.com/gkd-kit/gkd/assets/46374425/ac57ce98-5586-466e-8ace-5332b52411d9)

我也遇到同样的问题。
开屏广告都能跳过，应用内的`点击服务`能正常工作一段时间之后就停止工作。（点击服务内的规则组与最新订阅更新获取到的不一致，且无法手动切换）
尝试过重启无障碍权限、重启GKD服务、重启GKD软件，均未能使`点击服务`恢复工作。

手机：iQOO 10
系统：android 13
后台耗电管理：电池白名单+后台锁定
无障碍权限：一直开启状态
点击服务停止工作的应用程序及详情：微信朋友圈贴片广告

**Comment by lisonge** [comment]
@jmui114 

> 点击服务内的规则组与最新订阅更新获取到的不一致

这个是正常的，订阅那个卡片显示的是这个订阅所有的应用和规则组，一个订阅内是有默认不启用的规则组的

去掉不启用的规则组后，主页/通知栏显示的就是已经启用的规则组

**Comment by lisonge** [comment]
@jmui114 

根据日志，你的问题也是这个 onInterrupt 被调用了

**Comment by lsxuan12138** [comment]
我也遇到了这个情况，设备是华为mate40pro，系统是鸿蒙4。不过没有上面那么严重，把无障碍关了再打开就可以了

**Comment by philly1021** [comment]
+1，我是华为p30，基本上开了之后只能稳定运行一会，当天就会出现无障碍还是开启状态但是不工作了，想要恢复正常需要手动关掉再重新打开无障碍，我看了日志，也是这个 onInterrupt 被调用了

**Comment by s1oz** [comment]
+1 h无法在OriginOS中工作

**Comment by dysf888** [comment]
mate60pro 鸿蒙4.0 log 也是onInterrupt  一段时间后就不会点击了

**Comment by TUGOhost** [comment]
小米13也有类似的问题，开启一段时间后，应用直接退掉了，我还给应用上了进程锁

**Comment by doio** [comment]
MIUI 14 上面也有这个问题，过了一段时间，GKD 里面提示需要重新授权无障碍功能，无障碍里面提示 GKD 软件有问题

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0

**Comment by lisonge** [comment]
> 小米13也有类似的问题，开启一段时间后，应用直接退掉了，我还给应用上了进程锁

> MIUI 14 上面也有这个问题，过了一段时间，GKD 里面提示需要重新授权无障碍功能，无障碍里面提示 GKD 软件有问题

这两个应该属于是软件崩溃了，和这个问题不一样

**Comment by jmui114** [comment]
> https://github.com/gkd-kit/gkd/releases/tag/v1.3.0

直接在应用内检查更新到v1.3.0后，会丢失订阅信息只剩下本地订阅，但本地订阅内无规则，直接去简单测试了一下，开屏广告可跳，但应用内的点击服务应该是缺少订阅规则导致不可用

**Comment by lisonge** [comment]
> 会丢失订阅信息只剩下本地订阅

右下角+图标可以添加默认订阅，或者下拉刷新也能更新订阅
