### ISSUE TITLE
[BUG] 选择器是正常的, 但是写在订阅中无法触发规则

### ISSUE THREAD

**Issue by uuiid** [gkd-kit/gkd#643]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
- [X] 请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/user-attachments/files/16023831/file.zip

### BUG描述(文字/截图/视频)

https://github.com/user-attachments/files/16023831/file.zip

这个是广告的快照, 但是这个规则组不知道为什么不起作用, 请帮帮分析一下
```
,
    {
      name: '功能类-福利广告-2',
      key: 15,
      desc: '福利广告15秒后跳过, 结束广告.',
      activityIds: 'com.qq.e.tg.RewardvideoPortraitADActivity',
      quickFind: false,
      resetMatch: 'activity',
      matchTime: 20000,
      rules: [
        {
          matches: '[text="已观看视频15秒，可获得奖励"] - @[text="跳过广告"]',
        },
      ],
    },
```

但是另一个类似的就可以

```
    {
      name: '功能类-福利广告',
      key: 14,
      desc: '广告不足15 时, 结束广告',
      activityIds: 'com.qq.e.tg.RewardvideoPortraitADActivity',
      quickFind: false,
      resetMatch: 'activity',
      rules: [
        {
          matches:
            'FrameLayout[id="android:id/content"] >3 @android.widget.ImageView[id =null && text=null && top < 150 && left < 80]',
        },
      ],
    }

```

### 期望行为(文字/截图/视频)

规则组正常运行

### 实际行为(文字/截图/视频)

规则组不运行

**Comment by lisonge** [comment]
1. 没有提供快照
2. 使用最新版本运行看看

**Comment by uuiid** [comment]
[snapshot-1719545073504 (1).zip](https://github.com/user-attachments/files/16023898/snapshot-1719545073504.1.zip)
对不起, 快照的连接和日志的连接看差了

**Comment by uuiid** [comment]
版本号是1.7.3 是最新的了

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/latest

最新版本不是 1.7.3

**Comment by uuiid** [comment]
https://f.gkd.li/16023916

这个是使用 1.8.0-bata.2 版本的测试日志, 还是不行

**Comment by lisonge** [comment]
感谢反馈，是之前会预料到会出现的小概率情况，想着有人反馈了再解决

但是你给出的第二个规则我没有复现(不过问题不大)

**Comment by lisonge** [comment]
使用下面这个呢

使用这个版本 <https://github.com/gkd-kit/gkd/actions/runs/9796798489/artifacts/1668634821>
使用这个字段 <https://gkd.li/api/interfaces/RawCommonProps.html#matchroot>

或者直接粘贴下面的示例

```json5
{
      name: '功能类-福利广告-2',
      key: 15,
      desc: '福利广告15秒后跳过, 结束广告.',
      activityIds: 'com.qq.e.tg.RewardvideoPortraitADActivity',
      quickFind: false,
      resetMatch: 'activity',
      matchTime: 20000,
      matchRoot: true, // ==添加了这行==
      rules: [
        {
          matches: '[text="已观看视频15秒，可获得奖励"] - @[text="跳过广告"]',
        },
      ],
    }
```

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases

**Comment by uuiid** [comment]
可以了

**Comment by AIsouler** [comment]
添加了```matchRoot: true,```但在如下界面无效，使用网页审查工具执行选择器能关闭弹窗
日志：https://f.gkd.li/16326631
快照：https://i.gkd.li/i/16323123
规则：
```
{
  name: '全屏广告-弹窗广告',
  key: 0,
  fastQuery: true,
  matchRoot: true,
  actionMaximum: 1,
  forcedTime: 10000,
  matchTime: 10000,
  resetMatch: 'app',
  rules: [
    {
      key: 0,
      matches: ['@Button[text="关闭"] <<n [vid="webview"]'],
      snapshotUrls: ['https://i.gkd.li/i/16323123'],
      activityIds: ['com.xiaomi.market.ui.FloatWebActivity'],
    },
  ],
},
```

**Comment by lisonge** [comment]
`fastQuery:false`

**Comment by AIsouler** [comment]
> `fastQuery:false`

修改后能关闭弹窗了，方便问一下是什么原因吗？

**Comment by lisonge** [comment]
Button 没有在快照里标识 快速查找

**Comment by AIsouler** [comment]
是我文档没看仔细，只需要把Button 改为不符合快速查询的格式就行了：```@Button[clickable=true][text="关闭"] <<n [vid="webview"]```,这样对于```[vid="webview"]```还是可以使用快速查询
