### ISSUE TITLE
[BUG] 在开启无障碍的情况下无法使用

### ISSUE THREAD

**Issue by haoxiaoyueh** [gkd-kit/gkd#644]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
- [X] 请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16028027
[util_2024_06_28_li.songe.gkd.txt](https://github.com/user-attachments/files/16028157/util_2024_06_28_li.songe.gkd.txt)

### BUG描述(文字/截图/视频)

![Screenshot_20240628_181834](https://github.com/gkd-kit/gkd/assets/113106402/ae8a4390-50b3-4bb5-a27f-9b0e37b02683)
![Screenshot_2024_0628_181848](https://github.com/gkd-kit/gkd/assets/113106402/8a28d552-cca3-4967-85f7-8e6f07d898ad)

### 期望行为(文字/截图/视频)

正常情况下应该是开启了无障碍，这边就正常开启了

### 实际行为(文字/截图/视频)

现在是持续停留在授权页面，跳转到设置里，无障碍权限是已经给了的，但是就是显示没有权限。哪怕是把权限关了，然后重新授权打开，它还是显示没有。

**Comment by lisonge** [comment]
看起来和机型相关，不是 GKD 的问题

关于保活，我的设备上从来没有被杀过，这个问题在应用层面是无法解决的，应该是某个系统行为配置导致的

你可以参考 <https://gkd.li/faq/#persistent>
