### ISSUE TITLE
有计划开发鸿蒙版本吗？[Feature] 

### ISSUE THREAD

**Issue by tbeebt** [gkd-kit/gkd#646]
### 一些验证

- [X] GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li) 以及 [常见问题](https://gkd.li/faq/)
- [X] 请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你想要的功能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上没有找到 (如果不是请先更新到最新版本验证后再提交问题)

### 新功能描述

RT
有计划开发鸿蒙版本吗？

**Comment by lisonge** [comment]
给我买个华为mate60就开发，你能给我买吗？

**Comment by cxylh** [comment]
> 给我买个华为mate60就开发，你能给我买吗？

直接出6000
我有点难
但是200可以
或者你拉个众筹表
或者 Sponsors也行

**Comment by lisonge** [comment]
你好，没想到还有人在回复，补充一下

**鸿蒙 next 已经关闭了 无障碍 api，只有系统应用才能使用，也就是完全杜绝了自定义辅助点击软件存在的可能性**

https://www.bilibili.com/video/BV1Uf421v71f/?share_source=copy_web&vd_source=b8f844d0b945f8e6db886bf68b76cb61

---

此外以后再开鸿蒙版本相关的 issue 将直接删除，此类问题已没有意义
