### ISSUE TITLE
[bug] 应用卸载后规则列表排序未变动

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/gkd#65]
复现步骤（以七猫免费小说为例）：
1. 卸载七猫免费小说
2. 打开 gkd，默认订阅的规则排序中，七猫免费小说依旧排在已安装app这一段

预期效果：七猫免费小说排在后半段未安装app列表中

机型：Xiaomi 13
GKD 版本：1.2.1
系统版本： MIUI 14 V14.0.23.9.18 DEV
Android 版本：13

![5c53ada160dcddae89bca35b4acbc57](https://github.com/gkd-kit/gkd/assets/45487685/6aeceb0e-8524-476e-9068-0f572f31a94e)
![8605244cc2eb3d8c99591101a653930](https://github.com/gkd-kit/gkd/assets/45487685/a93c1218-5cd7-4a26-8cda-5a3c949ae5d8)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0
