### ISSUE TITLE
[BUG] 使用微博时候gkd报oom

### ISSUE THREAD

**Issue by shuohao** [gkd-kit/gkd#650]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
- [X] 请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16105498

### BUG描述(文字/截图/视频)

![9029e5885c993b1ad6e06ab670b58df](https://github.com/gkd-kit/gkd/assets/4637107/1e58339a-630b-4a1d-837f-88398799ddb8)
使用微博，然后点击某个广告触发的，从1.8.0.BETA3开始的，现在用的beta4也有这个问题，之前1.8.0beta1 beta2都正常

### 期望行为(文字/截图/视频)

正常

### 实际行为(文字/截图/视频)

oom，然后提示gdk停止运行

**Comment by lisonge** [comment]
你好，麻烦使用这个版本重新复现 [app-release.zip](https://github.com/user-attachments/files/16106344/app-release.zip) 后把日志重新上传一下

**Comment by shuohao** [comment]
> 你好，麻烦使用这个版本重新复现 [app-release.zip](https://github.com/user-attachments/files/16106344/app-release.zip) 后把日志重新上传一下

我覆盖安装复现没问题吧   https://f.gkd.li/16106676

**Comment by lisonge** [comment]
使用这个版本呢

<https://github.com/gkd-kit/gkd/actions/runs/9805742944/artifacts/1670547610>

**Comment by shuohao** [comment]
> 使用这个版本呢
> 
> https://github.com/gkd-kit/gkd/actions/runs/9805742944/artifacts/1670547610

这个版本可以，目前为止还没复现
