### ISSUE TITLE
啥时候出面具版本？（或者xp版本）

### ISSUE THREAD

**Issue by 244276041** [gkd-kit/gkd#656]
### 一些验证

- [X] GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你想要的功能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上没有找到 (如果不是请先更新到最新版本验证后再提交问题)

### 新功能描述

大佬，啥时候出面具版本？（或者xp版本）
习惯隐藏式使用，作者大佬，啥时候更新下其中一个版本？谢谢大佬求更新~~~~

**Comment by lisonge** [comment]
无计划

**Comment by 244276041** [comment]
....好吧
