### ISSUE TITLE
炼妖壶支持请求

### ISSUE THREAD

**Issue by PYUDNG** [gkd-kit/gkd#66]
使用炼妖壶安装在壶中界的应用，是否可以实现点击（之前用的 一指禅 可以做到）？感谢开发者。

**Comment by lisonge** [comment]
我不到啊，我后续测试一下

**Comment by PYUDNG** [comment]
附上ISLAND链接：https://github.com/oasisfeng/island

**Comment by lisonge** [comment]
目前除 shizuku 外，暂时不考虑支持其它框架，等完全适配 shizuku 后再考虑支持

**Comment by PYUDNG** [comment]
@lisonge 这条issue并不是请求支持shizuku以外框架，也就是说，这条issue并不是请求支持通过炼妖壶这个框架实现点击或者授权。这条issue是请求支持多用户，即：希望gkd可以点击 通过炼妖壶安装的应用 内的跳过按钮，而不是通过炼妖壶去实现点击功能。
炼妖壶不仅仅是一个类似shizuku的api框架，而是一个可以安装应用的应用管理器，它通过安卓的[“工作资料”机制](https://source.android.com/docs/devices/admin/managed-profiles?hl=zh-cn)将应用安装在另一个用户中，其功能看起来就像一个“应用分身大师”一样（尽管底层机制完全不同）。这条issue想要请求支持的功能的实质，其实是让gkd可以识别和点击到处于安卓“工作资料”之中安装的应用。

**Comment by lisonge** [comment]
麻烦上传一下炼妖壶应用的快照看看

**Comment by PYUDNG** [comment]
这是安装在炼妖壶的taptap的快照，如果需要其他应用的如果我有我也可以再拍。
[1698817281251.zip](https://github.com/gkd-kit/gkd/files/13223865/1698817281251.zip)

**Comment by lisonge** [comment]
我的意思是 可以先在炼妖壶外 正常安装，让 gkd 识别到这个应用 安装 从而启用它的规则

**Comment by PYUDNG** [comment]
可以是可以，但是我在炼妖壶外安装后还是要回到炼妖壶里用这个应用的，安装在炼妖壶外的那个也用不到，可以安装后就卸载掉吗？当然，如果可以手动启用规则（或者自动识别到应用activity就直接启用）就更好了。

**Comment by lisonge** [comment]
但是如果你卸载了外面的 app，那么 gkd 就无法验证 activityId 的正确性，也就是认为这个 app 的 activityId 始终是 null

大多数需要 activityId 的规则都不会运行
