### ISSUE TITLE
[BUG] gkd开启服务后频繁报错

### ISSUE THREAD

**Issue by jnlpc123** [gkd-kit/gkd#664]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16278113

### BUG描述(文字/截图/视频)

![Screenshot_2024-07-18-13-25-47-400_com microsoft emmx](https://github.com/user-attachments/assets/a9ce270f-35d4-40fd-ad91-ced141fb8882)

### 期望行为(文字/截图/视频)

修复bug

### 实际行为(文字/截图/视频)

打开gkd服务后，会一直提示这个报错，同时通知栏显示gkd正在显示在其他应用上层

**Comment by lisonge** [comment]
你这个是内部的 lru 缓存在清除数据时由于 数据错乱 导致的报错

但是我不能复现，你有开启什么额外的功能吗？

**Comment by jnlpc123** [comment]
> 你这个是内部的 lru 缓存在清除数据时由于 数据错乱 导致的报错
> 
> 但是我不能复现，你有开启什么额外的功能吗？

我开启了shizuku的两个选项，但是关闭还是会有弹窗，卸载重装gkd后目前没再触发这个bug

**Comment by lisonge** [comment]
还能复现吗？

如果不能复现那就是特定设备上升级应用导致的进程缓存问题，只和设备有关系了

**Comment by Trrrrw** [comment]
之前也出现这个问题，清除数据几天后又出现了。[log-1721440942584.zip](https://github.com/user-attachments/files/16318477/log-1721440942584.zip)
