### ISSUE TITLE
[Feature] “规则类别” 页面支持修改已手动操作过的app规则

### ISSUE THREAD

**Issue by jiuqianyuan** [gkd-kit/gkd#665]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭
[log-1721318042327.zip](https://github.com/user-attachments/files/16285731/log-1721318042327.zip)

### BUG描述(文字/截图/视频)

手动关闭阿里云盘的通知提示后，再在订阅的“规则类别”上操作不再有变化。

### 期望行为(文字/截图/视频)

“规则类别”等所有手动操作能正常修改app规则状态。

### 实际行为(文字/截图/视频)

“规则类别”无法修改已手动操作过的app规则

**Comment by jiuqianyuan** [comment]
另:APP内修改过状态的规则，无法再受“规则类别”操纵。建议一并修正，否则“规则类别”成了只能操纵新导入规则的状态

**Comment by jiuqianyuan** [comment]
https://fastly.jsdelivr.net 缓存未及时更新

**Comment by jiuqianyuan** [comment]
![1721319160851](https://github.com/user-attachments/assets/105b9b25-0b07-4c7e-94af-5f4181996f78)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/575#issuecomment-2018027986

我看看加个操作重置所有的被捕获的分类的 config 的 enable

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
