### ISSUE TITLE
[BUG] 排除匹配生效的情况下依然触发规则

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#669]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16313156

### BUG描述(文字/截图/视频)

预期外的点击界面快照：https://i.gkd.li/i/16312880

规则：
```
  {
    key: 0,
    name: '开屏广告',
    order: OPEN_AD_ORDER,
    matchTime: 10000,
    actionMaximum: 2,
    resetMatch: 'app',
    actionCdKey: 0,
    actionMaximumKey: 0,
    rules: [
      {
        key: 0,
        fastQuery: true,
        excludeMatches:
          '[text*="搜索" || vid~="(?is).*search.*" || desc*="搜索"][visibleToUser=true]', // 防止在应用的搜索页面误触
        matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
      },
      {
        key: 1,
        excludeMatches:
          '[text*="搜索" || vid~="(?is).*search.*" || desc*="搜索"][visibleToUser=true]', // 防止在应用的搜索页面误触
        matches:
          '[childCount=0][visibleToUser=true][((text*="跳过" || text*="跳過" || text~="(?is).*skip.*") && text.length<10) || ((desc*="跳过" || desc*="跳過" || desc~="(?is).*skip.*") && desc.length<10) || id~="(?is).*tt_splash_skip_btn" || vid~="(?is).*skip.*" || (vid~="(?is).*count.*" && vid~="(?is).*down.*" && vid!~="(?is).*load.*" && vid!~="(?is).*time.*" && vid!~="(?is).*hour.*" && vid!~="(?is).*minute.*" && vid!~="(?is).*second.*" && vid!~="(?is).*add.*" && vid!~="(?is).*ead.*" && text!~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]")]',
      },
      {
        key: 2,
        fastQuery: true,
        matches:
          'FrameLayout > FrameLayout[childCount>2] > @View[clickable=true][visibleToUser=true] + TextView[text=null] <<n [id="android:id/content"]',
      },
    ],
    apps: [...appList.openAdBlackListAppIDs]
      .map((id) => ({ id, enable: false }))
      .concat(
        [...appList.openAdWhiteListAppIDs].map((id) => ({ id, enable: true })),
      ),
  },
```

https://github.com/user-attachments/assets/ea5b74c8-ecbb-4e9c-9643-6b5a1d708b39

### 期望行为(文字/截图/视频)

不执行规则

### 实际行为(文字/截图/视频)

执行规则

**Comment by AIsouler** [comment]
https://f.gkd.li/16313372
补充一下上述规则的key: 1的触发日志，可排除错误使用fastQuery的问题

**Comment by lisonge** [comment]
匹配是从事件节点开始的，如果你要匹配的目标在事件节点之外，那就匹配不到

两种解决方法

1. 设置 [matchRoot](https://gkd.li/api/interfaces/RawCommonProps#matchroot) 为 `true` ，所有选择器都从根节点查询
2. 或者将排除的选择器 `[text='abc']`  改成 `[text='abc'] <<n [parent=null]`

**Comment by AIsouler** [comment]
> 匹配是从事件节点开始的，如果你要匹配的目标在事件节点之外，那就匹配不到
> 
> 两种解决方法
> 
> 1. 设置 [matchRoot](https://gkd.li/api/interfaces/RawCommonProps#matchroot) 为 `true` ，所有选择器都从根节点查询
> 2. 或者将排除的选择器 `[text='abc']`  改成 `[text='abc'] <<n [parent=null]`

好的，感谢解答
构想过另一种解决全局规则在搜索页误触的方法：全局规则支持排除activityid，同时activityid支持包含匹配，搜索页的activityid基本都有```search```字符，这样就可排除搜索页，不知能否实现？

**Comment by lisonge** [comment]
不能
