### ISSUE TITLE
[BUG] 华为鸿蒙4.2的版本，会出现无障碍是打开的情况，但是主页面仍需要授权，且规则不生效的情况

### ISSUE THREAD

**Issue by makejuang** [gkd-kit/gkd#670]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16342791

### BUG描述(文字/截图/视频)

华为鸿蒙4.2 基本上打开无障碍后，半天左右的时间是可以用的，超过了这个时间，就会无效，打开gkd会显示需要授权无障碍，测试多个版本，几乎都是这样。

### 期望行为(文字/截图/视频)

无

### 实际行为(文字/截图/视频)

无

**Comment by lisonge** [comment]
根据日志，你的无障碍权限已经正常打开了，我不知道怎么解决这个问题

你可以先讲数据备份后卸载重装解决

**Comment by miozus** [comment]
测试：不用卸载，apk重新安装，又可以正常用了。

鸿蒙手机就是垃圾，一觉醒来，就被杀掉进程，无障碍点授权了，又骗gkd软件给个假授权：gkd 在通知栏孤苦伶仃的说自己没授权。
