### ISSUE TITLE
[BUG] 华为4.2.0.120系统GKD授权自己会关闭，并且跳转后实际显示开启状态

### ISSUE THREAD

**Issue by VV-luyan** [gkd-kit/gkd#675]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

[log-1721790921790.zip](https://github.com/user-attachments/files/16356606/log-1721790921790.zip)

### BUG描述(文字/截图/视频)

如标题，
![0f0542ace4e33d40db070a27f6761a6](https://github.com/user-attachments/assets/343659c5-c8b6-4f9c-9800-8e0b78de3973)

### 期望行为(文字/截图/视频)

授权正常开启

### 实际行为(文字/截图/视频)

未开启授权，无法出现跳过行为

**Comment by VV-luyan** [comment]
![Uploading 0075d09744a2946cdcf1810b03d7c9d.jpg…]()

**Comment by lisonge** [comment]
#670

**Comment by lisonge** [comment]
>  3.请 不要 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除

> 请 确保 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)

**Comment by VV-luyan** [comment]
哦哦，谢谢，更新后可能还存在这个，问题，我再观察一下
________________________________
发件人: 二刺螈 ***@***.***>
发送时间: 2024年7月24日 11:49
收件人: gkd-kit/gkd ***@***.***>
抄送: 鲁岩 ***@***.***>; Author ***@***.***>
主题: Re: [gkd-kit/gkd] [BUG] 华为4.2.0.120系统GKD授权自己会关闭，并且跳转后实际显示开启状态 (Issue #675)


3.请 不要 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除

请 确保 你的问题能在 releases<https://github.com/gkd-kit/gkd/releases/latest> 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)

―
