### ISSUE TITLE
[Feature] 使全局规则的应用配置支持工作空间应用

### ISSUE THREAD

**Issue by wanzh5** [gkd-kit/gkd#678]
### 一些验证

- [X] 1.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 2.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 3.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [x] 请 **确保** 你想要的功能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上没有找到 (如果不是请先更新到最新版本验证后再提交问题)

### 新功能描述

全局规则支持为特定应用启用或禁用。但是当应用在工作空间中时（即gkd无法检测到该应用），该应用的enable配置无论是true还是false都不起作用（即无论全局规则是白名单还是黑名单模式，都无法添加该应用）。因此希望gkd能增加对此类情况的支持。

**Comment by lisonge** [comment]
全局规则: 在自定义禁用-手动编辑-添加 `!appId`

应用规则: 在应用规则-未安装应用-打开右侧开关
