### ISSUE TITLE
[BUG] activityIds似乎没有生效

### ISSUE THREAD

**Issue by fansangg** [gkd-kit/gkd#687]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16486707

### BUG描述(文字/截图/视频)

规则如下

{
  name: '开屏广告',
  key: 2,
  fastQuery: true,
  actionMaximum: 1,
  matchTime: 5000,
  resetMatch: 'app',
  activityIds: [
    'tv.danmaku.bili.MainActivityV2'
  ],
  rules: [
    {
      matches: [
        '[text*="跳"][visibleToUser=true]'
      ]
    }
  ]
}

activityId是 tv.danmaku.bili.MainActivityV2
在搜索页 com.bilibili.search2.main.BiliMainSearchActivity
也触发了这个规则，点击了包含“跳”的item

### 期望行为(文字/截图/视频)

这个规则虽然不太严谨，但是在搜索页不应该触发

### 实际行为(文字/截图/视频)

从后台返回前台，activity是搜索页，触发了非规则限定的事件

**Comment by lisonge** [comment]
你好，使用这个版本复现后把日志发出来看看

[release.zip](https://github.com/user-attachments/files/16486921/release.zip)

**Comment by fansangg** [comment]
[log-1722762943055.zip](https://github.com/user-attachments/files/16486987/log-1722762943055.zip)

com.sec.android.app.launcher.Launcher/8 -> tv.danmaku.bili/null/0

**Comment by lisonge** [comment]
那就是没有获取到 activityId，此时会忽略匹配所有界面

**Comment by lisonge** [comment]
这种情况应该是 普通节点事件 先于 activityId 节点事件 出现导致的

安装 shizuku 应该可以解决这个问题

https://github.com/orgs/gkd-kit/discussions/594

**Comment by lisonge** [comment]
或者更改你的选择器 为 `[text*="跳"][visibleToUser=true][vid!="tag_name"]`

另外，如果首页有一个标题或者up主的文字里包含 `跳` 仍然会误触
