### ISSUE TITLE
[BUG] 部分情况下 action 的 click 不生效

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/gkd#688]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16486855

### BUG描述(文字/截图/视频)

在快照 https://i.gkd.li/i/16486847 中
当使用规则 `[vid="ms_skipView"]` 企图点击跳过开屏广告时候，规则不生效。

通过执行选择器功能执行则生效

![image](https://github.com/user-attachments/assets/9066c045-d4f7-4e6c-b07a-3eaa19ee8e9d)

看到执行的是 clickCenter

而规则中是默认 click。而并且当 `clickNode` 事件没有被应用接收时, GKD不是会自动使用 `clickCenter` 吗

### 期望行为(文字/截图/视频)

点击跳过

### 实际行为(文字/截图/视频)

无法点击

**Comment by lisonge** [comment]
因为 `clickNode` 为 true 是系统告知的，应用可不一定使用这个事件点击

**Comment by lisonge** [comment]
<https://github.com/gkd-kit/docs/blob/1c45e9b894aebfd08b8aa15ef8ff31936670b955/api/src/index.ts#L456>

**Comment by aoguai** [comment]
如果 手动设置 `clickCenter`，如果目标节点是 clickable 的，是否还会点击成功。还是说 clickCenter 只针对不是 clickable 的节点生效。

**Comment by lisonge** [comment]
不知道，`clickCenter`/`clickNode` 都是一个事件，目标应用想接收就有用，不想接收就没有

**Comment by aoguai** [comment]
好的谢谢😢
