### ISSUE TITLE
【bug？】设置了后台隐藏，切后台依旧存在于应用列表，并且常驻通知栏（希望取消）

### ISSUE THREAD

**Issue by yqh2619** [gkd-kit/gkd#69]
个人机型：华为安卓10.1，非11

**Comment by lisonge** [comment]
> 设置了后台隐藏，切后台依旧存在于应用列表

https://github.com/gkd-kit/gkd/issues/56#issuecomment-1731846396

---

> 常驻通知栏（希望取消）

已有计划支持
