### ISSUE TITLE
[BUG] 部分弹窗页面不能通过返回/点击弹窗以外的位置关闭

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#696]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16540833

### BUG描述(文字/截图/视频)

以下页面不能通过```返回/点击弹窗以外的位置```关闭

![1723109693625](https://github.com/user-attachments/assets/2abce100-f338-46aa-8a2b-bd7e2c81e3a1)

### 期望行为(文字/截图/视频)

能通过```返回/点击弹窗以外的位置```关闭

### 实际行为(文字/截图/视频)

不能通过```返回/点击弹窗以外的位置```关闭

**Comment by lisonge** [comment]
可点击空白区域关闭的的条件是

- 输入框空字符串
- 单纯的提示
