### ISSUE TITLE
触发提示长时间未关闭

### ISSUE THREAD

**Issue by xfljy** [gkd-kit/gkd#697]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16568018

### BUG描述(文字/截图/视频)

![Screenshot_20240810_090712](https://github.com/user-attachments/assets/ffff406a-8f8b-4c80-aa2e-d6585cb30073)
关闭系统提示后，提示不会关闭

### 期望行为(文字/截图/视频)

能正常关闭

### 实际行为(文字/截图/视频)

如bug描述

**Comment by lisonge** [comment]
麻烦给一个复现视频，从截图看不出来

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/16568237/release.zip)

试试这个版本，复现后把日志发出来一下

**Comment by xfljy** [comment]
好的👌

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/698
