### ISSUE TITLE
[Bug] 短时间内多次触发后，悬浮窗toast无法消失

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/gkd#698]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16569326

### BUG描述(文字/截图/视频)

https://github.com/user-attachments/assets/4c435592-1dd6-4eea-b770-5069c8eef459

如视频

### 期望行为(文字/截图/视频)

悬浮窗toast在短时间内多次触发后自动消失

### 实际行为(文字/截图/视频)

如上方视频

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/16569618/release.zip)

你好，试试这个版本呢？

**Comment by adproqwq** [comment]
> [release.zip](https://github.com/user-attachments/files/16569618/release.zip)
> 
> 你好，试试这个版本呢？

这是actions里的版本吗？是的话上方就是使用该版本导致的。
如果是已经修改过代码进行修复的话，问题可能已经消失

**Comment by lisonge** [comment]
> 这是actions里的版本吗？

本地修改打包的

**Comment by lisonge** [comment]
不好意思我没看懂你的回答

我只想知道在 https://github.com/gkd-kit/gkd/issues/698#issuecomment-2281583263 发的本地打包版本 **是否** 能解决这个问题

**Comment by adproqwq** [comment]
> 不好意思我没看懂你的回答
> 
> 我只想知道在 https://github.com/gkd-kit/gkd/issues/698#issuecomment-2281583263 发的本地打包版本 **是否** 能解决这个问题
> 
> 

意思就是bug已经无法复现

**Comment by AIsouler** [comment]
beta11版本又出现了这个问题
日志：https://f.gkd.li/16613347


https://github.com/user-attachments/assets/61ecc2d0-d35e-4f49-835b-2c8527826008

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/16625899/release.zip)
@AIsouler 试试这个版本呢？

**Comment by AIsouler** [comment]
> [release.zip](https://github.com/user-attachments/files/16625899/release.zip) @AIsouler 试试这个版本呢？

写了个规则连续触发了1000多次，没出现这个问题，应该是解决了
