### ISSUE TITLE
能否为checkbox节点增加Checked属性？

### ISSUE THREAD

**Issue by xuanqb** [gkd-kit/gkd#7]
感谢作者开发的工具
主要是因为豆瓣标记看过的时候，不想同步到动态，目前这个软件没有Checked属性会一直触发点击，所以能否为checkbox 增加Checked属性
<img width="1875" alt="image" src="https://github.com/gkd-kit/gkd/assets/25526210/521a7a3b-b9d2-4051-9eaf-e94a9ed33172">
不太懂安卓开发，看文档有这个属性不知道能不能用上
https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#isChecked()

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/download/v1.0.1/app-release-v1.0.1.apk
