### ISSUE TITLE
[BUG] 显示应用不全

### ISSUE THREAD

**Issue by Matrix-bak** [gkd-kit/gkd#701]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/user-attachments/files/16621072/file.zip

### BUG描述(文字/截图/视频)

订阅支持的应用，一部分应用已安装，但没有显示，如淘宝京东
![Screenshot_20240815_111946](https://github.com/user-attachments/assets/f1e1ae86-2039-4338-93d1-9788d09f0139)
![Screenshot_20240815_111714](https://github.com/user-attachments/assets/88e32774-6ff9-40ab-b06a-73e24a4cf3f4)
![Screenshot_20240815_111710](https://github.com/user-attachments/assets/174c643d-90cc-4c76-8d9e-8d7d22771f59)
![Screenshot_20240815_111705](https://github.com/user-attachments/assets/4b88d978-5761-434c-a766-880e3357daa0)

### 期望行为(文字/截图/视频)

显示所有已安装且有对应规则的APP

### 实际行为(文字/截图/视频)

未显示部分APP已安装且有对应规则的APP

**Comment by lisonge** [comment]
你想表达什么，请问哪个应用没有显示？

**Comment by lisonge** [comment]
> 请 确保 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
