### ISSUE TITLE
[BUG] beta9.10.11版本弹出报错Toast

### ISSUE THREAD

**Issue by Supremesir** [gkd-kit/gkd#704]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16631765

导出了日志，但是不知道究竟有没有包含有用信息

### BUG描述(文字/截图/视频)

![396784b83064c961a26be418fb33c84](https://github.com/user-attachments/assets/44b3ca7f-672f-49bf-a8de-1756d6cac2e7)
如图所示，在不知道发生了什么场景的情况下，会弹出如图所示的报错Toast。
频率不高，可能一天见到一两次。
至于我是怎么确认他是gkd弹出的：（如果判断错了请指正并关闭issue）
1. 每次弹出的时候，Android有个弹窗“gkd正在其他应用上层显示”
2. gkd源码里有搜到activity_log的字段

### 期望行为(文字/截图/视频)

期望不会弹出报错弹窗。

### 实际行为(文字/截图/视频)

实际行为：偶现在其他应用界面时，gkd也弹出了报错弹窗。
大概beta9.10.11三个版本都有遇到过，不太确定更前面的版本有没有

**Comment by lisonge** [comment]
你的日志被你清空了，需要重新复现后上传
