### ISSUE TITLE
[BUG] 快速连续返回两级页面时动画闪烁

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#705]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16632541

### BUG描述(文字/截图/视频)

还有一个问题，点进二级页面时如果短时间内再点击进入下一级页面会不生效，需要等待一段时间

https://github.com/user-attachments/assets/834b11ab-59da-40be-a52d-4223f1071c75

闪烁时的画面

![image](https://github.com/user-attachments/assets/db2fd0c7-d402-4143-9e4f-d54f50260b56)

### 期望行为(文字/截图/视频)

动画流畅无闪烁

### 实际行为(文字/截图/视频)

动画闪烁

**Comment by AIsouler** [comment]
补一个订阅jie'mian界面的复现

https://github.com/user-attachments/assets/a865c945-88ce-4bb3-83b8-f06f7b6d66de

**Comment by lisonge** [comment]
有全局防止连续点击，点不了很正常，微信也有类似的逻辑

**Comment by lisonge** [comment]
> 动画流畅无闪烁

是 android compose 导航库自己渲染的问题

我后续会加一个和上面 `防止连续点击` 类似的 `防止连续返回` 的限制，只要避免这种情况出现就行了

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/16637799/release.zip)

试试这个本地编译的版本呢？应该是没你说的这个问题了

**Comment by AIsouler** [comment]
> [release.zip](https://github.com/user-attachments/files/16637799/release.zip)
> 
> 试试这个本地编译的版本呢？应该是没你说的这个问题了

没有问题了

**Comment by zhaozk123456** [comment]
> > [发布版本](https://github.com/user-attachments/files/16637799/release.zip)
> > 试试这个本地编译的版本吧？应该是没你说的这个问题了
> 
>大哥 我为啥用驾考宝典出现内置禁用啊老铁 我不知道为啥 等下我给你截图

**Comment by lisonge** [comment]
别问我，我不知道

**Comment by AIsouler** [comment]
@zhaozk123456 内置禁用有两种情况：
一种是维护者手动在全局规则的```apps```字段里添加包名设置```enable: false```，因为有些软件是不需要全局规则的，比如微信没有开屏广告就不需要开启全局规则的开屏广告，
一种是应用规则里已经有全局规则的某一类规则，则对此应用禁用对应全局规则
