### ISSUE TITLE
[Feature] 关于耗电，和占用

### ISSUE THREAD

**Issue by xzayp1324** [gkd-kit/gkd#706]
### 一些验证

- [X] 1.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 2.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 3.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你想要的功能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上没有找到 (如果不是请先更新到最新版本验证后再提交问题)

### 新功能描述

看到有人说过耗电问题了，但还是想吐槽一下，占用和耗电都比李跳跳多，跳跳一天也才10毫安左右，具体原理我也不懂，可以再狠狠的优化一下吗，直接订阅规则这个确实比李跳跳方便`

![Screenshot_20240816_063314](https://github.com/user-attachments/assets/8e5c5e0e-b0da-4ca3-844f-69ea6a4901f6)
![Screenshot_20240816_112226](https://github.com/user-attachments/assets/461cc4a0-4d9f-45bf-b111-2c0c840dc431)

**Comment by lisonge** [comment]
卸载 gkd

**Comment by xzayp1324** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by lisonge** [comment]
你开太多规则了，你开一堆规则又想要不耗电

是不是有点异想天开

**Comment by xzayp1324** [comment]
> 你开了太多规则了，你开了一堆规则又想要不耗电
> 
> 是不是有点异想天开

不是很懂跳跳为什么这么小，我也有倒入上万条规则

**Comment by lisonge** [comment]
因为你导入是全是一堆空的，无用的，重复的规则

这些规则全是营销号批量复制粘贴出来的
