### ISSUE TITLE
[Feature] 有想法搞个类似于之前轻启动那种创建规则的功能吗

### ISSUE THREAD

**Issue by 1592363624** [gkd-kit/gkd#708]
### 一些验证

- [X] 1.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 2.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 3.GKD 默认不提供任何规则, 你可以查看 [GKD 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你想要的功能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上没有找到 (如果不是请先更新到最新版本验证后再提交问题)

### 新功能描述

大致效果是  点击之后直接选择当前屏幕软件的某个按钮,之后遇到这个按钮就自动点击

**Comment by lisonge** [comment]
没有

**Comment by lisonge** [comment]
这东西你完全可以自己去写一个手机端网页解析快照文件然后生成规则，期待你的开源

**Comment by adproqwq** [comment]
> 这东西你完全可以自己去写一个手机端网页解析快照文件然后生成规则，期待你的开源

选择器的npm包有文档吗

**Comment by lisonge** [comment]
没有，同时已经发布的不对外的 npm 包，不保证任何 api 的稳定性

**Comment by adproqwq** [comment]
> 没有，同时已经发布的不对外的 npm 包，不保证任何 api 的稳定性

所以就是说自己实现快照审查工具最稳定的方法就是自己再手搓一个选择器

**Comment by lisonge** [comment]
意思是你想用就用，但是大概率升级版本后某些属性/方法就没了，这就叫 `不保证任何 api 的稳定性`

同时也不要反馈任何除了解析/查询错误的相关问题，因为暴露哪些 api 都是看 主应用 需要

它并不是一个面向开发者的库，也不遵循任何的版本规范

---

面向开发者的是这类比如

- <https://github.com/gkd-kit/tools>
- <https://github.com/lisonge/kotlin-json5>

它具有 api 稳定性，不会随意变更已经暴露的 api(就算变更也会做兼容旧代码)，版本号也尽量遵循 npm 推荐的规范

**Comment by adproqwq** [comment]
了解
