### ISSUE TITLE
[BUG] 微信小程序的广告规则不起作用

### ISSUE THREAD

**Issue by zhl111** [gkd-kit/gkd#709]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16633703

### BUG描述(文字/截图/视频)

![SmartSelect_20240816_142421_WeChat](https://github.com/user-attachments/assets/4e4aeffc-8b59-42a5-9437-c978132bfbd4)

### 期望行为(文字/截图/视频)

解决这个广告

### 实际行为(文字/截图/视频)

我试了多次仍无法解决这个问题，规则没有起作用。我只能手动点击取消

**Comment by luyanci** [comment]
https://github.com/AIsouler/GKD_subscription

可能是第三方规则问题，记得到那边提

**Comment by lisonge** [comment]
注意 gkd 没有规则，你应该去找提供规则的人反馈

**Comment by luyanci** [comment]
> 我刚看到说微信app有三条内置禁用，这也是与第三方订阅有关吗？

一般来说都是
