### ISSUE TITLE
[Feature] 允许将高级设置入口添加到主页

### ISSUE THREAD

**Issue by QieSen** [gkd-kit/gkd#712]
### 新功能描述

希望在高级设置页面中增加一个开关【**将高级设置添加到主页**】，开启后主页新增高级设置入口，可以直接进入。

对于订阅规则不能覆盖的应用，经常需要抓取快照进行分析。目前打开HTTP服务的步骤较为繁琐：`主页-设置-下滑到底-高级设置-点击HTTP服务开关`，如果需要访问快照记录入口或者打开界面记录，则需要更多步骤。

并且，当前HTTP服务没有快速关闭的方式，点击常驻通知只能够进入GKD主页，使用完毕需要再次进入高级设置。

**Comment by panhongtao07** [comment]
确实，调试操作太麻烦了

**Comment by lisonge** [comment]
可通过点击通知栏对应通知直接打开高级设置页面以及快照记录页面

https://github.com/gkd-kit/gkd/releases
