### ISSUE TITLE
[BUG] 无法截取快照，需重复操作很多次

### ISSUE THREAD

**Issue by Hong22286** [gkd-kit/gkd#713]
### 日志文件

[log-1724688131447.zip](https://github.com/user-attachments/files/16751046/log-1724688131447.zip)

### BUG描述(文字/截图/视频)

https://github.com/user-attachments/assets/79cc45a7-de6d-4d6a-ad76-d5228861d339

### 期望行为(文字/截图/视频)

视频看到最后，有提示快照成功提示

### 实际行为(文字/截图/视频)

视频看到最后，有提示快照成功提示。

**Comment by Hong22286** [comment]
悬浮窗点击一下就行。下拉状态栏快照还是无效。
音量快照还能恢复吗？

**Comment by lisonge** [comment]
你可以在 <https://gkd.li/guide/snapshot#capture-snapshot> 查看所有方式

**Comment by lisonge** [comment]
> 下拉状态栏快照还是无效。

这个到底是什么无效？你等待 3 s后无法抓取吗？

**Comment by Hong22286** [comment]
> > 下拉状态栏快照还是无效。
> 
> 这个到底是什么无效？ 你等待 3 s后无法抓取吗？

等3秒无反应

**Comment by lisonge** [comment]
那你点击抓取图标后有自动从 控制面板 返回 目标应用 界面吗？

另外可以把你执行操作后的日志重新发出来看看

**Comment by Hong22286** [comment]
li.songe.gkd.SnapshotActionService
这个好像需要root，有些笨有些复杂只能放弃🙃
音量快照很好用，功能希望保留让我们自由开启关闭。

**Comment by lisonge** [comment]
麻烦先回答上面的问题

**Comment by Hong22286** [comment]
> 那你点击抓取图标后有自动从 控制面板 返回 目标应用 界面吗？
> 
> 另外可以把你执行操作后的日志重新发出来看看

[log-1724691426129.zip](https://github.com/user-attachments/files/16751472/log-1724691426129.zip)
有返回应用界面，新的日志

**Comment by lisonge** [comment]
我看日志从你点击到抓取成功间隔也才 400ms 啊，这属于正常的时间

![image](https://github.com/user-attachments/assets/053c0f6f-bf29-45ee-b34c-5014cb6b918c)

---

我估计是已经截取成功了，但是没有后台提示成功了

你这样测试，点击按钮后静待 3s，然后去快照记录，看看快照记录数量有没有+1就知道截取是否成功了

**Comment by Hong22286** [comment]
> 我看日志从你点击到抓取成功间隔也才 400ms 啊，这属于正常的时间
> 
> ![image](https://private-user-images.githubusercontent.com/38517192/361514162-053c0f6f-bf29-45ee-b34c-5014cb6b918c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTI5MTcsIm5iZiI6MTcyNDY5MjYxNywicGF0aCI6Ii8zODUxNzE5Mi8zNjE1MTQxNjItMDUzYzBmNmYtYmYyOS00NWVlLWIzNGMtNTAxNGNiNmI5MThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE3MTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxN2YyODYzYTNmZTE0ZWRmNWY2MDNjMmFlZmQ0NjI5YjFhYTZjNWZkMjBhMWI0NzZiYWUxMGY3NjkxNzAxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SzgHx1n0DvHKJPCBrLf-KoFhqRACQ0LOoYQ-kMcD1yc)
> 
> 我估计是已经截取成功了，但是没有后台提示成功了
> 
> 你这样测试，点击按钮后静待 3s，然后去快照记录，看看快照记录数量有没有+1就知道截取是否成功了


https://github.com/user-attachments/assets/dff5ba07-eb02-4308-89f3-0107eec2f1ab

没有成功，就在快照保存界面操作，成功会新增一条记录

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/16751730/release.zip)

使用这个我本地编译的版本复现一下看看呢，然后把日志发出来

**Comment by Hong22286** [comment]
好的，那早些休息吧，明早复现了立马发

**Comment by Hong22286** [comment]
> [发布.zip](https://github.com/user-attachments/files/16751730/release.zip)
> 
> 使用这个我本地编译的版本复现一下看看呢，然后把日志发出来

[log-1724715147156.zip](https://github.com/user-attachments/files/16754676/log-1724715147156.zip)
这个版本可以使用，点击一下立马响应，附日志
