### ISSUE TITLE
[BUG] 常驻通知栏的图标过小

### ISSUE THREAD

**Issue by mengwangjingan** [gkd-kit/gkd#721]
### 日志文件

[Uploading log-1725092369359.zip…]()

### BUG描述(文字/截图/视频)

三星s24u oneui6.1
![Uploading Screenshot_20240831_161742_One UI Home.jpg…]()
 安卓14 通知栏图标大小不太正常，不太协调

### 期望行为(文字/截图/视频)

希望通知栏图标大小正常，和老版本类似

### 实际行为(文字/截图/视频)

通知栏图标大小不正常，如图中所示，gkd通知的图标和另一条其他app通知的图标，大小明显不统一

**Comment by lisonge** [comment]
图片看不到，请重新上传

**Comment by mengwangjingan** [comment]
![Screenshot_20240831_161742_One UI Home](https://github.com/user-attachments/assets/73c3e724-1cfc-45eb-99d5-2afd085a3a88)
这是日志文件
https://f.gkd.li/16823991

**Comment by lisonge** [comment]
好的，感谢反馈，后续修复

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/16824284/release.zip)

试试这个版本呢？

**Comment by mengwangjingan** [comment]
![Screenshot_20240831_183846_GKD](https://github.com/user-attachments/assets/e01dea87-8bdc-448b-bd1c-2ff36abb8b6c)
正常了，感谢

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
