### ISSUE TITLE
[Feature] 修改已添加订阅的链接

### ISSUE THREAD

**Issue by fxzxmicah** [gkd-kit/gkd#727]
### 新功能描述

增加修改已添加订阅的链接的功能，方便在某一个订阅更换发布链接以后可以持续更新而不需要重新导入重新设置。

**Comment by violetnight** [comment]
支持，现在连接改了得重新设置订阅太麻烦了

**Comment by pheotry** [comment]
确实，有时候用的加速方案失效了，换订阅地址得重新设置太麻烦了

**Comment by panhongtao07** [comment]
支持

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
