### ISSUE TITLE
[BUG] 安装最近的两个正式版，手机待机时会断电式的关机。

### ISSUE THREAD

**Issue by zxpp01** [gkd-kit/gkd#728]
### 日志文件

https://github.com/user-attachments/files/16842280/file.zip

你好，如题。
我手机型号：红米k20p,10.4.1版本，没root

### BUG描述(文字/截图/视频)

https://github.com/user-attachments/files/16842280/file.zip

你好，如题。
我手机型号：红米k20p,10.4.1版本，没root

### 期望行为(文字/截图/视频)

https://github.com/user-attachments/files/16842280/file.zip

你好，如题。
我手机型号：红米k20p,10.4.1版本，没root

### 实际行为(文字/截图/视频)

https://github.com/user-attachments/files/16842280/file.zip

你好，如题。
我手机型号：红米k20p,10.4.1版本，没root

**Comment by lisonge** [comment]
暂时卸载 gkd 后能否能复现此问题？

没见过这种会导致关机的问题，大概率是你自己的手机问题

**Comment by zxpp01** [comment]
卸载或关闭服务就不会关机。现在装了gkd-v1.8.0-beta.13.apk

昨天我也以为是手机问题，我还去找了修手机的。后来想想，也就是前天更新过这个软件，所以才测试出是这个软件的问题。

测试方法：关闭这个软件的服务，更换最近两个正式版。现在装的测试版。

还发现耗电异常,查看的不是你这个软件.
只是显示其他

感谢你的回复。

Donny lau

Mobile & WhatsApp: 66900019

**Comment by lisonge** [comment]
> 卸载或关闭服务就不会关机

使用其他无障碍类型的软件是否会触发关机？

**Comment by zxpp01** [comment]
没有使用其他无障碍类型的软件，手机里只装了这一个去广告的。

Donny lau

Mobile & WhatsApp: 66900019

**Comment by lisonge** [comment]
那你暂时卸载 gkd 后，试一下其他无障碍软件，看看会不会关机

你这个有可能是系统无障碍出现问题了

---

还有你上面给的日志文件是 `v1.7.3` 的并不是最新的 `v1.8.0`， 需要给出 `v1.8.0` 的复现日志

**Comment by zxpp01** [comment]
我来反馈一下，现在使用beta版本没有出现关机.感谢

Donny lau

Mobile & WhatsApp: 66900019
