### ISSUE TITLE
[BUG] 荣耀magicOS8.0需要授权两次才能成功

### ISSUE THREAD

**Issue by cloudpanl** [gkd-kit/gkd#729]
### 日志文件

[log-1725344563991.zip](https://github.com/user-attachments/files/16844415/log-1725344563991.zip)

### BUG描述(文字/截图/视频)

每次从“隐私时刻”出来，对GKD重新授权无障碍的时候，都需要授权两次才能生效，第一次无障碍授权显示是成功的，但在GKD还是显示授权按钮，并且软件的自动跳过广告也没生效，需要再次点击授权按钮，第二次授权后才能成功，每次都是这样，以前授权一次就可以的，最近两个月才是这种情况，之前用的是1.7.3版本，上周更新了1.8.0版本也一样，操作系统是荣耀magicOS8.0

### 期望行为(文字/截图/视频)

期望可以像以前一样一次授权成功，毕竟“隐私时刻”这个功能还是经常用的，每次出来都需要给GKD授权两次挺烦人的

### 实际行为(文字/截图/视频)

目前的操作是这样：GKD里点击“授权”，无障碍中开启一次，弹框点击“确定”，回到GKD发现授权没成功，再次点击“授权”，无障碍中需要先点击关闭，弹框点击“确定”，再点击无障碍中的开启，弹框再点击“确定”，这样才能授权成功，需要授权两次很烦人，操作下来需要点击不少东西

**Comment by lisonge** [comment]
这跟 gkd 没关系，是你的系统自己的问题， gkd 只负责显示服务的状态是否授权

**Comment by cloudpanl** [comment]
但是第一次授权的时候，系统无障碍中显示GKD已经开启，GKD中检测到系统没有开启，仍需要点击授权去开启

**Comment by lisonge** [comment]
如果检测到授权，gkd 是可以正常运行并执行点击的

但是没有检测到就是没有检测到，这要上哪给你要授权，我也不知道
