### ISSUE TITLE
问几个小白问题

### ISSUE THREAD

**Issue by lelexcv** [gkd-kit/gkd#73]
1.http服务 2.自动清除内存订阅 具体什么用，需要打开么，谢谢

**Comment by lisonge** [comment]
> http服务

向外提供接口，与网页工具 https://github.com/gkd-kit/inspect 配合使用

---

> 自动清除内存订阅

上面的网页工具可以给APP添加一个叫 `内存订阅` 的本地订阅，`自动清除内存订阅` 就是在这个 HTTP 服务关闭的时候清除这个 `内存订阅`

---

> 需要打开么

如果你需要快速测试订阅是否生效，那就打开使用，如果不需要，那就不用打开
