### ISSUE TITLE
[BUG] 小米手机在应用内安装新应用（更新或者安装其他apk）会直接跳过安装导致无法安装应用

### ISSUE THREAD

**Issue by ok406lhq** [gkd-kit/gkd#731]
### 日志文件

日志：
[log-1725603307131.zip](https://github.com/user-attachments/files/16903667/log-1725603307131.zip)
视频：
https://github.com/user-attachments/assets/b631a9c4-668a-4c3d-b19a-ce8c1234c32d

### BUG描述(文字/截图/视频)

问题描述：
应用内安装其他应用后跳转Android系统的应用安装系统，直接被拦截，无法安装新应用
出现设备：
小米11pro，HyperOS 1.0.3.0.UKACNXM

### 期望行为(文字/截图/视频)

别拦截系统的安装请求啊

### 实际行为(文字/截图/视频)

别拦截系统的安装请求啊

**Comment by lisonge** [comment]
这是你的手机设置问题，与 gkd 无关

**Comment by lisonge** [comment]
![image](https://github.com/user-attachments/assets/cd42e507-abc5-46e5-95cc-f850be38b85a)

![image](https://github.com/user-attachments/assets/349e9d0c-680d-4fec-a995-8ec2d6a85626)

**Comment by ok406lhq** [comment]
了解 感谢
