### ISSUE TITLE
[BUG] `preKeys` 非空时 `actionCd` 等限制条件失效

### ISSUE THREAD

**Issue by panhongtao07** [gkd-kit/gkd#733]
### 日志文件

[log-1725885178425.zip](https://github.com/user-attachments/files/16930504/log-1725885178425.zip)

### BUG描述(文字/截图/视频)

规则有`preKeys`时，状态机不受其他设置影响，导致`actionCd`等限制无效。
#### Bug 范围
涉及代码：`ResolvedRule.status`, `GkdAbService.newQueryTask`, `ResolvedRule.checkDelay`
完全失效的设置：`actionCd`, `matchDelay`, `matchTime`
部分失效的设置：`actionDelay`
#### 示例
如下规则的`key=1`的规则的`actionCd`实际是无效的，`key=2`的`actionDelay`也只在第一次query时有效，只要`key=0`规则再次触发，1号规则即可无视触发间隔立刻触发，2号进入延迟状态，但延迟期间只要其它规则触发了`newQueryTask`，2号即可无视延迟触发（因为本次已设置`actionDelayTriggerTime`和`actionDelayJob`，而有`preKeys`的规则状态机不会检查此两项是否满足条件）：
```json5
{ key: 0 },
{
    preKeys: 0, key: 1,
    actionCd: 10000000,
},
{
    preKeys: 0, key: 2,
    actionDelay: 500,
},
```

### 期望行为(文字/截图/视频)

目标规则必须同时满足前置键要求和其他限制时，才能触发。
```kt
if (preRules.isNotEmpty()) { // 需要提前点击某个规则 
    if (!preRules.any { it === lastTriggerRule }) { 
        return RuleStatus.Status2
    } 
}
```
需注意的是，延迟后那次触发的query可能应该跳过本规则preRules的检查，因为根据status的顺序，初次触发定时时已经确保满足了前置条件。这可能应该通过调用newQueryTask时额外的上下文执行：
```kt
if (rule.checkDelay() && rule.actionDelayJob == null) {
    rule.actionDelayJob = scope.launch(actionThread) {
        delay(rule.actionDelay)
        rule.actionDelayJob = null
        rule.isDelayAction = true
        newQueryTask()
        rule.isDelayAction = false
    }
    continue
}
```
另外，应当注意上述类似的延迟任务中，可能先进行query再清空`DelayJob`更不易出错。

### 实际行为(文字/截图/视频)

当`preKeys`非空时，只检查`preKeys`状态，若满足则可触发，否则不可。由于规则基本只检查status来判断能否执行，相关设置基本失效：
https://github.com/gkd-kit/gkd/blob/9ee1bbb429d4d993f756fd618215386d02e741eb/app/src/main/kotlin/li/songe/gkd/data/ResolvedRule.kt#L208-L224
ActionDelay在状态机外有额外检查，但这也会被第二次query时绕过：
https://github.com/gkd-kit/gkd/blob/ea48edc5ac0ad8fd8d74e4807657f8143a980383/app/src/main/kotlin/li/songe/gkd/service/GkdAbService.kt#L222-L229
第二次时，由于属性已设置，检查通过。
https://github.com/gkd-kit/gkd/blob/ea48edc5ac0ad8fd8d74e4807657f8143a980383/app/src/main/kotlin/li/songe/gkd/data/ResolvedRule.kt#L106-L112

**Comment by lisonge** [comment]
首先感谢你提出这个问题

> 目标规则必须同时满足前置键要求和其他限制时，才能触发。

这个应该是没问题的，应该是原始代码有错误，不应该直接返回 `StatusOk`

---

> 延迟后那次触发的query可能应该跳过本规则preRules的检查

中间可能触发其他规则导致 `lastTriggerRule` 发生改变，`preRules` 的检查仍然是有必要的

**Comment by lisonge** [comment]
> 只是以防万一避免设置两个任务？

是的

---
> 不过时间如果不够准的话岂不是没有上下文判断已经执行过delay了？

没懂不够准的意思，可以说一下实际场景

**Comment by panhongtao07** [comment]
稍等回复你的问题。
我一开始以为delay的作用是在那么久之后只重新检查那一个规则，这样性能开销比较小。看完代码发现是重新检查所有规则，要是规则多了开销会不会显著提升呢？
要不要考虑未来尝试一种重构，把newQueryTask拆成这种结构：
```kt
fun newQueryTask(byEvent: Boolean = false, byForced: Boolean = false) {
    // init works
    // update works
    for (rule in (activityRule.currentRules)) {
         checkRuleStatus(rule)
         checkActionAvailable(rule)
         performRuleAction(rule)
    }
}
```

**Comment by panhongtao07** [comment]
> 不过时间如果不够准的话岂不是没有上下文判断已经执行过delay了？
比如actionDelayJob这部分，`checkDelay`刚刚才设置`actionDelayTriggerTime`，就立刻安排了job，延迟也没有略微加长，假如在+delay时间后立刻唤醒触发job，进行的newQueryTask中岂不是有`actionDelayTriggerTime + actionDelay == t`，卡在status失败(>t)的边界值么。
根据我的经验延迟任务还是挺容易有点小波动的，有时候系统时间可能是舍入，就有点担心。

**Comment by lisonge** [comment]
> 看完代码发现是重新检查所有规则

现在改成 1 个了，<https://github.com/gkd-kit/gkd/commit/f859fa1d1523cdf7699f8252ceebaa53938449f5>

---

> 有时候系统时间可能是舍入，就有点担心

多数情况下由于其他规则本身会阻塞，事件节点的获取也会阻塞，以及其他 io 相关的操作都会阻塞

你说的这种情况基本不存在，目前暂不考虑

**Comment by panhongtao07** [comment]
> 现在改成 1 个了，[f859fa1](https://github.com/gkd-kit/gkd/commit/f859fa1d1523cdf7699f8252ceebaa53938449f5)

nb！

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
