### ISSUE TITLE
[BUG] 【已自行解决】ADB授权失败

### ISSUE THREAD

**Issue by chenjinhui2002** [gkd-kit/gkd#742]
### 日志文件

[log-1728003497808.zip](https://github.com/user-attachments/files/17251819/log-1728003497808.zip)

### BUG描述(文字/截图/视频)

![image](https://github.com/user-attachments/assets/33b42fa3-01fe-47b8-b493-27a852850ea2)
无法使用ADB手动授权，提示“Exception occurred while executing 'grant'”

### 期望行为(文字/截图/视频)

能够正常使用ADB进行高级授权

### 实际行为(文字/截图/视频)

尝试无障碍授权过程时，将手动授权命令复制并粘贴输入 powershell 后，提示上述报错，无法完成高级授权过程。GKD版本名称1.9.0-beta.1，版本代码43；系统版本MIUI14.0.7。

**Comment by chenjinhui2002** [comment]
未在开发者设置中打开“USB调试（安全设置）”导致

**Comment by zxpp01** [comment]
你好，
手机已安装GKD1.11.6,
Hyper 2.0.220.0

开发者模式里打开了，，，USB调试（安全设置），USB调试，USB 安装。

我在Tango里打开CMD. 贴上运行，显示：
mondrian:/ $ adb shell sh /storage/emulated/0/Android/data/li.songe.gkd/files/sh/start.sh
/system/bin/sh: adb: inaccessible or not found

请问知道要怎么做吗？

**Comment by mira-yy** [comment]
> 你好， 手机已安装GKD1.11.6, Hyper 2.0.220.0
> 
> 开发者模式里打开了，，，USB调试（安全设置），USB调试，USB 安装。
> 
> 我在Tango里打开CMD. 贴上运行，显示： mondrian:/ $ adb shell sh /storage/emulated/0/Android/data/li.songe.gkd/files/sh/start.sh /system/bin/sh: adb: inaccessible or not found
> 
> 请问知道要怎么做吗？

这个貌似是因为没有root权限，无法访问/storage/emulated/0/Android/data/目录导致的，这个要开放root权限，我还没有找到方法开启root的方法
