### ISSUE TITLE
[Feature] action 能不能添加向上滑动的操作，刷短剧的广告，有向上滑动的操作

### ISSUE THREAD

**Issue by Wirili** [gkd-kit/gkd#743]
### 新功能描述

action 能不能添加向上滑动的操作，刷短剧的广告，有向上滑动的操作

**Comment by xieyan110** [comment]
@Wirili 

我帮你编译了一个支持 上滑 的功能。
https://github.com/xieyan110/gkd/releases/tag/v2.33，还顺便写了一个短剧的上滑
