### ISSUE TITLE
[BUG] 安装新版本报错 Couldn't find meta-data for provider with authority li.songe.gkd.utilcode.fileprovider

### ISSUE THREAD

**Issue by AngryChocobo** [gkd-kit/gkd#746]
### 日志文件

[log-1728446520694(1).zip](https://github.com/user-attachments/files/17301828/log-1728446520694.1.zip)

### BUG描述(文字/截图/视频)

提示有版本更新，安装新版本时报错如下，手机版本和软件版本如图
![Screenshot_2024-10-09-12-01-15-053_li songe gkd](https://github.com/user-attachments/assets/af369c56-4cd7-4e34-8611-fc76b812513d)
![Screenshot_2024-10-09-12-01-28-893_com android se](https://github.com/user-attachments/assets/e4483a87-233a-4b66-8e0c-2a42498b50b4)

### 期望行为(文字/截图/视频)

可以正常更新

### 实际行为(文字/截图/视频)

![Screenshot_2024-10-09-11-59-48-323_li songe gkd](https://github.com/user-attachments/assets/8f4c381c-6ecb-4fba-9581-7f9b8b051306)

**Comment by lisonge** [comment]
你使用的那个特定的旧的测试版本有一个 安装 apk 失败的 bug，因此无法安装新版本

去 <https://gkd.li/guide/> 选择版本下载后手动安装
