### ISSUE TITLE
[BUG] 软件导致自动锁屏失效

### ISSUE THREAD

**Issue by ngo5** [gkd-kit/gkd#747]
### 日志文件

[log-1728755761043.zip](https://github.com/user-attachments/files/17350958/log-1728755761043.zip)

### BUG描述(文字/截图/视频)

系统默认一分钟自动锁屏，开启GKD无障碍服务后，自动锁屏失效。关闭GKD无障碍服务，自动锁屏恢复正常。

### 期望行为(文字/截图/视频)

手机自动锁屏。

### 实际行为(文字/截图/视频)

手机没有自动锁屏。

**Comment by lisonge** [comment]
关闭高级设置里的前台悬浮窗呢？

**Comment by ngo5** [comment]
> 关闭高级设置里的前台悬浮窗呢？

关了之后可以自动锁屏了。

**Comment by lisonge** [comment]
刚刚测试我的 RedMi 手机 没有出现这种情况

我的前台悬浮窗是打开的但是可以自动锁屏

看起来是你的手机系统配置问题

**Comment by ngo5** [comment]
刚才升级了个系统小版本，重启升级后，我去开启前台悬浮窗，又能自动锁屏了。
