### ISSUE TITLE
[BUG] 小米手机录屏无法定位到确定按钮

### ISSUE THREAD

**Issue by muzi-cheng** [gkd-kit/gkd#748]
### 日志文件

https://i.gkd.li/snapshot/1728757932989

### BUG描述(文字/截图/视频)

![image](https://github.com/user-attachments/assets/d5fc40c0-55fc-45c8-99e7-6f56ee70a3ac)

### 期望行为(文字/截图/视频)

出现这个界面可以自动点击，立即开始

### 实际行为(文字/截图/视频)

使用下面的规则，无法自动点击
{
  id: 'com.android.systemui',
  name: '系统界面',
  groups: [
    {
      key: 1,
      name: '[ChangeMe]规则名称-2024-10-13 02:33:20',
      desc: '[ChangeMe]本规则由GKD网页端审查工具生成',
      rules: [
        {
          quickFind: true,
          activityIds: 'com.android.systemui.media.MediaProjectionPermissionActivity',
          matches: '*[text*="开始"]',
        },
      ],
    },
  ],
}

**Comment by lisonge** [comment]
找不到就是系统没有提供无障碍节点
