### ISSUE TITLE
如何更新到最新的规则库

### ISSUE THREAD

**Issue by wokula** [gkd-kit/gkd#75]
如何更新到最新的规则库
APP 内置的规则库 好像只到V112，而现在最新的是V144

**Comment by lisonge** [comment]
从哪里看出是 v144 的？最新的就是 v112

https://github.com/gkd-kit/subscription

![image](https://github.com/gkd-kit/gkd/assets/38517192/ee41a2a5-c2c9-44c2-9a2c-adb2541d4ce1)

**Comment by wokula** [comment]
是看这个吗，V147

![image](https://github.com/gkd-kit/gkd/assets/23372812/6a18fe8a-7d1d-44a6-824d-e54f14664627)

**Comment by lisonge** [comment]
那个是 npm 发布的版本，和实际订阅版本没有关系

这个发布订阅的原理是将订阅文件发布到  <https://www.npmjs.com/package/@gkd-kit/subscription>

然后 APP 通过大陆镜像去更新 <https://registry.npmmirror.com/@gkd-kit/subscription/latest/files>

**Comment by lisonge** [comment]
这样的好处是在大陆能无需梯子也能 直接更新订阅和APP

实际上也可以用 <https://raw.githubusercontent.com/gkd-kit/subscription/main/dist/gkd.json> 作为默认订阅

但是这个地址是被墙的，必须开梯子才能更新
