### ISSUE TITLE
[BUG] 某些场景下无法进行快照

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/gkd#750]
### 日志文件

[log-1729064067371.zip](https://github.com/user-attachments/files/17391264/log-1729064067371.zip)

### BUG描述(文字/截图/视频)

在某些页面无法进行快照，包括悬浮窗，音量，截屏，电脑端快照都失败
![QQ20241016-153353](https://github.com/user-attachments/assets/40e511ea-b36e-46b9-9c8a-f33dd8548946)

https://github.com/user-attachments/assets/156269b9-dab1-4791-9c02-811484d31d13

### 期望行为(文字/截图/视频)

正常快照

### 实际行为(文字/截图/视频)

无法快照

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/commit/4fc031a3fe019e0e68ada2464c7406648b775fdc

https://github.com/gkd-kit/gkd/actions/runs/11288629953/artifacts/2044216579

试试最新版本

**Comment by aoguai** [comment]
4fc031a 后正常
