### ISSUE TITLE
[BUG] 更新1.9Beta2之后规则概率不触发

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#752]
### 日志文件

https://f.gkd.li/17447684

### BUG描述(文字/截图/视频)

具体表现为在一些信息流广告上，如果下拉控制中心点击截取快照就能触发，退回到以下版本后正常跳过https://github.com/gkd-kit/gkd/actions/runs/11368126225

https://github.com/user-attachments/assets/fc80bff3-efad-4356-96e5-1885a59c9ffe

### 期望行为(文字/截图/视频)

正常触发

### 实际行为(文字/截图/视频)

概率不触发

**Comment by baby170303** [comment]
我也是

**Comment by lsllc999** [comment]
一样，今早更新beta2后多数场景失效。回退beta1后正常。反复安装两个版本确认问题属实。

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/17451635/release.zip)

试试这个版本呢？

**Comment by lsllc999** [comment]
其它好像正常了，微信公众号页面内广告点击异常。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月21日(周一) 凌晨2:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gkd-kit/gkd] [BUG] 更新1.9Beta2之后规则概率不触发 (Issue #752)




 
release.zip
 
试试这个版本呢？

**Comment by AIsouler** [comment]
> [release.zip](https://github.com/user-attachments/files/17451635/release.zip)
> 
> 试试这个版本呢？

没问题了

**Comment by lsllc999** [comment]
其它没试，微信公众号页面的问题依旧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月21日(周一) 上午7:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gkd-kit/gkd] [BUG] 更新1.9Beta2之后规则概率不触发 (Issue #752)




  
release.zip
 
试试这个版本呢？
  
没问题了

**Comment by CuSO4with5H2O** [comment]
+1

**Comment by xzhlksh** [comment]
同样，而且主要是需要多次点击的动作只点击第一步，后续步骤不执行

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.9.0-beta.3
