### ISSUE TITLE
[BUG] 无法开启App内的服务状态始终为关闭

### ISSUE THREAD

**Issue by 961739124** [gkd-kit/gkd#754]
### 日志文件

[log-1729421097790.zip](https://github.com/user-attachments/files/17449932/log-1729421097790.zip)

### BUG描述(文字/截图/视频)

https://github.com/user-attachments/assets/5bf7dd74-a725-414e-adf4-388f735c9012

### 期望行为(文字/截图/视频)

开启服务

### 实际行为(文字/截图/视频)

App内的无障碍服务为关闭状态

**Comment by lisonge** [comment]
请使用最新版本复现

**Comment by 961739124** [comment]
> 请使用最新版本复现

就是1.9.0 beta2

**Comment by 961739124** [comment]
https://github.com/user-attachments/assets/a1af834a-84c8-447f-87b5-cbaa72dd7a98

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/17450053/release.zip)

试试这个本地修复编译的版本呢？

**Comment by 961739124** [comment]
开是能开了，但是不能触发点击

**Comment by lisonge** [comment]
需要日志

**Comment by 961739124** [comment]
[log-1729424973617.zip](https://github.com/user-attachments/files/17450088/log-1729424973617.zip)

**Comment by lisonge** [comment]
从日志中得知，无障碍已经正常运行

另外，你的订阅更新失败

其他情况我不知道，先这样吧
