### ISSUE TITLE
[Feature] 希望能出自动滑动功能，以实现滑动关闭广告

### ISSUE THREAD

**Issue by bocchi810** [gkd-kit/gkd#757]
### 新功能描述

如题，有些软件（例如Gmail）要右滑才能关闭广告

**Comment by zsl0000** [comment]
返回可以实现
  {
      key: 2,
      name: '返回',
      action: 'back',
      matches: [
        '[text*="浏览成功"]',
      ],
      actionCd: 1000,
    }
