### ISSUE TITLE
[Feature] 快照能否本地查看，有些敏感应用上传到网络，如果忘记删除，大家都能看到

### ISSUE THREAD

**Issue by kxcare** [gkd-kit/gkd#758]
### 新功能描述

希望增加这个功能，谢谢大佬

**Comment by lisonge** [comment]
https://i.gkd.li/

![image](https://github.com/user-attachments/assets/d6f08691-5daf-4961-af29-d91ccbac767a)

**Comment by kxcare** [comment]
> https://i.gkd.li/
> 
> ![image](https://private-user-images.githubusercontent.com/38517192/381131247-d6f08691-5daf-4961-af29-d91ccbac767a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNDU2MTQsIm5iZiI6MTczMDI0NTMxNCwicGF0aCI6Ii8zODUxNzE5Mi8zODExMzEyNDctZDZmMDg2OTEtNWRhZi00OTYxLWFmMjktZDkxY2NiYWM3NjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDIzNDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNmU5NDU5MTdhN2EyZDA4NTU4ZjA2YjA3ZjJjZmJmOTk2YjkwMTllYzFiODZkNDE4ODZiYTVlYWNmNWFhMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x0p45O8-NRvkDrp0WMU1cMai1NW-xhhMSjH1st-wx68)

手动的不是很方便，如果能自动在自己的代理链接里面操作就好了，比如自己的是192.168.1.102:8888，在这里面进行快照查看。 就像autojspro那样，也是手机上布局分析，然后，用局域网链接打开查看布局。如果能实现，万分感谢

**Comment by lisonge** [comment]
![image](https://github.com/user-attachments/assets/e69dc9a8-2e04-44dc-b235-0841eaf0d2a1)

**Comment by kxcare** [comment]
> ![image](https://private-user-images.githubusercontent.com/38517192/381366542-e69dc9a8-2e04-44dc-b235-0841eaf0d2a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzQ5NTMsIm5iZiI6MTczMDI3NDY1MywicGF0aCI6Ii8zODUxNzE5Mi8zODEzNjY1NDItZTY5ZGM5YTgtMmUwNC00NGRjLWIyMzUtMDg0MWVhZjBkMmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA3NTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ODBmZTUyMGQ5NzU0MGY1MmQ0MWRlZDdlYTFkMzhjNTViMjQyMTJlYTU2MzAzNTY2YjA2NjViNGYwNWI4ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ikop9bELTOV7V25aHGcKS1kE23i5wdgvGu9Oz_1Iji8)

链接设备以后只要点击查看布局，在快照就会保存在这个网站上https://i.gkd.li/，需要每次删掉，要不，换台设备登录这个网站，还是能够看到自己的截图

**Comment by lisonge** [comment]
![image](https://github.com/user-attachments/assets/fe610450-0ee3-4a2e-b528-0ac101fc29fe)

**Comment by kxcare** [comment]
> ![image](https://private-user-images.githubusercontent.com/38517192/381447650-fe610450-0ee3-4a2e-b528-0ac101fc29fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Njk4NzYsIm5iZiI6MTczMDQ2OTU3NiwicGF0aCI6Ii8zODUxNzE5Mi8zODE0NDc2NTAtZmU2MTA0NTAtMGVlMy00YTJlLWI1MjgtMGFjMTAxZmMyOWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEzNTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OGUyNWNmZmJiM2YzNTRmYjNlNWY5MWU4YTk5YWQ0ZThmNGEzZmVlYjliZmU3OTg4NDYyN2I0YzEzYjY2ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aDqgWvGoBsG4RTva14ODbiEuH5sHdnjt9dILzvkzJ2k)
> 
> 它默认情况应该是关闭的，也就是不会自动生成，除非用户手动点击上传
> 
> 你的情况应该是打开了之后忘记关闭了

可以了，非常感谢
