### ISSUE TITLE
[BUG] 出现大量报错提示

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#759]
### 日志文件

https://f.gkd.li/17574495

### BUG描述(文字/截图/视频)

昨天出现过一次，用beta版的时候也出现过一次，这个提示过几秒就消失了，当时没截到图，下面这个图是别人的

![9FABD8BF41588F7D8D403B98046C0A59](https://github.com/user-attachments/assets/37e4d5ed-2ffa-4c25-bd19-f25e116637d3)

### 期望行为(文字/截图/视频)

不出现报错提示

### 实际行为(文字/截图/视频)

出现报错提示

**Comment by lisonge** [comment]
看起来应该是这里的顺序写反导致多线程同时 `setGeneratedTime` 出现的报错

<https://github.com/gkd-kit/gkd/blob/3e884b57d6b56d8d09e732641a0446eb6045dd5b/app/src/main/kotlin/li/songe/gkd/service/NodeExt.kt#L24-L28>

试试下面这个版本呢？

[release.zip](https://github.com/user-attachments/files/17582140/release.zip)

**Comment by AIsouler** [comment]
好的，我用一段时间看看

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases
