### ISSUE TITLE
一加13 Color os 15 打不开gkd的无障碍

### ISSUE THREAD

**Issue by Paradox98** [gkd-kit/gkd#772]
### 日志文件

[log-1731390389757.zip](https://github.com/user-attachments/files/17711694/log-1731390389757.zip)

### BUG描述(文字/截图/视频)

coloros 15 root了 magisk28 lsposd 1.10.1 gkd 1.9.1
给了root权限 给了shizuku权限 点无障碍没反应

### 期望行为(文字/截图/视频)

能够正常使用无障碍

### 实际行为(文字/截图/视频)

无障碍点了没有报错但是就是打不开

https://github.com/user-attachments/assets/46a82fff-ab84-4e01-b0c7-8096956f6cdb

**Comment by lisonge** [comment]
> 点无障碍没反应

录个视频看看
