### ISSUE TITLE
[Feature] 关于对开屏广告的优化

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/gkd#777]
### 新功能描述

新功能：当 ```excludeMatches``` 生效时直接休眠此规则，可新增一个 ```boolean``` 类型的字段来决定是否开启此功能，对于一个 ```开屏广告规则组``` 有多条规则并且设置了 ```actionMaximumKey: 0,``` 的情况，当 ```excludeMatches``` 生效时仅休眠单个规则，而不是整个规则组，这样可进一步降低开屏广告的误触概率。

灵感来源于我写排除搜索页选择器的时候，规则如下：
```
    {
      key: 0,
      // 防止在应用的搜索页面误触
      excludeMatches:
        '[text*="搜索" || text^="猜你" || text="历史记录" || text$="在搜"][text.length>3 && text.length<6][visibleToUser=true]',
      matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
    },
```
虽然可排除掉绝大部分搜索页，但是当我点进软件后的10秒内在搜索框中输入 ```跳过``` 时，搜索框下面出现的搜索联想会把页面原来的节点覆盖掉，导致 ```excludeMatches``` 未匹配到任何节点，于是就出现了误触。这时候我突然想到既然用户都进入搜索页了，开屏广告的规则就没必要参与匹配了，因为开屏广告仅在用户进入软件时才出现，延伸一下就是对于应用的任何界面都可使用排除匹配来让开屏广告的规则休眠，因为当应用页面节点出现时就说明用户已经进入软件正常使用了，开屏广告的规则没必要参与匹配，于是有了以上新功能的想法。

**Comment by lisonge** [comment]
你的意思是你不想使用 excludeMatches 排除搜索联想节点

如果已经在搜索页输入 跳过 并且出现了搜索联想，此时切换到其它应用再切换回来

由于 excludeMatches 不生效，会直接触发点击

**Comment by AIsouler** [comment]
> 你的意思是你不想使用 excludeMatches 排除搜索联想节点
> 
> 如果已经在搜索页输入 跳过 并且出现了搜索联想，此时切换到其它应用再切换回来
> 
> 由于 excludeMatches 不生效，会直接触发点击

大佬说的对，是我考虑欠佳了
