### ISSUE TITLE
无障碍开启不了

### ISSUE THREAD

**Issue by lhyaax** [gkd-kit/gkd#78]
oppo find x6p
coloros14
![1111](https://github.com/gkd-kit/gkd/assets/3948065/c5ac1cd0-2cda-4d9c-9710-0426b0cd8a30)

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/35#issuecomment-1723393936

**Comment by lhyaax** [comment]
> [#35 (comment)](https://github.com/gkd-kit/gkd/issues/35#issuecomment-1723393936)

谢谢，ok了
