### ISSUE TITLE
能否配置一个类似李跳跳那样的通用规则

### ISSUE THREAD

**Issue by Crisy1084** [gkd-kit/gkd#79]
有一些不在订阅列表的应用也有广告，但是不会被关闭。

李跳跳设置了通用规则，三方应用打开后检索通用的广告关闭按钮，来进行关闭

**Comment by conglinyizhi** [comment]
#48 中有同样的需求

**Comment by tangqiu0205** [comment]
一样需要这个需求

**Comment by lisonge** [comment]
duplicate

https://github.com/gkd-kit/gkd/issues/48
