### ISSUE TITLE
[BUG] 更新到1.9.2后打不开无障碍

### ISSUE THREAD

**Issue by bugme2** [gkd-kit/gkd#792]
### 日志文件

[log-1732539856938.zip](https://github.com/user-attachments/files/17903297/log-1732539856938.zip)

### BUG描述(文字/截图/视频)

授权root在软件内打开和去无障碍列表打开都不行，开关点不开(非安全设置的灰色)

### 期望行为(文字/截图/视频)

系统环境：RealmeUI 6.0

### 实际行为(文字/截图/视频)

1.9.1是正常的，软件内更新安装到1.9.2后自动关闭无障碍且点不开

**Comment by lisonge** [comment]
#773

**Comment by bugme2** [comment]
> 应该是你们的设备魔改了什么特性，不是 gkd 的问题
> 
> 目前我也不知道怎么解决

找到根源所在了，需要添加一个权限
appops set li.songe.gkd ACCESS_RESTRICTED_SETTINGS allow

**Comment by lisonge** [comment]
感谢提供参考命令

已内置到最新版本高级授权中
