### ISSUE TITLE
无法在OriginOS中工作

### ISSUE THREAD

**Issue by Anivie** [gkd-kit/gkd#80]
在开屏广告页面时没有触发自动跳过，也没有弹窗提醒。
已经在主页中正确配置所需权限
[log.zip](https://github.com/gkd-kit/gkd/files/12738874/log.zip)

**Comment by lisonge** [comment]
根据日志判断是和 https://github.com/gkd-kit/gkd/issues/64 一样的原因，会尽快修复

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0
