### ISSUE TITLE
[BUG] 通过调用服务进行快照时 GKD 出现崩溃

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/gkd#803]
### 日志文件

https://f.gkd.li/18031578

### BUG描述(文字/截图/视频)

通过调用服务进行快照时 GKD 提示快照成功（实际成功）后出现程序崩溃。
使用  shortx 或者，shell 脚本执行调用时随机出现，原因不明。

https://github.com/user-attachments/assets/4955f4f5-38c1-411a-bfc4-8f37c46a53b9

### 期望行为(文字/截图/视频)

正常可以使用服务进行快照，程序不崩溃。

### 实际行为(文字/截图/视频)

调用服务进行快照时 GKD 提示快照成功（实际成功）后程序出现崩溃。

**Comment by aoguai** [comment]
视频通知栏没录上，实际想展示的是，快照成功后通过通知栏可知gkd崩溃后重启

**Comment by lisonge** [comment]
[release.zip](https://github.com/user-attachments/files/18032479/release.zip)

试试这个版本

**Comment by aoguai** [comment]
> 试试这个版本

该版本运行正常
