### ISSUE TITLE
[BUG] 荣耀Magic6 magicOS9.0 跳过跳过广告功能经常不触发

### ISSUE THREAD

**Issue by LiMuBai-ACE** [gkd-kit/gkd#804]
### 日志文件

[log-1733469684094.zip](https://github.com/user-attachments/files/18034194/log-1733469684094.zip)

### BUG描述(文字/截图/视频)

https://github.com/user-attachments/assets/e82c7a7f-4ff6-4fe3-a1aa-07d8ea99a69c

### 期望行为(文字/截图/视频)

期望能够正常触发，跳过广告

### 实际行为(文字/截图/视频)

例如 我的荣耀，向日葵远程控制，Youtube，以及上面的毒舌电影等也时常不能触发，不知道是否是更新了Magic9.0系统的原因，之前Magic8.0出现此问题较少

**Comment by lisonge** [comment]
哪个规则不触发去找维护规则的人
