### ISSUE TITLE
[Feature] 关于activityids和界面识别

### ISSUE THREAD

**Issue by MagicHello** [gkd-kit/gkd#810]
### 新功能描述

当我的规则限定了activityids，但当gkd无法识别界面id时（也就是null）任然执行了我的规则，希望改变这种逻辑（也就是限定了activityids时，只有准确识别出界面ID才进行执行）

**Comment by lisonge** [comment]
那你直接安装 shizuku 就行了

界面识别到 null 是完全随机的行为

**Comment by lisonge** [comment]
在没有 shizuku 情况下

识别界面 activityId 依赖无障碍事件

如果在应用内进入另一个界面，但是没有无障碍事件发出

那么也会发生界面识别错误

---

这个时候你应该使用选择器来纠正匹配
