### ISSUE TITLE
gkd在游戏页面乱点，然后打开gkd就清空点击日志和订阅了，软件bug还是什么

### ISSUE THREAD

**Issue by KiraR886** [gkd-kit/gkd#827]
### 日志文件

[log-1734526610720.zip](https://github.com/user-attachments/files/18181529/log-1734526610720.zip)

### BUG描述(文字/截图/视频)

gkd在游戏页面乱点，然后打开gkd就清空点击日志和订阅了，软件bug还是什么

### 期望行为(文字/截图/视频)

gkd在游戏页面乱点，然后打开gkd就清空点击日志和订阅了，软件bug还是什么

### 实际行为(文字/截图/视频)

gkd在游戏页面乱点，然后打开gkd就清空点击日志和订阅了，软件bug还是什么

**Comment by lisonge** [comment]
在日志中没看到任何点击记录，你关掉 gkd 后也是这样？

给个复现视频和此复现视频后的日志文件

**Comment by lisonge** [comment]
我注意到你安装了 自动点击器，你是否在后台使用此软件？

![image](https://github.com/user-attachments/assets/07c5a380-ed66-452f-9a68-36acc95e29fe)

**Comment by KiraR886** [comment]
没有使用自动点击器
当时在游戏页面，忽然开始乱动，我就退出游戏打开gkd想看看是不是gkd误识别，结果发现订阅和点击统计都没了，暂时无法复现

**Comment by KiraR886** [comment]
只出现了一次，然后我就重新订阅了一下，没有再复现
> 在日志中没看到任何点击记录，你关掉 gkd 后也是这样？
> 
> 给个复现视频和此复现视频后的日志文件

**Comment by lisonge** [comment]
那是你系统的数据错乱问题

我不知道你的系统怎么回事
