### ISSUE TITLE
[BUG] 如果设备在息屏时会断开网络连接，可能导致订阅自动更新卡住

### ISSUE THREAD

**Issue by chr431** [gkd-kit/gkd#830]
### 日志文件

[log-1734614360000.zip](https://github.com/user-attachments/files/18198443/log-1734614360000.zip)

### BUG描述(文字/截图/视频)

我有两个设备，手机设置了息屏不断开网络连接，gkd的订阅自动更新一直正常；而平板一两天才打开一次，为了省电设置了息屏时断开网络，结果经常打开之后发现gkd的订阅界面一直显示更新中，手动强行停止应用之后重启才能恢复。我猜测这是gkd在息屏时尝试进行自动更新导致的，此时并没有网络连接，所以一直卡死。建议增加超时检测或者在息屏时不进行订阅的自动更新。

### 期望行为(文字/截图/视频)

![微信图片_2024-12-19_212129_162](https://github.com/user-attachments/assets/48f7d446-35bd-4efb-a444-ace6fd8694e9)
一直转圈，除非手动强行停止应用，否则无法正常更新

### 实际行为(文字/截图/视频)

正常更新

**Comment by lisonge** [comment]
试试这个版本呢

https://github.com/gkd-kit/gkd/actions/runs/12374462163/artifacts/2332150634

**Comment by chr431** [comment]
我先使用几天，看问题是否复现
