### ISSUE TITLE
[BUG] APP中可以看到识别到了跳过，但实际并未触发点击

### ISSUE THREAD

**Issue by fissionq** [gkd-kit/gkd#835]
### 日志文件

[log-1735038593962.zip](https://github.com/user-attachments/files/18238950/log-1735038593962.zip)

### BUG描述(文字/截图/视频)

![Screenshot_2024-12-24-19-13-37-066_li songe gkd](https://github.com/user-attachments/assets/7b7e97ab-e24e-4fb0-9257-b3f94c56950b)
有点击记录，但实际没有点击

### 期望行为(文字/截图/视频)

可以正常关闭广告

### 实际行为(文字/截图/视频)

https://github.com/user-attachments/assets/373f8d0c-a308-45aa-9c11-9e83a9179d49

**Comment by lisonge** [comment]
日志文件只有 `19:09:52.458` 之前的，但是你的视频示例中是 `19:14`

请给出此时间段的日志

**Comment by fissionq** [comment]
Uploading Screenrecorder-2024-12-24-19-38-53-956.mp4…

[log-1735040355094.zip](https://github.com/user-attachments/files/18239133/log-1735040355094.zip)

**Comment by lisonge** [comment]
视频没有上传成功

**Comment by lisonge** [comment]
可以顺便提供这个广告的快照吗？

可能是点击太早了导致不响应

**Comment by AIsouler** [comment]
相似问题，这几个软件在我手机上不会出现开屏广告，所以我也无法调整规则进行测试
https://github.com/AIsouler/GKD_subscription/issues/651
https://github.com/AIsouler/GKD_subscription/issues/644
https://github.com/AIsouler/GKD_subscription/issues/643

**Comment by fissionq** [comment]
手机系统问题，现在可以正常使用了
