### ISSUE TITLE
[Feature] 模拟滑动屏幕

### ISSUE THREAD

**Issue by MuYan-lshc** [gkd-kit/gkd#840]
### 新功能描述

希望可以实现识别到广告时，执行向上滑动屏幕的操作。我并没有在文档中看到类似操作。因为我 在使用某一些网剧短视频app时中会时不时穿插一些广告，必须手动滑动。

**Comment by zsl0000** [comment]
我也需要

**Comment by xieyan110** [comment]
@MuYan-lshc 

我帮你编译了一个支持  上滑 的功能。
https://github.com/xieyan110/gkd/releases/tag/v2.33，还顺便写了一个短剧的上滑 json
