### ISSUE TITLE
显示触发提示但是貌似目标软件不响应

### ISSUE THREAD

**Issue by KiraR886** [gkd-kit/gkd#841]
1

**Comment by lisonge** [comment]
你说的太宽泛了，你需要给出实际的规则和具体的应用快照，否则我无法解决此问题

**Comment by lisonge** [comment]
可以参考

https://github.com/gkd-kit/gkd/issues/835#issuecomment-2563399472

**Comment by KiraR886** [comment]
> 可以参考
> 
> https://github.com/gkd-kit/gkd/issues/835#issuecomment-2563399472

可能确实是系统的问题，我也是ColorOS15，但是在此之前14好像也会这样
