### ISSUE TITLE
[BUG] HTTP 服务 无法开启

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/gkd#843]
### 日志文件

[log-1735391853580.zip](https://github.com/user-attachments/files/18266268/log-1735391853580.1.zip)

### BUG描述(文字/截图/视频)

HTTP 服务 无法开启

![43e6d226e3479b6e7326b5390629299](https://github.com/user-attachments/assets/53165be9-0c28-4c43-b557-86e06ec5ec39)

### 期望行为(文字/截图/视频)

HTTP 服务 开启

### 实际行为(文字/截图/视频)

HTTP 服务 无法开启

**Comment by lisonge** [comment]
https://youtrack.jetbrains.com/issue/KTOR-7298

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/commit/d403da03aace9c9233b18d91bf2fd01e1599d011
