### ISSUE TITLE
对规则进行分组，提供批量开关能力

### ISSUE THREAD

**Issue by keleus** [gkd-kit/gkd#87]
目前按照广告形式可以分为：
1. 开屏广告
2. 青少年弹窗
3. 广告弹窗
4. 信息流（评论区）广告
5. 活动弹窗
6. 其它（如更新等）

应用提供按上述类型关闭和打开规则的能力。比如信息流广告，很多时候并不在意，但自动点击关闭的时候却会闪屏，影响体验。

----

补充：希望是能批量一键关闭所有APP的特定分类的，而不是点进每个app单独关闭。

**Comment by Snoopy1866** [comment]
你可以点击默认订阅->*app名称*，就能看到分好类的规则了，每个规则组都有单独的控制开关

**Comment by BaiQingGuaJunior** [comment]
确实

**Comment by cangming99** [comment]
确实很需要这功能，我只需要跳过开屏和弹窗就能够满足了，信息流广告的跳过反而经常让我误触，希望能够批量关闭

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/issues/248
