### ISSUE TITLE
root用户

### ISSUE THREAD

**Issue by 189521394** [gkd-kit/gkd#92]
既然有了shizuku授权，希望会有root授权

**Comment by xiuciy** [comment]
刷sui模块即可

**Comment by lisonge** [comment]
授权太难搞了，全部走 shizuku 吧，shizuku 本来也能通过 root 使用

https://github.com/gkd-kit/gkd/issues/92#issuecomment-1747354380

**Comment by lisonge** [comment]
下个版本将增加 ROOT/ADB/命令 授权支持，可在无 shizuku 的情况下自我提权

这将由另外一个正在进行的开源项目 https://github.com/priv-kit/priv-kit 实现

**Comment by BAIIIZE** [comment]
root模式被去除了吗？

**Comment by helloworld2540** [comment]
> root模式被去除了吗？

是的，可以选择替代方案
[Sui 模块](https://github.com/XiaoTong6666/Sui/releases/tag/nightly)
