### ISSUE TITLE
MIUI14无障碍权限总是自动关闭

### ISSUE THREAD

**Issue by SolSolis** [gkd-kit/gkd#95]
MIUI14，安卓13同时安装了李跳跳2.2和GKD1.2.1，对两款软件均开启了自启动和无限制，GKD1.2.1的无障碍权限开启一段时间后会被自动关闭，同时李跳跳2.2的权限不会关闭，是否是因为李跳跳采用了某种特殊方式？

**Comment by lenvoh** [comment]
遇到了同样的问题

**Comment by DearZack** [comment]
插眼

**Comment by MrCharlesWu** [comment]
同样问题，有解决办法了不

**Comment by lisonge** [comment]
试试最新版本呢

https://github.com/gkd-kit/gkd/releases

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.5.0
