### ISSUE TITLE
快照黑屏

### ISSUE THREAD

**Issue by judycarrot** [gkd-kit/gkd#98]

**Comment by judycarrot** [comment]
> https://gkd-kit.gitee.io/import/12784507
> 
> 并不是黑屏，只是透明空白图片，你的截屏服务没有开启吗？

原来鸿蒙3也要开截屏服务……明白了！

**Comment by lisonge** [comment]
看看一下，你的 Android 版本是 10，只有 11 才支持无障碍直接截图
